/* IASD APP - banco extra do Jogo Coletivo: perguntas novas, Verdadeiro/Falso próprio, personagens, frases e linhas do tempo.
   Mesmos formatos dos bancos originais; carregado depois deles. vf: [categoria, afirmação, verdadeira(1/0), referência, dificuldade, correção quando falsa] */
(function(){
const B=window.IASDBank=window.IASDBank||{};
B.quiz=B.quiz||[];
B.who=B.who||[];
B.said=B.said||[];
B.timeline=B.timeline||[];
B.quiz.push.apply(B.quiz,[
 ["Lugares","Para qual povoado caminhavam dois discípulos quando Jesus ressuscitado se juntou a eles?","Emaús",["Betânia","Belém","Jericó"],"Lucas 24:13",2],
 ["Lugares","Em que cidade os ourives provocaram um tumulto por causa do templo de Diana?","Éfeso",["Corinto","Atenas","Filipos"],"Atos 19:24-29",3],
 ["Lugares","Em que monte Deus pediu a Abraão que oferecesse Isaque?","Monte Moriá",["Monte Sinai","Monte Carmelo","Monte Hermom"],"Gênesis 22:2",3],
 ["Lugares","Em que rio o general Naamã foi mandado lavar-se sete vezes para ser curado da lepra?","Rio Jordão",["Rio Eufrates","Rio Nilo","Rio Tigre"],"2 Reis 5:10",2],
 ["Lugares","Em que cidade Pedro ressuscitou Dorcas (Tabita)?","Jope",["Cesareia","Lida","Antioquia"],"Atos 9:36-40",3],
 ["Lugares","Em que cidade vivia Cornélio, o centurião que chamou Pedro para lhe falar de Jesus?","Cesareia",["Jope","Antioquia","Tarso"],"Atos 10:1",3],
 ["Lugares","Em que lugar Jesus orou na noite anterior à sua prisão?","Getsêmani",["Betânia","Gólgota","Cedrom"],"Mateus 26:36",1],
 ["Lugares","Perto de que poço Jesus conversou com a mulher samaritana?","Poço de Jacó, em Sicar",["Poço de Berseba","Poço de Harã","Poço de Siloé"],"João 4:5-7",3],
 ["Lugares","Em qual cidade Jesus curou um paralítico que foi descido pelo telhado?","Cafarnaum",["Jericó","Naim","Caná"],"Marcos 2:1-5",3],
 ["Personagens","Quem foi vendido pelos irmãos e depois governou o Egito?","José",["Benjamim","Judá","Rúben"],"Gênesis 37–41",1],
 ["Personagens","Qual juiz de Israel tinha uma força enorme ligada ao seu cabelo?","Sansão",["Gideão","Jefté","Otniel"],"Juízes 16:17",1],
 ["Personagens","Quem foi o irmão de Moisés que serviu como sumo sacerdote?","Arão",["Josué","Calebe","Hur"],"Êxodo 28:1",2],
 ["Personagens","Quem substituiu Moisés na liderança de Israel para entrar em Canaã?","Josué",["Calebe","Arão","Gideão"],"Josué 1:1-2",1],
 ["Personagens","Qual rei da Babilônia mandou lançar três jovens hebreus na fornalha de fogo?","Nabucodonosor",["Dario","Ciro","Belsazar"],"Daniel 3",2],
 ["Personagens","Qual rei viu uma mão escrever na parede durante uma festa?","Belsazar",["Nabucodonosor","Dario","Ciro"],"Daniel 5:5",3],
 ["Personagens","Qual espião, junto com Josué, trouxe um bom relatório sobre Canaã?","Calebe",["Arão","Hur","Eleazar"],"Números 14:6-9",2],
 ["Personagens","Qual foi o nome babilônico dado a Daniel?","Beltessazar",["Sadraque","Mesaque","Abede-Nego"],"Daniel 1:7",3],
 ["Personagens","Qual filho de Isaque vendeu a primogenitura por um prato de lentilhas?","Esaú",["Jacó","Ismael","Judá"],"Gênesis 25:34",1],
 ["Personagens","Quantos anos Jacó trabalhou ao todo por Lia e Raquel?","Catorze",["Sete","Dez","Vinte"],"Gênesis 29:20-30",2],
 ["Personagens","Qual filho de Davi se rebelou contra o pai e tomou o trono em Hebrom?","Absalão",["Salomão","Adonias","Amnom"],"2 Samuel 15:10",2],
 ["Personagens","Qual amigo fiel de Davi era filho do rei Saul?","Jonatã",["Abner","Joabe","Absalão"],"1 Samuel 18:1-3",1],
 ["Milagres e Parábolas","Na parábola do filho pródigo, quem recebeu o filho de volta com uma festa?","O pai",["O irmão mais velho","Um servo","O juiz"],"Lucas 15:20-24",1],
 ["Milagres e Parábolas","Na parábola do bom samaritano, quem parou para ajudar o homem ferido?","Um samaritano",["Um sacerdote","Um levita","Um soldado romano"],"Lucas 10:33",1],
 ["Milagres e Parábolas","Qual milagre Jesus fez quando os discípulos temiam afundar no barco?","Acalmou a tempestade",["Multiplicou os pães","Curou um leproso","Ressuscitou Lázaro"],"Marcos 4:37-39",1],
 ["Milagres e Parábolas","Na parábola do semeador, o que representa a semente?","A palavra de Deus",["O dinheiro","Os discípulos","Os milagres"],"Lucas 8:11",2],
 ["Milagres e Parábolas","Na parábola da ovelha perdida, quantas ovelhas o pastor tinha ao todo?","Cem",["Dez","Cinquenta","Mil"],"Lucas 15:4",2],
 ["Milagres e Parábolas","Na parábola do fariseu e do publicano, quem voltou justificado para casa?","O publicano",["O fariseu","Os dois","Nenhum deles"],"Lucas 18:14",2],
 ["Milagres e Parábolas","Quem teve a sogra curada de febre por Jesus?","Pedro",["André","Tiago","João"],"Mateus 8:14-15",2],
 ["Milagres e Parábolas","Que semente Jesus usou para ilustrar o poder de uma fé pequena?","Grão de mostarda",["Grão de trigo","Semente de figo","Semente de uva"],"Mateus 17:20",1],
 ["Milagres e Parábolas","Que alimento Jesus multiplicou para alimentar quatro mil pessoas?","Sete pães e alguns peixes",["Cinco pães e dois peixes","Doze pães e três peixes","Dez pães e um peixe"],"Marcos 8:5-9",3],
 ["Milagres e Parábolas","Onde o homem da parábola de Jesus construiu a casa que resistiu à tempestade?","Sobre a rocha",["Sobre a areia","Sobre a colina","Perto do rio"],"Mateus 7:24-25",1],
 ["Milagres e Parábolas","O que o samaritano fez antes de levar o ferido à hospedaria?","Derramou óleo e vinho nas feridas",["Deu-lhe pão e água","Cobriu-o com um manto","Chamou um médico"],"Lucas 10:34",3],
 ["Profetas e Reis","Qual profeta foi levado ao céu em um redemoinho?","Elias",["Eliseu","Isaías","Enoque"],"2 Reis 2:11",1],
 ["Profetas e Reis","Qual rei de Israel foi casado com Jezabel?","Acabe",["Jeú","Onri","Jeroboão"],"1 Reis 16:30-31",2],
 ["Profetas e Reis","Qual rei de Judá encontrou o livro da Lei no templo e fez grandes reformas?","Josias",["Ezequias","Manassés","Joás"],"2 Reis 22:8",3],
 ["Profetas e Reis","Qual profeta é conhecido como o “profeta chorão”?","Jeremias",["Isaías","Ezequiel","Oseias"],"Jeremias 9:1",2],
 ["Profetas e Reis","Qual profeta viu o Senhor no templo, cercado de serafins?","Isaías",["Jeremias","Ezequiel","Daniel"],"Isaías 6:1-3",2],
 ["Profetas e Reis","Qual rei subiu ao trono ainda criança, depois de ter sido escondido no templo?","Joás",["Josias","Ezequias","Uzias"],"2 Reis 11:21",3],
 ["Profetas e Reis","Qual rei teve setecentas esposas e trezentas concubinas e se afastou de Deus na velhice?","Salomão",["Davi","Acabe","Roboão"],"1 Reis 11:3-4",2],
 ["Profetas e Reis","Qual profeta anunciou que o Espírito seria derramado sobre toda a carne, citado em Atos 2?","Joel",["Naum","Ageu","Obadias"],"Joel 2:28",3],
 ["Profetas e Reis","Qual profeta pregou aos exilados enquanto vivia na Babilônia e viu rodas e criaturas viventes?","Ezequiel",["Jeremias","Isaías","Habacuque"],"Ezequiel 1",3],
 ["Apóstolos e Igreja Primitiva","Quem era chamado “filho da consolação”?","Barnabé",["Silas","Marcos","Timóteo"],"Atos 4:36",2],
 ["Apóstolos e Igreja Primitiva","Quem adormeceu na janela e caiu enquanto Paulo pregava?","Êutico",["Timóteo","Tito","Marcos"],"Atos 20:9",3],
 ["Apóstolos e Igreja Primitiva","Que casal caiu morto depois de mentir sobre uma oferta na igreja primitiva?","Ananias e Safira",["Áquila e Priscila","Zacarias e Isabel","Elcana e Ana"],"Atos 5:1-10",2],
 ["Apóstolos e Igreja Primitiva","Qual era a profissão de Lucas, autor do Evangelho e de Atos?","Médico",["Pescador","Cobrador de impostos","Fabricante de tendas"],"Colossenses 4:14",2],
 ["Apóstolos e Igreja Primitiva","Qual discípulo era irmão de Pedro?","André",["Tiago","Filipe","Tomé"],"João 1:40",1],
 ["Apóstolos e Igreja Primitiva","Qual era a profissão de Mateus antes de seguir a Jesus?","Cobrador de impostos",["Pescador","Pastor","Soldado"],"Mateus 9:9",1],
 ["Apóstolos e Igreja Primitiva","Quem era o centurião romano que recebeu o evangelho pela pregação de Pedro?","Cornélio",["Júlio","Ananias","Sérgio Paulo"],"Atos 10:1-2,44",3],
 ["Vida de Jesus","Qual rei quis matar o menino Jesus?","Herodes",["Pilatos","Agripa","Augusto"],"Mateus 2:16",1],
 ["Vida de Jesus","A quem Jesus apareceu primeiro depois de ressuscitar?","Maria Madalena",["Pedro","Tomé","João"],"João 20:14-16",2],
 ["Vida de Jesus","Quantos dias Jesus ficou com os discípulos entre a ressurreição e a ascensão?","Quarenta dias",["Três dias","Sete dias","Cinquenta dias"],"Atos 1:3",2],
 ["Vida de Jesus","Qual fariseu procurou Jesus de noite para conversar sobre o novo nascimento?","Nicodemos",["Caifás","Gamaliel","José de Arimateia"],"João 3:1-2",2],
 ["Vida de Jesus","Quem reconheceu o menino Jesus no templo e disse “meus olhos viram a tua salvação”?","Simeão",["Zacarias","Eli","Natanael"],"Lucas 2:25-30",3],
 ["Vida de Jesus","Qual era o nome do sumo sacerdote que julgou Jesus na noite da prisão?","Caifás",["Anás","Gamaliel","Zacarias"],"Mateus 26:57",2],
 ["Vida de Jesus","Qual discípulo cortou a orelha do servo do sumo sacerdote no jardim?","Pedro",["João","Tiago","André"],"João 18:10",2],
 ["Antigo Testamento","Que ave Noé enviou e que voltou com um ramo de oliveira?","Uma pomba",["Um corvo","Uma águia","Uma andorinha"],"Gênesis 8:11",1],
 ["Antigo Testamento","O que aconteceu com a língua dos homens que construíam a torre de Babel?","Foi confundida",["Foi unificada","Foi esquecida","Foi silenciada"],"Gênesis 11:7-9",2],
 ["Antigo Testamento","O que guiava Israel durante o dia no deserto?","Uma coluna de nuvem",["Uma estrela","Um anjo","Uma águia"],"Êxodo 13:21",2],
 ["Antigo Testamento","Qual foi a primeira praga enviada sobre o Egito?","A água virou sangue",["Rãs","Piolhos","Gafanhotos"],"Êxodo 7:20",2],
 ["Antigo Testamento","Qual rio Israel atravessou a pé enxuto sob a liderança de Josué?","Rio Jordão",["Rio Arnom","Rio Jaboque","Rio Eufrates"],"Josué 3:15-17",1],
 ["Antigo Testamento","Qual festa lembra a noite em que o anjo passou pelas casas marcadas com sangue?","Páscoa",["Pentecostes","Tabernáculos","Purim"],"Êxodo 12:11-13",2],
 ["Antigo Testamento","Qual sinal Deus deu a Abraão da sua aliança?","A circuncisão",["O arco-íris","As tábuas da lei","Um altar"],"Gênesis 17:10-11",3],
 ["Antigo Testamento","Quantos jovens hebreus foram lançados na fornalha ardente?","Três",["Dois","Quatro","Sete"],"Daniel 3:23",1],
 ["Antigo Testamento","Quantas vezes Naamã teve de mergulhar no Jordão para ser curado?","Sete",["Três","Doze","Quarenta"],"2 Reis 5:14",2],
 ["Antigo Testamento","Que rei pagão reconheceu o Deus de Daniel depois que ele foi salvo dos leões?","Dario",["Nabucodonosor","Ciro","Belsazar"],"Daniel 6:25-27",3],
 ["Novo Testamento","Qual carta fala dos heróis da fé no capítulo 11?","Hebreus",["Tiago","Romanos","Efésios"],"Hebreus 11",2],
 ["Novo Testamento","Qual apóstolo escreveu: “A fé sem obras é morta”?","Tiago",["Pedro","João","Judas"],"Tiago 2:26",2],
 ["Novo Testamento","Que carta Paulo escreveu da prisão a uma igreja da Macedônia, cheia de alegria?","Filipenses",["Gálatas","Romanos","Tito"],"Filipenses 1:7; 4:4",3],
 ["Novo Testamento","Qual dos grandes mandamentos Jesus disse ser o primeiro e maior?","Amar a Deus de todo o coração",["Guardar o sábado","Honrar pai e mãe","Não matar"],"Mateus 22:37-38",2],
 ["Novo Testamento","Qual das cartas abaixo foi escrita por Paulo?","Gálatas",["Tiago","Judas","1 Pedro"],"Gálatas 1:1",2],
 ["Novo Testamento","Quantos discípulos Jesus enviou de dois em dois, além dos doze?","Setenta",["Doze","Cem","Trinta"],"Lucas 10:1",3],
 ["Novo Testamento","Como se chamam os quatro primeiros livros do Novo Testamento?","Os Evangelhos",["As Epístolas","Os Profetas","Os Atos"],"Mateus a João",1],
 ["Novo Testamento","Qual livro conta a história da igreja primitiva logo depois dos Evangelhos?","Atos",["Romanos","Hebreus","Apocalipse"],"Atos 1:1",1],
 ["Novo Testamento","Que peça da armadura de Deus apaga os dardos inflamados do maligno?","O escudo da fé",["O capacete da salvação","A espada do Espírito","A couraça da justiça"],"Efésios 6:16",2],
 ["Livros e Números","Qual livro profético tem apenas um capítulo e fala sobre Edom?","Obadias",["Naum","Habacuque","Ageu"],"Obadias 1",3],
 ["Livros e Números","Quem tradicionalmente escreveu os cinco primeiros livros da Bíblia?","Moisés",["Josué","Samuel","Esdras"],"Lucas 24:44",1],
 ["Livros e Números","Qual livro do Antigo Testamento reúne a sabedoria de Salomão em ditados?","Provérbios",["Salmos","Lamentações","Jó"],"Provérbios 1:1",2],
 ["Livros e Números","Qual livro do Antigo Testamento lamenta a destruição de Jerusalém?","Lamentações",["Cantares","Eclesiastes","Naum"],"Lamentações 1",2],
 ["Livros e Números","Qual livro fecha a Bíblia?","Apocalipse",["Judas","Hebreus","Atos"],"Apocalipse 22",1],
 ["Livros e Números","Qual destes livros é um dos livros históricos do Antigo Testamento?","Josué",["Isaías","Provérbios","Naum"],"Josué 1",2],
 ["Livros e Números","Em qual livro do Antigo Testamento aparece a história de Nabucodonosor e da cova dos leões?","Daniel",["Ezequiel","Ester","Neemias"],"Daniel 1–6",1],
 ["Livros e Números","Em qual livro está a história do general que se lavou sete vezes no Jordão?","2 Reis",["Josué","Juízes","Jó"],"2 Reis 5",3],
 ["Mulheres da Bíblia","Qual mulher foi esposa de Boaz?","Rute",["Noemi","Orfa","Débora"],"Rute 4:13",1],
 ["Mulheres da Bíblia","Qual mulher vendedora de púrpura acolheu Paulo em Filipos?","Lídia",["Dorcas","Priscila","Febe"],"Atos 16:14-15",3],
 ["Mulheres da Bíblia","Qual era o nome da irmã de Moisés que vigiou o cesto no rio?","Miriã",["Zípora","Débora","Eliseba"],"Êxodo 2:4",2],
 ["Mulheres da Bíblia","Qual mulher da igreja primitiva era conhecida por fazer roupas para os pobres?","Dorcas (Tabita)",["Lídia","Priscila","Febe"],"Atos 9:36,39",3],
 ["Apocalipse e Profecia","Quantos são os cavaleiros dos quatro primeiros selos do Apocalipse?","Quatro",["Três","Sete","Doze"],"Apocalipse 6:1-8",1],
 ["Apocalipse e Profecia","Por quanto tempo Satanás ficará preso, segundo Apocalipse 20?","Mil anos",["Cem anos","Sete anos","Quarenta anos"],"Apocalipse 20:2",1],
 ["Apocalipse e Profecia","Como se chama a cidade que desce do céu em Apocalipse 21?","Nova Jerusalém",["Nova Babilônia","Nova Sião","Nova Belém"],"Apocalipse 21:2",1],
 ["Apocalipse e Profecia","Quantos animais subiram do mar na visão de Daniel 7?","Quatro",["Três","Sete","Dois"],"Daniel 7:3",2],
 ["Apocalipse e Profecia","Quem é o arcanjo que luta contra o dragão no Apocalipse?","Miguel",["Gabriel","Rafael","Uriel"],"Apocalipse 12:7",2],
 ["Apocalipse e Profecia","Qual profeta recebeu as visões das setenta semanas do anjo Gabriel?","Daniel",["Ezequiel","Isaías","Zacarias"],"Daniel 9:21-24",3],
 ["Apocalipse e Profecia","O que o Apocalipse diz que Deus enxugará dos olhos do seu povo?","Toda lágrima",["Todo suor","Toda poeira","Todo cansaço"],"Apocalipse 21:4",1],
 ["Apocalipse e Profecia","Que cidade, no Apocalipse, é chamada “a grande” e símbolo de confusão?","Babilônia",["Roma","Jerusalém","Nínive"],"Apocalipse 17:5",2],
 ["Mandamentos e Sábado","Em que material foram gravados os Dez Mandamentos?","Tábuas de pedra",["Papiro","Couro","Bronze"],"Êxodo 31:18",1],
 ["Mandamentos e Sábado","Quem escreveu os Dez Mandamentos nas tábuas, segundo a Bíblia?","O próprio Deus",["Moisés","Arão","Josué"],"Êxodo 31:18",1],
 ["Mandamentos e Sábado","O que Deus fez no sétimo dia da criação?","Descansou",["Criou o homem","Fez as estrelas","Separou as águas"],"Gênesis 2:2",1],
 ["Mandamentos e Sábado","Jesus disse que o sábado foi feito para quem?","O homem",["Os sacerdotes","Os fariseus","Os anjos"],"Marcos 2:27",2],
 ["Mandamentos e Sábado","Quando Deus abençoou e santificou o sábado?","Na criação",["No Sinai","No dilúvio","No Jordão"],"Gênesis 2:3",2],
 ["Mandamentos e Sábado","Em que dia o povo no deserto recolhia porção dobrada de maná?","No sexto dia",["No primeiro dia","No terceiro dia","No sétimo dia"],"Êxodo 16:22-26",3],
 ["Mandamentos e Sábado","Qual mandamento proíbe fazer imagens de escultura para adorá-las?","O segundo",["O primeiro","O terceiro","O sexto"],"Êxodo 20:4-5",2],
 ["Mandamentos e Sábado","Qual é o terceiro mandamento?","Não tomarás o nome do Senhor em vão",["Não furtarás","Honra teu pai e tua mãe","Não matarás"],"Êxodo 20:7",2],
 ["Mandamentos e Sábado","O que Jesus fazia no sábado, conforme seu costume, em Nazaré?","Ia à sinagoga",["Viajava","Pescava","Ficava sozinho no monte"],"Lucas 4:16",2],
 ["Mandamentos e Sábado","Que mulheres descansaram no sábado depois da crucificação, segundo Lucas?","As que acompanhavam Jesus desde a Galileia",["As mulheres de Jerusalém","As irmãs de Pedro","Apenas Maria, mãe de Jesus"],"Lucas 23:55-56",3],
 ["Antigo Testamento","Qual objeto ficava no Lugar Santíssimo do tabernáculo?","A arca da aliança",["O candelabro de ouro","A mesa dos pães","O altar de incenso"],"Êxodo 26:33",1],
 ["Antigo Testamento","O que ficava sobre a arca da aliança, entre dois querubins?","O propiciatório",["A mesa dos pães","O candelabro","O altar de bronze"],"Êxodo 25:21-22",3],
 ["Antigo Testamento","Quantas lâmpadas tinha o candelabro de ouro do tabernáculo?","Sete",["Cinco","Doze","Dez"],"Êxodo 25:37",3],
 ["Antigo Testamento","O que separava o Lugar Santo do Lugar Santíssimo?","O véu",["Uma muralha","Uma porta de bronze","Um altar"],"Êxodo 26:33",2],
 ["Antigo Testamento","Quem foi o artesão escolhido por Deus para dirigir a construção do tabernáculo?","Bezalel",["Hirão","Hur","Calebe"],"Êxodo 31:2-5",3],
 ["Antigo Testamento","Qual rei de Tiro forneceu cedro do Líbano para o templo de Salomão?","Hirão",["Nabucodonosor","Ciro","Faraó"],"1 Reis 5:1-10",3],
 ["Antigo Testamento","Quantos anos Salomão levou para construir o templo?","Sete anos",["Três anos","Dez anos","Quarenta anos"],"1 Reis 6:38",3],
 ["Antigo Testamento","Quem liderou a reconstrução do templo depois do exílio na Babilônia?","Zorobabel",["Neemias","Esdras","Daniel"],"Esdras 3:2; Ageu 1:1",3],
 ["Antigo Testamento","Que profeta animou o povo a reconstruir o templo depois do exílio?","Ageu",["Joel","Naum","Obadias"],"Ageu 1:7-8",3],
 ["Antigo Testamento","Que metal era usado no bezerro que Israel adorou no deserto?","Ouro",["Prata","Bronze","Ferro"],"Êxodo 32:4",1],
 ["Antigo Testamento","De que madeira foi feita a arca da aliança?","Madeira de acácia",["Cedro do Líbano","Oliveira","Ébano"],"Êxodo 25:10",3],
 ["Antigo Testamento","De que madeira Deus mandou Noé fazer a arca?","Madeira de gofer",["Cedro do Líbano","Acácia","Oliveira"],"Gênesis 6:14",3],
 ["Antigo Testamento","Qual tribo foi separada para servir no tabernáculo?","Levi",["Judá","Benjamim","Dã"],"Números 1:50",1],
 ["Personagens","De qual tribo veio o rei Davi?","Judá",["Levi","Benjamim","Efraim"],"Rute 4:18-22",2],
 ["Personagens","De qual tribo veio o rei Saul?","Benjamim",["Judá","Levi","Efraim"],"1 Samuel 9:1-2",2],
 ["Personagens","De qual tribo era o apóstolo Paulo?","Benjamim",["Judá","Levi","Manassés"],"Filipenses 3:5",3],
 ["Personagens","Quais dois filhos de José deram nome a tribos de Israel?","Efraim e Manassés",["Rúben e Simeão","Dã e Gade","Aser e Naftali"],"Gênesis 48:5",2],
 ["Profetas e Reis","Quem foi o primeiro rei de Judá depois da divisão do reino?","Roboão",["Jeroboão","Asa","Josafá"],"1 Reis 12:17",3],
 ["Profetas e Reis","Qual rei foi ungido para destruir a casa de Acabe?","Jeú",["Joás","Onri","Jeroboão"],"2 Reis 9:6-7",3],
 ["Profetas e Reis","Qual rainha tentou exterminar toda a descendência real de Judá?","Atalia",["Jezabel","Vasti","Ester"],"2 Reis 11:1",3],
 ["Profetas e Reis","Qual rei de Judá colocou cantores diante do exército e viu Deus dar a vitória?","Josafá",["Asa","Uzias","Ezequias"],"2 Crônicas 20:21-22",3],
 ["Profetas e Reis","Qual cidade foi a capital do reino do norte, construída pelo rei Onri?","Samaria",["Jerusalém","Belém","Hebrom"],"1 Reis 16:24",3],
 ["Profetas e Reis","Em qual cidade Davi reinou os primeiros sete anos, antes de ir para Jerusalém?","Hebrom",["Belém","Siquém","Siló"],"2 Samuel 5:5",3],
 ["Profetas e Reis","Qual profeta falou de uma praga de gafanhotos como sinal do dia do Senhor?","Joel",["Amós","Oseias","Naum"],"Joel 1:4",3],
 ["Profetas e Reis","Qual profeta ouviu de Deus: “O justo viverá pela sua fé”?","Habacuque",["Naum","Sofonias","Ageu"],"Habacuque 2:4",3],
 ["Profetas e Reis","Qual profeta anunciou que Elias viria antes do grande dia do Senhor?","Malaquias",["Zacarias","Ageu","Joel"],"Malaquias 4:5",3],
 ["Profetas e Reis","Qual profeta anunciou a queda de Nínive?","Naum",["Jonas","Joel","Obadias"],"Naum 1:1",3],
 ["Profetas e Reis","Qual profeta viu um candelabro de ouro e duas oliveiras?","Zacarias",["Ageu","Malaquias","Joel"],"Zacarias 4:2-3",3],
 ["Profetas e Reis","Qual profeta escreveu: “Do Egito chamei o meu filho”, citado por Mateus?","Oseias",["Amós","Isaías","Miqueias"],"Oseias 11:1; Mateus 2:15",3],
 ["Profetas e Reis","Qual profeta escreveu que o rei viria humilde, montado em um jumentinho?","Zacarias",["Isaías","Malaquias","Joel"],"Zacarias 9:9",3],
 ["Lugares","Que outro nome a Bíblia dá ao mar da Galileia?","Lago de Genesaré",["Mar Morto","Mar Vermelho","Mar Grande"],"Lucas 5:1",3],
 ["Lugares","Em que cidade Pedro foi preso e libertado por um anjo?","Jerusalém",["Roma","Antioquia","Jope"],"Atos 12:3-10",2],
 ["Lugares","Para qual cidade Paulo viajou como prisioneiro, ao fim do livro de Atos?","Roma",["Corinto","Atenas","Antioquia"],"Atos 28:14-16",1],
 ["Lugares","Qual cidade grega recebeu duas cartas de Paulo e era marcada por divisões na igreja?","Corinto",["Éfeso","Filipos","Atenas"],"1 Coríntios 1:10-12",2],
 ["Lugares","Qual igreja do Apocalipse foi chamada de morna?","Laodiceia",["Esmirna","Sardes","Filadélfia"],"Apocalipse 3:16",3],
 ["Novo Testamento","Que ave cantou depois da terceira negação de Pedro?","Um galo",["Uma pomba","Uma águia","Um corvo"],"Mateus 26:74-75",1],
 ["Antigo Testamento","Que aves alimentaram o profeta Elias junto ao ribeiro de Querite?","Corvos",["Pombas","Águias","Codornizes"],"1 Reis 17:4-6",2],
 ["Antigo Testamento","Que animal Sansão matou com as próprias mãos?","Um leão",["Um urso","Um lobo","Um touro"],"Juízes 14:5-6",2],
 ["Antigo Testamento","Que animais Davi matou para proteger as ovelhas de seu pai?","Um leão e um urso",["Um lobo e uma raposa","Um leão e um lobo","Um urso e uma serpente"],"1 Samuel 17:34-36",2],
 ["Antigo Testamento","Que fruto os espias israelitas trouxeram do vale de Escol?","Um cacho de uvas",["Maçãs","Azeitonas","Tâmaras"],"Números 13:23",3],
 ["Antigo Testamento","Que planta Deus fez crescer para dar sombra a Jonas?","Uma aboboreira",["Um sicômoro","Uma figueira","Uma palmeira"],"Jonas 4:6",3],
 ["Antigo Testamento","Que instrumentos os sacerdotes tocaram nas voltas ao redor de Jericó?","Trombetas",["Harpas","Tamborins","Flautas"],"Josué 6:4",2],
 ["Antigo Testamento","Que instrumento tocava Davi para acalmar o rei Saul?","Harpa",["Tambor","Trombeta","Flauta"],"1 Samuel 16:23",1],
 ["Antigo Testamento","Que objetos os trezentos homens de Gideão levavam nas mãos?","Trombetas, cântaros e tochas",["Espadas e lanças","Arcos e flechas","Fundas e pedras"],"Juízes 7:16",2],
 ["Milagres e Parábolas","O que o bom pastor dá pelas ovelhas, segundo Jesus?","A própria vida",["O cajado","O manto","O pão"],"João 10:11",2],
 ["Milagres e Parábolas","Na parábola de uma mulher que mistura três medidas de farinha, a que Jesus compara o reino?","Ao fermento",["À semente de mostarda","À pérola","À rede"],"Mateus 13:33",3],
 ["Milagres e Parábolas","Na parábola da pérola de grande valor, o que fez o mercador?","Vendeu tudo para comprá-la",["Escondeu-a no campo","Deu-a de presente","Trocou-a por ouro"],"Mateus 13:45-46",2],
 ["Milagres e Parábolas","Quanto tempo esteve doente o paralítico curado junto ao tanque de Betesda?","Trinta e oito anos",["Doze anos","Quarenta anos","Dezoito anos"],"João 5:5",3],
 ["Milagres e Parábolas","Em qual tanque ficava o paralítico que Jesus curou em Jerusalém?","Betesda",["Siloé","Giom","Jordão"],"João 5:2",3],
 ["Milagres e Parábolas","Quem Jesus ressuscitou na cidade de Naim?","O filho de uma viúva",["Lázaro","A filha de Jairo","Dorcas"],"Lucas 7:11-15",2],
 ["Milagres e Parábolas","Que milagre Eliseu fez com um machado que caiu no rio?","Fez o ferro flutuar",["Secou o rio","Multiplicou o azeite","Curou a água"],"2 Reis 6:5-6",3],
 ["Milagres e Parábolas","O que Eliseu multiplicou para ajudar uma viúva endividada?","O azeite",["O trigo","O pão","O vinho"],"2 Reis 4:1-7",2],
 ["Milagres e Parábolas","O que aconteceu no vale de Gibeão quando Josué orou?","O sol parou",["Choveu fogo","A terra tremeu","O rio se abriu"],"Josué 10:12-13",2],
 ["Milagres e Parábolas","Quantos degraus a sombra recuou como sinal para o rei Ezequias?","Dez degraus",["Três degraus","Sete degraus","Doze degraus"],"2 Reis 20:11",3],
 ["Novo Testamento","Qual Evangelho começa com a frase “No princípio era o Verbo”?","João",["Mateus","Marcos","Lucas"],"João 1:1",1],
 ["Novo Testamento","Qual Evangelho começa com a genealogia que liga Jesus a Abraão?","Mateus",["Marcos","Lucas","João"],"Mateus 1:1-2",2],
 ["Novo Testamento","Qual é o Evangelho mais curto, com dezesseis capítulos?","Marcos",["Mateus","Lucas","João"],"Marcos 1–16",3],
 ["Novo Testamento","Quais dois livros foram dirigidos a Teófilo?","Lucas e Atos",["Mateus e Marcos","João e Atos","Atos e Romanos"],"Lucas 1:3; Atos 1:1",3],
 ["Novo Testamento","Quantas viagens missionárias de Paulo costumam ser contadas?","Três",["Duas","Quatro","Cinco"],"Atos 13–21",2],
 ["Antigo Testamento","Qual espião, além de Josué, entrou na terra prometida entre os adultos que saíram do Egito?","Calebe",["Hur","Arão","Eleazar"],"Números 14:30",3],
 ["Antigo Testamento","Qual foi a profissão de Amós antes de ser profeta?","Pastor e colhedor de sicômoros",["Sacerdote","Escriba","Pescador"],"Amós 7:14",3],
 ["Antigo Testamento","Qual era a profissão de Neemias na corte persa?","Copeiro do rei",["Escriba real","Capitão da guarda","Sacerdote"],"Neemias 1:11",3],
 ["Antigo Testamento","Quem encontrou o livro da Lei no templo, no tempo de Josias?","O sumo sacerdote Hilquias",["O escriba Safã","O profeta Jeremias","O rei Josias"],"2 Reis 22:8",3],
 ["Antigo Testamento","Quem foi o servo do profeta Eliseu que ficou leproso por cobiça?","Giezi",["Baruque","Obadias","Abisai"],"2 Reis 5:20-27",3],
 ["Antigo Testamento","Quem foi o escriba que escreveu as palavras de Jeremias num rolo?","Baruque",["Giezi","Esdras","Obadias"],"Jeremias 36:4",3],
 ["Antigo Testamento","Qual era o ofício de Esdras?","Sacerdote e escriba",["Copeiro do rei","Profeta","Pastor"],"Esdras 7:6",3],
 ["Vida de Jesus","Qual era o ofício de Pedro, André, Tiago e João antes de seguirem Jesus?","Pescadores",["Pastores","Carpinteiros","Cobradores de impostos"],"Marcos 1:16-20",1],
 ["Vida de Jesus","Qual tetrarca da Galileia mandou decapitar João Batista?","Herodes Antipas",["Herodes, o Grande","Pilatos","Agripa"],"Marcos 6:17-27",3],
 ["Vida de Jesus","Qual mulher pediu, por sugestão da mãe, a cabeça de João Batista?","A filha de Herodias",["Maria Madalena","Joana","Salomé, mãe de Tiago"],"Marcos 6:22-25",3],
 ["Vida de Jesus","Que moeda Pedro encontrou na boca do peixe para pagar o imposto do templo?","Um estáter",["Um denário","Um talento","Uma dracma"],"Mateus 17:27",3],
 ["Vida de Jesus","Qual era o ofício de Zaqueu?","Chefe dos cobradores de impostos",["Pescador","Escriba","Pastor"],"Lucas 19:2",1],
 ["Apóstolos e Igreja Primitiva","Quem era o governador de Chipre que creu quando viu Paulo cegar o mago Elimas?","Sérgio Paulo",["Félix","Festo","Gálio"],"Atos 13:7-12",3],
 ["Apóstolos e Igreja Primitiva","Em que cidade Paulo foi apedrejado e dado por morto, mas se levantou?","Listra",["Icônio","Derbe","Filipos"],"Atos 14:19-20",3],
 ["Apóstolos e Igreja Primitiva","Quem era o procônsul de Acaia diante de quem Paulo foi acusado em Corinto?","Gálio",["Félix","Festo","Sérgio Paulo"],"Atos 18:12-16",3],
 ["Apocalipse e Profecia","Quantos anjos tocam trombetas nas sete trombetas do Apocalipse?","Sete anjos",["Quatro anjos","Doze anjos","Três anjos"],"Apocalipse 8:2",2],
 ["Apocalipse e Profecia","Como João vê Jesus ressuscitado entre os sete candeeiros, com os olhos como chama de fogo?","Semelhante a um filho de homem",["Como um cordeiro imolado","Como um leão","Como uma águia"],"Apocalipse 1:13-14",3],
 ["Apocalipse e Profecia","Qual é o nome do rio que corre do trono de Deus na Nova Jerusalém?","Rio da água da vida",["Rio Jordão","Rio da paz","Rio Eufrates"],"Apocalipse 22:1",3],
 ["Apocalipse e Profecia","Que árvore cresce de cada lado do rio em Apocalipse 22?","A árvore da vida",["A figueira","A oliveira","O cedro"],"Apocalipse 22:2",2],
 ["Mandamentos e Sábado","No Êxodo, que mandamento diz “Seis dias trabalharás”?","O quarto mandamento",["O terceiro","O quinto","O sexto"],"Êxodo 20:9",2],
 ["Mandamentos e Sábado","O que o sábado lembra, segundo o quarto mandamento?","A criação em seis dias",["A saída do Egito","O dilúvio","A entrada em Canaã"],"Êxodo 20:11",2],
 ["Mandamentos e Sábado","Qual festa lembra a saída dos hebreus do Egito, com pão sem fermento?","Páscoa e Pães Asmos",["Pentecostes","Tabernáculos","Purim"],"Êxodo 12:17",2],
 ["Mandamentos e Sábado","Quantos dias durava a festa dos tabernáculos?","Sete dias",["Três dias","Dez dias","Quarenta dias"],"Levítico 23:34",3],
 ["Mandamentos e Sábado","Qual festa celebrava a colheita das primícias, cinquenta dias depois da Páscoa?","Pentecostes",["Tabernáculos","Purim","Dedicação"],"Levítico 23:15-16",3],
 ["Mandamentos e Sábado","Qual dia foi o grande dia da expiação em Israel, em que o sumo sacerdote entrava no Santíssimo?","Dia da Expiação",["Dia de Purim","Festa das Trombetas","Páscoa"],"Levítico 16:29-30",3]
]);
B.who.push.apply(B.who,[
 ["Miqueias",[],["Profetizei no tempo de Isaías.","Anunciei que um governante sairia de uma pequena cidade.","Essa cidade é Belém."],"Miqueias 5:2","Reis e Profetas",["Naum","Amós","Oseias"],3],
 ["Dorcas",["tabita"],["Também me chamavam Tabita.","Fazia túnicas e roupas para os necessitados.","Pedro me chamou de volta à vida em Jope."],"Atos 9:36-41","Mulheres da Bíblia",["Lídia","Priscila","Febe"],2],
 ["Onésimo",["onesimo"],["Fui escravo e fugi do meu dono.","Encontrei Paulo na prisão.","Paulo mandou-me de volta com uma carta para Filemom."],"Filemom 10-12","Apóstolos e Igreja",["Tíquico","Epafras","Tito"],3],
 ["Marcos",[],["Também me chamavam João.","Minha mãe tinha uma casa em Jerusalém onde se reuniam em oração.","Escrevi o segundo Evangelho."],"Atos 12:12; Marcos 1:1","Apóstolos e Igreja",["Lucas","Mateus","Silas"],2],
 ["Getsêmani",["getsemani"],["Sou um jardim ao pé de um monte.","Jesus orou em mim com grande angústia.","Nesse lugar Judas veio entregá-lo com soldados."],"Mateus 26:36-47","Lugares e Objetos",["Gólgota","Betânia","Cafarnaum"],2],
 ["Gólgota",["golgota"],["Meu nome significa Lugar da Caveira.","Fico fora dos muros de Jerusalém.","Fui o lugar onde Jesus foi crucificado."],"Mateus 27:33","Lugares e Objetos",["Getsêmani","Betel","Monte Sinai"],1],
 ["Rio Jordão",["jordao","rio jordao"],["Fui atravessado a seco por Israel.","Jesus foi batizado em mim.","Naamã mergulhou sete vezes em mim."],"Josué 3; Mateus 3:13; 2 Reis 5:14","Lugares e Objetos",["Rio Nilo","Rio Eufrates","Rio Jaboque"],1],
 ["Boaz",[],["Fui dono de campos de cevada em Belém.","Mandei meus ceifeiros deixarem espigas para uma estrangeira.","Casei-me com Rute depois de agir como resgatador."],"Rute 2–4","Êxodo e Juízes",["Elimeleque","Obede","Calebe"],2],
 ["Hur",[],["Fui companheiro de Moisés e de Arão.","Segurei os braços de Moisés durante uma batalha.","Fui deixado com Arão como responsável enquanto Moisés subiu ao monte."],"Êxodo 17:10-12; 24:14","Êxodo e Juízes",["Calebe","Josué","Bezalel"],3],
 ["Joquebede",[],["Fui mãe de três filhos que lideraram Israel.","Escondi meu bebê por três meses.","Coloquei-o num cesto de junco às margens do rio."],"Êxodo 2:1-3; 6:20","Mulheres da Bíblia",["Miriã","Zípora","Ana"],2],
 ["Zípora",["zipora"],["Era filha de um sacerdote de Midiã.","Casei-me com um estrangeiro que pastoreava as ovelhas do meu pai.","Circuncidei meu filho com uma pedra afiada."],"Êxodo 2:21; 4:25","Mulheres da Bíblia",["Miriã","Joquebede","Raabe"],3],
 ["Otniel",[],["Fui sobrinho de Calebe.","Conquistei uma cidade e recebi a filha de Calebe por esposa.","Fui o primeiro juiz de Israel depois de Josué."],"Juízes 1:12-13; 3:9-11","Êxodo e Juízes",["Eúde","Sangar","Baraque"],3],
 ["Elcana",[],["Tinha duas esposas.","Subia todos os anos a Siló para adorar.","Fui pai de um grande profeta e amava minha esposa que não tinha filhos."],"1 Samuel 1:1-8","Reis e Profetas",["Eli","Jessé","Cis"],3],
 ["Hulda",[],["Fui profetisa em Jerusalém.","Meu marido cuidava das vestes do templo.","O rei Josias mandou me consultar sobre o livro da Lei que foi encontrado."],"2 Reis 22:14-20","Mulheres da Bíblia",["Débora","Miriã","Ana"],3],
 ["Joabe",[],["Fui sobrinho do rei e comandante do seu exército.","Matei Abner e também Absalão.","Servi a Davi durante quase todo o seu reinado."],"2 Samuel 2:23; 18:14","Reis e Profetas",["Abisai","Abner","Urias"],3],
 ["Urias",[],["Era hitita e soldado fiel de um rei.","Recusei ir para casa enquanto a arca e meus companheiros estavam no campo.","Fui posto na frente da batalha por ordem do rei Davi."],"2 Samuel 11","Reis e Profetas",["Joabe","Abner","Abisai"],2],
 ["Mefibosete",[],["Sou neto de um rei e filho de Jônatas.","Fiquei aleijado dos pés por uma queda quando criança.","Davi me convidou para comer sempre à sua mesa."],"2 Samuel 4:4; 9:7","Reis e Profetas",["Absalão","Adonias","Salomão"],3],
 ["Hirão",["hirao"],["Fui rei de Tiro.","Fui amigo de Davi e de Salomão.","Mandei cedros do Líbano para a construção do templo."],"1 Reis 5:1-10","Reis e Profetas",["Ciro","Faraó","Nabucodonosor"],3],
 ["Zorobabel",[],["Sou descendente de Davi e governador de Judá.","Voltei da Babilônia com o primeiro grupo de exilados.","Liderei a reconstrução do templo."],"Esdras 3:2; Ageu 1:1","Reis e Profetas",["Neemias","Esdras","Daniel"],3],
 ["Ageu",[],["Fui profeta depois do exílio.","Disse ao povo que reconstruísse a casa de Deus em vez de enfeitar as próprias casas.","Meu livro tem apenas dois capítulos."],"Ageu 1–2","Reis e Profetas",["Zacarias","Malaquias","Joel"],3],
 ["Oseias",[],["Deus mandou que eu me casasse com uma mulher infiel.","Meus filhos receberam nomes simbólicos.","Anunciei o amor fiel de Deus por Israel."],"Oseias 1–3","Reis e Profetas",["Amós","Joel","Miqueias"],3],
 ["Joel",[],["Descrevi uma praga de gafanhotos como sinal do dia do Senhor.","Convoquei o povo a rasgar o coração, e não as vestes.","Profetizei que Deus derramaria o seu Espírito sobre toda a carne."],"Joel 1–2","Reis e Profetas",["Amós","Oseias","Naum"],3],
 ["Habacuque",[],["Perguntei a Deus por que permitia tanta violência.","Subi a uma torre para esperar a resposta.","Ouvi: O justo viverá pela sua fé."],"Habacuque 1–2","Reis e Profetas",["Naum","Sofonias","Ageu"],3],
 ["Malaquias",[],["Meu livro encerra o Antigo Testamento.","Falei sobre dízimos e ofertas.","Anunciei que Elias viria antes do grande dia do Senhor."],"Malaquias 3–4","Reis e Profetas",["Zacarias","Ageu","Joel"],3],
 ["Zacarias, o profeta",["zacarias profeta"],["Vi um candelabro de ouro e duas oliveiras.","Anunciei que o rei viria humilde, montado em um jumentinho.","Profetizei depois do exílio, no tempo de Ageu."],"Zacarias 4; 9:9","Reis e Profetas",["Ageu","Malaquias","Joel"],3],
 ["Giezi",[],["Fui servo de um profeta.","Corri atrás de um general sírio para pedir presentes.","Fiquei leproso por causa da minha cobiça."],"2 Reis 5:20-27","Reis e Profetas",["Baruque","Obadias","Abisai"],3],
 ["Baruque",[],["Fui escriba de um profeta.","Escrevi num rolo as palavras que ele ditava.","Li o rolo no templo diante do povo."],"Jeremias 36:4-10","Reis e Profetas",["Giezi","Esdras","Obadias"],3],
 ["Sadraque, Mesaque e Abede-Nego",[],["Fomos levados cativos para a Babilônia quando jovens.","Recusamos curvar-nos diante de uma estátua de ouro.","Fomos lançados numa fornalha e um quarto ser estava conosco."],"Daniel 3","Reis e Profetas",["Davi, Salomão e Jeú","Pedro, Tiago e João","Noé, Sem e Cam"],1],
 ["Belsazar",[],["Fui rei da Babilônia.","Dei um banquete usando os vasos sagrados do templo.","Vi uma mão escrever na parede: Mene, Mene, Tequel, Parsim."],"Daniel 5","Reis e Profetas",["Nabucodonosor","Dario","Ciro"],2],
 ["Dario, o medo",["dario"],["Fui rei dos medos.","Fui enganado por oficiais e assinei um decreto contra a oração.","Passei a noite em jejum porque meu servo estava na cova dos leões."],"Daniel 6","Reis e Profetas",["Belsazar","Nabucodonosor","Assuero"],2],
 ["Ciro",[],["Fui rei da Pérsia.","Deus me chamou pelo nome antes que eu nascesse.","Permiti que os judeus voltassem a Jerusalém para reconstruir o templo."],"Isaías 45:1; Esdras 1:1-3","Reis e Profetas",["Dario","Artaxerxes","Nabucodonosor"],3],
 ["Assuero",["xerxes"],["Reinei sobre cento e vinte e sete províncias.","Dei um grande banquete e minha rainha recusou comparecer.","Escolhi como rainha uma jovem judia sem saber a sua origem."],"Ester 1–2","Reis e Profetas",["Dario","Artaxerxes","Ciro"],3],
 ["Hamã",["hama"],["Fui o conselheiro mais poderoso do rei.","Odiava um judeu que não se curvava diante de mim.","Fui enforcado na forca que mandei construir."],"Ester 3; 7:10","Reis e Profetas",["Mardoqueu","Assuero","Zeres"],2],
 ["Atalia",[],["Fui filha de Acabe e Jezabel.","Mandei matar a família real de Judá.","Reinei seis anos até que meu neto foi coroado."],"2 Reis 11","Mulheres da Bíblia",["Jezabel","Vasti","Dalila"],3],
 ["Jeú",["jeu"],["Fui ungido rei por ordem de Eliseu.","Executei a casa de Acabe.","Era conhecido por conduzir a carruagem com fúria."],"2 Reis 9:1-20","Reis e Profetas",["Acabe","Jeroboão","Onri"],3],
 ["Jeroboão",["jeroboao"],["Fui oficial de Salomão.","Fiz dois bezerros de ouro, em Betel e em Dã.","Fui o primeiro rei do reino do norte."],"1 Reis 11–12","Reis e Profetas",["Roboão","Acabe","Jeú"],3],
 ["Roboão",["roboao"],["Sou filho de Salomão.","Não ouvi os conselheiros idosos.","Por minha dureza, o reino se dividiu."],"1 Reis 12","Reis e Profetas",["Jeroboão","Asa","Abias"],3],
 ["Uzias",[],["Reinei em Judá por cinquenta e dois anos.","Fiquei forte e me tornei orgulhoso.","Entrei no templo para queimar incenso e fiquei leproso."],"2 Crônicas 26","Reis e Profetas",["Josafá","Asa","Joás"],3],
 ["Josafá",["josafa"],["Fui rei de Judá.","Enviei levitas para ensinar a Lei às cidades.","Coloquei cantores diante do exército e Deus deu a vitória."],"2 Crônicas 17; 20","Reis e Profetas",["Uzias","Asa","Ezequias"],3],
 ["Sísera",["sisera"],["Comandei um exército com novecentos carros de ferro.","Perdi a batalha contra Baraque.","Morri na tenda de uma mulher."],"Juízes 4","Êxodo e Juízes",["Jabim","Abner","Joabe"],2],
 ["Jairo",[],["Era chefe da sinagoga.","Pedi a Jesus que viesse à minha casa.","Minha filha de doze anos foi ressuscitada."],"Marcos 5:22-42","Vida de Jesus",["Zaqueu","Nicodemos","Bartimeu"],2],
 ["Herodias",[],["Deixei meu marido para casar com o irmão dele.","Fui criticada por João Batista.","Por meio da minha filha, pedi a cabeça de João."],"Marcos 6:17-28","Mulheres da Bíblia",["Jezabel","Atalia","Dalila"],2],
 ["Herodes Antipas",[],["Fui tetrarca da Galileia.","Mandei prender e decapitar João Batista.","Pilatos me enviou Jesus para ser interrogado."],"Lucas 23:7-11; Marcos 6:27","Vida de Jesus",["Herodes, o Grande","Pilatos","Agripa"],3],
 ["Rei Agripa",["agripa"],["Era rei e descendente de Herodes.","Ouvi Paulo defender-se em Cesareia.","Disse que por pouco não fui persuadido."],"Atos 26:28","Apóstolos e Igreja",["Félix","Festo","Herodes Antipas"],3],
 ["Tito",[],["Fui companheiro de Paulo, grego de nascimento.","Fui deixado em Creta para organizar as igrejas.","Recebi uma carta de Paulo com meu nome."],"Tito 1:4-5","Apóstolos e Igreja",["Timóteo","Silas","Filemom"],3],
 ["Filemom",["filemon"],["Fui dono de um escravo fugitivo.","Paulo me chamou de amado colaborador.","Recebi uma carta pedindo que acolhesse meu escravo como irmão."],"Filemom 1,16","Apóstolos e Igreja",["Tito","Epafras","Tíquico"],3],
 ["Áquila",["aquila"],["Era judeu natural do Ponto.","Tinha o mesmo ofício de Paulo: fazer tendas.","Fui expulso de Roma com minha esposa Priscila."],"Atos 18:2-3","Apóstolos e Igreja",["Silas","Apolo","Tíquico"],3],
 ["Febe",[],["Fui serva da igreja em Cencreia.","Paulo me chamou de auxiliadora de muitos.","Provavelmente levei a carta de Paulo aos romanos."],"Romanos 16:1-2","Mulheres da Bíblia",["Lídia","Priscila","Dorcas"],3],
 ["Jericó",["jerico"],["Fui chamada cidade das palmeiras.","Sete sacerdotes com trombetas deram voltas ao meu redor.","Meus muros caíram e uma mulher chamada Raabe foi poupada."],"Josué 6","Lugares e Objetos",["Ai","Gibeão","Hebrom"],1],
 ["Belém",["belem"],["Meu nome significa Casa do Pão.","Davi nasceu em mim.","Ali nasceu o Salvador, como Miqueias havia anunciado."],"Miqueias 5:2; Lucas 2:4","Lugares e Objetos",["Nazaré","Hebrom","Cafarnaum"],1],
 ["Nazaré",["nazare"],["Fui uma pequena cidade da Galileia.","Natanael perguntou se de mim poderia sair algo bom.","Jesus cresceu em mim."],"João 1:46; Lucas 2:51","Lugares e Objetos",["Belém","Caná","Naim"],1],
 ["Cafarnaum",[],["Fico à beira do mar da Galileia.","Pedro tinha uma casa em mim.","Jesus fez de mim sua cidade durante seu ministério na Galileia."],"Mateus 4:13; Marcos 1:21-29","Lugares e Objetos",["Nazaré","Betsaida","Corazim"],2],
 ["Tabernáculo",[],["Fui uma tenda de reunião desmontável.","Fui construído segundo o modelo mostrado no monte.","Dentro de mim ficava a arca da aliança."],"Êxodo 25:8-9","Lugares e Objetos",["Templo de Salomão","Arca de Noé","Torre de Babel"],2],
 ["Templo de Salomão",["templo"],["Levei sete anos para ser construído.","Fui feito com cedro do Líbano e ouro.","Fui dedicado com uma grande oração do rei."],"1 Reis 6–8","Lugares e Objetos",["Tabernáculo","Torre de Babel","Palácio de Davi"],2],
 ["Mar da Galileia",["lago de genesare"],["Também me chamam lago de Genesaré.","Pedro e André lançavam redes em mim.","Jesus acalmou uma tempestade sobre mim."],"Marcos 4:39; Lucas 5:1","Lugares e Objetos",["Mar Morto","Mar Vermelho","Rio Jordão"],1],
 ["Monte das Oliveiras",[],["Fico diante de Jerusalém, do outro lado do vale.","Jesus ensinou sobre o fim dos tempos em mim.","De mim Jesus subiu ao céu."],"Atos 1:9-12","Lugares e Objetos",["Monte Sinai","Monte Carmelo","Monte Nebo"],2],
 ["Patmos",[],["Sou uma pequena ilha do mar Egeu.","Um apóstolo foi exilado em mim.","Nele recebeu uma grande revelação."],"Apocalipse 1:9","Lugares e Objetos",["Malta","Chipre","Creta"],2],
 ["Jerusalém",["jerusalem"],["Sou chamada cidade de Davi e cidade do grande Rei.","Fui destruída pelos babilônios e reconstruída por Neemias.","Jesus foi crucificado fora dos meus muros."],"Salmo 48:2; Neemias 6:15","Lugares e Objetos",["Belém","Samaria","Hebrom"],2]
]);
B.said.push.apply(B.said,[
 ["Deixa ir o meu povo.","Moisés",["Arão","Josué","Jetro"],"Êxodo 5:1",2],
 ["Lembra-te de mim quando entrares no teu reino.","O ladrão na cruz",["Pilatos","Barrabás","O centurião"],"Lucas 23:42",2],
 ["Verdadeiramente este era o Filho de Deus.","O centurião",["Pilatos","Herodes","Caifás"],"Mateus 27:54",2],
 ["Quase me persuades a me fazer cristão.","Rei Agripa",["Félix","Festo","Pilatos"],"Atos 26:28",3],
 ["O Senhor o deu, e o Senhor o tomou; bendito seja o nome do Senhor.","Jó",["Davi","Elias","Jeremias"],"Jó 1:21",1],
 ["Sou eu, porventura, guardador do meu irmão?","Caim",["Abel","Lameque","Esaú"],"Gênesis 4:9",1],
 ["Quem és tu, Senhor?","Saulo (Paulo)",["Pedro","Estêvão","Ananias"],"Atos 9:5",2],
 ["Senhor, salva-nos, que perecemos!","Os discípulos",["Os fariseus","Os soldados","Os pastores"],"Mateus 8:25",2],
 ["Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos.","Paulo",["Pedro","Tiago","João"],"Filipenses 4:4",2],
 ["Mais importa obedecer a Deus do que aos homens.","Pedro",["Paulo","João","Tiago"],"Atos 5:29",2],
 ["A obediência é melhor do que o sacrifício.","Samuel",["Natã","Elias","Eli"],"1 Samuel 15:22",3],
 ["Eis-nos aqui nas tuas mãos; faze conosco o que parecer bom e reto aos teus olhos.","Os gibeonitas",["Os filisteus","Os midianitas","Os amonitas"],"Josué 9:25",3],
 ["Pai nosso, que estás nos céus, santificado seja o teu nome.","Jesus",["Paulo","Davi","Moisés"],"Mateus 6:9",1],
 ["Eu sou a luz do mundo.","Jesus",["João Batista","Moisés","Paulo"],"João 8:12",1],
 ["Pequei contra o Senhor.","Davi",["Saul","Salomão","Natã"],"2 Samuel 12:13",2],
 ["Vaidade de vaidades, tudo é vaidade.","Salomão",["Davi","Jó","Isaías"],"Eclesiastes 1:2",2],
 ["Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim.","Paulo",["Pedro","João","Tiago"],"Gálatas 2:20",2],
 ["Porque o salário do pecado é a morte.","Paulo",["Pedro","João","Tiago"],"Romanos 6:23",2],
 ["Resisti ao diabo, e ele fugirá de vós.","Tiago",["Pedro","Paulo","João"],"Tiago 4:7",2],
 ["Amados, amemo-nos uns aos outros, porque o amor é de Deus.","João",["Pedro","Paulo","Tiago"],"1 João 4:7",2],
 ["O nosso Deus, a quem nós servimos, é poderoso para nos livrar da fornalha de fogo ardente.","Sadraque, Mesaque e Abede-Nego",["Daniel","Nabucodonosor","Ciro"],"Daniel 3:17",2],
 ["Rabi, tu és o Filho de Deus, tu és o Rei de Israel.","Natanael",["Filipe","André","Pedro"],"João 1:49",3],
 ["Eu sei que ressuscitará na ressurreição, no último dia.","Marta",["Maria","Lázaro","Pedro"],"João 11:24",3],
 ["Senhor, não sou digno de que entres debaixo do meu telhado.","Um centurião",["Zaqueu","Nicodemos","Pilatos"],"Mateus 8:8",2],
 ["O teu Deus, a quem tu continuamente serves, ele te livrará.","Rei Dario",["Nabucodonosor","Belsazar","Ciro"],"Daniel 6:16",3],
 ["Lembra-te de mim, Deus meu, para bem.","Neemias",["Esdras","Davi","Mardoqueu"],"Neemias 13:31",3],
 ["Peço-te que me caiba por herança uma porção dobrada do teu espírito.","Eliseu",["Giezi","Samuel","Josué"],"2 Reis 2:9",3],
 ["Vive o Senhor, em cuja presença estou.","Elias",["Eliseu","Samuel","Natã"],"1 Reis 17:1",3],
 ["O meu coração exulta no Senhor.","Ana (mãe de Samuel)",["Maria, mãe de Jesus","Isabel","Rute"],"1 Samuel 2:1",3],
 ["A espada do Senhor e de Gideão!","Gideão",["Baraque","Sansão","Jefté"],"Juízes 7:20",3],
 ["Quem dizem os homens ser o Filho do Homem?","Jesus",["Pedro","João Batista","Tomé"],"Mateus 16:13",2],
 ["Eu sou a videira, vós, as varas.","Jesus",["João Batista","Paulo","Pedro"],"João 15:5",1],
 ["Tende bom ânimo; eu venci o mundo.","Jesus",["Paulo","Pedro","João"],"João 16:33",2],
 ["Não temais, porque eis aqui vos trago novas de grande alegria.","Um anjo",["Os pastores","Os magos","Zacarias"],"Lucas 2:10",1],
 ["Glória a Deus nas alturas, paz na terra, boa vontade para com os homens.","Os anjos",["Os pastores","Os magos","Simeão"],"Lucas 2:14",1],
 ["Vimos a sua estrela no oriente e viemos adorá-lo.","Os magos",["Os pastores","Herodes","Simeão"],"Mateus 2:2",2],
 ["Este é o meu Filho amado, em quem me comprazo.","A voz do céu (Deus Pai)",["João Batista","Um anjo","Pedro"],"Mateus 3:17",2],
 ["Se és Filho de Deus, manda que estas pedras se tornem em pães.","Satanás",["Pilatos","Herodes","Um fariseu"],"Mateus 4:3",2],
 ["Está consumado!","Jesus",["Pilatos","Pedro","João"],"João 19:30",1],
 ["Pai, nas tuas mãos entrego o meu espírito.","Jesus",["Estêvão","Pedro","Paulo"],"Lucas 23:46",2],
 ["Não está aqui, mas ressuscitou.","Um anjo",["Maria Madalena","Pedro","João"],"Lucas 24:6",1]
]);
B.timeline.push.apply(B.timeline,[
 {"t":"A história de Rute","items":["Noemi e a família vão para Moabe","Morrem o marido e os filhos de Noemi","Rute decide seguir Noemi","Rute respiga no campo de Boaz","Boaz resgata Rute","Nasce Obede"],"ref":"Rute 1–4","d":2},
 {"t":"A história de Jó","items":["Deus permite que Satanás prove Jó","Jó perde bens e filhos","Jó perde a saúde","Os três amigos o visitam","Deus fala do meio do redemoinho","Deus restaura Jó em dobro"],"ref":"Jó 1–42","d":2},
 {"t":"A reconstrução dos muros","items":["Neemias ouve que os muros estão caídos","Neemias ora e pede licença ao rei","Neemias examina os muros de noite","O povo reconstrói os muros","Os inimigos tentam impedir a obra","Muros concluídos em cinquenta e dois dias","Esdras lê a Lei ao povo"],"ref":"Neemias 1–8","d":3},
 {"t":"O filho pródigo","items":["Pede a herança ao pai","Parte para uma terra distante","Gasta tudo","Passa fome cuidando de porcos","Decide voltar para casa","O pai o recebe com festa"],"ref":"Lucas 15:11-32","d":1},
 {"t":"Ana e Samuel","items":["Ana ora pedindo um filho","Eli a abençoa","Nasce Samuel","Ana leva Samuel ao templo","Deus chama Samuel de noite","Samuel unge Saul como rei"],"ref":"1 Samuel 1–10","d":2},
 {"t":"Paulo e Silas em Filipos","items":["Paulo expulsa um espírito de uma jovem","Paulo e Silas são açoitados","São lançados na prisão","Cantam à meia-noite","Um terremoto abre as portas","O carcereiro e sua casa são batizados"],"ref":"Atos 16:16-34","d":2},
 {"t":"Elias e a seca","items":["Elias anuncia a seca a Acabe","Os corvos alimentam Elias","A viúva de Sarepta o hospeda","Desafio no monte Carmelo","Cai fogo do céu","Chove depois da seca"],"ref":"1 Reis 17–18","d":2},
 {"t":"Jesus no jardim e na cruz","items":["A última ceia","Jesus ora no Getsêmani","Judas o entrega","Jesus é julgado por Pilatos","Jesus é crucificado","Jesus é sepultado"],"ref":"Mateus 26–27","d":1},
 {"t":"O bom samaritano","items":["Um homem desce de Jerusalém para Jericó","Assaltantes o deixam ferido","Um sacerdote passa de largo","Um levita passa de largo","O samaritano cuida dele","O samaritano o leva a uma hospedaria"],"ref":"Lucas 10:30-35","d":1},
 {"t":"A parábola dos talentos","items":["O senhor distribui talentos","O servo dos cinco negocia","O servo dos dois negocia","O servo do um enterra o dinheiro","O senhor volta e acerta contas","O servo inútil é lançado fora"],"ref":"Mateus 25:14-30","d":2},
 {"t":"De Jesus a Pentecostes","items":["Jesus sobe ao céu","Os discípulos aguardam em Jerusalém","Matias é escolhido","Chega o dia de Pentecostes","O Espírito Santo desce","Pedro prega e cerca de três mil se batizam"],"ref":"Atos 1–2","d":2},
 {"t":"A conversão de Paulo","items":["Saulo persegue a igreja","Saulo vai a Damasco","Uma luz o cega no caminho","Ananias ora por ele","Saulo recupera a visão","Saulo é batizado e prega"],"ref":"Atos 9:1-20","d":2},
 {"t":"A visita dos magos","items":["Os magos veem a estrela","Chegam a Jerusalém e perguntam por Jesus","Herodes consulta os sacerdotes","Os magos encontram Jesus em Belém","Os magos oferecem presentes","Voltam por outro caminho"],"ref":"Mateus 2:1-12","d":2}
]);
B.vf=[
 ["Antigo Testamento","Noé tinha três filhos: Sem, Cam e Jafé.",1,"Gênesis 6:10",1],
 ["Antigo Testamento","Noé tinha cinco filhos que entraram na arca com ele.",0,"Gênesis 6:10",1,"Eram três filhos: Sem, Cam e Jafé."],
 ["Antigo Testamento","Moisés foi criado na casa da filha do faraó.",1,"Êxodo 2:10",1],
 ["Antigo Testamento","Moisés nasceu dentro do palácio do faraó.",0,"Êxodo 2:1-2",2,"Moisés nasceu entre os hebreus escravos e foi adotado depois."],
 ["Antigo Testamento","Davi era o filho mais novo de Jessé.",1,"1 Samuel 16:11",1],
 ["Antigo Testamento","Davi era o filho mais velho de Jessé.",0,"1 Samuel 16:11",2,"Davi era o mais novo dos filhos de Jessé."],
 ["Antigo Testamento","Os muros de Jericó caíram no sétimo dia, depois de sete voltas da procissão.",1,"Josué 6:15-20",2],
 ["Antigo Testamento","Os muros de Jericó caíram ao terceiro dia de cerco.",0,"Josué 6:15-20",2,"Caíram no sétimo dia, depois de sete voltas."],
 ["Antigo Testamento","Jonas ficou três dias e três noites dentro do grande peixe.",1,"Jonas 1:17",1],
 ["Antigo Testamento","Jonas ficou sete dias dentro do grande peixe.",0,"Jonas 1:17",1,"Foram três dias e três noites."],
 ["Antigo Testamento","A rainha de Sabá visitou o rei Salomão.",1,"1 Reis 10:1",1],
 ["Antigo Testamento","A rainha de Sabá visitou o rei Davi.",0,"1 Reis 10:1",2,"Ela visitou Salomão."],
 ["Antigo Testamento","Elias foi levado ao céu em um redemoinho.",1,"2 Reis 2:11",1],
 ["Antigo Testamento","Eliseu foi levado ao céu em um redemoinho sem ver a morte.",0,"2 Reis 2:11",2,"Quem foi levado foi Elias."],
 ["Antigo Testamento","Daniel foi lançado na cova dos leões no reinado de Dario.",1,"Daniel 6",3],
 ["Antigo Testamento","Daniel foi lançado na cova dos leões por ordem de Nabucodonosor.",0,"Daniel 6",3,"Foi no reinado de Dario."],
 ["Antigo Testamento","Saul foi o primeiro rei de Israel.",1,"1 Samuel 10:1",1],
 ["Antigo Testamento","Davi foi o primeiro rei de Israel.",0,"1 Samuel 10:1",1,"O primeiro rei foi Saul."],
 ["Antigo Testamento","Deus mudou o nome de Jacó para Israel.",1,"Gênesis 32:28",1],
 ["Antigo Testamento","Deus mudou o nome de Isaque para Israel.",0,"Gênesis 32:28",2,"Foi o nome de Jacó que mudou para Israel."],
 ["Antigo Testamento","Salomão construiu o primeiro templo de Jerusalém.",1,"1 Reis 6:1",1],
 ["Antigo Testamento","Davi construiu o primeiro templo de Jerusalém.",0,"1 Reis 6:1",1,"Quem construiu foi Salomão, seu filho."],
 ["Antigo Testamento","Absalão era filho de Davi.",1,"2 Samuel 13:1",2],
 ["Antigo Testamento","Absalão era filho do rei Saul.",0,"2 Samuel 13:1",2,"Absalão era filho de Davi."],
 ["Antigo Testamento","Ismael era filho de Abraão e de Hagar.",1,"Gênesis 16:15",2],
 ["Antigo Testamento","Ismael era filho de Abraão e de Sara.",0,"Gênesis 16:15",2,"A mãe de Ismael era Hagar; Sara foi mãe de Isaque."],
 ["Antigo Testamento","O mar Vermelho se abriu quando Moisés estendeu a mão sobre ele.",1,"Êxodo 14:21",1],
 ["Antigo Testamento","O mar Vermelho se abriu quando Josué ergueu o cajado.",0,"Êxodo 14:21",2,"Foi Moisés; Josué atravessou o Jordão."],
 ["Antigo Testamento","Nabucodonosor foi rei da Babilônia.",1,"Daniel 1:1",1],
 ["Antigo Testamento","Nabucodonosor foi rei do Egito.",0,"Daniel 1:1",1,"Ele foi rei da Babilônia."],
 ["Antigo Testamento","Moisés conduziu o povo de Israel para dentro de Canaã.",0,"Deuteronômio 34:4-5",2,"Moisés morreu antes; Josué conduziu o povo."],
 ["Antigo Testamento","Josué conduziu Israel para dentro da terra de Canaã.",1,"Josué 1–3",1],
 ["Antigo Testamento","Raquel foi a mãe de José e de Benjamim.",1,"Gênesis 35:24",2],
 ["Antigo Testamento","Lia foi a mãe de José.",0,"Gênesis 30:22-24",3,"A mãe de José foi Raquel."],
 ["Antigo Testamento","Ezequiel viu um vale cheio de ossos secos que voltaram à vida.",1,"Ezequiel 37",2],
 ["Antigo Testamento","Jeremias viu um vale cheio de ossos secos que voltaram à vida.",0,"Ezequiel 37",3,"A visão foi de Ezequiel."],
 ["Antigo Testamento","O Salmo 23 começa com “O Senhor é o meu pastor”.",1,"Salmo 23:1",1],
 ["Antigo Testamento","O Salmo 23 começa com “Bem-aventurado o homem que não anda segundo o conselho dos ímpios”.",0,"Salmos 1:1; 23:1",2,"Essa é a abertura do Salmo 1."],
 ["Antigo Testamento","A arca de Noé pousou nos montes de Ararate.",1,"Gênesis 8:4",2],
 ["Antigo Testamento","A arca de Noé pousou no monte Sinai.",0,"Gênesis 8:4",2,"Pousou nos montes de Ararate."],
 ["Antigo Testamento","Abraão saiu de Ur dos caldeus rumo a Canaã.",1,"Gênesis 11:31",2],
 ["Antigo Testamento","Abraão saiu de Nínive rumo a Canaã.",0,"Gênesis 11:31",2,"Ele saiu de Ur dos caldeus."],
 ["Antigo Testamento","Isaque foi o filho prometido de Abraão e de Sara.",1,"Gênesis 21:2-3",1],
 ["Antigo Testamento","Isaque foi vendido pelos irmãos como escravo para o Egito.",0,"Gênesis 37:28",1,"Quem foi vendido foi José."],
 ["Antigo Testamento","Neemias reconstruiu os muros de Jerusalém.",1,"Neemias 6:15",2],
 ["Antigo Testamento","Esdras terminou de reconstruir os muros de Jerusalém em cinquenta e dois dias.",0,"Neemias 6:15",3,"Quem liderou a reconstrução dos muros foi Neemias."],
 ["Antigo Testamento","Eliseu curou Naamã da lepra.",1,"2 Reis 5:14",2],
 ["Antigo Testamento","Elias curou Naamã da lepra no rio Eufrates.",0,"2 Reis 5:14",3,"Foi Eliseu, no rio Jordão."],
 ["Antigo Testamento","Gideão derrotou os midianitas com trezentos homens.",1,"Juízes 7:7",2],
 ["Antigo Testamento","Gideão derrotou os midianitas com dez mil homens.",0,"Juízes 7:7",2,"Deus reduziu o exército a trezentos homens."],
 ["Antigo Testamento","Sansão era nazireu desde o nascimento.",1,"Juízes 13:5",2],
 ["Antigo Testamento","Sansão era sacerdote da tribo de Levi.",0,"Juízes 13:2",3,"Sansão era da tribo de Dã e nazireu."],
 ["Antigo Testamento","Rute era moabita.",1,"Rute 1:4",2],
 ["Antigo Testamento","Rute era filisteia.",0,"Rute 1:4",2,"Rute era de Moabe."],
 ["Antigo Testamento","Boaz era parente de Noemi.",1,"Rute 2:1",2],
 ["Antigo Testamento","Boaz era rei de Moabe.",0,"Rute 2:1",3,"Boaz era um israelita de Belém, parente de Noemi."],
 ["Antigo Testamento","Ester foi criada por Mardoqueu, seu primo.",1,"Ester 2:7",2],
 ["Antigo Testamento","Ester foi criada por Hamã, o conselheiro do rei.",0,"Ester 2:7",3,"Mardoqueu a criou; Hamã foi o inimigo dos judeus."],
 ["Antigo Testamento","O livro de Provérbios é atribuído em grande parte a Salomão.",1,"Provérbios 1:1",1],
 ["Antigo Testamento","O livro de Provérbios foi escrito principalmente por Moisés.",0,"Provérbios 1:1",2,"É atribuído em grande parte a Salomão."],
 ["Antigo Testamento","Jó vivia na terra de Uz.",1,"Jó 1:1",3],
 ["Antigo Testamento","Jó era um rei de Israel.",0,"Jó 1:1",2,"Jó vivia em Uz e era um homem íntegro e rico, não um rei de Israel."],
 ["Antigo Testamento","Êxodo é o segundo livro da Bíblia.",1,"Êxodo 1:1",1],
 ["Antigo Testamento","Levítico é o segundo livro da Bíblia.",0,"Êxodo 1:1",1,"O segundo livro é Êxodo."],
 ["Antigo Testamento","Jacó viu uma escada que chegava ao céu em Betel.",1,"Gênesis 28:12-19",2],
 ["Antigo Testamento","Jacó viu a escada que chegava ao céu em Jericó.",0,"Gênesis 28:12-19",2,"O lugar foi Betel."],
 ["Antigo Testamento","Mardoqueu denunciou uma conspiração contra o rei Assuero.",1,"Ester 2:21-23",3],
 ["Antigo Testamento","Hamã foi enforcado na forca que preparou para Mardoqueu.",1,"Ester 7:10",3],
 ["Antigo Testamento","Natã foi o profeta que ungiu Saul como rei.",0,"1 Samuel 10:1",3,"Quem ungiu Saul foi Samuel."],
 ["Antigo Testamento","O profeta Samuel ungiu Saul e Davi como reis.",1,"1 Samuel 10:1; 16:13",2],
 ["Antigo Testamento","O dilúvio começou com chuva que durou quarenta dias e quarenta noites.",1,"Gênesis 7:12",1],
 ["Antigo Testamento","No dilúvio, a chuva durou sete dias e sete noites.",0,"Gênesis 7:12",1,"Choveu quarenta dias e quarenta noites."],
 ["Antigo Testamento","Joel profetizou que o Espírito seria derramado sobre toda a carne.",1,"Joel 2:28",3],
 ["Antigo Testamento","Naum profetizou que o Espírito seria derramado sobre toda a carne.",0,"Joel 2:28",3,"Essa profecia é de Joel."],
 ["Novo Testamento","Jesus foi batizado por João Batista no rio Jordão.",1,"Mateus 3:13",1],
 ["Novo Testamento","Jesus foi batizado por Pedro no rio Jordão.",0,"Mateus 3:13",1,"Quem batizou Jesus foi João Batista."],
 ["Novo Testamento","Paulo escreveu a carta aos Romanos.",1,"Romanos 1:1",1],
 ["Novo Testamento","Pedro escreveu a carta aos Romanos.",0,"Romanos 1:1",2,"A carta é de Paulo."],
 ["Novo Testamento","Jesus alimentou cinco mil homens com cinco pães e dois peixes.",1,"Mateus 14:17-21",1],
 ["Novo Testamento","Jesus alimentou cinco mil homens com sete pães e três peixes.",0,"Mateus 14:17-21",2,"Foram cinco pães e dois peixes."],
 ["Novo Testamento","Zaqueu era chefe dos publicanos em Jericó.",1,"Lucas 19:2",2],
 ["Novo Testamento","Zaqueu era um pescador da Galileia.",0,"Lucas 19:2",1,"Zaqueu era cobrador de impostos."],
 ["Novo Testamento","Lázaro estava morto havia quatro dias quando Jesus o ressuscitou.",1,"João 11:39",2],
 ["Novo Testamento","Lázaro estava morto havia três dias quando Jesus o ressuscitou.",0,"João 11:39",3,"Eram quatro dias."],
 ["Novo Testamento","Judas entregou Jesus por trinta moedas de prata.",1,"Mateus 26:15",1],
 ["Novo Testamento","Judas entregou Jesus por quarenta moedas de ouro.",0,"Mateus 26:15",1,"Foram trinta moedas de prata."],
 ["Novo Testamento","Pedro era irmão de André.",1,"João 1:40",2],
 ["Novo Testamento","Pedro era irmão de João.",0,"Mateus 4:18-21",2,"Pedro era irmão de André; João era irmão de Tiago."],
 ["Novo Testamento","Mateus era cobrador de impostos antes de seguir a Jesus.",1,"Mateus 9:9",1],
 ["Novo Testamento","João era cobrador de impostos antes de seguir a Jesus.",0,"Mateus 9:9",2,"Quem era cobrador de impostos era Mateus."],
 ["Novo Testamento","A visão de Pedro com animais limpos e imundos aconteceu em Jope.",1,"Atos 10:9-16",3],
 ["Novo Testamento","Pedro teve a visão dos animais limpos e imundos em Damasco.",0,"Atos 10:9-16",3,"Foi em Jope."],
 ["Novo Testamento","Timóteo foi um dos doze apóstolos escolhidos por Jesus.",0,"Atos 16:1-3",2,"Timóteo foi companheiro de Paulo, não um dos doze."],
 ["Novo Testamento","Timóteo foi companheiro de viagem de Paulo.",1,"Atos 16:1-3",1],
 ["Novo Testamento","Maria Madalena foi a primeira a ver Jesus ressuscitado, segundo o Evangelho de João.",1,"João 20:14-16",2],
 ["Novo Testamento","Pedro foi o primeiro a ver Jesus ressuscitado, segundo o Evangelho de João.",0,"João 20:14-16",2,"Segundo João, foi Maria Madalena."],
 ["Novo Testamento","Jesus transformou água em vinho em uma festa de casamento em Caná.",1,"João 2:1-11",1],
 ["Novo Testamento","Jesus transformou água em vinho em uma festa de casamento em Jerusalém.",0,"João 2:1-11",2,"O milagre foi em Caná da Galileia."],
 ["Novo Testamento","O apóstolo João esteve exilado na ilha de Patmos.",1,"Apocalipse 1:9",2],
 ["Novo Testamento","O apóstolo Paulo escreveu o Apocalipse na ilha de Patmos.",0,"Apocalipse 1:9",2,"Quem escreveu foi João."],
 ["Novo Testamento","O livro de Atos foi escrito por Lucas.",1,"Atos 1:1; Lucas 1:3",2],
 ["Novo Testamento","O livro de Atos foi escrito por Mateus.",0,"Atos 1:1; Lucas 1:3",2,"O autor foi Lucas."],
 ["Novo Testamento","Tomé duvidou da ressurreição até ver as marcas das mãos de Jesus.",1,"João 20:25-28",1],
 ["Novo Testamento","Tomé foi o discípulo que negou Jesus três vezes.",0,"João 18:25-27",1,"Quem negou foi Pedro."],
 ["Novo Testamento","Paulo foi picado por uma víbora na ilha de Malta.",1,"Atos 28:1-3",3],
 ["Novo Testamento","Paulo foi picado por uma víbora na ilha de Creta.",0,"Atos 28:1-3",3,"Foi em Malta."],
 ["Novo Testamento","Estêvão morreu apedrejado.",1,"Atos 7:59",1],
 ["Novo Testamento","Estêvão morreu crucificado de cabeça para baixo.",0,"Atos 7:59",2,"Estêvão foi apedrejado."],
 ["Novo Testamento","Paulo e Silas cantaram hinos na prisão em Filipos.",1,"Atos 16:25",2],
 ["Novo Testamento","Paulo e Silas cantaram hinos na prisão em Atenas.",0,"Atos 16:25",3,"Foi em Filipos."],
 ["Novo Testamento","Jesus ressuscitou ao terceiro dia.",1,"1 Coríntios 15:4",1],
 ["Novo Testamento","Jesus ressuscitou ao sétimo dia.",0,"1 Coríntios 15:4",1,"Ressuscitou ao terceiro dia."],
 ["Novo Testamento","O Espírito Santo desceu sobre os discípulos no dia de Pentecostes.",1,"Atos 2:1-4",1],
 ["Novo Testamento","O Espírito Santo desceu sobre os discípulos no dia da Páscoa.",0,"Atos 2:1-4",2,"Foi no dia de Pentecostes."],
 ["Novo Testamento","Bartimeu foi curado da cegueira perto de Jericó.",1,"Marcos 10:46-52",2],
 ["Novo Testamento","Bartimeu foi curado da cegueira em Cafarnaum.",0,"Marcos 10:46-52",3,"Foi perto de Jericó."],
 ["Novo Testamento","Jesus nasceu em Belém.",1,"Mateus 2:1",1],
 ["Novo Testamento","Jesus nasceu em Nazaré.",0,"Mateus 2:1",1,"Jesus nasceu em Belém e cresceu em Nazaré."],
 ["Novo Testamento","Herodes mandou matar os meninos de Belém.",1,"Mateus 2:16",1],
 ["Novo Testamento","Pilatos mandou matar os meninos de Belém.",0,"Mateus 2:16",2,"Quem mandou foi Herodes."],
 ["Novo Testamento","Pilatos lavou as mãos diante da multidão.",1,"Mateus 27:24",1],
 ["Novo Testamento","Herodes lavou as mãos diante da multidão no julgamento de Jesus.",0,"Mateus 27:24",2,"Quem lavou as mãos foi Pilatos."],
 ["Novo Testamento","Jesus foi crucificado no Gólgota.",1,"Mateus 27:33",1],
 ["Novo Testamento","Jesus foi crucificado no monte das Oliveiras.",0,"Mateus 27:33",2,"Foi no Gólgota."],
 ["Novo Testamento","Barnabé acompanhou Paulo na primeira viagem missionária.",1,"Atos 13:2",2],
 ["Novo Testamento","Cornélio era um centurião romano.",1,"Atos 10:1",2],
 ["Novo Testamento","Cornélio era um fariseu de Jerusalém.",0,"Atos 10:1",3,"Cornélio era centurião romano em Cesareia."],
 ["Novo Testamento","Jesus tinha doze apóstolos.",1,"Marcos 3:14",1],
 ["Novo Testamento","Jesus escolheu dez apóstolos.",0,"Marcos 3:14",1,"Foram doze."],
 ["Novo Testamento","Pedro andou sobre as águas por alguns instantes ao encontro de Jesus.",1,"Mateus 14:29",1],
 ["Novo Testamento","Tiago andou sobre as águas ao encontro de Jesus.",0,"Mateus 14:29",2,"Foi Pedro."],
 ["Novo Testamento","Marta e Maria eram irmãs de Lázaro.",1,"João 11:1-2",1],
 ["Novo Testamento","Marta e Maria eram irmãs de Pedro.",0,"João 11:1-2",1,"Eram irmãs de Lázaro."],
 ["Novo Testamento","O livro de Apocalipse tem vinte e dois capítulos.",1,"Apocalipse 22",3],
 ["Novo Testamento","O livro de Apocalipse tem trinta e três capítulos.",0,"Apocalipse 22",3,"Tem vinte e dois capítulos."],
 ["Novo Testamento","A Bíblia protestante tem sessenta e seis livros.",1,"Cânon protestante",1],
 ["Novo Testamento","A Bíblia protestante tem setenta e dois livros.",0,"Cânon protestante",1,"Tem sessenta e seis."],
 ["Novo Testamento","Jesus disse: “Eu sou o caminho, a verdade e a vida”.",1,"João 14:6",1],
 ["Novo Testamento","Jesus disse: “Eu sou o caminho, a verdade e a luz”.",0,"João 14:6",2,"A frase é “Eu sou o caminho, a verdade e a vida”."],
 ["Novo Testamento","Os magos do oriente deram a Jesus ouro, incenso e mirra.",1,"Mateus 2:11",1],
 ["Novo Testamento","Os pastores deram ouro, incenso e mirra ao menino Jesus.",0,"Mateus 2:11",2,"Quem trouxe os presentes foram os magos do oriente."],
 ["Novo Testamento","Nicodemos visitou Jesus de noite.",1,"João 3:2",2],
 ["Novo Testamento","Nicodemos visitou Jesus ao meio-dia e o seguiu como discípulo imediatamente.",0,"João 3:2",3,"Ele foi de noite, e só depois mostrou apoio a Jesus."],
 ["Novo Testamento","Barrabás foi solto no lugar de Jesus.",1,"Mateus 27:26",1],
 ["Novo Testamento","Caifás foi solto no lugar de Jesus.",0,"Mateus 27:26",2,"Quem foi solto foi Barrabás."],
 ["Novo Testamento","Lucas era médico.",1,"Colossenses 4:14",2],
 ["Novo Testamento","Lucas era pescador do mar da Galileia.",0,"Colossenses 4:14",2,"Lucas era médico."],
 ["Novo Testamento","Paulo era fabricante de tendas.",1,"Atos 18:3",2],
 ["Novo Testamento","Paulo era pescador antes de conhecer Jesus.",0,"Atos 18:3",1,"Paulo fabricava tendas e era fariseu."],
 ["Novo Testamento","Ananias e Safira caíram mortos depois de mentir aos apóstolos.",1,"Atos 5:1-10",2],
 ["Novo Testamento","Áquila e Priscila foram punidos com morte por mentir aos apóstolos.",0,"Atos 5:1-10",3,"Quem mentiu foram Ananias e Safira."],
 ["Personagens","Esaú vendeu a primogenitura a Jacó por um prato de lentilhas.",1,"Gênesis 25:34",1],
 ["Personagens","Jacó vendeu a primogenitura a Esaú por um prato de lentilhas.",0,"Gênesis 25:34",2,"Quem vendeu foi Esaú."],
 ["Personagens","Samuel serviu ao sacerdote Eli quando era criança.",1,"1 Samuel 2:11",2],
 ["Personagens","Samuel serviu ao rei Davi quando era criança.",0,"1 Samuel 2:11",2,"Servia ao sacerdote Eli."],
 ["Personagens","Jonatã, filho de Saul, era grande amigo de Davi.",1,"1 Samuel 18:1",1],
 ["Personagens","Absalão, filho de Davi, era grande amigo de Saul.",0,"1 Samuel 18:1",3,"O amigo de Davi era Jonatã, filho de Saul."],
 ["Personagens","Jetro era sogro de Moisés.",1,"Êxodo 3:1",3],
 ["Personagens","Labão era sogro de Moisés.",0,"Êxodo 3:1",3,"Jetro era o sogro de Moisés; Labão foi sogro de Jacó."],
 ["Personagens","Arão foi sumo sacerdote e irmão de Moisés.",1,"Êxodo 28:1",2],
 ["Personagens","Josué foi irmão de Moisés e primeiro sumo sacerdote.",0,"Êxodo 28:1",2,"Quem foi sumo sacerdote foi Arão."],
 ["Mulheres da Bíblia","Abigail foi esposa de Nabal e depois de Davi.",1,"1 Samuel 25:42",3],
 ["Mulheres da Bíblia","Abigail foi esposa de Saul e depois de Salomão.",0,"1 Samuel 25:42",3,"Abigail casou-se com Nabal e depois com Davi."],
 ["Mulheres da Bíblia","Raabe escondeu os espiões israelitas em Jericó.",1,"Josué 2:4",2],
 ["Mulheres da Bíblia","Dalila escondeu os espiões israelitas em Jericó.",0,"Josué 2:4",2,"Quem escondeu foi Raabe."],
 ["Mulheres da Bíblia","Lídia vendia púrpura e acolheu Paulo em Filipos.",1,"Atos 16:14-15",3],
 ["Mulheres da Bíblia","Lídia fabricava tendas e hospedou Paulo em Corinto.",0,"Atos 16:14-15",3,"Lídia vendia púrpura em Filipos."],
 ["Mulheres da Bíblia","Miriã era irmã de Moisés.",1,"Êxodo 15:20",2],
 ["Mulheres da Bíblia","Miriã era esposa de Moisés.",0,"Êxodo 15:20",2,"A esposa foi Zípora; Miriã era irmã."],
 ["Mulheres da Bíblia","Isabel foi a mãe de João Batista.",1,"Lucas 1:13",1],
 ["Mulheres da Bíblia","Ana foi a mãe de João Batista.",0,"Lucas 1:13",2,"A mãe de João Batista foi Isabel."],
 ["Mulheres da Bíblia","Ana, mãe de Samuel, orou no santuário pedindo um filho.",1,"1 Samuel 1:10-11",2],
 ["Mulheres da Bíblia","Rebeca foi a mãe de Samuel.",0,"1 Samuel 1:20",2,"A mãe de Samuel foi Ana."],
 ["Mulheres da Bíblia","Dorcas (Tabita) foi ressuscitada por Pedro.",1,"Atos 9:40",3],
 ["Mulheres da Bíblia","Dorcas (Tabita) foi ressuscitada por Paulo.",0,"Atos 9:40",3,"Quem a ressuscitou foi Pedro."],
 ["Apocalipse e Profecia","No Apocalipse, são sete as igrejas que recebem cartas.",1,"Apocalipse 1:11",1],
 ["Apocalipse e Profecia","No Apocalipse, são doze as igrejas que recebem cartas.",0,"Apocalipse 1:11",1,"São sete igrejas."],
 ["Apocalipse e Profecia","A cabeça de ouro do sonho de Nabucodonosor representa a Babilônia.",1,"Daniel 2:38",1],
 ["Apocalipse e Profecia","A cabeça de ouro do sonho de Nabucodonosor representa a Grécia.",0,"Daniel 2:38",2,"A cabeça de ouro é a Babilônia."],
 ["Apocalipse e Profecia","Gabriel foi o anjo que anunciou a Maria o nascimento de Jesus.",1,"Lucas 1:26-31",1],
 ["Apocalipse e Profecia","Miguel foi o anjo que anunciou a Maria o nascimento de Jesus.",0,"Lucas 1:26-31",2,"Foi o anjo Gabriel."],
 ["Apocalipse e Profecia","Miguel é o arcanjo que luta contra o dragão no Apocalipse.",1,"Apocalipse 12:7",2],
 ["Apocalipse e Profecia","O Apocalipse fala de uma Nova Jerusalém que desce do céu.",1,"Apocalipse 21:2",1],
 ["Apocalipse e Profecia","O Apocalipse fala de uma Nova Babilônia que sobe da terra.",0,"Apocalipse 21:2",2,"A cidade nova é a Nova Jerusalém, que desce do céu."],
 ["Mandamentos e Sábado","O quarto mandamento fala do dia de sábado.",1,"Êxodo 20:8",1],
 ["Mandamentos e Sábado","O quarto mandamento fala de honrar pai e mãe.",0,"Êxodo 20:8,12",1,"O quarto trata do sábado; honrar pai e mãe é o quinto."],
 ["Mandamentos e Sábado","Deus descansou no sétimo dia da criação.",1,"Gênesis 2:2",1],
 ["Mandamentos e Sábado","Deus descansou no sexto dia da criação.",0,"Gênesis 2:2",1,"Foi no sétimo dia."],
 ["Mandamentos e Sábado","Os Dez Mandamentos foram escritos pelo dedo de Deus em tábuas de pedra.",1,"Êxodo 31:18",1],
 ["Mandamentos e Sábado","Moisés escreveu os Dez Mandamentos em papiro por ordem do faraó.",0,"Êxodo 31:18",1,"Foram escritos pelo dedo de Deus em tábuas de pedra."],
 ["Mandamentos e Sábado","O sábado foi abençoado e santificado por Deus na criação.",1,"Gênesis 2:3",2],
 ["Mandamentos e Sábado","O sábado foi instituído somente depois que Israel saiu do Egito.",0,"Gênesis 2:3",3,"O sábado foi abençoado e santificado já na criação."],
 ["Mandamentos e Sábado","Jesus disse que o sábado foi feito por causa do homem.",1,"Marcos 2:27",2],
 ["Mandamentos e Sábado","Jesus disse que o homem foi feito para o sábado.",0,"Marcos 2:27",2,"Jesus disse o contrário: o sábado foi feito para o homem."],
 ["Livros e Números","Salmos é o livro da Bíblia com mais capítulos.",1,"Salmos 1–150",1],
 ["Livros e Números","Isaías é o livro da Bíblia com mais capítulos.",0,"Salmos 1–150",2,"O livro com mais capítulos é Salmos (150)."],
 ["Livros e Números","Obadias tem apenas um capítulo.",1,"Obadias 1",3],
 ["Livros e Números","Jeremias tem apenas um capítulo.",0,"Jeremias 1–52",2,"Jeremias tem 52 capítulos."]
];
})();
