/* IASD APP - banco de personagens e citações bíblicas (Almeida). Formatos: ver especificação. */
(window.IASDBank=window.IASDBank||{}).who=[
// ===== Patriarcas =====
["Adão",[],["Não tive pai nem mãe humanos.","Dei nome a todos os animais do jardim.","Fui o primeiro homem, formado do pó da terra."],"Gênesis 2:7,19","Patriarcas",["Noé","Enoque","Sete"],1],
["Caim",[],["Minha oferta não foi aceita e fiquei muito irado.","Ouvi dizer que o pecado estava à porta, como que à espreita.","Fui lavrador e matei meu irmão no campo."],"Gênesis 4:3-8","Patriarcas",["Esaú","Sete","Rúben"],1],
["Abel",[],["Fui pastor de ovelhas.","Minha oferta dos primogênitos do rebanho agradou a Deus.","Meu irmão mais velho me matou no campo."],"Gênesis 4:2-8","Patriarcas",["Sete","Enoque","Ló"],1],
["Enoque",[],["Andei com Deus por trezentos anos.","Não vi a morte.","Vivi 365 anos e Deus me tomou para si."],"Gênesis 5:22-24","Patriarcas",["Noé","Sete","Ló"],2],
["Matusalém",["matusalem"],["Tenho o recorde bíblico de idade.","Meu pai andou com Deus e meu filho se chamou Lameque.","Vivi 969 anos."],"Gênesis 5:21-27","Patriarcas",["Jarede","Sete","Noé"],2],
["Noé",["noe"],["Vivi em tempos de muita violência na terra.","Achei graça aos olhos do Senhor e construí algo enorme.","Construí uma arca e sobrevivi ao dilúvio com minha família."],"Gênesis 6-8","Patriarcas",["Ló","Matusalém","Abraão"],1],
["Abraão",["abraao","abrao"],["Deixei minha terra sem saber para onde ia.","Recebi a promessa de uma descendência como as estrelas do céu.","Quase sacrifiquei meu filho Isaque no monte Moriá."],"Gênesis 12; 22","Patriarcas",["Ló","Noé","Jacó"],1],
["Ló",["lo"],["Acompanhei meu tio em sua jornada.","Escolhi a planície bem irrigada do Jordão.","Escapei de Sodoma antes de o fogo cair, mas minha mulher olhou para trás."],"Gênesis 13; 19","Patriarcas",["Labão","Esaú","Benjamim"],2],
["Isaque",[],["Nasci quando meus pais já eram idosos.","Levei lenha nas costas para um monte.","Meu pai Abraão quase me ofereceu, mas um carneiro foi provido."],"Gênesis 21-22","Patriarcas",["Ismael","José","Labão"],1],
["Esaú",["esau"],["Nasci primeiro, mas perdi algo precioso.","Troquei um direito por um prato de comida.","Vendi minha primogenitura por um guisado de lentilhas ao meu irmão gêmeo."],"Gênesis 25:29-34","Patriarcas",["Ismael","Rúben","Labão"],1],
["Jacó",["jaco","israel"],["Nasci segurando o calcanhar do meu irmão.","Sonhei com uma escada que chegava ao céu.","Lutei com um anjo e recebi o nome Israel."],"Gênesis 25:26; 28:12; 32:28","Patriarcas",["Esaú","Isaque","Judá"],1],
["José do Egito",["jose do egito","jose"],["Meus irmãos me invejaram por causa de uma túnica.","Fui vendido por vinte peças de prata a mercadores.","Interpretei os sonhos do faraó e governei o Egito."],"Gênesis 37; 41","Patriarcas",["Benjamim","Rúben","Judá"],1],
["Benjamim",[],["Minha mãe morreu ao me dar à luz.","Um irmão governador pediu que me levassem ao Egito.","Fui o filho mais novo de Jacó; acharam o copo de prata no meu saco."],"Gênesis 35:16-18; 44:12","Patriarcas",["Rúben","Judá","Levi"],2],
["Judá",["juda"],["Sugeri vender meu irmão em vez de matá-lo.","Ofereci-me como refém no lugar do caçula.","Dei nome à tribo da qual viria o Leão, o Messias."],"Gênesis 37:26-27; 44:33; 49:9-10","Patriarcas",["Rúben","Simeão","Levi"],2],
["Melquisedeque",["melquisedec"],["Fui rei e sacerdote ao mesmo tempo.","Abençoei um patriarca após uma batalha e dele recebi o dízimo.","Fui rei de Salém e sacerdote do Deus Altíssimo."],"Gênesis 14:18-20","Patriarcas",["Jetro","Eli","Zadoque"],3],
["Labão",["labao"],["Enganei meu sobrinho na noite de núpcias.","Troquei a noiva combinada pela mais velha.","Fui sogro de Jacó e pai de Lia e Raquel."],"Gênesis 29:21-28","Patriarcas",["Esaú","Potifar","Jetro"],2],
["Rúben",["ruben"],["Tentei salvar meu irmão da cova, mas cheguei tarde.","Fui o primogênito de um patriarca com doze filhos.","Fui o filho mais velho de Jacó e tentei livrar José da morte."],"Gênesis 37:21-22,29","Patriarcas",["Judá","Levi","Benjamim"],2],
["Ismael",[],["Fui expulso com minha mãe para o deserto.","Um anjo e um poço de água nos salvaram ali.","Fui filho de Abraão com Hagar e me tornei flecheiro no deserto de Parã."],"Gênesis 21:9-21","Patriarcas",["Isaque","Esaú","Rúben"],2],
["Jó",["jo"],["Perdi tudo num só dia.","Três amigos vieram me consolar, mas acabaram me acusando.","Sofri muito e disse: O Senhor o deu, o Senhor o tomou; bendito seja o nome do Senhor."],"Jó 1:21","Patriarcas",["Elifaz","Jeremias","Naum"],1],

// ===== Êxodo e Juízes =====
["Moisés",["moises"],["Fui salvo das águas por causa de uma ordem cruel.","Falei com Deus numa sarça e pastoreei ovelhas em Midiã.","Guiei Israel para fora do Egito e recebi a lei no monte."],"Êxodo 2-3; 20","Êxodo e Juízes",["Josué","Arão","Calebe"],1],
["Arão",["arao"],["Fui porta-voz do meu irmão.","Fabriquei uma imagem de ouro quando o povo se impacientou.","Fui o primeiro sumo sacerdote, e minha vara floresceu."],"Êxodo 4:14-16; 32; Números 17","Êxodo e Juízes",["Eleazar","Coré","Jetro"],2],
["Miriã",["miria"],["Vigiei um cesto de junco no rio.","Conduzi as mulheres com pandeiro num cântico de vitória.","Fui irmã de Moisés e Arão e fiquei leprosa por murmurar."],"Êxodo 2:4; 15:20; Números 12","Êxodo e Juízes",["Séfora","Débora","Raabe"],2],
["Josué",["josue"],["Fui um dos doze espiões enviados a observar a terra.","Fui servo de um grande líder e depois seu sucessor.","Conduzi Israel pelo Jordão e à conquista de Jericó."],"Números 13; Josué 1; 6","Êxodo e Juízes",["Calebe","Gideão","Eleazar"],1],
["Calebe",[],["Aos oitenta e cinco anos ainda me sentia forte como aos quarenta.","Com Josué, fui um dos dois espiões que confiaram em Deus.","Pedi Hebrom como herança e fui espião da tribo de Judá."],"Números 14:6-9; Josué 14:10-14","Êxodo e Juízes",["Fineias","Otniel","Eleazar"],2],
["Jetro",[],["Fui sacerdote em Midiã.","Aconselhei um líder a repartir as tarefas de julgar o povo.","Fui sogro de Moisés."],"Êxodo 18","Êxodo e Juízes",["Labão","Balaque","Eli"],2],
["Balaão",["balaao"],["Fui chamado por um rei para amaldiçoar um povo.","Um animal enxergou o que eu não via.","Minha jumenta falou comigo no caminho."],"Números 22","Êxodo e Juízes",["Balaque","Coré","Jetro"],2],
["Coré",["core"],["Levantei-me contra meus líderes com duzentos e cinquenta homens.","Reivindiquei o sacerdócio para todos.","A terra abriu a boca e me engoliu com minha família rebelde."],"Números 16","Êxodo e Juízes",["Hur","Eleazar","Balaão"],3],
["Gideão",["gideao","gedeao"],["Debulhava trigo escondido num lagar.","Pedi sinais com um velo de lã, o orvalho e o chão seco.","Com trezentos homens, trombetas e jarros, derrotei Midiã."],"Juízes 6-7","Êxodo e Juízes",["Sansão","Jefté","Baraque"],1],
["Sansão",["sansao"],["Nasci de uma mulher estéril, por promessa de um anjo.","Navalha nunca passou na minha cabeça.","Perdi a força quando Dalila cortou meus cabelos."],"Juízes 13-16","Êxodo e Juízes",["Gideão","Jefté","Eúde"],1],
["Débora",["debora"],["Julguei Israel debaixo de uma palmeira.","Chamei um general para a batalha e profetizei que uma mulher teria a honra.","Fui profetisa e juíza; cantei com Baraque após a vitória sobre Sísera."],"Juízes 4-5","Êxodo e Juízes",["Jael","Miriã","Hulda"],2],
["Jefté",["jefte"],["Fui rejeitado pelos meus irmãos por ser filho de outra mulher.","Fiz um voto ao Senhor antes de uma batalha contra os amonitas.","Fui juiz de Gileade e fiz um voto sobre quem saísse primeiro da minha casa."],"Juízes 11","Êxodo e Juízes",["Gideão","Sansão","Eúde"],2],
["Eúde",["eude"],["Era canhoto.","Levei um presente a um rei muito gordo.","Matei o rei Eglom de Moabe com uma espada de dois gumes escondida."],"Juízes 3:15-22","Êxodo e Juízes",["Sansão","Baraque","Otniel"],3],
["Baraque",[],["Só fui à batalha se uma profetisa fosse comigo.","Desci do monte Tabor com dez mil homens.","Fui general de Israel; Sísera foi derrotado na minha batalha com Débora."],"Juízes 4:6-8","Êxodo e Juízes",["Gideão","Eúde","Abner"],3],
["Bezalel",["bezaleel"],["Fui cheio do Espírito de Deus em sabedoria e habilidade.","Trabalhei com ouro, prata, bronze, pedras e madeira.","Fiz o tabernáculo e a arca no deserto, junto com Aoliabe."],"Êxodo 31:1-6","Êxodo e Juízes",["Arão","Hur","Eleazar"],3],
["Eli",[],["Minha vista se escureceu na velhice.","Criei um menino no santuário e vi meus filhos pecarem.","Fui sacerdote em Siló e cuidei do menino Samuel."],"1 Samuel 1-4","Êxodo e Juízes",["Zadoque","Abiatar","Jetro"],2],

// ===== Reis e Profetas =====
["Samuel",[],["Fui dedicado ao Senhor antes de nascer.","Ouvi uma voz de noite e pensei que era meu mestre.","Ungi Saul e depois Davi como reis."],"1 Samuel 1-3; 10; 16","Reis e Profetas",["Eli","Natã","Elias"],1],
["Saul",[],["Saí à procura de jumentas perdidas e achei um reino.","Era mais alto que todo o povo.","Fui o primeiro rei de Israel e perseguia Davi."],"1 Samuel 9-10; 18","Reis e Profetas",["Davi","Jônatas","Abner"],1],
["Davi",["rei davi"],["Fui o menor dos irmãos e guardava ovelhas.","Toquei harpa para aliviar um rei atormentado.","Derrotei o gigante Golias com uma funda e escrevi salmos."],"1 Samuel 16-17","Reis e Profetas",["Saul","Salomão","Jônatas"],1],
["Golias",[],["Vim de Gate.","Desafiei o exército de Israel durante quarenta dias.","Fui um gigante filisteu derrubado por uma pedra da funda de um pastor."],"1 Samuel 17","Reis e Profetas",["Sísera","Abner","Joabe"],1],
["Jônatas",["jonatas"],["Dei minhas roupas e armas a um amigo.","Avisei meu amigo com flechas lançadas no campo.","Fui filho do rei Saul e amigo fiel de Davi."],"1 Samuel 18:4; 20:20-22","Reis e Profetas",["Absalão","Abner","Joabe"],2],
["Natã",["nata"],["Contei uma história sobre uma ovelhinha.","Fui mensageiro de Deus a um rei que tomara a mulher de outro.","Disse ao rei Davi: Tu és o homem."],"2 Samuel 12","Reis e Profetas",["Samuel","Gade","Elias"],2],
["Absalão",["absalao"],["Fui muito elogiado pela minha beleza e meus cabelos.","Roubei o coração dos homens de Israel na porta da cidade.","Me rebelei contra meu pai Davi e fiquei preso pelos cabelos numa árvore."],"2 Samuel 14:25; 15:6; 18:9","Reis e Profetas",["Amnom","Adonias","Salomão"],2],
["Salomão",["salomao","rei salomao"],["Pedi algo ainda jovem e recebi mais do que pedi.","Julguei entre duas mulheres que disputavam um bebê.","Construí o templo em Jerusalém e fui famoso pela sabedoria."],"1 Reis 3; 6","Reis e Profetas",["Roboão","Davi","Ezequias"],1],
["Elias",["tesbita"],["Fui alimentado por corvos junto a um ribeiro.","Desafiei profetas de Baal no monte Carmelo.","Fui levado ao céu num carro de fogo, sem morrer."],"1 Reis 17-18; 2 Reis 2","Reis e Profetas",["Eliseu","Jeremias","Natã"],1],
["Eliseu",[],["Fui chamado enquanto arava com doze juntas de bois.","Pedi porção dobrada do espírito do meu mestre.","Herdei o manto de Elias e curei Naamã."],"1 Reis 19:19; 2 Reis 2:9","Reis e Profetas",["Elias","Geazi","Isaías"],2],
["Isaías",["isaias"],["Vi o Senhor assentado num alto e sublime trono.","Um serafim tocou meus lábios com uma brasa.","Respondi: Eis-me aqui, envia-me a mim; profetizei sobre o Messias."],"Isaías 6; 53","Reis e Profetas",["Jeremias","Ezequiel","Oseias"],1],
["Jeremias",[],["Fui chamado ainda jovem e disse que não sabia falar.","Chorei pelo meu povo e fui lançado numa cisterna.","Fui o profeta que anunciou setenta anos de cativeiro na Babilônia."],"Jeremias 1:6; 38:6; 29:10","Reis e Profetas",["Isaías","Ezequiel","Daniel"],2],
["Ezequiel",[],["Vi rodas dentro de rodas perto do rio Quebar.","Vi um vale de ossos secos ganhar vida.","Fui profeta entre os exilados na Babilônia."],"Ezequiel 1; 37","Reis e Profetas",["Jeremias","Daniel","Isaías"],2],
["Daniel",[],["Fui levado cativo ainda jovem para a Babilônia.","Recusei a comida do rei e interpretei sonhos.","Passei uma noite na cova dos leões sem ser ferido."],"Daniel 1; 2; 6","Reis e Profetas",["Ezequiel","Jeremias","Mardoqueu"],1],
["Jonas",[],["Fugi da missão que Deus me deu.","Dormi no porão de um navio durante uma tempestade.","Fui engolido por um grande peixe e preguei em Nínive."],"Jonas 1-3","Reis e Profetas",["Amós","Oseias","Naum"],1],
["Ezequias",[],["Recebi uma carta ameaçadora e a estendi diante do Senhor.","Orei e recebi quinze anos a mais de vida.","Fui rei de Judá; minha oração deteve o exército de Senaqueribe."],"2 Reis 19-20","Reis e Profetas",["Josias","Acaz","Manassés"],2],
["Josias",[],["Assumi o trono ainda menino.","Um livro da lei foi encontrado no templo em meu reinado.","Fui rei de Judá que rasgou as vestes ao ouvir o livro e reformou a nação."],"2 Reis 22-23","Reis e Profetas",["Ezequias","Manassés","Jeoaquim"],3],
["Acabe",[],["Desejei a vinha de um vizinho.","Minha esposa providenciou a morte de Nabote.","Fui rei de Israel, casado com Jezabel e inimigo de Elias."],"1 Reis 21","Reis e Profetas",["Jeú","Jeroboão","Onri"],2],
["Nabucodonosor",[],["Sonhei com uma estátua de metais diversos.","Mandei lançar três jovens numa fornalha.","Fui rei da Babilônia e vivi como animal por sete tempos."],"Daniel 2-4","Reis e Profetas",["Belsazar","Ciro","Hamã"],2],
["Naamã",["naama"],["Fui comandante de um exército estrangeiro.","Fiquei irritado com a simplicidade da ordem do profeta.","Fui curado da lepra após me banhar sete vezes no Jordão."],"2 Reis 5","Reis e Profetas",["Geazi","Hazael","Acabe"],2],
["Neemias",[],["Eu servia o rei como copeiro.","Chorei ao saber que os muros da cidade santa estavam quebrados.","Reconstruí os muros de Jerusalém em cinquenta e dois dias."],"Neemias 1-2; 6:15","Reis e Profetas",["Esdras","Zorobabel","Mardoqueu"],2],
["Esdras",[],["Fui sacerdote e escriba.","Li o livro da lei ao povo em praça pública.","Voltei da Babilônia a Jerusalém para ensinar a lei de Deus."],"Esdras 7; Neemias 8","Reis e Profetas",["Neemias","Zorobabel","Zadoque"],3],
["Amós",["amos"],["Era pastor e colhedor de sicômoros.","Não era filho de profeta.","Fui profeta de Tecoa e disse: Corra o juízo como as águas."],"Amós 1:1; 5:24; 7:14","Reis e Profetas",["Oseias","Joel","Miqueias"],3],
["Mardoqueu",["mordecai"],["Não me ajoelhei diante de um alto oficial.","Descobri uma conspiração contra o rei.","Fui primo e tutor de Ester e vi Hamã cair."],"Ester 2-7","Reis e Profetas",["Hamã","Neemias","Esdras"],2],

// ===== Mulheres da Bíblia =====
["Eva",[],["Fui formada de uma costela.","Fui enganada por uma serpente.","Fui a primeira mulher e comi do fruto proibido."],"Gênesis 2:22; 3","Mulheres da Bíblia",["Sara","Hagar","Lia"],1],
["Sara",["sarai"],["Ri quando ouvi uma promessa dentro da tenda.","Tive um filho depois dos noventa anos.","Fui esposa de Abraão e mãe de Isaque."],"Gênesis 18:12; 21","Mulheres da Bíblia",["Rebeca","Raquel","Hagar"],1],
["Hagar",[],["Fui serva egípcia.","Um anjo me achou junto a uma fonte no deserto.","Dei um filho a Abraão e fui mandada embora com ele."],"Gênesis 16; 21","Mulheres da Bíblia",["Sara","Zilpa","Bila"],2],
["Rebeca",[],["Dei de beber a dez camelos de um estranho.","Saí de casa para me casar com quem nunca vira.","Fui esposa de Isaque e mãe de Esaú e Jacó."],"Gênesis 24","Mulheres da Bíblia",["Lia","Raquel","Sara"],1],
["Raquel",[],["Pastoreava as ovelhas de meu pai.","Fui amada por sete anos de trabalho.","Fui esposa amada de Jacó e mãe de José e Benjamim."],"Gênesis 29-30; 35","Mulheres da Bíblia",["Lia","Rebeca","Sara"],2],
["Lia",[],["Tinha olhos tenros e fui entregue no lugar de minha irmã.","Fui a primeira esposa de Jacó por engano de meu pai.","Fui mãe de Rúben, Levi e Judá."],"Gênesis 29:16-35","Mulheres da Bíblia",["Raquel","Sara","Hagar"],2],
["Raabe",[],["Morava na muralha de uma cidade.","Escondi espiões sob feixes de linho.","Pendurei um cordão escarlate na janela e fui salva em Jericó."],"Josué 2; 6","Mulheres da Bíblia",["Rute","Jael","Dalila"],2],
["Rute",[],["Deixei minha terra e minha gente.","Respiguei espigas no campo de um parente.","Disse à minha sogra: Onde quer que fores, irei eu."],"Rute 1:16; 2","Mulheres da Bíblia",["Noemi","Orfa","Ester"],1],
["Noemi",[],["Saí de Belém por causa da fome e voltei viúva.","Pedi que me chamassem de Mara, que quer dizer amarga.","Fui sogra de Rute e voltei a Belém."],"Rute 1:20","Mulheres da Bíblia",["Rute","Orfa","Ana"],2],
["Ana (mãe de Samuel)",["ana","ana mae de samuel"],["Orei tão intensamente que o sacerdote pensou que eu estava embriagada.","Fui estéril e fiz um voto no santuário.","Fui mãe de Samuel, que entreguei ao serviço do Senhor."],"1 Samuel 1","Mulheres da Bíblia",["Penina","Noemi","Isabel"],2],
["Dalila",[],["Fui amada por um juiz muito forte.","Filisteus me prometeram prata.","Cortei os cabelos de Sansão enquanto ele dormia."],"Juízes 16","Mulheres da Bíblia",["Jezabel","Jael","Raabe"],1],
["Jael",[],["Ofereci leite a um fugitivo cansado.","Usei uma estaca de tenda e um martelo.","Matei o general Sísera enquanto ele dormia em minha tenda."],"Juízes 4:17-21","Mulheres da Bíblia",["Débora","Dalila","Raabe"],3],
["Abigail",[],["Levei pão, vinho e ovelhas para evitar um massacre.","Meu marido era chamado de insensato.","Fui esposa de Nabal, acalmei Davi e depois me casei com ele."],"1 Samuel 25","Mulheres da Bíblia",["Mical","Bate-Seba","Noemi"],3],
["Bate-Seba",["bateseba","bate seba"],["Fui vista de um terraço.","Perdi o primeiro filho que tive com o rei.","Fui esposa de Urias, depois de Davi, e mãe de Salomão."],"2 Samuel 11-12; 1 Reis 1","Mulheres da Bíblia",["Abigail","Mical","Tamar"],2],
["Ester",["hadassa"],["Fui órfã criada por um primo.","Cheguei a ser rainha, escondendo minha origem.","Arrisquei minha vida entrando sem ser chamada e salvei meu povo de Hamã."],"Ester 2-7","Mulheres da Bíblia",["Vasti","Rute","Débora"],1],
["Jezabel",[],["Vim de Sidom como esposa de um rei.","Mandei matar profetas do Senhor.","Fui a rainha ímpia que ameaçou Elias."],"1 Reis 16:31; 18:4; 19:2","Mulheres da Bíblia",["Atalia","Dalila","Vasti"],2],
["Rainha de Sabá",["saba","sheba","rainha de saba"],["Viajei de muito longe com camelos e especiarias.","Testei um rei com perguntas difíceis.","Visitei Salomão e disse que não me contaram nem a metade."],"1 Reis 10:1-7","Mulheres da Bíblia",["Ester","Vasti","Atalia"],2],
["Maria, mãe de Jesus",["maria","virgem maria","maria mae de jesus"],["Era jovem e noiva de um carpinteiro quando recebi uma mensagem.","Fui saudada como muito favorecida entre as mulheres.","Dei à luz em Belém o Filho de Deus."],"Lucas 1:26-38; 2:7","Mulheres da Bíblia",["Isabel","Maria Madalena","Marta"],1],
["Isabel",[],["Sentia vergonha por não ter filhos.","Senti uma criança saltar no ventre quando recebi uma visita.","Fui esposa de Zacarias e mãe de João Batista."],"Lucas 1:24,41","Mulheres da Bíblia",["Ana","Noemi","Marta"],2],
["Marta",[],["Andava ocupada com muito serviço.","Reclamei que minha irmã não me ajudava.","Irmã de Maria e Lázaro, hospedei Jesus em Betânia."],"Lucas 10:38-42","Mulheres da Bíblia",["Maria Madalena","Lídia","Priscila"],1],
["Maria Madalena",["madalena","maria de magdala"],["Jesus expulsou sete demônios de mim.","Estive ao pé da cruz.","Fui a primeira a ver o Senhor ressuscitado junto ao túmulo vazio."],"Lucas 8:2; João 20:14-16","Mulheres da Bíblia",["Marta","Salomé","Joana"],1],
["Tabita (Dorcas)",["tabita","dorcas"],["Vivia em Jope e fazia muitas boas obras.","Costurava túnicas e vestidos para as viúvas.","Morri e fui ressuscitada por Pedro."],"Atos 9:36-41","Mulheres da Bíblia",["Lídia","Priscila","Febe"],2],
["Lídia",["lidia"],["Vendia tecido de cor púrpura.","Era de Tiatira, mas morava em Filipos.","Adoradora de Deus, me converti junto ao rio e abri minha casa a Paulo."],"Atos 16:14-15","Mulheres da Bíblia",["Priscila","Febe","Tabita"],3],
["Priscila",["prisca"],["Fabricava tendas como profissão.","Com meu marido, ensinei com mais exatidão o caminho a um orador eloquente.","Fui esposa de Áquila e ajudei Paulo em Corinto e Éfeso."],"Atos 18:2-3,26","Mulheres da Bíblia",["Lídia","Febe","Eunice"],3],

// ===== Vida de Jesus =====
["João Batista",["joao batista","batista"],["Vivi no deserto e me vesti de pelos de camelo.","Comia gafanhotos e mel silvestre.","Batizei Jesus no rio Jordão."],"Mateus 3","Vida de Jesus",["Zacarias","Simeão","André"],1],
["José de Nazaré",["jose de nazare","jose esposo de maria"],["Era um homem justo e não quis expor minha noiva.","Fui avisado várias vezes em sonhos por um anjo.","Fui carpinteiro e pai adotivo de Jesus."],"Mateus 1:19-20; 2:13","Vida de Jesus",["Zacarias","Simeão","Jairo"],1],
["Zacarias",[],["Fiquei mudo por não acreditar em um anjo.","Estava queimando incenso no templo.","Escrevi numa tábua: O nome dele é João."],"Lucas 1:11-22,63","Vida de Jesus",["Simeão","Jairo","Eli"],2],
["Simeão",["simeao"],["Esperava a consolação de Israel.","Foi-me revelado que não veria a morte antes de ver o Cristo do Senhor.","Tomei o menino Jesus nos braços no templo."],"Lucas 2:25-35","Vida de Jesus",["Zacarias","Nicodemos","Jairo"],2],
["Herodes, o Grande",["herodes","herodes o grande"],["Fui rei da Judeia e muito desconfiado.","Mandei chamar sábios que seguiam uma estrela.","Mandei matar os meninos de Belém com até dois anos."],"Mateus 2","Vida de Jesus",["Pilatos","Augusto","Caifás"],2],
["Zaqueu",[],["Era pequeno de estatura.","Cobrava impostos em Jericó e era rico.","Subi num sicômoro para ver Jesus passar."],"Lucas 19:1-10","Vida de Jesus",["Mateus","Nicodemos","Jairo"],1],
["Lázaro",["lazaro"],["Moro em Betânia com minhas duas irmãs.","Fiquei quatro dias no túmulo.","Jesus chorou e me chamou para fora do sepulcro."],"João 11","Vida de Jesus",["Nicodemos","Zaqueu","Bartimeu"],1],
["Nicodemos",[],["Fui fariseu e principal entre os judeus.","Fui ter com Jesus de noite.","Ouvi dizer: É necessário nascer de novo."],"João 3:1-7","Vida de Jesus",["Gamaliel","José de Arimateia","Caifás"],2],
["Bartimeu",[],["Sentava à beira do caminho em Jericó.","Lancei fora minha capa e fui ter com Jesus.","Fui um mendigo cego curado ao clamar: Filho de Davi, tem misericórdia de mim."],"Marcos 10:46-52","Vida de Jesus",["Zaqueu","Lázaro","Jairo"],2],
["Barrabás",["barrabas"],["Estava preso por sedição e homicídio.","O povo me preferiu em lugar de outro.","Fui solto em lugar de Jesus."],"Mateus 27:16-21","Vida de Jesus",["Pilatos","Caifás","Anás"],1],
["Pôncio Pilatos",["poncio pilatos","pilatos"],["Lavei as mãos diante da multidão.","Fui governador romano da Judeia.","Condenei Jesus à cruz, embora não achasse culpa nele."],"Mateus 27:24; Lucas 23:4","Vida de Jesus",["Caifás","Herodes Antipas","Anás"],1],
["Judas Iscariotes",["judas","iscariotes"],["Cuidava da bolsa do grupo.","Reclamei do perfume derramado em Betânia.","Traí Jesus com um beijo por trinta moedas de prata."],"João 12:4-6; Mateus 26:14-16,48-49","Vida de Jesus",["Tomé","André","Filipe"],1],
["José de Arimateia",["jose de arimateia","arimateia"],["Era membro do conselho e discípulo em secreto.","Fui rico e fui pedir algo a Pilatos.","Cedi meu sepulcro novo para o corpo de Jesus."],"Mateus 27:57-60","Vida de Jesus",["Nicodemos","Caifás","Gamaliel"],2],
["Caifás",["caifas"],["Era sumo sacerdote naquele ano.","Disse que convinha morrer um homem pelo povo.","Presidi o julgamento de Jesus como sumo sacerdote."],"João 11:49-50; Mateus 26:57","Vida de Jesus",["Anás","Pilatos","Zadoque"],2],

// ===== Apóstolos e Igreja =====
["Simão Pedro",["pedro","simao pedro","simao"],["Era pescador no mar da Galileia.","Andei sobre as águas por alguns passos.","Neguei Jesus três vezes antes de o galo cantar."],"Mateus 14:29; 26:74-75","Apóstolos e Igreja",["André","Tomé","Mateus"],1],
["André",["andre"],["Fui primeiro discípulo de João Batista.","Levei meu irmão a Jesus.","Levei a Jesus um menino com cinco pães e dois peixes."],"João 1:40-42; 6:8-9","Apóstolos e Igreja",["Bartolomeu","Tomé","Mateus"],2],
["Tiago, filho de Zebedeu",["tiago","tiago filho de zebedeu","tiago irmao de joao"],["Fui chamado enquanto consertava redes.","Jesus nos apelidou Boanerges, filhos do trovão.","Fui o primeiro apóstolo martirizado, morto à espada por Herodes."],"Marcos 3:17; Atos 12:2","Apóstolos e Igreja",["Pedro","André","Tomé"],2],
["João, o discípulo amado",["joao","joao apostolo","joao evangelista"],["Fui pescador com meu pai Zebedeu.","Recostei-me ao peito de Jesus na ceia.","Escrevi o Apocalipse na ilha de Patmos."],"João 13:23; Apocalipse 1:9","Apóstolos e Igreja",["André","Tomé","Mateus"],1],
["Filipe",[],["Fui de Betsaida.","Convidei um amigo dizendo: Vem e vê.","Jesus me perguntou onde compraríamos pão para a multidão."],"João 1:45-46; 6:5","Apóstolos e Igreja",["Tomé","Mateus","Tiago"],2],
["Natanael",["bartolomeu"],["Estava debaixo de uma figueira.","Duvidei que algo bom pudesse vir de Nazaré.","Jesus disse que eu era um verdadeiro israelita, sem dolo."],"João 1:45-49","Apóstolos e Igreja",["Filipe","Tomé","Mateus"],3],
["Tomé",["tome"],["Não estava com os outros quando o Mestre apareceu pela primeira vez.","Disse que só creria se visse as marcas.","Toquei nas mãos e no lado do Senhor e exclamei: Senhor meu e Deus meu!"],"João 20:24-28","Apóstolos e Igreja",["Filipe","André","Mateus"],1],
["Mateus",[],["Sentava na coletoria.","Fui chamado com as palavras: Segue-me.","Era cobrador de impostos e escrevi um Evangelho."],"Mateus 9:9","Apóstolos e Igreja",["Tomé","André","Filipe"],1],
["Matias",[],["Fui escolhido por sorte.","Substituí alguém que abandonou o apostolado.","Tomei o lugar de Judas entre os doze."],"Atos 1:23-26","Apóstolos e Igreja",["Barsabás","Barnabé","Silas"],3],
["Paulo",["saulo","paulo de tarso"],["Estive presente quando um jovem foi apedrejado e guardei as vestes dos que o apedrejavam.","Uma luz me cegou no caminho de Damasco.","Fui perseguidor e virei apóstolo dos gentios; antes me chamavam Saulo."],"Atos 7:58; 9:3-9","Apóstolos e Igreja",["Barnabé","Silas","Timóteo"],1],
["Barnabé",["barnabe"],["Vendi um campo e entreguei o dinheiro aos apóstolos.","Fui chamado Filho da Consolação.","Apresentei Saulo aos apóstolos e viajei com ele."],"Atos 4:36-37; 9:27; 13","Apóstolos e Igreja",["Silas","Timóteo","Marcos"],2],
["Estêvão",["estevao"],["Fui escolhido para servir às mesas.","Meu rosto parecia o de um anjo.","Fui o primeiro mártir cristão, apedrejado."],"Atos 6-7","Apóstolos e Igreja",["Silas","Timóteo","Tito"],2],
["Timóteo",["timoteo"],["Minha avó e minha mãe tinham fé sincera.","Fui circuncidado por causa dos judeus daquela região.","Fui jovem discípulo de Paulo, de Listra, a quem ele escreveu duas cartas."],"2 Timóteo 1:5; Atos 16:1-3","Apóstolos e Igreja",["Tito","Silas","Marcos"],2],
["Silas",[],["Cantei hinos à meia-noite numa prisão.","Um terremoto abriu as portas.","Fui companheiro de Paulo na segunda viagem e fui preso em Filipos."],"Atos 16:25-26","Apóstolos e Igreja",["Barnabé","Timóteo","Lucas"],2],
["Cornélio",["cornelio"],["Era soldado e orava sempre.","Um anjo me orientou a chamar um homem de Jope.","Fui centurião romano em Cesareia, o primeiro gentio batizado por Pedro."],"Atos 10","Apóstolos e Igreja",["Sérgio Paulo","Júlio","Cláudio Lísias"],3],
["Ananias de Damasco",["ananias"],["Era discípulo e tinha medo de um perseguidor da igreja.","Deus falou comigo numa visão sobre a rua chamada Direita.","Impus as mãos em Saulo e algo como escamas caiu dos seus olhos."],"Atos 9:10-18","Apóstolos e Igreja",["Barnabé","Cornélio","Tito"],3],
["Lucas",[],["Fui médico.","Escrevi duas obras dirigidas a Teófilo.","Fui o autor de um Evangelho e do livro de Atos."],"Colossenses 4:14; Lucas 1:3","Apóstolos e Igreja",["Marcos","Timóteo","Tito"],2],
["Apolo",[],["Era natural de Alexandria.","Era eloquente e poderoso nas Escrituras.","Fui ensinado por Priscila e Áquila e preguei em Éfeso e Corinto."],"Atos 18:24-26","Apóstolos e Igreja",["Timóteo","Tito","Silas"],3],
["Eutico",["eutico"],["Sentei numa janela durante um longo sermão.","Adormeci profundamente no terceiro andar.","Caí e morri, mas Paulo me abraçou e fui restaurado."],"Atos 20:9-12","Apóstolos e Igreja",["Timóteo","Demas","Tíquico"],2],

// ===== Lugares e Objetos =====
["Arca de Noé",["arca de noe"],["Fui feita de madeira de gofer.","Tive três andares e uma janela.","Flutuei sobre o dilúvio com oito pessoas e muitos animais."],"Gênesis 6:14-16; 1 Pedro 3:20","Lugares e Objetos",["Arca da Aliança","Torre de Babel","Cesta de Moisés"],1],
["Arca da Aliança",["arca da alianca","arca do testemunho"],["Fui coberta de ouro puro por dentro e por fora.","Dois querubins me cobriam.","Guardei as tábuas da lei e fui carregada no deserto."],"Êxodo 25:10-22","Lugares e Objetos",["Candelabro de Ouro","Altar de Incenso","Arca de Noé"],1],
["Burra de Balaão",["jumenta de balaao","jumenta","burra","burra de balaao"],["Enxerguei o que meu dono não via.","Encostei-me contra o muro e apertei o pé dele.","Fui um animal que falou com voz humana."],"Números 22:23-30","Lugares e Objetos",["Grande Peixe de Jonas","Corvos de Elias","Carneiro de Isaque"],1],
["Monte Sinai",["sinai"],["Fui envolvido em fumaça, trovões e relâmpagos.","O povo não podia tocar em mim.","Nele Moisés recebeu as duas tábuas da lei."],"Êxodo 19-20","Lugares e Objetos",["Monte Carmelo","Monte Nebo","Monte Moriá"],1],
["Mar Vermelho",["vermelho"],["Fui dividido por um vento forte vindo do oriente.","Fui atravessado em seco por uma multidão.","Minhas águas voltaram sobre o exército do faraó."],"Êxodo 14","Lugares e Objetos",["Rio Jordão","Mar da Galileia","Mar Morto"],1],
["Sarça Ardente",["sarca ardente","sarca"],["Queimava e não me consumia.","Estive no monte Horebe.","Deus falou a Moisés do meio de mim."],"Êxodo 3:2-4","Lugares e Objetos",["Coluna de Fogo","Vara de Arão","Maná"],1],
["Torre de Babel",["babel"],["Fui construída na terra de Sinar.","Usaram tijolos e betume para me erguer.","Tentaram chegar ao céu por mim, e Deus confundiu as línguas."],"Gênesis 11:1-9","Lugares e Objetos",["Muralhas de Jericó","Torre de Siloé","Templo de Salomão"],1],
["Jardim do Éden",["eden","jardim de eden"],["Quatro rios saíam de mim.","Tinha duas árvores especiais no meio.","Nele viveram Adão e Eva antes da queda."],"Gênesis 2:8-17","Lugares e Objetos",["Terra de Canaã","Monte Sião","Jardim do Getsêmani"],1],
["Maná",["mana"],["Apareci com o orvalho da manhã.","Parecia semente de coentro e tinha gosto de bolos com mel.","Fui o pão do céu que alimentou Israel durante quarenta anos."],"Êxodo 16:14-31","Lugares e Objetos",["Codornizes","Água da Rocha","Pães da Proposição"],1],
["Grande Peixe de Jonas",["grande peixe","peixe","baleia"],["Fui preparado pelo Senhor para uma missão.","Ganhei um passageiro que ficou três dias dentro de mim.","Engoli Jonas e o vomitei na terra seca."],"Jonas 1:17; 2:10","Lugares e Objetos",["Burra de Balaão","Corvos de Elias","Leões de Daniel"],1]
];

(window.IASDBank=window.IASDBank||{}).said=[
["Eis-me aqui, envia-me a mim.","Isaías",["Jeremias","Ezequiel","Oseias"],"Isaías 6:8",1],
["Sou eu guardador do meu irmão?","Caim",["Esaú","Labão","Rúben"],"Gênesis 4:9",1],
["A mulher que me deste por companheira, ela me deu da árvore, e comi.","Adão",["Caim","Abel","Sete"],"Gênesis 3:12",1],
["A serpente me enganou, e eu comi.","Eva",["Sara","Hagar","Lia"],"Gênesis 3:13",1],
["Deus me deu motivo de riso; todo aquele que ouvir rirá comigo.","Sara",["Rebeca","Raquel","Hagar"],"Gênesis 21:6",2],
["Não haja contenda entre mim e ti, porque irmãos somos.","Abraão",["Isaque","Labão","Jacó"],"Gênesis 13:8",2],
["Eis o fogo e a lenha; mas onde está o cordeiro para o holocausto?","Isaque",["Ismael","Jacó","Esaú"],"Gênesis 22:7",2],
["Deus proverá para si o cordeiro para o holocausto, meu filho.","Abraão",["Isaque","Ló","Jacó"],"Gênesis 22:8",2],
["Eis que estou a ponto de morrer; de que me serve a primogenitura?","Esaú",["Jacó","Ismael","Rúben"],"Gênesis 25:32",2],
["Não te deixarei ir, se me não abençoares.","Jacó",["Esaú","Isaque","Labão"],"Gênesis 32:26",2],
["Poucos e maus têm sido os dias dos anos da minha vida.","Jacó",["Isaque","Abraão","Esaú"],"Gênesis 47:9",3],
["Dá-me filhos, senão morro.","Raquel",["Lia","Sara","Rebeca"],"Gênesis 30:1",2],
["Como, pois, faria eu este tamanho mal e pecaria contra Deus?","José do Egito",["Judá","Rúben","Benjamim"],"Gênesis 39:9",2],
["Eu sou José, vosso irmão, a quem vendestes para o Egito.","José do Egito",["Judá","Rúben","Benjamim"],"Gênesis 45:4",1],
["Vós bem intentastes mal contra mim, porém Deus o tornou em bem.","José do Egito",["Judá","Rúben","Jacó"],"Gênesis 50:20",2],
["Quem sou eu para que vá a Faraó?","Moisés",["Arão","Josué","Calebe"],"Êxodo 3:11",2],
["Quem é o Senhor, cuja voz eu ouça?","Faraó",["Moisés","Arão","Balaque"],"Êxodo 5:2",2],
["Não temais; estai quietos e vede o livramento do Senhor.","Moisés",["Arão","Josué","Calebe"],"Êxodo 14:13",2],
["Cantai ao Senhor, porque gloriosamente triunfou.","Miriã",["Jael","Raabe","Dalila"],"Êxodo 15:21",3],
["Quem é do Senhor, venha a mim.","Moisés",["Arão","Josué","Coré"],"Êxodo 32:26",3],
["Não é bom o que fazes.","Jetro",["Arão","Josué","Coré"],"Êxodo 18:17",3],
["Como amaldiçoarei o que Deus não amaldiçoou?","Balaão",["Balaque","Jetro","Coré"],"Números 23:8",3],
["Vem, pois, agora, amaldiçoa-me este povo.","Balaque",["Balaão","Jetro","Coré"],"Números 22:6",3],
["Dá-me, pois, este monte.","Calebe",["Josué","Otniel","Eleazar"],"Josué 14:12",2],
["Sol, detém-te em Gibeão.","Josué",["Moisés","Calebe","Gideão"],"Josué 10:12",2],
["Escolhei hoje a quem sirvais; eu e a minha casa serviremos ao Senhor.","Josué",["Moisés","Calebe","Gideão"],"Josué 24:15",1],
["Sei que o Senhor vos deu esta terra.","Raabe",["Rute","Jael","Dalila"],"Josué 2:9",3],
["Levanta-te, porque este é o dia em que o Senhor entregou a Sísera nas tuas mãos.","Débora",["Jael","Miriã","Hulda"],"Juízes 4:14",3],
["Se fores comigo, irei; mas, se não fores comigo, não irei.","Baraque",["Gideão","Eúde","Sísera"],"Juízes 4:8",3],
["Ai, Senhor meu! Com que livrarei Israel?","Gideão",["Sansão","Baraque","Jefté"],"Juízes 6:15",2],
["Abri a minha boca ao Senhor e não poderei tornar atrás.","Jefté",["Gideão","Sansão","Eúde"],"Juízes 11:35",3],
["Sansão, os filisteus vêm sobre ti!","Dalila",["Jael","Raabe","Jezabel"],"Juízes 16:9",2],
["Morra eu com os filisteus!","Sansão",["Gideão","Jefté","Eúde"],"Juízes 16:30",2],
["Onde quer que fores, irei eu; o teu povo é o meu povo, e o teu Deus é o meu Deus.","Rute",["Noemi","Orfa","Ester"],"Rute 1:16",1],
["Não me chameis Noemi; chamai-me Mara, porque o Todo-Poderoso me tem enchido de amargura.","Noemi",["Rute","Orfa","Ana"],"Rute 1:20",2],
["Por este menino orava eu, e o Senhor me concedeu o que lhe pedi.","Ana (mãe de Samuel)",["Penina","Noemi","Isabel"],"1 Samuel 1:27",3],
["Fala, Senhor, porque o teu servo ouve.","Samuel",["Saul","Davi","Natã"],"1 Samuel 3:10",1],
["É o Senhor; faça o que bem lhe parecer.","Eli",["Samuel","Saul","Davi"],"1 Samuel 3:18",3],
["Eis que o obedecer é melhor do que o sacrificar.","Samuel",["Natã","Elias","Eli"],"1 Samuel 15:22",2],
["Nada impede ao Senhor salvar com muitos ou com poucos.","Jônatas",["Saul","Davi","Abner"],"1 Samuel 14:6",3],
["Sou eu algum cão, que vens a mim com paus?","Golias",["Saul","Abner","Joabe"],"1 Samuel 17:43",2],
["O Senhor não salva com espada nem com lança.","Davi",["Saul","Jônatas","Samuel"],"1 Samuel 17:47",2],
["É esta a tua voz, meu filho Davi?","Saul",["Jônatas","Samuel","Abner"],"1 Samuel 24:16",3],
["Senhor meu, caia sobre mim a culpa.","Abigail",["Mical","Bate-Seba","Noemi"],"1 Samuel 25:24",3],
["A arca, Israel e Judá ficam em tendas; não farei tal coisa.","Urias",["Joabe","Abner","Jônatas"],"2 Samuel 11:11",3],
["Tu és o homem.","Natã",["Samuel","Elias","Gade"],"2 Samuel 12:7",1],
["Meu filho Absalão, meu filho! Quem me dera que eu morrera por ti!","Davi",["Joabe","Saul","Salomão"],"2 Samuel 18:33",2],
["O Senhor é o meu pastor, nada me faltará.","Davi",["Salomão","Asafe","Moisés"],"Salmo 23:1",1],
["Dá, pois, ao teu servo um coração compreensivo.","Salomão",["Davi","Roboão","Ezequias"],"1 Reis 3:9",2],
["Dividi em duas partes o menino vivo.","Salomão",["Davi","Roboão","Natã"],"1 Reis 3:25",2],
["Foi verdade a palavra que ouvi na minha terra a teu respeito.","Rainha de Sabá",["Ester","Jezabel","Atalia"],"1 Reis 10:6",3],
["Até quando coxeareis entre dois pensamentos?","Elias",["Eliseu","Samuel","Natã"],"1 Reis 18:21",1],
["Basta; toma agora, ó Senhor, a minha alma.","Elias",["Eliseu","Natã","Samuel"],"1 Reis 19:4",3],
["Achaste-me, inimigo meu?","Acabe",["Jeú","Jeroboão","Onri"],"1 Reis 21:20",3],
["Guarde-me o Senhor de que eu te dê a herança de meus pais.","Nabote",["Acabe","Elias","Jeú"],"1 Reis 21:3",3],
["Vive o Senhor que o que o Senhor me disser, isso falarei.","Micaías",["Elias","Eliseu","Natã"],"1 Reis 22:14",3],
["Meu pai, meu pai, carros de Israel e seus cavaleiros!","Eliseu",["Elias","Geazi","Samuel"],"2 Reis 2:12",2],
["Agora sei que em toda a terra não há Deus senão em Israel.","Naamã",["Geazi","Hazael","Acabe"],"2 Reis 5:15",3],
["O Senhor, Deus dos céus, me deu todos os reinos da terra.","Ciro",["Dario","Nabucodonosor","Artaxerxes"],"Esdras 1:2",3],
["Faço uma grande obra, de modo que não poderei descer.","Neemias",["Esdras","Zorobabel","Sambalate"],"Neemias 6:3",2],
["Quem sabe se para tal tempo como este chegaste ao reino?","Mardoqueu",["Hamã","Neemias","Daniel"],"Ester 4:14",2],
["Se perecer, pereci.","Ester",["Rute","Débora","Vasti"],"Ester 4:16",1],
["Nu saí do ventre de minha mãe, e nu tornarei para lá.","Jó",["Elifaz","Davi","Salomão"],"Jó 1:21",2],
["Ainda que ele me mate, nele esperarei.","Jó",["Elifaz","Davi","Jeremias"],"Jó 13:15",2],
["Eu sei que o meu Redentor vive.","Jó",["Elifaz","Davi","Isaías"],"Jó 19:25",2],
["Ai de mim, que vou perecendo! Porque sou homem de lábios impuros.","Isaías",["Jeremias","Ezequiel","Daniel"],"Isaías 6:5",3],
["Ah, Senhor Deus! Eis que não sei falar, porque ainda sou uma criança.","Jeremias",["Isaías","Ezequiel","Jonas"],"Jeremias 1:6",2],
["Bendito seja o Deus de Sadraque, Mesaque e Abede-Nego.","Nabucodonosor",["Belsazar","Ciro","Hamã"],"Daniel 3:28",3],
["O meu Deus enviou o seu anjo e fechou a boca dos leões.","Daniel",["Sadraque","Mardoqueu","Nabucodonosor"],"Daniel 6:22",2],
["Levantai-me e lançai-me ao mar.","Jonas",["Amós","Oseias","Naum"],"Jonas 1:12",2],
["Agora, Senhor, podes despedir em paz o teu servo.","Simeão",["Zacarias","José de Nazaré","Eli"],"Lucas 2:29",2],
["Eis aqui a serva do Senhor; cumpra-se em mim segundo a tua palavra.","Maria, mãe de Jesus",["Isabel","Marta","Ana"],"Lucas 1:38",1],
["A minha alma engrandece ao Senhor.","Maria, mãe de Jesus",["Isabel","Marta","Maria Madalena"],"Lucas 1:46",1],
["Bendita és tu entre as mulheres, e bendito o fruto do teu ventre.","Isabel",["Maria","Ana","Marta"],"Lucas 1:42",2],
["O seu nome é João.","Zacarias",["Simeão","José de Nazaré","Eli"],"Lucas 1:63",2],
["Eis o Cordeiro de Deus, que tira o pecado do mundo.","João Batista",["André","Pedro","Zacarias"],"João 1:29",1],
["Convém que ele cresça e que eu diminua.","João Batista",["André","Zacarias","Simeão"],"João 3:30",2],
["Achamos o Messias.","André",["Tomé","Tiago","Mateus"],"João 1:41",2],
["Vem e vê.","Filipe",["Natanael","André","Tomé"],"João 1:46",2],
["Pode vir alguma coisa boa de Nazaré?","Natanael",["Filipe","Tomé","Pedro"],"João 1:46",2],
["Como pode o homem nascer, sendo velho?","Nicodemos",["Zaqueu","Caifás","José de Arimateia"],"João 3:4",2],
["Senhor, para quem iremos? Tu tens as palavras da vida eterna.","Pedro",["Tomé","André","Filipe"],"João 6:68",2],
["Vamos nós também, para morrermos com ele.","Tomé",["André","Filipe","Mateus"],"João 11:16",3],
["Convém que um homem morra pelo povo.","Caifás",["Anás","Pilatos","Nicodemos"],"João 11:50",2],
["Tu és o Cristo, o Filho do Deus vivo.","Pedro",["Tiago","André","Mateus"],"Mateus 16:16",1],
["Senhor, afasta-te de mim, porque sou homem pecador.","Pedro",["André","Tiago","João"],"Lucas 5:8",2],
["Senhor, tu sabes todas as coisas; tu sabes que te amo.","Pedro",["João","Tomé","André"],"João 21:17",1],
["Não tenho prata nem ouro, mas o que tenho isso te dou.","Pedro",["Paulo","Estêvão","Barnabé"],"Atos 3:6",2],
["Senhor meu e Deus meu!","Tomé",["Pedro","André","Filipe"],"João 20:28",1],
["Que me quereis dar, e eu vo-lo entregarei?","Judas Iscariotes",["Caifás","Pedro","Pilatos"],"Mateus 26:15",2],
["Pequei, traindo o sangue inocente.","Judas Iscariotes",["Pilatos","Caifás","Pedro"],"Mateus 27:4",2],
["Que é a verdade?","Pôncio Pilatos",["Caifás","Anás","Nicodemos"],"João 18:38",1],
["Estou inocente do sangue deste justo.","Pôncio Pilatos",["Caifás","Anás","Nicodemos"],"Mateus 27:24",2],
["O que escrevi, escrevi.","Pôncio Pilatos",["Caifás","Anás","Gamaliel"],"João 19:22",2],
["Ide e informai-vos com diligência do menino; e, quando o achardes, participai-mo.","Herodes, o Grande",["Pilatos","Caifás","Augusto"],"Mateus 2:8",2],
["Senhor, eis que dou aos pobres metade dos meus bens.","Zaqueu",["Mateus","Nicodemos","Bartimeu"],"Lucas 19:8",2],
["Filho de Davi, tem misericórdia de mim!","Bartimeu",["Zaqueu","Lázaro","Jairo"],"Marcos 10:47",2],
["Senhor, não te importas que minha irmã me deixe servir só?","Marta",["Maria Madalena","Isabel","Lídia"],"Lucas 10:40",2],
["Se este conselho ou esta obra é de homens, se desfará.","Gamaliel",["Caifás","Nicodemos","Paulo"],"Atos 5:38",3],
["Senhor Jesus, recebe o meu espírito.","Estêvão",["Filipe","Paulo","Pedro"],"Atos 7:59",2],
["Entendes tu o que lês?","Filipe, o evangelista",["Pedro","Estêvão","Barnabé"],"Atos 8:30",3],
["Senhor, que queres que eu faça?","Paulo",["Barnabé","Ananias de Damasco","Silas"],"Atos 9:6",2],
["Por agora vai-te; e, em tendo oportunidade, chamar-te-ei.","Félix",["Festo","Agripa","Pilatos"],"Atos 24:25",3],
["Por pouco me persuades a fazer-me cristão.","Agripa",["Félix","Festo","Pilatos"],"Atos 26:28",3],
["Combati o bom combate, acabei a carreira, guardei a fé.","Paulo",["Pedro","Timóteo","Barnabé"],"2 Timóteo 4:7",1],
["Posso todas as coisas naquele que me fortalece.","Paulo",["Pedro","João","Tiago"],"Filipenses 4:13",1],
["Para mim o viver é Cristo, e o morrer é lucro.","Paulo",["Pedro","João","Tiago"],"Filipenses 1:21",2],
["Onde está, ó morte, o teu aguilhão?","Paulo",["Pedro","João","Tiago"],"1 Coríntios 15:55",3],
["A fé sem obras é morta.","Tiago",["Paulo","Pedro","João"],"Tiago 2:26",2],
["Deus é amor.","João, o discípulo amado",["Paulo","Pedro","Tiago"],"1 João 4:8",1],
["Eu sou o caminho, e a verdade, e a vida.","Jesus",["João Batista","Pedro","Paulo"],"João 14:6",1],
["Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.","Jesus",["João Batista","Pedro","Paulo"],"Mateus 11:28",1],
["Eu sou o pão da vida.","Jesus",["João Batista","Moisés","Davi"],"João 6:35",1],
["Deixai vir a mim os pequeninos.","Jesus",["Pedro","Paulo","João Batista"],"Marcos 10:14",1],
["Pai, perdoa-lhes, porque não sabem o que fazem.","Jesus",["Estêvão","Pedro","Paulo"],"Lucas 23:34",2]
];
