/* IASD APP - banco de estudo bíblico (timeline, memória, versículos) */
(window.IASDBank=window.IASDBank||{}).timeline=[
 {t:'Dias da criação',items:['Criação da luz','Separação do céu e das águas','Terra seca e plantas','Sol, lua e estrelas','Peixes e aves','Animais e o homem','Descanso do sábado'],ref:'Gênesis 1–2',d:1},
 {t:'Do Éden aos primeiros filhos',items:['Deus forma Adão','Deus planta o jardim do Éden','Adão dá nome aos animais','Criação de Eva','Serpente tenta Eva','Expulsão do Éden','Nascimento de Caim e Abel'],ref:'Gênesis 2–4',d:1},
 {t:'De Caim à Torre de Babel',items:['Caim mata Abel','Nascimento de Sete','Enoque anda com Deus','Dilúvio','Torre de Babel','Chamado de Abraão'],ref:'Gênesis 4–12',d:1},
 {t:'A história de Noé',items:['Deus manda construir a arca','Animais entram na arca','Dilúvio cobre a terra','Arca pousa no Ararate','Pomba traz ramo de oliveira','Aliança do arco-íris'],ref:'Gênesis 6–9',d:1},
 {t:'A vida de Abraão',items:['Chamado de Abraão','Separação de Abraão e Ló','Destruição de Sodoma','Nascimento de Isaque','Isaque no monte Moriá','Morte de Sara'],ref:'Gênesis 12–23',d:2},
 {t:'Isaque e Jacó',items:['Nascimento de Esaú e Jacó','Esaú vende a primogenitura','Jacó recebe a bênção','Sonho da escada em Betel','Jacó serve Labão','Luta com o anjo em Peniel','Reencontro com Esaú'],ref:'Gênesis 25–33',d:2},
 {t:'A história de José',items:['José é vendido pelos irmãos','José na casa de Potifar','José preso injustamente','José interpreta sonhos do faraó','José governador do Egito','José se revela aos irmãos','Família de Jacó desce ao Egito'],ref:'Gênesis 37–46',d:1},
 {t:'A vida de Moisés',items:['Nascimento de Moisés','Moisés criado no palácio','Fuga para Midiã','Sarça ardente','Pragas do Egito','Travessia do Mar Vermelho','Recebe os Dez Mandamentos'],ref:'Êxodo 2–20',d:1},
 {t:'Do Egito ao Sinai',items:['Páscoa no Egito','Travessia do Mar Vermelho','Maná no deserto','Água da rocha em Refidim','Dez Mandamentos no Sinai','Bezerro de ouro','Construção do tabernáculo'],ref:'Êxodo 12–40',d:2},
 {t:'Pragas do Egito',items:['Água em sangue','Rãs','Moscas','Peste nos animais','Saraiva','Gafanhotos','Trevas','Morte dos primogênitos'],ref:'Êxodo 7–12',d:3},
 {t:'Peregrinação no deserto',items:['Envio dos doze espias','Rebelião de Corá','Vara de Arão floresce','Serpente de bronze','Burra de Balaão','Morte de Moisés no monte Nebo'],ref:'Números 13–Deuteronômio 34',d:3},
 {t:'A conquista de Canaã',items:['Josué sucede Moisés','Travessia do Jordão','Queda de Jericó','Derrota em Ai por causa de Acã','Sol para em Gibeão','Divisão da terra entre as tribos'],ref:'Josué 1–21',d:2},
 {t:'Gideão',items:['Anjo chama Gideão','Gideão derruba o altar de Baal','Sinal da lã','Exército reduzido a 300','Ataque noturno com trombetas'],ref:'Juízes 6–7',d:1},
 {t:'A vida de Sansão',items:['Anúncio do nascimento de Sansão','Sansão mata o leão','Enigma no casamento','Sansão queima as plantações','Sansão carrega as portas de Gaza','Dalila corta seu cabelo','Sansão derruba o templo'],ref:'Juízes 13–16',d:2},
 {t:'Os juízes de Israel',items:['Eúde mata o rei Eglom','Débora e Baraque vencem Sísera','Gideão e os 300','Jefté e sua promessa','Sansão e Dalila','Morte de Sansão'],ref:'Juízes 3–16',d:3},
 {t:'De Rute a Samuel',items:['Rute segue Noemi a Belém','Rute casa com Boaz','Nascimento de Samuel','Deus chama Samuel','Arca capturada pelos filisteus','Israel pede um rei'],ref:'Rute; 1 Samuel 1–8',d:2},
 {t:'De Saul a Davi',items:['Samuel unge Saul','Samuel unge Davi','Davi derrota Golias','Davi foge de Saul','Morte de Saul','Davi se torna rei'],ref:'1 Samuel 9–31; 2 Samuel 2',d:1},
 {t:'Davi fugitivo',items:['Davi toca harpa para Saul','Davi derrota Golias','Amizade com Jônatas','Davi poupa Saul na caverna','Davi e Abigail','Davi poupa Saul no acampamento'],ref:'1 Samuel 16–26',d:2},
 {t:'O reinado de Davi',items:['Davi é ungido rei em Hebrom','Davi conquista Jerusalém','Arca levada a Jerusalém','Davi e Bate-Seba','Natã repreende Davi','Rebelião de Absalão','Salomão é coroado rei'],ref:'2 Samuel 2–1 Reis 1',d:2},
 {t:'A arca da aliança',items:['Construção da arca no Sinai','Arca atravessa o Jordão','Arca cerca Jericó','Arca capturada pelos filisteus','Davi leva a arca a Jerusalém','Arca no templo de Salomão'],ref:'Êxodo 25; Josué 3–6; 1 Samuel 4; 2 Samuel 6; 1 Reis 8',d:3},
 {t:'O reinado de Salomão',items:['Salomão pede sabedoria','Sentença das duas mães','Construção do templo','Dedicação do templo','Visita da rainha de Sabá','Divisão do reino após Salomão'],ref:'1 Reis 3–12',d:2},
 {t:'Reis de Israel',items:['Saul é o primeiro rei','Davi sucede Saul','Salomão constrói o templo','Reino dividido','Queda de Samaria','Exílio na Babilônia'],ref:'1 Samuel–2 Reis',d:1},
 {t:'A vida de Elias',items:['Elias prediz a seca','Elias é alimentado pelos corvos','Viúva de Sarepta','Fogo no monte Carmelo','Elias foge para o Horebe','Vinha de Nabote','Elias arrebatado ao céu'],ref:'1 Reis 17–2 Reis 2',d:1},
 {t:'A vida de Eliseu',items:['Eliseu recebe o manto de Elias','Eliseu purifica as águas de Jericó','Azeite da viúva multiplicado','Filho da sunamita ressuscitado','Naamã curado da lepra','Machado de ferro flutua'],ref:'2 Reis 2–6',d:2},
 {t:'O reino dividido',items:['Divisão entre Israel e Judá','Elias no monte Carmelo','Queda de Samaria','Cura de Ezequias','Josias acha o livro da lei','Queda de Jerusalém'],ref:'1 Reis 12–2 Reis 25',d:3},
 {t:'Os profetas',items:['Ministério de Elias','Jonas em Nínive','Isaías vê o Senhor no templo','Jeremias é chamado profeta','Ezequiel vê o vale de ossos','Daniel na cova dos leões'],ref:'Profetas',d:3},
 {t:'A história de Jonas',items:['Deus chama Jonas','Jonas foge num navio','Tempestade no mar','Jonas lançado ao mar','Jonas no grande peixe','Nínive se arrepende','Jonas e a aboboreira'],ref:'Jonas 1–4',d:1},
 {t:'A vida de Daniel',items:['Daniel levado à Babilônia','Daniel recusa a comida do rei','Sonho da grande estátua','Fornalha ardente','Nabucodonosor enlouquece','Banquete de Belsazar','Daniel na cova dos leões'],ref:'Daniel 1–6',d:1},
 {t:'Exílio e retorno',items:['Queda de Jerusalém','Exílio na Babilônia','Queda da Babilônia','Decreto de Ciro','Retorno com Zorobabel','Reconstrução do templo','Neemias reconstrói os muros'],ref:'2 Reis 25; Esdras; Neemias',d:2},
 {t:'A história de Ester',items:['Vasti é deposta','Ester torna-se rainha','Mardoqueu descobre conspiração','Hamã decreta exterminar judeus','Ester se apresenta ao rei','Hamã é enforcado','Festa de Purim'],ref:'Ester 1–9',d:1},
 {t:'Templos de Israel',items:['Construção do tabernáculo','Templo de Salomão','Templo destruído por Nabucodonosor','Reconstrução sob Zorobabel','Jesus purifica o templo'],ref:'Êxodo 35–40; 1 Reis 6; 2 Reis 25; Esdras 6; João 2',d:3},
 {t:'O nascimento de Jesus',items:['Anúncio do anjo a Maria','Visita de Maria a Isabel','Nascimento de João Batista','Nascimento de Jesus','Visita dos pastores','Visita dos magos','Fuga para o Egito'],ref:'Mateus 1–2; Lucas 1–2',d:1},
 {t:'A infância de Jesus',items:['Circuncisão de Jesus','Apresentação no templo','Fuga para o Egito','Volta a Nazaré','Jesus aos 12 anos no templo','Batismo de Jesus'],ref:'Mateus 2; Lucas 2–3',d:2},
 {t:'Início do ministério',items:['Batismo de Jesus','Tentação no deserto','Primeiros discípulos seguem Jesus','Casamento em Caná','Jesus purifica o templo','Conversa com Nicodemos'],ref:'Mateus 3–4; João 1–3',d:1},
 {t:'Milagres em Marcos',items:['Tempestade acalmada','Endemoninhado geraseno','Filha de Jairo ressuscitada','Cinco mil alimentados','Jesus anda sobre o mar','Transfiguração'],ref:'Marcos 4–9',d:2},
 {t:'Ministério na Galileia',items:['Sermão do Monte','Cura do servo do centurião','Filho da viúva de Naim','Jesus acalma a tempestade','Envio dos doze','Morte de João Batista','Alimentação dos cinco mil'],ref:'Mateus 5–14; Lucas 7',d:3},
 {t:'Sinais no Evangelho de João',items:['Água em vinho','Cura do filho do oficial','Cura no tanque de Betesda','Multiplicação dos pães','Jesus anda sobre o mar','Cura do cego de nascença','Ressurreição de Lázaro'],ref:'João 2–11',d:3},
 {t:'Rumo a Jerusalém',items:['Transfiguração','Ressurreição de Lázaro','Cura de Bartimeu em Jericó','Entrada triunfal em Jerusalém','Jesus purifica o templo','Última Ceia'],ref:'Marcos 9–14; João 11',d:3},
 {t:'A semana da paixão',items:['Entrada triunfal em Jerusalém','Última Ceia','Oração no Getsêmani','Prisão de Jesus','Negação de Pedro','Julgamento diante de Pilatos','Crucificação','Ressurreição'],ref:'Mateus 21–28',d:1},
 {t:'Sexta-feira da crucificação',items:['Pedro nega Jesus','Pilatos lava as mãos','Simão carrega a cruz','Jesus crucificado no Gólgota','Trevas cobrem a terra','Jesus morre','Sepultamento por José de Arimateia'],ref:'Mateus 26–27',d:2},
 {t:'Após a ressurreição',items:['Sepultamento de Jesus','Mulheres encontram a tumba vazia','Jesus aparece a Maria Madalena','Caminho de Emaús','Jesus aparece a Tomé','Pesca milagrosa em Tiberíades','Ascensão ao céu','Pentecostes'],ref:'Lucas 24; João 20–21; Atos 1–2',d:1},
 {t:'A igreja primitiva',items:['Ascensão de Jesus','Escolha de Matias','Pentecostes','Cura do coxo no templo','Morte de Ananias e Safira','Escolha dos sete diáconos','Martírio de Estêvão','Conversão de Paulo'],ref:'Atos 1–9',d:1},
 {t:'Expansão da igreja',items:['Filipe e o eunuco etíope','Conversão de Paulo','Pedro e Cornélio','Chamados cristãos em Antioquia','Herodes mata Tiago','Pedro libertado da prisão'],ref:'Atos 8–12',d:3},
 {t:'A vida de Pedro',items:['Jesus chama Pedro','Pedro anda sobre as águas','Pedro confessa Jesus como o Cristo','Pedro nega Jesus','Pedro restaurado à beira do mar','Pedro prega no Pentecostes','Pedro visita Cornélio'],ref:'Evangelhos; Atos 2; 10',d:2},
 {t:'A vida de Paulo',items:['Apedrejamento de Estêvão','Conversão a caminho de Damasco','Ananias restaura sua vista','Primeira viagem missionária','Prisão em Filipos','Naufrágio em Malta','Chegada a Roma'],ref:'Atos 7–28',d:1},
 {t:'Primeira viagem de Paulo',items:['Barnabé e Saulo são enviados','Elimas fica cego em Chipre','Sermão em Antioquia da Pisídia','Cura do coxo em Listra','Paulo apedrejado em Listra','Concílio de Jerusalém'],ref:'Atos 13–15',d:2},
 {t:'Segunda viagem de Paulo',items:['Paulo escolhe Silas','Visão do homem da Macedônia','Conversão de Lídia em Filipos','Prisão em Filipos e o terremoto','Paulo em Atenas no Areópago','Um ano e meio em Corinto'],ref:'Atos 15–18',d:2},
 {t:'Terceira viagem e Roma',items:['Dois anos de ministério em Éfeso','Tumulto dos ourives em Éfeso','Eutico cai da janela em Trôade','Despedida dos anciãos em Mileto','Paulo preso em Jerusalém','Paulo apela a César','Naufrágio em Malta','Paulo chega a Roma'],ref:'Atos 19–28',d:2}
];
(window.IASDBank=window.IASDBank||{}).memory=[
 {t:'Personagens e feitos',emoji:'🕊️',pairs:[['Noé','Arca'],['Davi','Golias'],['Daniel','Leões'],['Jonas','Grande peixe'],['Moisés','Sarça ardente'],['Sansão','Cabelo'],['Abraão','Isaque'],['Jacó','Escada'],['José','Túnica colorida'],['Zaqueu','Sicômoro'],['Elias','Corvos'],['Gideão','300 homens'],['Josué','Jericó'],['Eva','Fruto proibido']]},
 {t:'Eventos e lugares',emoji:'📍',pairs:[['Dez Mandamentos','Monte Sinai'],['Arca pousa','Monte Ararate'],['Elias vence Baal','Monte Carmelo'],['Crucificação','Gólgota'],['Oração de Jesus','Getsêmani'],['Nascimento de Jesus','Belém'],['Água em vinho','Caná'],['Lázaro ressuscitado','Betânia'],['Muros caem','Jericó'],['Confusão de línguas','Babel'],['Visão do Apocalipse','Ilha de Patmos'],['Primeiro pecado','Éden'],['Conversão de Paulo','Estrada de Damasco'],['Naufrágio de Paulo','Malta']]},
 {t:'Livros da Bíblia e temas',emoji:'📚',pairs:[['Gênesis','Origens'],['Êxodo','Saída do Egito'],['Levítico','Leis e sacrifícios'],['Números','Peregrinação'],['Deuteronômio','Discursos de Moisés'],['Josué','Conquista de Canaã'],['Juízes','Gideão e Sansão'],['Rute','Moabita fiel'],['Neemias','Muros de Jerusalém'],['Ester','Festa de Purim'],['Jó','Paciência na prova'],['Salmos','Hinos de louvor'],['Provérbios','Sabedoria prática'],['Daniel','Leões e fornalha'],['Atos','Igreja primitiva'],['Apocalipse','Visões de João']]},
 {t:'Discípulos e características',emoji:'🙏',pairs:[['Pedro','Negou Jesus'],['Tomé','Duvidou'],['João','Discípulo amado'],['Judas Iscariotes','Traidor'],['Mateus','Cobrador de impostos'],['André','Irmão de Pedro'],['Paulo','Apóstolo dos gentios'],['Matias','Substituto de Judas'],['Lucas','Médico amado'],['Barnabé','Filho da consolação'],['Estêvão','Primeiro mártir'],['Tiago, filho de Zebedeu','Apóstolo mártir'],['Timóteo','Pupilo de Paulo']]},
 {t:'Mulheres da Bíblia',emoji:'👩',pairs:[['Eva','Primeira mulher'],['Sara','Mãe de Isaque'],['Rebeca','Deu água aos camelos'],['Raquel','Mãe de José'],['Miriã','Irmã de Moisés'],['Débora','Juíza e profetisa'],['Rute','Fiel a Noemi'],['Ana','Mãe de Samuel'],['Ester','Rainha da Pérsia'],['Maria','Mãe de Jesus'],['Lídia','Vendedora de púrpura'],['Raabe','Escondeu os espias'],['Jael','Matou Sísera'],['Dalila','Traiu Sansão'],['Isabel','Mãe de João Batista']]},
 {t:'Casais da Bíblia',emoji:'💞',pairs:[['Adão','Eva'],['Abraão','Sara'],['Isaque','Rebeca'],['Jacó','Raquel'],['Boaz','Rute'],['Elcana','Ana'],['Zacarias','Isabel'],['José','Maria'],['Áquila','Priscila'],['Ananias','Safira'],['Moisés','Zípora'],['Oseias','Gômer']]},
 {t:'Parábolas de Jesus',emoji:'🌱',pairs:[['Semeador','Sementes'],['Bom Samaritano','Estalagem'],['Filho Pródigo','Porcos'],['Ovelha Perdida','Noventa e nove'],['Dez Virgens','Azeite'],['Talentos','Cinco talentos'],['Grão de Mostarda','Menor semente'],['Fermento','Três medidas'],['Tesouro Escondido','Campo'],['Pérola','Mercador'],['Rede','Peixes bons e maus'],['Casa na Rocha','Tempestade'],['Fariseu e Publicano','Templo'],['Credor Incompassivo','Dez mil talentos']]},
 {t:'Profetas e mensagens',emoji:'📢',pairs:[['Isaías','Emanuel'],['Jonas','Nínive'],['Ezequiel','Ossos secos'],['Joel','Derramar do Espírito'],['Miqueias','Belém'],['Malaquias','Dízimos'],['Ageu','Reconstruir o templo'],['Zacarias','Rei em jumentinho'],['Amós','Pastor de Tecoa'],['Natã','Parábola da ovelha'],['Eliseu','Naamã'],['Elias','Carmelo'],['Jeremias','Oleiro']]},
 {t:'Pessoas curadas por Jesus',emoji:'✨',pairs:[['Jairo','Filha ressuscitada'],['Lázaro','Saiu do túmulo'],['Bartimeu','Voltou a ver'],['Sogra de Pedro','Febre curada'],['Malco','Orelha curada'],['Mulher do fluxo','Tocou o manto'],['Paralítico','Descido pelo telhado'],['Geraseno','Porcos'],['Cego de nascença','Barro e Siloé'],['Centurião','Servo curado'],['Noivos de Caná','Vinho'],['Dez leprosos','Um voltou agradecido']]},
 {t:'Viagens de Paulo',emoji:'⛵',pairs:[['Damasco','Conversão'],['Listra','Apedrejado'],['Filipos','Prisão e terremoto'],['Atenas','Areópago'],['Éfeso','Templo de Diana'],['Corinto','Áquila e Priscila'],['Trôade','Eutico'],['Mileto','Despedida dos anciãos'],['Malta','Naufrágio'],['Roma','Prisão domiciliar'],['Chipre','Elimas'],['Cesareia','Félix e Festo'],['Bereia','Examinavam as Escrituras'],['Jerusalém','Concílio']]},
 {t:'Apocalipse',emoji:'📜',pairs:[['Éfeso','Primeiro amor'],['Esmirna','Fiel até a morte'],['Pérgamo','Trono de Satanás'],['Tiatira','Jezabel'],['Sardes','Nome de vivo'],['Filadélfia','Porta aberta'],['Laodiceia','Morna'],['Dragão','Satanás'],['Cordeiro','Cristo'],['Nova Jerusalém','Cidade santa'],['Trombetas','Sete anjos'],['Selos','Livro'],['Alfa','Ômega'],['Patmos','João']]},
 {t:'Símbolos e significados',emoji:'🔥',pairs:[['Pão','Corpo de Cristo'],['Vinho','Sangue de Cristo'],['Pomba','Espírito Santo'],['Arco-íris','Promessa a Noé'],['Cordeiro','Sacrifício'],['Sal da terra','Discípulos'],['Serpente de bronze','Cruz'],['Maná','Pão da vida'],['Incenso','Orações dos santos'],['Sinal de Jonas','Ressurreição'],['Sete estrelas','Anjos das igrejas'],['Sete candeeiros','Sete igrejas'],['Véu rasgado','Acesso a Deus']]},
 {t:'Reis e feitos',emoji:'👑',pairs:[['Saul','Primeiro rei'],['Davi','Coração de Deus'],['Salomão','Templo'],['Roboão','Reino dividido'],['Jeroboão','Bezerros de ouro'],['Acabe','Jezabel'],['Ezequias','Senaqueribe'],['Josias','Livro da lei'],['Nabucodonosor','Estátua de ouro'],['Belsazar','Escrita na parede'],['Dario','Cova dos leões'],['Ciro','Decreto de retorno'],['Herodes','Meninos de Belém'],['Faraó','Coração endurecido']]},
 {t:'Nomes de Jesus',emoji:'☀️',pairs:[['Pão da vida','Multiplicação dos pães'],['Luz do mundo','Cego de nascença'],['Ressurreição e vida','Lázaro'],['Videira verdadeira','Ramos'],['Bom Pastor','Ovelhas'],['Caminho, verdade e vida','Tomé'],['Água viva','Samaritana'],['Emanuel','Deus conosco'],['Cordeiro de Deus','João Batista'],['Verbo','No princípio'],['Príncipe da Paz','Isaías'],['Leão de Judá','Sete selos']]},
 {t:'O santuário',emoji:'⛺',pairs:[['Arca da aliança','Tábuas da lei'],['Candeeiro','Sete lâmpadas'],['Mesa','Pães da proposição'],['Altar do holocausto','Cordeiro'],['Bacia','Lavagem dos sacerdotes'],['Altar de incenso','Perfume'],['Propiciatório','Querubins'],['Véu','Lugar santíssimo'],['Sumo sacerdote','Dia da Expiação'],['Tabernáculo','Moisés'],['Bezalel','Artífice'],['Efode','Pedras do peitoral']]},
 {t:'Criação e Éden',emoji:'🌍',pairs:[['Dia 1','Luz'],['Dia 2','Firmamento'],['Dia 3','Terra seca e plantas'],['Dia 4','Sol e lua'],['Dia 5','Peixes e aves'],['Dia 6','Homem'],['Dia 7','Descanso'],['Adão','Pó da terra'],['Eva','Costela'],['Serpente','Astuta'],['Querubim','Espada flamejante'],['Abel','Pastor de ovelhas'],['Caim','Lavrador']]},
 {t:'Lugares de Jesus',emoji:'🗺️',pairs:[['Nazaré','Cresceu'],['Belém','Nasceu'],['Cafarnaum','Sede do ministério'],['Jericó','Zaqueu'],['Sicar','Poço de Jacó'],['Naim','Filho da viúva'],['Emaús','Dois discípulos'],['Betânia','Marta e Maria'],['Jerusalém','Crucificado'],['Cesareia de Filipe','Confissão de Pedro'],['Jordão','Batismo'],['Caná','Primeiro milagre']]}
];
(window.IASDBank=window.IASDBank||{}).verses=[
 ['Gênesis 1:1','No princípio criou Deus os ___ e a terra.','céus',['mares','montes','campos']],
 ['Gênesis 1:27','E criou Deus o homem à sua ___: à imagem de Deus o criou; homem e mulher os criou.','imagem',['glória','sabedoria','presença']],
 ['Gênesis 1:31','E viu Deus tudo quanto tinha feito, e eis que era muito bom; e foi a tarde e a manhã, o dia ___.','sexto',['quinto','quarto','terceiro']],
 ['Gênesis 12:2','E far-te-ei uma grande ___, e abençoar-te-ei, e engrandecerei o teu nome; e tu serás uma bênção.','nação',['cidade','herança','riqueza']],
 ['Gênesis 22:14','E chamou Abraão o nome daquele lugar Jeová-Jiré, como se diz até ao dia de hoje: No monte do SENHOR se ___.','proverá',['verá','ouvirá','reinará']],
 ['Êxodo 14:14','O SENHOR ___ por vós, e vós vos calareis.','pelejará',['caminhará','falará','reinará']],
 ['Êxodo 20:2','Eu sou o SENHOR teu Deus, que te tirei da terra do Egito, da casa da ___.','servidão',['tristeza','pobreza','tribulação']],
 ['Êxodo 20:3','Não terás outros ___ diante de mim.','deuses',['reis','profetas','anjos']],
 ['Êxodo 20:7','Não tomarás o nome do SENHOR teu Deus em vão; porque o SENHOR não terá por ___ o que tomar o seu nome em vão.','inocente',['culpado','fiel','sábio']],
 ['Êxodo 20:8','Lembra-te do dia do ___, para o santificar.','sábado',['domingo','jejum','festa']],
 ['Êxodo 20:10','Mas o ___ dia é o sábado do SENHOR teu Deus; não farás nenhuma obra.','sétimo',['primeiro','terceiro','quarto']],
 ['Êxodo 20:12','___ a teu pai e a tua mãe, para que se prolonguem os teus dias na terra que o SENHOR teu Deus te dá.','Honra',['Ama','Serve','Teme']],
 ['Êxodo 20:16','Não dirás falso ___ contra o teu próximo.','testemunho',['juramento','conselho','louvor']],
 ['Êxodo 20:17','Não ___ a casa do teu próximo.','cobiçarás',['habitarás','visitarás','venderás']],
 ['Números 23:19','Deus não é homem, para que ___; nem filho de homem, para que se arrependa.','minta',['erre','morra','durma']],
 ['Deuteronômio 6:5','Amarás, pois, ao SENHOR teu Deus de todo o teu coração, e de toda a tua alma, e de todas as tuas ___.','forças',['riquezas','palavras','obras']],
 ['Deuteronômio 31:6','___, e tende bom ânimo; não temais, nem tenhais medo deles; porque o SENHOR vosso Deus é o que vai convosco.','Esforçai-vos',['Alegrai-vos','Levantai-vos','Confiai']],
 ['Josué 1:9','Não to mandei eu? Esforça-te, e tem bom ânimo; não pasmes, nem te ___, porque o SENHOR teu Deus é contigo, por onde quer que andares.','espantes',['cansas','esqueças','voltes']],
 ['Josué 24:15','Mas, eu e a minha casa ___ ao SENHOR.','serviremos',['louvaremos','seguiremos','esconderemos']],
 ['1 Samuel 15:22','Eis que o ___ é melhor do que o sacrificar, e o atender melhor do que a gordura dos carneiros.','obedecer',['ofertar','jejuar','orar']],
 ['1 Samuel 16:7','Porque o SENHOR não vê como o homem vê, pois o homem vê o que está diante dos olhos, porém o SENHOR olha para o ___.','coração',['espírito','rosto','futuro']],
 ['2 Reis 6:16','E ele disse: Não ___, porque mais são os que estão conosco do que os que estão com eles.','temas',['foges','cales','voltes']],
 ['2 Crônicas 7:14','Se o meu povo, que se chama pelo meu nome, se ___, e orar, e buscar a minha face, e se converter dos seus maus caminhos, então eu ouvirei dos céus.','humilhar',['levantar','alegrar','calar']],
 ['Neemias 8:10','Porque a alegria do SENHOR é a vossa ___.','força',['glória','paz','riqueza']],
 ['Jó 19:25','Porque eu sei que o meu ___ vive, e por fim se levantará sobre a terra.','Redentor',['Juiz','Pastor','Amigo']],
 ['Jó 23:10','Mas ele sabe o meu caminho; prová-me-á, e sairei como o ___.','ouro',['prata','bronze','ferro']],
 ['Salmos 1:2','Antes tem o seu prazer na lei do SENHOR, e na sua lei ___ de dia e de noite.','medita',['descansa','dorme','fala']],
 ['Salmos 1:3','Pois será como a árvore plantada junto a ___ de águas, que dá o seu fruto na estação própria.','ribeiros',['montes','desertos','poços']],
 ['Salmos 14:1','Disse o ___ no seu coração: Não há Deus.','insensato',['sábio','justo','rico']],
 ['Salmos 19:1','Os céus declaram a glória de Deus e o ___ anuncia a obra das suas mãos.','firmamento',['horizonte','oceano','sol']],
 ['Salmos 19:14','Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, SENHOR, ___ minha e Redentor meu!','Rocha',['Pastor','Escudo','Refúgio']],
 ['Salmos 23:1','O SENHOR é o meu ___, nada me faltará.','pastor',['rei','escudo','juiz']],
 ['Salmos 23:2','Deitar-me faz em verdes ___, guia-me mansamente a águas tranquilas.','pastos',['montes','jardins','desertos']],
 ['Salmos 23:3','Refrigera a minha alma; guia-me pelas veredas da ___, por amor do seu nome.','justiça',['paz','verdade','bondade']],
 ['Salmos 23:4','Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo; a tua vara e o teu ___ me consolam.','cajado',['escudo','manto','cetro']],
 ['Salmos 23:5','Preparas uma mesa perante mim na presença dos meus inimigos; unges a minha cabeça com óleo, o meu ___ transborda.','cálice',['prato','cesto','odre']],
 ['Salmos 23:6','Certamente que a bondade e a ___ me seguirão todos os dias da minha vida.','misericórdia',['justiça','sabedoria','fortaleza']],
 ['Salmos 24:1','Do SENHOR é a terra e a sua plenitude, o mundo e aqueles que nele ___.','habitam',['caminham','dormem','reinam']],
 ['Salmos 27:1','O SENHOR é a minha luz e a minha ___; a quem temerei?','salvação',['esperança','alegria','coroa']],
 ['Salmos 27:14','Espera no SENHOR, anima-te, e ele ___ o teu coração; espera, pois, no SENHOR.','fortalecerá',['consolará','guardará','curará']],
 ['Salmos 32:8','Instruir-te-ei, e ensinar-te-ei o caminho que deves seguir; guiar-te-ei com os meus ___.','olhos',['mãos','passos','lábios']],
 ['Salmos 34:8','___, e vede que o SENHOR é bom; bem-aventurado o homem que nele confia.','Provai',['Crede','Buscai','Louvai']],
 ['Salmos 34:18','Perto está o SENHOR dos que têm o coração ___, e salva os contritos de espírito.','quebrantado',['endurecido','alegre','orgulhoso']],
 ['Salmos 37:4','Deleita-te também no SENHOR, e ele te concederá os ___ do teu coração.','desejos',['tesouros','caminhos','planos']],
 ['Salmos 37:5','___ o teu caminho ao SENHOR; confia nele, e ele o fará.','Entrega',['Consagra','Planeja','Mostra']],
 ['Salmos 46:1','Deus é o nosso ___ e fortaleza, socorro bem presente na angústia.','refúgio',['escudo','pastor','juiz']],
 ['Salmos 46:10','___, e sabei que eu sou Deus; serei exaltado entre as nações, serei exaltado sobre a terra.','Aquietai-vos',['Levantai-vos','Esperai','Orai']],
 ['Salmos 51:10','Cria em mim, ó Deus, um coração ___, e renova em mim um espírito reto.','puro',['fiel','forte','manso']],
 ['Salmos 55:22','Lança o teu ___ sobre o SENHOR, e ele te susterá; nunca permitirá que o justo seja abalado.','cuidado',['peso','pecado','temor']],
 ['Salmos 84:10','Porque vale mais um dia nos teus ___ do que em outra parte mil.','átrios',['campos','montes','palácios']],
 ['Salmos 90:12','Ensina-nos a ___ os nossos dias, de tal maneira que alcancemos corações sábios.','contar',['guardar','desprezar','esquecer']],
 ['Salmos 91:1','Aquele que habita no ___ do Altíssimo e descansa à sombra do Onipotente.','esconderijo',['palácio','deserto','vale']],
 ['Salmos 91:11','Porque aos seus ___ dará ordem a teu respeito, para te guardarem em todos os teus caminhos.','anjos',['servos','profetas','filhos']],
 ['Salmos 95:6','Vinde, adoremos e prostremo-nos; ___ diante do SENHOR que nos criou.','ajoelhemos',['cantemos','levantemos','caminhemos']],
 ['Salmos 100:4','Entrai pelas suas ___ com louvor, e em seus átrios com hinos de louvor; louvai-o, bendizei o seu nome.','portas',['muros','tendas','torres']],
 ['Salmos 103:1','Bendize, ó minha alma, ao SENHOR, e tudo o que há em mim ___ o seu santo nome.','bendiga',['tema','siga','sirva']],
 ['Salmos 103:12','Quanto dista o ___ do ocidente, tanto afastou de nós as nossas transgressões.','oriente',['norte','mar','céu']],
 ['Salmos 107:1','Louvai ao SENHOR, porque ele é bom; porque a sua ___ dura para sempre.','benignidade',['justiça','glória','verdade']],
 ['Salmos 118:24','Este é o dia que fez o SENHOR; ___ e alegremo-nos nele.','regozijemo-nos',['descansemos','caminhemos','choremos']],
 ['Salmos 119:11','Escondi a tua palavra no meu coração, para não ___ contra ti.','pecar',['cair','temer','fugir']],
 ['Salmos 119:105','___ para os meus pés é tua palavra, e luz para o meu caminho.','Lâmpada',['Espada','Estrela','Escudo']],
 ['Salmos 121:2','O meu ___ vem do SENHOR que fez o céu e a terra.','socorro',['descanso','poder','conforto']],
 ['Salmos 122:1','___ quando me disseram: Vamos à casa do SENHOR.','Alegrei-me',['Entristeci-me','Levantei-me','Escondi-me']],
 ['Salmos 127:1','Se o SENHOR não guardar a cidade, em vão vigia a ___.','sentinela',['profeta','pastor','rei']],
 ['Salmos 133:1','Oh! quão bom e quão suave é que os irmãos vivam em ___!','união',['distância','riqueza','guerra']],
 ['Salmos 139:23','Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece os meus ___.','pensamentos',['sonhos','temores','inimigos']],
 ['Salmos 150:6','Tudo quanto tem ___ louve ao SENHOR. Louvai ao SENHOR.','fôlego',['voz','asas','corpo']],
 ['Provérbios 1:7','O ___ do SENHOR é o princípio do conhecimento; os loucos desprezam a sabedoria e a instrução.','temor',['amor','serviço','louvor']],
 ['Provérbios 3:5','Confia no SENHOR de todo o teu coração, e não te estribes no teu próprio ___.','entendimento',['esforço','poder','desejo']],
 ['Provérbios 3:6','Reconhece-o em todos os teus caminhos, e ele ___ as tuas veredas.','endireitará',['iluminará','esconderá','apagará']],
 ['Provérbios 3:9','Honra ao SENHOR com os teus bens, e com a ___ de toda a tua renda.','primícia',['metade','sobra','riqueza']],
 ['Provérbios 4:23','Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as ___ da vida.','saídas',['frutos','águas','sombras']],
 ['Provérbios 9:10','O temor do SENHOR é o princípio da ___, e o conhecimento do Santo a prudência.','sabedoria',['justiça','bondade','vida']],
 ['Provérbios 10:12','O ódio excita ___, mas o amor cobre todas as transgressões.','contendas',['amizades','riquezas','bênçãos']],
 ['Provérbios 13:20','Aquele que anda com os sábios será sábio, mas o ___ dos insensatos será destruído.','companheiro',['inimigo','mestre','servo']],
 ['Provérbios 15:1','A resposta ___ desvia o furor, mas a palavra dura suscita a ira.','branda',['rápida','longa','forte']],
 ['Provérbios 15:13','O coração ___ aformoseia o rosto, mas com a tristeza do coração o espírito se abate.','alegre',['justo','puro','fiel']],
 ['Provérbios 16:3','Confia ao SENHOR as tuas ___, e teus pensamentos serão estabelecidos.','obras',['dores','dias','filhos']],
 ['Provérbios 16:18','Antes da ruína vai a ___, e antes da queda a altivez do espírito.','soberba',['ira','riqueza','avareza']],
 ['Provérbios 17:17','Em todo o tempo ama o amigo, e na ___ nasce o irmão.','angústia',['guerra','pobreza','fome']],
 ['Provérbios 17:22','O coração alegre serve de bom ___, mas o espírito abatido seca os ossos.','remédio',['alimento','conselho','tesouro']],
 ['Provérbios 18:10','___ forte é o nome do SENHOR; para ela correrá o justo, e estará em alto refúgio.','Torre',['Escudo','Cidade','Espada']],
 ['Provérbios 18:21','A morte e a vida estão no poder da ___; e aqueles que a amam comerão do seu fruto.','língua',['mão','espada','coroa']],
 ['Provérbios 19:21','Muitos propósitos há no coração do homem, mas o conselho do SENHOR ___.','permanecerá',['desaparecerá','vacilará','cairá']],
 ['Provérbios 22:6','Instrui o menino no ___ em que deve andar, e, até quando envelhecer, não se desviará dele.','caminho',['mundo','templo','sonho']],
 ['Provérbios 27:17','Como o ferro com o ferro se ___, assim o homem aguça o rosto do seu amigo.','aguça',['quebra','enferruja','dobra']],
 ['Provérbios 28:13','O que encobre as suas transgressões nunca prosperará; mas o que as ___ e deixa alcançará misericórdia.','confessa',['esquece','teme','ignora']],
 ['Provérbios 31:30','Enganosa é a graça, e vã a ___, mas a mulher que teme ao SENHOR, essa será louvada.','formosura',['riqueza','juventude','sabedoria']],
 ['Eclesiastes 3:1','Tudo tem o seu tempo determinado, e há tempo para todo o ___ debaixo do céu.','propósito',['pecado','descanso','jejum']],
 ['Eclesiastes 12:1','Lembra-te também do teu ___ nos dias da tua mocidade, antes que venham os maus dias.','Criador',['Pastor','Redentor','Rei']],
 ['Isaías 1:18','Ainda que os vossos pecados sejam como a ___, eles se tornarão brancos como a neve.','escarlata',['lama','poeira','noite']],
 ['Isaías 6:8','Depois disto ouvi a voz do Senhor, que dizia: A quem ___, e quem há de ir por nós? Então disse eu: Eis-me aqui, envia-me a mim.','enviarei',['chamarei','levarei','ouvirei']],
 ['Isaías 7:14','Eis que a ___ conceberá, e dará à luz um filho, e chamará o seu nome Emanuel.','virgem',['rainha','serva','esposa']],
 ['Isaías 9:6','E o seu nome será Maravilhoso Conselheiro, Deus Forte, Pai da Eternidade, ___ da Paz.','Príncipe',['Senhor','Juiz','Guardião']],
 ['Isaías 26:3','Tu conservarás em perfeita ___ aquele cuja mente está firme em ti; porque ele confia em ti.','paz',['luz','força','alegria']],
 ['Isaías 40:8','Seca-se a erva, e caem as flores, mas a ___ de nosso Deus subsiste eternamente.','palavra',['casa','glória','terra']],
 ['Isaías 40:31','Subirão com asas como ___; correrão, e não se cansarão; caminharão, e não se fatigarão.','águias',['pombas','corças','anjos']],
 ['Isaías 41:10','Não temas, porque eu sou contigo; eu te fortaleço, e te ajudo, e te sustento com a ___ da minha justiça.','destra',['sombra','paz','glória']],
 ['Isaías 43:1','Não temas, porque eu te remi; chamei-te pelo teu ___, tu és meu.','nome',['rosto','povo','sangue']],
 ['Isaías 53:5','O castigo que nos traz a paz estava sobre ele, e pelas suas ___ fomos sarados.','pisaduras',['lágrimas','palavras','orações']],
 ['Isaías 53:6','Todos nós andamos desgarrados como ___; cada um se desviou pelo seu caminho.','ovelhas',['cabras','pastores','aves']],
 ['Isaías 55:6','___ ao SENHOR enquanto se pode achar, invocai-o enquanto está perto.','Buscai',['Louvai','Temei','Servi']],
 ['Jeremias 1:5','Antes que eu te formasse no ventre, te conheci, e, antes que saísses da madre, te ___; às nações te dei por profeta.','santifiquei',['ungi','chamei','guardei']],
 ['Jeremias 17:7','Bendito o homem que confia no SENHOR, e cuja ___ é o SENHOR.','esperança',['força','pressa','riqueza']],
 ['Jeremias 29:11','Porque eu bem sei os pensamentos que tenho a vosso respeito, diz o SENHOR; pensamentos de ___, e não de mal.','paz',['guerra','glória','riqueza']],
 ['Jeremias 29:13','E buscar-me-eis, e me ___, quando me procurardes de todo o vosso coração.','achareis',['vereis','temereis','ouvireis']],
 ['Jeremias 31:3','Porquanto com amor eterno te amei, também com benignidade te ___.','atraí',['afastei','esqueci','temi']],
 ['Jeremias 32:27','Eis que eu sou o SENHOR, Deus de toda a carne; acaso haveria coisa alguma demasiado ___ para mim?','difícil',['pequena','oculta','distante']],
 ['Lamentações 3:23','Novas são cada ___; grande é a tua fidelidade.','manhã',['noite','semana','tarde']],
 ['Ezequiel 36:26','E tirarei da vossa carne o coração de ___, e vos darei um coração de carne.','pedra',['ferro','bronze','madeira']],
 ['Miqueias 6:8','E que é o que o SENHOR pede de ti, senão que pratiques a justiça, e ames a benignidade, e andes ___ com o teu Deus?','humildemente',['fielmente','alegremente','sempre']],
 ['Malaquias 3:10','Trazei todos os ___ à casa do tesouro, para que haja mantimento na minha casa.','dízimos',['cordeiros','frutos','presentes']],
 ['Mateus 1:21','E ela dará à luz um filho, e chamarás o seu nome JESUS; porque ele ___ o seu povo dos seus pecados.','salvará',['guiará','julgará','governará']],
 ['Mateus 4:4','Nem só de ___ viverá o homem, mas de toda a palavra que sai da boca de Deus.','pão',['água','riqueza','carne']],
 ['Mateus 4:19','Vinde após mim, e eu vos farei ___ de homens.','pescadores',['servos','pastores','mestres']],
 ['Mateus 5:3','Bem-aventurados os ___ de espírito, porque deles é o reino dos céus.','pobres',['fracos','sábios','simples']],
 ['Mateus 5:4','Bem-aventurados os que choram, porque eles serão ___.','consolados',['curados','recompensados','ouvidos']],
 ['Mateus 5:5','Bem-aventurados os ___, porque eles herdarão a terra.','mansos',['fortes','ricos','sábios']],
 ['Mateus 5:6','Bem-aventurados os que têm fome e sede de ___, porque eles serão fartos.','justiça',['riqueza','poder','glória']],
 ['Mateus 5:7','Bem-aventurados os ___, porque eles alcançarão misericórdia.','misericordiosos',['sábios','fortes','ricos']],
 ['Mateus 5:8','Bem-aventurados os ___ de coração, porque eles verão a Deus.','limpos',['fiéis','sábios','simples']],
 ['Mateus 5:9','Bem-aventurados os ___, porque eles serão chamados filhos de Deus.','pacificadores',['justos','mansos','fiéis']],
 ['Mateus 5:13','Vós sois o sal da terra; e se o sal for ___, com que se há de salgar?','insípido',['escasso','doce','puro']],
 ['Mateus 5:14','Vós sois a luz do mundo; não se pode esconder uma ___ edificada sobre um monte.','cidade',['casa','tenda','torre']],
 ['Mateus 5:16','Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas ___ e glorifiquem a vosso Pai, que está nos céus.','obras',['palavras','ofertas','orações']],
 ['Mateus 5:44','Amai a vossos ___, bendizei os que vos maldizem, fazei bem aos que vos odeiam.','inimigos',['vizinhos','irmãos','pais']],
 ['Mateus 6:9','Pai nosso, que estás nos céus, ___ seja o teu nome.','santificado',['louvado','exaltado','temido']],
 ['Mateus 6:11','O ___ nosso de cada dia nos dá hoje.','pão',['vinho','leite','mel']],
 ['Mateus 6:12','E perdoa-nos as nossas dívidas, assim como nós perdoamos aos nossos ___.','devedores',['inimigos','irmãos','vizinhos']],
 ['Mateus 6:19','Não ajunteis tesouros na terra, onde a ___ e a ferrugem tudo consomem.','traça',['chuva','poeira','geada']],
 ['Mateus 6:21','Porque onde estiver o vosso ___, aí estará também o vosso coração.','tesouro',['trabalho','descanso','medo']],
 ['Mateus 6:24','Ninguém pode servir a dois senhores. Não podeis servir a Deus e a ___.','Mamom',['Baal','César','Herodes']],
 ['Mateus 6:33','Mas, buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão ___.','acrescentadas',['negadas','guardadas','tiradas']],
 ['Mateus 6:34','Não vos ___, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo.','inquieteis',['esqueçais','orgulheis','canseis']],
 ['Mateus 7:1','Não ___, para que não sejais julgados.','julgueis',['mintais','murmureis','esqueçais']],
 ['Mateus 7:7','Pedi, e dar-se-vos-á; buscai, e encontrareis; ___, e abrir-se-vos-á.','bati',['orai','esperai','andai']],
 ['Mateus 7:12','Portanto, tudo o que vós quereis que os homens vos façam, fazei-lho também vós, porque esta é a lei e os ___.','profetas',['sacerdotes','juízes','anjos']],
 ['Mateus 7:13','Entrai pela porta ___; porque larga é a porta, e espaçoso o caminho que conduz à perdição.','estreita',['pequena','baixa','escura']],
 ['Mateus 7:24','Todo aquele que escuta estas minhas palavras, e as pratica, assemelhá-lo-ei ao homem prudente, que edificou a sua casa sobre a ___.','rocha',['areia','colina','terra']],
 ['Mateus 11:28','Vinde a mim, todos os que estais cansados e oprimidos, e eu vos ___.','aliviarei',['sustentarei','guardarei','curarei']],
 ['Mateus 11:29','Tomai sobre vós o meu jugo, e aprendei de mim, que sou ___ e humilde de coração.','manso',['forte','sábio','justo']],
 ['Mateus 16:26','Pois que aproveitaria ao homem ganhar o mundo inteiro e perder a sua ___?','alma',['saúde','honra','família']],
 ['Mateus 18:20','Porque onde estiverem dois ou três ___ em meu nome, ali estou no meio deles.','reunidos',['sentados','perdidos','presos']],
 ['Mateus 22:37','Amarás o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todo o teu ___.','pensamento',['dinheiro','sonho','descanso']],
 ['Mateus 22:39','E o segundo, semelhante a este, é: Amarás o teu ___ como a ti mesmo.','próximo',['inimigo','rei','estrangeiro']],
 ['Mateus 25:21','Muito bem, servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei; entra no ___ do teu senhor.','gozo',['templo','tesouro','palácio']],
 ['Mateus 25:40','Em verdade vos digo que quando o fizestes a um destes meus ___ irmãos, a mim o fizestes.','pequeninos',['pobres','humildes','fiéis']],
 ['Mateus 28:19','Portanto ide, ensinai todas as ___, batizando-as em nome do Pai, e do Filho, e do Espírito Santo.','nações',['cidades','famílias','aldeias']],
 ['Marcos 2:17','Os sãos não necessitam de ___, mas, sim, os que estão doentes.','médico',['mestre','pastor','juiz']],
 ['Marcos 9:23','Jesus disse-lhe: Se tu podes crer, tudo é ___ ao que crê.','possível',['fácil','permitido','certo']],
 ['Marcos 10:45','Porque o Filho do homem também não veio para ser servido, mas para servir, e dar a sua vida em ___ de muitos.','resgate',['favor','memória','honra']],
 ['Marcos 16:15','E disse-lhes: Ide por todo o mundo, pregai o evangelho a toda ___.','criatura',['nação','cidade','casa']],
 ['Lucas 1:37','Porque para Deus nada é ___.','impossível',['proibido','oculto','distante']],
 ['Lucas 2:10','Não temais, porque eis aqui vos trago novas de grande ___, que será para todo o povo.','alegria',['paz','glória','esperança']],
 ['Lucas 2:11','Pois que hoje vos nasceu, na cidade de Davi, o ___, que é Cristo, o Senhor.','Salvador',['Rei','Pastor','Mestre']],
 ['Lucas 2:14','Glória a Deus nas ___, paz na terra, boa vontade para com os homens.','alturas',['montes','mares','templos']],
 ['Lucas 2:52','E crescia Jesus em sabedoria, em ___, e em graça para com Deus e os homens.','estatura',['força','riqueza','poder']],
 ['Lucas 6:38','Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando vos deitarão no vosso ___.','regaço',['cesto','celeiro','bolso']],
 ['Lucas 9:23','Se alguém quer vir após mim, renuncie-se a si mesmo, tome cada dia a sua ___, e siga-me.','cruz',['vida','carga','espada']],
 ['Lucas 15:7','Haverá maior alegria no céu por um pecador que se arrepende, do que por ___ e nove justos que não necessitam de arrependimento.','noventa',['cem','setenta','cinquenta']],
 ['Lucas 19:10','Porque o Filho do homem veio buscar e salvar o que se tinha ___.','perdido',['ferido','fraco','pobre']],
 ['Lucas 23:34','E dizia Jesus: Pai, ___, porque não sabem o que fazem.','perdoa-lhes',['abençoa-os','guarda-os','ouve-os']],
 ['Lucas 24:6','Não está aqui, mas ___; lembrai-vos de como vos falou, estando ainda na Galiléia.','ressuscitou',['partiu','subiu','dormiu']],
 ['João 1:1','No ___ era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.','princípio',['fim','meio','tempo']],
 ['João 1:12','Mas, a todos quantos o receberam, deu-lhes o ___ de serem feitos filhos de Deus.','poder',['desejo','dever','sinal']],
 ['João 1:14','E o Verbo se fez ___, e habitou entre nós, cheio de graça e de verdade.','carne',['pó','luz','pão']],
 ['João 1:29','Eis o ___ de Deus, que tira o pecado do mundo.','Cordeiro',['Leão','Pastor','Escudo']],
 ['João 3:3','Em verdade, em verdade te digo que aquele que não ___ de novo, não pode ver o reino de Deus.','nascer',['crer','morrer','orar']],
 ['João 3:16','Porque Deus amou o mundo de tal maneira que deu o seu Filho ___, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.','unigênito',['amado','primogênito','precioso']],
 ['João 3:17','Porque Deus enviou o seu Filho ao mundo, não para que condenasse o mundo, mas para que o mundo fosse ___ por ele.','salvo',['curado','liberto','perdoado']],
 ['João 4:24','Deus é ___, e importa que os que o adoram o adorem em espírito e em verdade.','Espírito',['Luz','Fogo','Rei']],
 ['João 6:35','Eu sou o pão da vida; aquele que vem a mim não terá fome; e quem crê em mim nunca terá ___.','sede',['medo','dor','cansaço']],
 ['João 8:12','Eu sou a luz do mundo; quem me segue não andará em ___, mas terá a luz da vida.','trevas',['medo','dúvida','perigo']],
 ['João 8:32','E ___ a verdade, e a verdade vos libertará.','conhecereis',['ouvireis','guardareis','esquecereis']],
 ['João 10:10','Eu vim para que tenham vida, e a tenham em ___.','abundância',['saúde','glória','liberdade']],
 ['João 10:11','Eu sou o bom Pastor; o bom Pastor dá a sua vida pelas ___.','ovelhas',['amigos','filhos','servos']],
 ['João 10:27','As minhas ovelhas ouvem a minha ___, e eu conheço-as, e elas me seguem.','voz',['mão','casa','luz']],
 ['João 11:25','Disse-lhe Jesus: Eu sou a ___ e a vida; quem crê em mim, ainda que esteja morto, viverá.','ressurreição',['salvação','esperança','verdade']],
 ['João 13:34','Um novo ___ vos dou: Que vos ameis uns aos outros; como eu vos amei a vós.','mandamento',['caminho','pacto','ensino']],
 ['João 14:1','Não se ___ o vosso coração; credes em Deus, crede também em mim.','turbe',['canse','perca','endureça']],
 ['João 14:2','Na casa de meu Pai há muitas ___; se não fosse assim, eu vo-lo teria dito.','moradas',['portas','salas','tendas']],
 ['João 14:6','Disse-lhe Jesus: Eu sou o ___, e a verdade, e a vida; ninguém vem ao Pai, senão por mim.','caminho',['pastor','porta','mestre']],
 ['João 14:15','Se me amais, ___ os meus mandamentos.','guardai',['ouvi','pregai','temei']],
 ['João 14:27','Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se ___.','atemorize',['canse','entristeça','perca']],
 ['João 15:5','Eu sou a ___, vós as varas; quem está em mim, e eu nele, esse dá muito fruto.','videira',['oliveira','figueira','palmeira']],
 ['João 15:13','Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus ___.','amigos',['irmãos','filhos','inimigos']],
 ['João 16:33','No mundo tereis ___, mas tende bom ânimo, eu venci o mundo.','aflições',['riquezas','descanso','bênçãos']],
 ['João 20:31','Mas estas coisas foram ___ para que creiais que Jesus é o Cristo, o Filho de Deus.','escritas',['ditas','feitas','guardadas']],
 ['Atos 1:8','Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis ___ tanto em Jerusalém como em toda a Judéia e Samaria.','testemunhas',['discípulos','mensageiros','servos']],
 ['Atos 2:38','E disse-lhes Pedro: ___, e cada um de vós seja batizado em nome de Jesus Cristo, para perdão dos pecados.','Arrependei-vos',['Jejuai','Orai','Regozijai-vos']],
 ['Atos 4:12','E em nenhum outro há ___, porque também debaixo do céu nenhum outro nome há, dado entre os homens, pelo qual devamos ser salvos.','salvação',['esperança','perdão','vida']],
 ['Atos 16:31','E eles disseram: Crê no Senhor Jesus Cristo e serás salvo, tu e a tua ___.','casa',['nação','cidade','igreja']],
 ['Atos 20:35','Mais bem-aventurada coisa é dar do que ___.','receber',['guardar','pedir','juntar']],
 ['Romanos 1:16','Porque não me ___ do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê.','envergonho',['esqueço','canso','afasto']],
 ['Romanos 3:23','Porque todos pecaram e destituídos estão da ___ de Deus.','glória',['lei','paz','bondade']],
 ['Romanos 5:8','Mas Deus ___ o seu amor para conosco, em que Cristo morreu por nós, sendo nós ainda pecadores.','prova',['nega','esconde','mede']],
 ['Romanos 6:23','Porque o ___ do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus nosso Senhor.','salário',['fruto','castigo','fim']],
 ['Romanos 8:1','Portanto, agora, nenhuma ___ há para os que estão em Cristo Jesus.','condenação',['tristeza','dúvida','lei']],
 ['Romanos 8:28','E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu ___.','propósito',['mandamento','caminho','nome']],
 ['Romanos 8:31','Que ___, pois, a estas coisas? Se Deus é por nós, quem será contra nós?','diremos',['faremos','pediremos','esperaremos']],
 ['Romanos 10:9','Se com a tua boca ___ ao Senhor Jesus, e em teu coração creres que Deus o ressuscitou dos mortos, serás salvo.','confessares',['louvares','pregares','negares']],
 ['Romanos 10:17','De sorte que a fé é pelo ___, e o ouvir pela palavra de Deus.','ouvir',['ver','ler','pedir']],
 ['Romanos 12:1','Que apresenteis o vosso corpo em ___ vivo, santo e agradável a Deus, que é o vosso culto racional.','sacrifício',['templo','cântico','altar']],
 ['Romanos 12:2','E não sereis conformados com este mundo, mas sede transformados pela ___ do vosso entendimento.','renovação',['sabedoria','força','ciência']],
 ['Romanos 12:21','Não te deixes vencer do mal, mas ___ o mal com o bem.','vence',['foge','teme','esquece']],
 ['Romanos 13:10','O amor não faz mal ao ___; de sorte que o cumprimento da lei é o amor.','próximo',['irmão','inimigo','amigo']],
 ['Romanos 15:13','Ora o Deus de esperança vos ___ de todo o gozo e paz no vosso crer.','encha',['guarde','cubra','guie']],
 ['1 Coríntios 13:4','O amor é ___, é benigno; o amor não é invejoso; o amor não trata com leviandade, não se ensoberbece.','sofredor',['orgulhoso','ansioso','rico']],
 ['1 Coríntios 13:7','Tudo sofre, tudo crê, tudo ___, tudo suporta.','espera',['teme','ignora','vence']],
 ['1 Coríntios 13:13','Agora, pois, permanecem a fé, a esperança e o amor, estes três, mas o ___ destes é o amor.','maior',['menor','primeiro','único']],
 ['1 Coríntios 15:55','Onde está, ó morte, o teu ___? Onde está, ó inferno, a tua vitória?','aguilhão',['poder','espada','domínio']],
 ['1 Coríntios 15:57','Mas graças a Deus, que nos dá a ___ por nosso Senhor Jesus Cristo.','vitória',['paz','esperança','força']],
 ['1 Coríntios 15:58','Estai firmes e ___, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.','constantes',['calados','quietos','unidos']],
 ['1 Coríntios 16:13','___, estai firmes na fé, portai-vos varonilmente, e fortalecei-vos.','Vigiai',['Dormi','Andai','Cantai']],
 ['2 Coríntios 5:7','Porque andamos por fé, e não por ___.','vista',['razão','ciência','sinais']],
 ['2 Coríntios 5:17','Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já ___; eis que tudo se fez novo.','passaram',['cresceram','voltaram','ficaram']],
 ['2 Coríntios 9:7','Cada um contribua segundo propôs no seu coração, não com tristeza, nem por necessidade; porque Deus ama ao que dá com ___.','alegria',['pressa','medida','fartura']],
 ['2 Coríntios 12:9','E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na ___.','fraqueza',['pobreza','riqueza','dor']],
 ['Gálatas 2:20','Já estou ___ com Cristo; e vivo, não mais eu, mas Cristo vive em mim.','crucificado',['sepultado','batizado','ungido']],
 ['Gálatas 5:1','Estai, pois, firmes na ___ com que Cristo nos libertou, e não torneis a colocar-vos debaixo do jugo de escravidão.','liberdade',['riqueza','ciência','alegria']],
 ['Gálatas 5:22','Mas o fruto do Espírito é: amor, gozo, paz, ___, benignidade, bondade, fé.','longanimidade',['sabedoria','justiça','esperança']],
 ['Gálatas 5:23','Mansidão, ___; contra estas coisas não há lei.','temperança',['sabedoria','coragem','ciência']],
 ['Gálatas 6:7','Não erreis: Deus não se deixa escarnecer; pois tudo o que o homem semear, isso também ___.','ceifará',['perderá','guardará','pagará']],
 ['Gálatas 6:9','E não nos ___ de fazer bem, porque a seu tempo ceifaremos, se não houvermos desfalecido.','cansemos',['alegremos','esqueçamos','gloriemos']],
 ['Efésios 2:8','Porque pela ___ sois salvos, por meio da fé; e isto não vem de vós; é dom de Deus.','graça',['lei','obra','esperança']],
 ['Efésios 2:10','Porque somos ___ sua, criados em Cristo Jesus para as boas obras.','feitura',['herança','imagem','casa']],
 ['Efésios 4:32','Antes sede uns para com os outros ___, misericordiosos, perdoando-vos uns aos outros, como também Deus, em Cristo, vos perdoou.','benignos',['severos','firmes','ricos']],
 ['Efésios 6:10','Finalmente, meus irmãos, ___ no Senhor e na força do seu poder.','fortalecei-vos',['alegrai-vos','escondei-vos','dormi']],
 ['Efésios 6:11','Revesti-vos de toda a ___ de Deus, para que possais estar firmes contra as astúcias do diabo.','armadura',['espada','força','sabedoria']],
 ['Efésios 6:14','Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a ___ da justiça.','couraça',['coroa','capa','túnica']],
 ['Efésios 6:16','Tomando sobretudo o ___ da fé, com o qual podereis apagar todos os dardos inflamados do maligno.','escudo',['elmo','arco','manto']],
 ['Efésios 6:17','Tomai também o capacete da salvação, e a ___ do Espírito, que é a palavra de Deus.','espada',['lança','coroa','armadura']],
 ['Filipenses 1:6','Aquele que em vós começou a boa obra a ___ até ao dia de Jesus Cristo.','aperfeiçoará',['abandonará','esquecerá','ocultará']],
 ['Filipenses 2:5','De sorte que haja em vós o mesmo ___ que houve também em Cristo Jesus.','sentimento',['poder','desejo','nome']],
 ['Filipenses 2:10','Para que ao nome de Jesus se dobre todo o ___ dos que estão nos céus, e na terra, e debaixo da terra.','joelho',['monte','rei','povo']],
 ['Filipenses 4:4','Regozijai-vos ___ no Senhor; outra vez digo: Regozijai-vos.','sempre',['hoje','apenas','nunca']],
 ['Filipenses 4:6','Não estejais ___ por coisa alguma; antes as vossas petições sejam em tudo conhecidas diante de Deus.','inquietos',['cansados','calados','ricos']],
 ['Filipenses 4:7','E a paz de Deus, que excede todo o entendimento, ___ os vossos corações e os vossos sentimentos em Cristo Jesus.','guardará',['afastará','encherá','seguirá']],
 ['Filipenses 4:8','Quanto ao mais, irmãos, tudo o que é verdadeiro, tudo o que é honesto, tudo o que é justo, tudo o que é puro, nisso ___.','pensai',['falai','ouvi','cantai']],
 ['Filipenses 4:13','Posso todas as coisas em Cristo que me ___.','fortalece',['guarda','espera','teme']],
 ['Filipenses 4:19','O meu Deus, segundo as suas riquezas, ___ todas as vossas necessidades em glória, por Cristo Jesus.','suprirá',['negará','limitará','guardará']],
 ['Colossenses 3:2','___ nas coisas que são de cima, e não nas que são da terra.','Pensai',['Falai','Ouvi','Cuidai']],
 ['Colossenses 3:14','E, sobre tudo isto, revesti-vos de ___, que é o vínculo da perfeição.','caridade',['paciência','fidelidade','humildade']],
 ['Colossenses 3:23','E tudo quanto fizerdes, fazei-o de todo o ___, como ao Senhor, e não aos homens.','coração',['poder','tempo','modo']],
 ['1 Tessalonicenses 5:17','Orai sem ___.','cessar',['medo','pressa','dúvida']],
 ['1 Tessalonicenses 5:21','___ tudo. Retende o bem.','Examinai',['Aceitai','Esquecei','Negai']],
 ['1 Timóteo 2:5','Porque há um só Deus, e um só ___ entre Deus e os homens, Jesus Cristo, homem.','Mediador',['Rei','Juiz','Pastor']],
 ['1 Timóteo 4:12','Ninguém despreze a tua ___; mas sê o exemplo dos fiéis, na palavra, no trato, na caridade, no espírito, na fé e na pureza.','mocidade',['bondade','riqueza','simplicidade']],
 ['1 Timóteo 6:10','Porque o amor ao dinheiro é a ___ de toda a espécie de males.','raiz',['fruto','fim','ramo']],
 ['2 Timóteo 1:7','Porque Deus não nos deu o espírito de ___, mas de fortaleza, e de amor, e de moderação.','temor',['orgulho','tristeza','ira']],
 ['2 Timóteo 3:16','Toda a ___ divinamente inspirada é proveitosa para ensinar, para repreender, para corrigir, para instruir em justiça.','Escritura',['profecia','sabedoria','igreja']],
 ['2 Timóteo 4:7','Combati o bom combate, acabei a ___, guardei a fé.','carreira',['jornada','viagem','missão']],
 ['Hebreus 4:12','Porque a palavra de Deus é ___ e eficaz, e mais penetrante do que espada alguma de dois gumes.','viva',['santa','justa','doce']],
 ['Hebreus 4:16','Cheguemos, pois, com confiança ao ___ da graça, para que possamos alcançar misericórdia.','trono',['altar','templo','monte']],
 ['Hebreus 10:23','Retenhamos firmes a confissão da nossa esperança, porque fiel é o que ___.','prometeu',['jurou','ensinou','chamou']],
 ['Hebreus 11:1','Ora, a fé é o firme ___ das coisas que se esperam, e a prova das coisas que se não vêem.','fundamento',['desejo','poder','sinal']],
 ['Hebreus 11:6','Ora, sem fé é impossível agradar-lhe; porque é necessário que aquele que se aproxima de Deus creia que ele existe, e que é ___ dos que o buscam.','galardoador',['protetor','juiz','amigo']],
 ['Hebreus 12:1','Portanto nós também, pois, estando rodeados de uma tão grande ___ de testemunhas, deixemos todo o embaraço.','nuvem',['sombra','muralha','coroa']],
 ['Hebreus 12:2','Olhando para Jesus, autor e ___ da fé.','consumador',['guardador','mestre','doador']],
 ['Hebreus 13:5','Não te deixarei, nem te ___.','desampararei',['ferirei','trairei','perderei']],
 ['Hebreus 13:8','Jesus Cristo é o mesmo ___, e hoje, e eternamente.','ontem',['amanhã','então','depois']],
 ['Tiago 1:5','E, se algum de vós tem falta de ___, peça-a a Deus, que a todos dá liberalmente, e o não lança em rosto.','sabedoria',['fé','paz','força']],
 ['Tiago 1:22','E sede ___ da palavra, e não somente ouvintes, enganando-vos a vós mesmos.','cumpridores',['leitores','mestres','pregadores']],
 ['Tiago 2:17','Assim também a fé, se não tiver as obras, é ___ em si mesma.','morta',['fraca','vazia','falsa']],
 ['Tiago 4:7','Sujeitai-vos, pois, a Deus; resisti ao diabo, e ele ___ de vós.','fugirá',['cairá','dormirá','falará']],
 ['Tiago 4:8','___ a Deus, e ele se chegará a vós.','Chegai-vos',['Voltai-vos','Orai','Clamai']],
 ['Tiago 5:16','Confessai as vossas culpas uns aos outros, e orai uns pelos outros, para que ___.','sareis',['cresçais','vençais','vivais']],
 ['1 Pedro 5:7','Lançando sobre ele toda a vossa ___, porque ele tem cuidado de vós.','ansiedade',['esperança','dor','confiança']],
 ['1 Pedro 5:8','Sede sóbrios; vigiai; porque o diabo, vosso adversário, anda em derredor, bramando como ___, buscando a quem possa tragar.','leão',['lobo','urso','serpente']],
 ['2 Pedro 3:9','O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é ___ para convosco.','longânimo',['justo','forte','sábio']],
 ['1 João 1:9','Se ___ os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda a injustiça.','confessarmos',['negarmos','escondermos','esquecermos']],
 ['1 João 3:1','___ quão grande amor nos tem concedido o Pai, que fôssemos chamados filhos de Deus.','Vede',['Sabei','Ouvi','Crede']],
 ['1 João 4:8','Aquele que não ama não ___ a Deus, porque Deus é amor.','conhece',['serve','teme','segue']],
 ['1 João 4:19','Nós o amamos a ele porque ele nos amou ___.','primeiro',['sempre','muito','ontem']],
 ['Apocalipse 1:8','Eu sou o Alfa e o ___, o princípio e o fim, diz o Senhor.','Ômega',['Beta','Sigma','Delta']],
 ['Apocalipse 2:10','Sê ___ até à morte, e dar-te-ei a coroa da vida.','fiel',['forte','firme','sábio']],
 ['Apocalipse 3:20','Eis que estou à porta, e ___; se alguém ouvir a minha voz, e abrir a porta, entrarei em sua casa.','bato',['espero','clamo','vigio']],
 ['Apocalipse 14:7','Temei a Deus, e dai-lhe glória, porque vinda é a hora do seu ___.','juízo',['reino','poder','perdão']],
 ['Apocalipse 14:12','Aqui está a ___ dos santos, aqui estão os que guardam os mandamentos de Deus e a fé em Jesus.','paciência',['esperança','coragem','alegria']],
 ['Apocalipse 21:4','E Deus limpará de seus olhos toda a ___, e a morte já não existirá.','lágrima',['mancha','tristeza','sombra']],
 ['Apocalipse 21:5','E o que estava assentado sobre o trono disse: Eis que faço ___ todas as coisas.','novas',['belas','grandes','santas']],
 ['Apocalipse 22:12','E eis que depressa venho, e o meu ___ está comigo, para dar a cada um segundo a sua obra.','galardão',['reino','juízo','perdão']]
];
