(window.IASDBank=window.IASDBank||{}).quiz=[
 ['Antigo Testamento','O que Deus criou no primeiro dia?','A luz',['Os animais','O sol','A terra seca'],'Gênesis 1:3-5',1],
 ['Antigo Testamento','Em que dia da criação Deus fez o sol, a lua e as estrelas?','No quarto dia',['No segundo dia','No terceiro dia','No sexto dia'],'Gênesis 1:14-19',2],
 ['Antigo Testamento','Em que dia Deus criou o homem e a mulher?','No sexto dia',['No quinto dia','No sétimo dia','No quarto dia'],'Gênesis 1:26-31',1],
 ['Antigo Testamento','Quem foi o primeiro homem criado por Deus?','Adão',['Abel','Sete','Noé'],'Gênesis 2:7',1],
 ['Antigo Testamento','De que Deus formou o corpo de Adão?','Do pó da terra',['Da água do mar','De uma rocha','De uma nuvem'],'Gênesis 2:7',1],
 ['Antigo Testamento','De que Deus formou Eva?','De uma costela de Adão',['Do pó da terra','De uma nuvem','Do barro do rio'],'Gênesis 2:21-22',1],
 ['Antigo Testamento','Qual era o nome do jardim onde viviam Adão e Eva?','Éden',['Getsêmani','Canaã','Sinar'],'Gênesis 2:8',1],
 ['Antigo Testamento','Que animal enganou Eva no jardim?','A serpente',['O leão','O corvo','O lobo'],'Gênesis 3:1-5',1],
 ['Antigo Testamento','Quem matou Abel, seu irmão?','Caim',['Sete','Lameque','Enoque'],'Gênesis 4:8',1],
 ['Antigo Testamento','Que homem andou com Deus e foi trasladado sem ver a morte?','Enoque',['Noé','Matusalém','Sete'],'Gênesis 5:24',2],
 ['Antigo Testamento','Quantas pessoas entraram na arca de Noé?','Oito',['Doze','Dez','Sete'],'1 Pedro 3:20',2],
 ['Antigo Testamento','Quantos dias e noites choveu sobre a terra no dilúvio?','Quarenta',['Sete','Trinta','Cem'],'Gênesis 7:12',2],
 ['Antigo Testamento','Que ave Noé soltou que voltou com uma folha de oliveira?','A pomba',['O corvo','A águia','A andorinha'],'Gênesis 8:11',1],
 ['Antigo Testamento','Em que montes a arca repousou?','Ararate',['Sinai','Carmelo','Sião'],'Gênesis 8:4',2],
 ['Antigo Testamento','Que sinal Deus deu de que não destruiria a terra com água?','O arco-íris',['Uma estrela','Uma nuvem de fogo','Uma pomba branca'],'Gênesis 9:13-15',1],
 ['Antigo Testamento','Que torre os homens tentaram construir até o céu?','Torre de Babel',['Torre de Ur','Torre de Sodoma','Torre de Nínive'],'Gênesis 11:1-9',1],
 ['Antigo Testamento','Como se chamava o pai de Abraão?','Terá',['Naor','Ló','Harã'],'Gênesis 11:26',3],
 ['Antigo Testamento','De que cidade Terá saiu com Abrão rumo a Canaã?','Ur dos caldeus',['Babilônia','Nínive','Damasco'],'Gênesis 11:31',3],
 ['Antigo Testamento','Quem era sobrinho de Abraão e morava em Sodoma?','Ló',['Isaque','Labão','Esaú'],'Gênesis 14:12',2],
 ['Antigo Testamento','Que cidades Deus destruiu com fogo e enxofre no tempo de Ló?','Sodoma e Gomorra',['Babel e Nínive','Jericó e Ai','Tiro e Sidom'],'Gênesis 19:24',1],
 ['Antigo Testamento','O que aconteceu à mulher de Ló quando olhou para trás?','Virou estátua de sal',['Ficou cega','Foi levada ao céu','Perdeu a voz'],'Gênesis 19:26',1],
 ['Antigo Testamento','Que filho Deus pediu que Abraão oferecesse em sacrifício?','Isaque',['Ismael','Jacó','Esaú'],'Gênesis 22:2',1],
 ['Antigo Testamento','O que Deus providenciou no lugar de Isaque?','Um carneiro',['Um bode','Um touro','Uma pomba'],'Gênesis 22:13',2],
 ['Antigo Testamento','Quem era o irmão gêmeo de Jacó?','Esaú',['Labão','Ismael','Judá'],'Gênesis 25:24-26',1],
 ['Antigo Testamento','Esaú vendeu sua primogenitura por quê?','Por um prato de lentilhas',['Por um rebanho','Por um manto','Por um pão de trigo'],'Gênesis 25:29-34',2],
 ['Antigo Testamento','Com o que Jacó sonhou em Betel?','Com uma escada até o céu',['Com sete vacas gordas','Com um rio de fogo','Com uma grande árvore'],'Gênesis 28:12',1],
 ['Antigo Testamento','Que novo nome Jacó recebeu depois de lutar com o anjo?','Israel',['Judá','Efraim','Benjamim'],'Gênesis 32:28',2],
 ['Antigo Testamento','Quantos filhos teve Jacó, que originaram as tribos de Israel?','Doze',['Dez','Sete','Catorze'],'Gênesis 35:22',1],
 ['Antigo Testamento','Que filho de Jacó recebeu uma túnica de várias cores?','José',['Benjamim','Judá','Rúben'],'Gênesis 37:3',1],
 ['Antigo Testamento','Por quanto os irmãos venderam José aos ismaelitas?','Vinte peças de prata',['Trinta peças de prata','Dez peças de prata','Cem moedas de ouro'],'Gênesis 37:28',3],
 ['Antigo Testamento','Em que país José se tornou governador?','Egito',['Babilônia','Assíria','Canaã'],'Gênesis 41:41',1],
 ['Antigo Testamento','O que significava o sonho do Faraó sobre as sete vacas gordas e as sete magras?','Sete anos de fartura e fome',['Uma guerra com Canaã','A morte do Faraó','Uma grande inundação'],'Gênesis 41',2],
 ['Antigo Testamento','Que irmão de José ficou preso como refém no Egito?','Simeão',['Rúben','Levi','Judá'],'Gênesis 42:24',3],
 ['Antigo Testamento','Em que foi colocado o bebê Moisés no rio Nilo?','Numa cesta de juncos',['Numa arca de cedro','Num barco de pesca','Num cântaro de barro'],'Êxodo 2:3',1],
 ['Antigo Testamento','Como Deus falou com Moisés no monte Horebe?','De uma sarça ardente',['De uma nuvem escura','De um vento forte','De um sonho'],'Êxodo 3:2-4',1],
 ['Antigo Testamento','Em que se transformou o cajado de Moisés diante do Faraó?','Numa serpente',['Numa pomba','Numa espada','Numa pedra'],'Êxodo 7:10',2],
 ['Antigo Testamento','Quem era o irmão de Moisés que falou ao Faraó em seu lugar?','Arão',['Calebe','Hur','Josué'],'Êxodo 4:14-16',1],
 ['Antigo Testamento','Quantas pragas Deus enviou sobre o Egito?','Dez',['Sete','Doze','Cinco'],'Êxodo 7-12',1],
 ['Antigo Testamento','Qual foi a última praga enviada sobre o Egito?','A morte dos primogênitos',['As trevas','Os gafanhotos','O granizo'],'Êxodo 12:29',1],
 ['Antigo Testamento','O que os israelitas puseram nas portas na noite da Páscoa?','Sangue de cordeiro',['Azeite','Água do Nilo','Folhas de palmeira'],'Êxodo 12:7',2],
 ['Antigo Testamento','Que mar Deus abriu para o povo atravessar a pé enxuto?','Mar Vermelho',['Mar Morto','Mar da Galileia','Mar Mediterrâneo'],'Êxodo 14',1],
 ['Antigo Testamento','Que alimento caía do céu para Israel no deserto?','Maná',['Trigo','Figos','Tâmaras'],'Êxodo 16',1],
 ['Antigo Testamento','O que Israel fez enquanto Moisés estava no monte?','Um bezerro de ouro',['Uma torre','Um altar de pedra','Uma serpente de bronze'],'Êxodo 32:1-4',1],
 ['Antigo Testamento','Quantos anos Israel peregrinou no deserto?','Quarenta',['Vinte','Setenta','Doze'],'Números 14:33-34',1],
 ['Antigo Testamento','Quantos espias Moisés enviou para explorar Canaã?','Doze',['Setenta','Dez','Sete'],'Números 13',2],
 ['Antigo Testamento','Quais espias trouxeram um relatório fiel, confiando em Deus?','Josué e Calebe',['Arão e Hur','Finéias e Eleazar','Coré e Datã'],'Números 14:6-9',2],
 ['Antigo Testamento','O que Moisés levantou no deserto para curar os picados por serpentes?','Uma serpente de bronze',['Um cajado de ouro','Uma estátua de ferro','Um estandarte de prata'],'Números 21:9',2],
 ['Antigo Testamento','Que animal falou com Balaão?','A jumenta',['O camelo','O leão','O cavalo'],'Números 22:28',2],
 ['Antigo Testamento','Em que monte Moisés morreu, depois de ver a terra prometida?','Monte Nebo',['Monte Sinai','Monte Hermom','Monte Carmelo'],'Deuteronômio 34:1-5',3],
 ['Antigo Testamento','Quem sucedeu Moisés como líder de Israel?','Josué',['Calebe','Arão','Gideão'],'Josué 1:1-2',1],
 ['Antigo Testamento','Que rio Israel atravessou a pé seco para entrar em Canaã?','Rio Jordão',['Rio Nilo','Rio Eufrates','Rio Jaboque'],'Josué 3',1],
 ['Antigo Testamento','O que aconteceu com os muros de Jericó?','Caíram quando o povo gritou',['Foram escalados','Foram queimados','Foram cavados'],'Josué 6:20',1],
 ['Antigo Testamento','Quantas vezes o povo rodeou Jericó no sétimo dia?','Sete vezes',['Três vezes','Uma vez','Doze vezes'],'Josué 6:15',2],
 ['Antigo Testamento','Complete: O Senhor é o meu pastor, nada me...','faltará',['sobrará','assustará','cansará'],'Salmos 23:1',1],
 ['Antigo Testamento','Complete: Lâmpada para os meus pés é a tua palavra e luz para o meu...','caminho',['coração','lar','dia'],'Salmos 119:105',2],
 ['Antigo Testamento','Complete: O temor do Senhor é o princípio da...','sabedoria',['riqueza','vitória','paz'],'Provérbios 1:7',2],
 ['Antigo Testamento','Complete: Confia no Senhor de todo o teu coração e não te estribes no teu próprio...','entendimento',['poder','caminho','desejo'],'Provérbios 3:5',2],
 ['Novo Testamento','Qual é o primeiro livro do Novo Testamento?','Mateus',['Marcos','João','Atos'],'Mateus 1:1',1],
 ['Novo Testamento','Qual é o último livro do Novo Testamento?','Apocalipse',['Judas','Hebreus','Atos'],'Apocalipse 1:1',1],
 ['Novo Testamento','Qual evangelista era médico?','Lucas',['Marcos','Mateus','João'],'Colossenses 4:14',2],
 ['Novo Testamento','Qual evangelho foi escrito por um ex-cobrador de impostos?','Mateus',['Marcos','Lucas','João'],'Mateus 9:9',2],
 ['Novo Testamento','Qual livro narra o início da igreja após a ascensão de Jesus?','Atos dos Apóstolos',['Romanos','Gálatas','Hebreus'],'Atos 1:1-2',1],
 ['Novo Testamento','Quem escreveu a maior parte das cartas do Novo Testamento?','Paulo',['Pedro','João','Tiago'],'Romanos 1:1',1],
 ['Novo Testamento','Complete: Deus amou o mundo de tal maneira que deu o seu Filho, para que todo aquele que nele crê não...','pereça',['chore','tema','caia'],'João 3:16',2],
 ['Novo Testamento','Complete: Tudo posso naquele que me...','fortalece',['guia','ama','guarda'],'Filipenses 4:13',1],
 ['Novo Testamento','Qual é o versículo mais curto da Bíblia em português?','Jesus chorou',['Orai sem cessar','Deus é amor','Alegrai-vos sempre'],'João 11:35',2],
 ['Novo Testamento','Segundo 1 Coríntios 13, qual é o maior entre fé, esperança e amor?','O amor',['A fé','A esperança','A sabedoria'],'1 Coríntios 13:13',1],
 ['Novo Testamento','Segundo Efésios 2:8, somos salvos por...','Graça, mediante a fé',['Nossas obras','Nossos sacrifícios','Nossa sabedoria'],'Efésios 2:8',2],
 ['Novo Testamento','Que carta afirma que a fé sem obras é morta?','Tiago',['Romanos','Gálatas','Hebreus'],'Tiago 2:26',2],
 ['Novo Testamento','Que carta define a fé como a certeza das coisas que se esperam?','Hebreus',['Romanos','Tiago','1 Pedro'],'Hebreus 11:1',2],
 ['Novo Testamento','A quem Paulo escreveu a carta sobre o escravo Onésimo?','Filemom',['Tito','Timóteo','Silas'],'Filemom 1:10',3],
 ['Novo Testamento','Segundo Romanos 6:23, o salário do pecado é...','A morte',['A dor','O exílio','A pobreza'],'Romanos 6:23',1],
 ['Novo Testamento','Segundo Romanos 3:23, todos pecaram e destituídos de quê?','Da glória de Deus',['Da lei de Moisés','Da paz do mundo','Da bênção de Abraão'],'Romanos 3:23',2],
 ['Novo Testamento','Qual carta diz que não há condenação para os que estão em Cristo Jesus?','Romanos',['Gálatas','Efésios','Colossenses'],'Romanos 8:1',3],
 ['Novo Testamento','Em que carta Paulo diz repetidamente: Alegrai-vos no Senhor?','Filipenses',['Efésios','Gálatas','Colossenses'],'Filipenses 4:4',2],
 ['Novo Testamento','Qual carta diz que toda a Escritura é divinamente inspirada?','2 Timóteo',['1 Timóteo','Tito','Hebreus'],'2 Timóteo 3:16',3],
 ['Novo Testamento','Qual carta afirma que Deus é amor?','1 João',['2 Pedro','Judas','Tiago'],'1 João 4:8',2],
 ['Novo Testamento','Em que carta está o famoso capítulo sobre o amor, o capítulo 13?','1 Coríntios',['Romanos','Efésios','Filipenses'],'1 Coríntios 13',2],
 ['Novo Testamento','Em que carta Pedro chama os cristãos de geração eleita e sacerdócio real?','1 Pedro',['1 João','Tiago','Judas'],'1 Pedro 2:9',3],
 ['Novo Testamento','Segundo Tiago 1:5, o que fazer se faltar sabedoria?','Pedi-la a Deus',['Estudar os sábios','Jejuar sete dias','Consultar os anciãos'],'Tiago 1:5',2],
 ['Novo Testamento','Complete: Submetei-vos a Deus; resisti ao...','diabo',['mundo','medo','orgulho'],'Tiago 4:7',2],
 ['Novo Testamento','Complete: O diabo anda em derredor como leão...','rugidor',['faminto','dormindo','cansado'],'1 Pedro 5:8',2],
 ['Novo Testamento','Segundo 2 Coríntios 5:17, quem está em Cristo é nova...','criatura',['esperança','pessoa','semente'],'2 Coríntios 5:17',3],
 ['Novo Testamento','Complete: Jesus Cristo é o mesmo ontem, hoje e...','eternamente',['no fim','na glória','na terra'],'Hebreus 13:8',2],
 ['Novo Testamento','Segundo 1 Tessalonicenses 5:17, como devemos orar?','Sem cessar',['Somente em público','Apenas de manhã','Só em jejum'],'1 Tessalonicenses 5:17',1],
 ['Novo Testamento','Qual destes é um fruto do Espírito?','Domínio próprio',['Sabedoria','Coragem','Riqueza'],'Gálatas 5:22-23',2],
 ['Novo Testamento','Qual é o primeiro fruto do Espírito citado em Gálatas 5:22?','Amor',['Alegria','Paz','Fé'],'Gálatas 5:22',2],
 ['Novo Testamento','Quantos são os frutos do Espírito listados em Gálatas 5:22-23?','Nove',['Sete','Doze','Dez'],'Gálatas 5:22-23',2],
 ['Novo Testamento','Na armadura de Deus, o que é chamado de espada do Espírito?','A Palavra de Deus',['A oração','A fé','A justiça'],'Efésios 6:17',2],
 ['Novo Testamento','Na armadura de Deus, que peça é chamada de escudo?','A fé',['A verdade','A paz','A salvação'],'Efésios 6:16',2],
 ['Novo Testamento','Na armadura de Deus, com o que se cinge os lombos?','Com a verdade',['Com a justiça','Com a paz','Com a fé'],'Efésios 6:14',3],
 ['Novo Testamento','Na armadura de Deus, o que protege o peito?','A couraça da justiça',['O escudo da fé','O capacete da salvação','O cinto da verdade'],'Efésios 6:14',3],
 ['Novo Testamento','Na armadura de Deus, o que calça os pés?','O evangelho da paz',['A justiça','A fé','A oração'],'Efésios 6:15',3],
 ['Novo Testamento','Na armadura de Deus, o que protege a cabeça?','O capacete da salvação',['A couraça da justiça','O escudo da fé','O cinto da verdade'],'Efésios 6:17',2],
 ['Novo Testamento','Complete: O que fizerdes, fazei-o de todo o...','coração',['tempo','poder','modo'],'Colossenses 3:23',3],
 ['Novo Testamento','Complete: Não andeis ansiosos por coisa alguma; em tudo, pela oração e súplica, com...','ações de graças',['lágrimas','jejum','silêncio'],'Filipenses 4:6',3],
 ['Novo Testamento','Segundo Gálatas 6:7, o que o homem semear...','Isso também ceifará',['Perderá','Guardará','Esquecerá'],'Gálatas 6:7',3],
 ['Novo Testamento','Segundo Hebreus 11:6, sem fé é impossível...','Agradar a Deus',['Viver bem','Ser rico','Alcançar a paz'],'Hebreus 11:6',2],
 ['Vida de Jesus','Em que cidade Jesus nasceu?','Belém',['Nazaré','Jerusalém','Cafarnaum'],'Mateus 2:1',1],
 ['Vida de Jesus','Que anjo anunciou a Maria que ela seria mãe de Jesus?','Gabriel',['Miguel','Rafael','Uriel'],'Lucas 1:26-27',1],
 ['Vida de Jesus','Onde Jesus foi colocado logo depois de nascer?','Numa manjedoura',['Num berço de madeira','Numa cesta de vime','Numa tenda'],'Lucas 2:7',1],
 ['Vida de Jesus','Quem recebeu primeiro o anúncio dos anjos sobre o nascimento de Jesus?','Pastores',['Magos','Sacerdotes','Soldados'],'Lucas 2:8-14',1],
 ['Vida de Jesus','Que presentes os magos deram a Jesus?','Ouro, incenso e mirra',['Ouro, prata e bronze','Incenso, azeite e vinho','Mirra, nardo e pérolas'],'Mateus 2:11',2],
 ['Vida de Jesus','Que rei mandou matar os meninos de Belém?','Herodes',['Pilatos','Augusto','Agripa'],'Mateus 2:16',1],
 ['Vida de Jesus','Para que país José e Maria fugiram com Jesus?','Egito',['Síria','Babilônia','Roma'],'Mateus 2:13-14',2],
 ['Vida de Jesus','Em que cidade Jesus cresceu?','Nazaré',['Belém','Jericó','Betânia'],'Lucas 2:39',1],
 ['Vida de Jesus','Qual era a profissão de José, pai terreno de Jesus?','Carpinteiro',['Pescador','Pastor','Oleiro'],'Mateus 13:55',1],
 ['Vida de Jesus','Com que idade Jesus ficou no templo conversando com os doutores?','Doze anos',['Oito anos','Quinze anos','Vinte anos'],'Lucas 2:42',2],
 ['Vida de Jesus','Quem batizou Jesus?','João Batista',['Pedro','André','Tiago'],'Mateus 3:13',1],
 ['Vida de Jesus','Em que rio Jesus foi batizado?','Rio Jordão',['Rio Nilo','Rio Eufrates','Rio Jaboque'],'Mateus 3:13',1],
 ['Vida de Jesus','Que ave desceu sobre Jesus no seu batismo?','Uma pomba',['Uma águia','Um corvo','Um pardal'],'Mateus 3:16',1],
 ['Vida de Jesus','Quantos dias Jesus jejuou no deserto?','Quarenta',['Sete','Vinte e um','Trinta'],'Mateus 4:2',1],
 ['Vida de Jesus','Quem tentou Jesus no deserto?','O diabo',['Herodes','Pilatos','Caifás'],'Mateus 4:1-3',1],
 ['Vida de Jesus','Complete: Nem só de pão viverá o homem, mas de toda a...','palavra de Deus',['sabedoria do céu','obra de Moisés','lei do templo'],'Mateus 4:4',2],
 ['Vida de Jesus','Segundo Lucas, com que idade Jesus começou seu ministério?','Cerca de trinta anos',['Doze anos','Cerca de vinte anos','Cerca de quarenta anos'],'Lucas 3:23',2],
 ['Vida de Jesus','Com quem Jesus conversou à noite e disse que era preciso nascer de novo?','Nicodemos',['Zaqueu','Lázaro','Natanael'],'João 3:1-7',2],
 ['Vida de Jesus','Quem disse: Eis o Cordeiro de Deus que tira o pecado do mundo?','João Batista',['Pedro','André','Natanael'],'João 1:29',2],
 ['Vida de Jesus','Complete: Bem-aventurados os mansos, porque eles herdarão...','a terra',['o reino','o céu','a glória'],'Mateus 5:5',2],
 ['Vida de Jesus','Complete: Bem-aventurados os puros de coração, porque eles verão...','a Deus',['o reino','a luz','o Filho'],'Mateus 5:8',2],
 ['Vida de Jesus','Complete: Bem-aventurados os pacificadores, porque serão chamados...','filhos de Deus',['servos de Deus','amigos de Deus','herdeiros de Deus'],'Mateus 5:9',2],
 ['Vida de Jesus','Complete: Bem-aventurados os que choram, porque serão...','consolados',['ricos','honrados','ouvidos'],'Mateus 5:4',2],
 ['Vida de Jesus','Que oração Jesus ensinou aos discípulos?','O Pai Nosso',['A oração de Jabez','O Salmo 91','O cântico de Maria'],'Mateus 6:9-13',1],
 ['Vida de Jesus','Complete, no Pai Nosso: Venha o teu...','reino',['poder','trono','nome'],'Mateus 6:10',1],
 ['Vida de Jesus','Complete: Buscai primeiro o reino de Deus e a sua...','justiça',['glória','paz','verdade'],'Mateus 6:33',2],
 ['Vida de Jesus','Segundo Jesus, qual é o maior mandamento?','Amar ao Senhor, teu Deus',['Honrar pai e mãe','Não matar','Dar o dízimo'],'Mateus 22:37-38',2],
 ['Vida de Jesus','Segundo Jesus, o segundo grande mandamento é amar a quem?','O próximo como a si mesmo',['Somente os inimigos','Os sacerdotes','Somente a família'],'Mateus 22:39',2],
 ['Vida de Jesus','Complete: Eu sou o caminho, e a verdade, e...','a vida',['a luz','a porta','o pão'],'João 14:6',1],
 ['Vida de Jesus','Complete: Eu sou o bom...','pastor',['mestre','rei','juiz'],'João 10:11',1],
 ['Vida de Jesus','Complete: Eu sou o pão da...','vida',['luz','paz','terra'],'João 6:35',1],
 ['Vida de Jesus','Quantas vezes Jesus disse que devemos perdoar ao irmão?','Setenta vezes sete',['Sete vezes apenas','Três vezes','Cem vezes'],'Mateus 18:22',2],
 ['Vida de Jesus','O que Jesus pediu ao jovem rico que fizesse?','Vender tudo e dar aos pobres',['Jejuar quarenta dias','Deixar a família','Entregar o templo'],'Mateus 19:21',2],
 ['Vida de Jesus','Que cobrador de impostos subiu numa árvore para ver Jesus?','Zaqueu',['Levi','Nicodemos','Natanael'],'Lucas 19:1-10',1],
 ['Vida de Jesus','Em que tipo de árvore Zaqueu subiu?','Sicômoro',['Cedro','Oliveira','Palmeira'],'Lucas 19:4',3],
 ['Vida de Jesus','Sobre que animal Jesus entrou em Jerusalém?','Um jumentinho',['Um cavalo branco','Um camelo','Um boi'],'Mateus 21:5-7',1],
 ['Vida de Jesus','O que o povo espalhou no caminho quando Jesus entrou em Jerusalém?','Mantos e ramos',['Flores e perfumes','Trigo e cevada','Tapetes e moedas'],'Mateus 21:8',2],
 ['Vida de Jesus','O que Jesus fez com os cambistas no templo?','Expulsou-os e virou as mesas',['Ensinou-os','Pagou-lhes','Ignorou-os'],'Mateus 21:12',1],
 ['Vida de Jesus','O que Jesus fez aos discípulos antes da última ceia terminar?','Lavou-lhes os pés',['Ungiu-lhes a cabeça','Deu-lhes moedas','Cortou-lhes o cabelo'],'João 13:5',2],
 ['Vida de Jesus','Que alimentos Jesus usou como símbolos na Santa Ceia?','Pão e cálice',['Peixe e pão','Água e sal','Cordeiro e ervas'],'Mateus 26:26-28',1],
 ['Vida de Jesus','Em que jardim Jesus orou antes de ser preso?','Getsêmani',['Éden','Betânia','Siloé'],'Mateus 26:36',1],
 ['Vida de Jesus','Qual discípulo traiu Jesus?','Judas Iscariotes',['Tomé','Pedro','Filipe'],'Mateus 26:14-16',1],
 ['Vida de Jesus','Por quanto Judas entregou Jesus?','Trinta moedas de prata',['Vinte moedas de prata','Doze moedas de ouro','Cem moedas de prata'],'Mateus 26:15',2],
 ['Vida de Jesus','Como Judas indicou Jesus aos soldados?','Com um beijo',['Apontando','Com uma senha','Com um abraço'],'Mateus 26:48-49',2],
 ['Vida de Jesus','Qual discípulo negou Jesus três vezes?','Pedro',['João','André','Tomé'],'Mateus 26:69-75',1],
 ['Vida de Jesus','O que aconteceu logo após a terceira negação de Pedro?','O galo cantou',['Trovejou','Escureceu','A terra tremeu'],'Lucas 22:60',1],
 ['Vida de Jesus','Que governador romano condenou Jesus à crucificação?','Pôncio Pilatos',['Félix','Festo','Cirênio'],'Mateus 27:26',1],
 ['Vida de Jesus','Que prisioneiro foi solto em lugar de Jesus?','Barrabás',['Caifás','Simão','Judas'],'Mateus 27:21',2],
 ['Vida de Jesus','Como se chama o lugar onde Jesus foi crucificado?','Gólgota',['Getsêmani','Monte das Oliveiras','Betânia'],'Mateus 27:33',2],
 ['Vida de Jesus','Quem foi obrigado a carregar a cruz de Jesus?','Simão de Cirene',['José de Arimateia','Nicodemos','Barrabás'],'Mateus 27:32',3],
 ['Vida de Jesus','Quem pediu o corpo de Jesus a Pilatos e o sepultou em seu túmulo novo?','José de Arimateia',['Nicodemos','Simão de Cirene','Lázaro'],'Mateus 27:57-60',2],
 ['Vida de Jesus','Qual frase Jesus disse pouco antes de expirar, segundo João?','Está consumado',['Pai, perdoa-lhes','Deus meu, Deus meu','Em tuas mãos'],'João 19:30',3],
 ['Vida de Jesus','Quantos dias Jesus ficou no túmulo?','Três dias',['Um dia','Sete dias','Quarenta dias'],'Mateus 12:40',1],
 ['Vida de Jesus','Em que dia da semana Jesus ressuscitou?','Domingo',['Na sexta-feira','No sábado','Na quinta-feira'],'Mateus 28:1',1],
 ['Vida de Jesus','Qual discípulo duvidou até ver as marcas nas mãos de Jesus?','Tomé',['Pedro','Filipe','André'],'João 20:25-27',1],
 ['Vida de Jesus','Quantos dias Jesus ficou com os discípulos depois de ressuscitar, até subir ao céu?','Quarenta',['Três','Sete','Cinquenta'],'Atos 1:3',2],
 ['Vida de Jesus','Quem apareceu com Moisés a Jesus no monte da transfiguração?','Elias',['Isaías','Enoque','João Batista'],'Mateus 17:3',2],
 ['Vida de Jesus','Quem era o pai de João Batista?','Zacarias',['Eli','Simeão','Jairo'],'Lucas 1:13',2],
 ['Vida de Jesus','Que homem justo pegou Jesus nos braços no templo e louvou a Deus?','Simeão',['Zacarias','Nicodemos','José'],'Lucas 2:25-32',3],
 ['Vida de Jesus','Complete: No princípio era o Verbo, e o Verbo estava com...','Deus',['o mundo','a luz','os anjos'],'João 1:1',2],
 ['Personagens','Quem construiu a arca por ordem de Deus?','Noé',['Moisés','Abraão','Enoque'],'Gênesis 6:14',1],
 ['Personagens','Quem é chamado de pai da fé?','Abraão',['Isaque','Moisés','Noé'],'Romanos 4:16',2],
 ['Personagens','Qual foi o primeiro filho de Adão e Eva?','Caim',['Abel','Sete','Enoque'],'Gênesis 4:1',1],
 ['Personagens','Qual filho de Abraão nasceu de Hagar?','Ismael',['Isaque','Esaú','Midiã'],'Gênesis 16:15',2],
 ['Personagens','Quem recebeu a bênção de Isaque disfarçado de Esaú?','Jacó',['José','Judá','Labão'],'Gênesis 27',1],
 ['Personagens','Quem era o sogro de Moisés, sacerdote de Midiã?','Jetro',['Labão','Balaque','Eli'],'Êxodo 3:1',3],
 ['Personagens','Quem segurou os braços de Moisés com Hur durante a batalha contra Amaleque?','Arão',['Josué','Calebe','Finéias'],'Êxodo 17:12',3],
 ['Personagens','Que juiz derrotou os midianitas com trezentos homens?','Gideão',['Sansão','Baraque','Jefté'],'Juízes 7',2],
 ['Personagens','Que juiz, junto com Débora, derrotou Sísera?','Baraque',['Gideão','Jefté','Otniel'],'Juízes 4:6-8',3],
 ['Personagens','Que juiz fez um voto imprudente envolvendo sua filha?','Jefté',['Gideão','Sansão','Samuel'],'Juízes 11:30-31',3],
 ['Personagens','Quem era o homem mais forte da Bíblia, traído por Dalila?','Sansão',['Golias','Gideão','Davi'],'Juízes 16',1],
 ['Personagens','Qual era o segredo da força de Sansão?','O cabelo nunca cortado',['Um anel mágico','Uma armadura de bronze','Um cinto de couro'],'Juízes 16:17',1],
 ['Personagens','Que menino ouviu a voz de Deus no templo enquanto servia a Eli?','Samuel',['Davi','Timóteo','Jeremias'],'1 Samuel 3',1],
 ['Personagens','Que pastor de ovelhas foi ungido rei por Samuel?','Davi',['Saul','Jessé','Jônatas'],'1 Samuel 16:13',1],
 ['Personagens','Que gigante Davi derrotou com uma pedra?','Golias',['Og','Sísera','Abner'],'1 Samuel 17:49-50',1],
 ['Personagens','Quantas pedras Davi pegou no ribeiro para enfrentar Golias?','Cinco',['Três','Sete','Uma'],'1 Samuel 17:40',2],
 ['Personagens','Quem era o melhor amigo de Davi, filho do rei Saul?','Jônatas',['Abner','Joabe','Absalão'],'1 Samuel 18:1',2],
 ['Personagens','Que filho de Davi se revoltou contra o pai e morreu preso a um carvalho?','Absalão',['Adonias','Salomão','Amnom'],'2 Samuel 18:9',2],
 ['Personagens','Quem Paulo chamou de varão segundo o coração de Deus?','Davi',['Salomão','Saul','Samuel'],'Atos 13:22',2],
 ['Personagens','Quem subiu ao céu num redemoinho, com carros de fogo?','Elias',['Eliseu','Isaías','Moisés'],'2 Reis 2:11',1],
 ['Personagens','Quem recebeu o manto de Elias?','Eliseu',['Geazi','Jeú','Micaías'],'2 Reis 2:13',2],
 ['Personagens','Quem foi alimentado por corvos junto ao ribeiro de Querite?','Elias',['Eliseu','Davi','Jeremias'],'1 Reis 17:4-6',2],
 ['Personagens','Quem foi lançado na cova dos leões?','Daniel',['José','Jonas','Elias'],'Daniel 6',1],
 ['Personagens','Quem foram lançados na fornalha ardente junto com Sadraque?','Mesaque e Abede-Nego',['Daniel e Dario','Daniel e Mordecai','Esdras e Neemias'],'Daniel 3',2],
 ['Personagens','Quem foi engolido por um grande peixe?','Jonas',['Jó','Jeremias','Noé'],'Jonas 1:17',1],
 ['Personagens','Que homem perdeu tudo, mas permaneceu fiel a Deus?','Jó',['Jonas','Jacó','Ló'],'Jó 1',1],
 ['Personagens','Que sumo sacerdote rasgou as vestes no julgamento de Jesus?','Caifás',['Eli','Zadoque','Arão'],'Mateus 26:57-65',3],
 ['Personagens','Quem ressuscitou ao quarto dia no túmulo, chamado por Jesus?','Lázaro',['Jairo','Bartimeu','Malco'],'João 11:43-44',1],
 ['Personagens','Quem foi o escravo por quem Paulo intercedeu junto a Filemom?','Onésimo',['Tíquico','Epafras','Demas'],'Filemom 1:10',3],
 ['Personagens','Que jovem aprendeu as Escrituras com a mãe e a avó, e depois serviu com Paulo?','Timóteo',['Tito','Silas','Marcos'],'2 Timóteo 1:5',2],
 ['Personagens','Que homem recebeu de Jesus o nome Pedro?','Simão',['André','Tiago','Levi'],'João 1:42',1],
 ['Personagens','Que discípulo é chamado o amado, que se reclinou no peito de Jesus?','João',['Pedro','André','Tiago'],'João 13:23',2],
 ['Personagens','Que rei da Babilônia mandou fazer uma estátua de ouro e exigiu que a adorassem?','Nabucodonosor',['Belsazar','Dario','Ciro'],'Daniel 3:1',2],
 ['Personagens','Que profeta foi jogado numa cisterna de lama?','Jeremias',['Isaías','Amós','Ezequiel'],'Jeremias 38:6',3],
 ['Personagens','Quem era o pai de Davi?','Jessé',['Elcana','Obede','Boaz'],'1 Samuel 16:1',2],
 ['Personagens','Quem era o pai de Samuel?','Elcana',['Jessé','Eli','Saul'],'1 Samuel 1:1',3],
 ['Milagres e Parábolas','Qual foi o primeiro milagre de Jesus?','Transformar água em vinho',['Multiplicar os pães','Curar um cego','Andar sobre o mar'],'João 2:1-11',1],
 ['Milagres e Parábolas','Em que cidade Jesus transformou água em vinho?','Caná da Galileia',['Betânia','Cafarnaum','Naim'],'João 2:1',2],
 ['Milagres e Parábolas','Com quantos pães e peixes Jesus alimentou os cinco mil?','Cinco pães e dois peixes',['Sete pães e três peixes','Dois pães e cinco peixes','Doze pães e dois peixes'],'Mateus 14:17',1],
 ['Milagres e Parábolas','Quantos cestos de sobras foram recolhidos após alimentar os cinco mil?','Doze',['Sete','Cinco','Dez'],'Mateus 14:20',2],
 ['Milagres e Parábolas','Quantos pães Jesus usou para alimentar os quatro mil?','Sete',['Cinco','Doze','Três'],'Mateus 15:34',3],
 ['Milagres e Parábolas','O que Jesus fez quando a tempestade ameaçou o barco dos discípulos?','Acalmou o vento e o mar',['Mandou remar mais forte','Mandou abandonar o barco','Fez o barco voar'],'Marcos 4:39',1],
 ['Milagres e Parábolas','Que discípulo tentou andar sobre as águas ao encontro de Jesus?','Pedro',['Tiago','João','André'],'Mateus 14:29',1],
 ['Milagres e Parábolas','Que chefe da sinagoga pediu a Jesus que curasse sua filha de doze anos?','Jairo',['Nicodemos','Cornélio','Zaqueu'],'Marcos 5:22-23',2],
 ['Milagres e Parábolas','Quantos anos a mulher que tocou no manto de Jesus sofria de hemorragia?','Doze anos',['Sete anos','Trinta anos','Dezoito anos'],'Marcos 5:25',2],
 ['Milagres e Parábolas','Quem foi curada ao tocar no manto de Jesus?','A mulher com hemorragia',['A sogra de Pedro','A viúva de Naim','A mulher cananeia'],'Marcos 5:25-34',2],
 ['Milagres e Parábolas','Em que animais Jesus mandou os demônios entrarem?','Em porcos',['Em cabras','Em ovelhas','Em camelos'],'Marcos 5:13',1],
 ['Milagres e Parábolas','Quantos leprosos curados voltaram para agradecer a Jesus?','Um',['Dois','Três','Nove'],'Lucas 17:15-16',2],
 ['Milagres e Parábolas','De que povo era o leproso que voltou para agradecer?','Samaritano',['Galileu','Romano','Grego'],'Lucas 17:16',2],
 ['Milagres e Parábolas','Como os amigos levaram o paralítico até Jesus?','Desceram-no pelo telhado',['Por um muro','Por uma janela lateral','Numa barca'],'Marcos 2:4',1],
 ['Milagres e Parábolas','Que cego gritou: Filho de Davi, tem compaixão de mim, junto a Jericó?','Bartimeu',['Jairo','Malco','Lázaro'],'Marcos 10:46-52',2],
 ['Milagres e Parábolas','O que Jesus usou para curar o cego de nascença?','Lodo feito com saliva',['Azeite e sal','Água do Jordão','Pão de cevada'],'João 9:6',2],
 ['Milagres e Parábolas','Em que tanque o cego de nascença lavou o rosto?','Tanque de Siloé',['Tanque de Betesda','Poço de Jacó','Mar da Galileia'],'João 9:7',3],
 ['Milagres e Parábolas','Havia quantos anos estava doente o paralítico de Betesda?','Trinta e oito anos',['Doze anos','Quarenta anos','Dezoito anos'],'João 5:5',3],
 ['Milagres e Parábolas','Que oficial romano pediu a Jesus que curasse seu servo sem entrar em sua casa?','O centurião',['O governador','O sumo sacerdote','O cobrador de impostos'],'Mateus 8:5-13',2],
 ['Milagres e Parábolas','Em que cidade Jesus ressuscitou o filho de uma viúva?','Naim',['Caná','Betsaida','Corazim'],'Lucas 7:11-15',3],
 ['Milagres e Parábolas','Complete a ordem de Jesus no túmulo: Lázaro, vem para...','fora',['casa','perto','cima'],'João 11:43',3],
 ['Milagres e Parábolas','Que árvore Jesus amaldiçoou e secou?','A figueira',['A oliveira','A videira','A palmeira'],'Mateus 21:19',2],
 ['Milagres e Parábolas','Quem teve a orelha cortada por Pedro e curada por Jesus?','Malco',['Caifás','Barrabás','Anás'],'João 18:10',3],
 ['Milagres e Parábolas','Que profeta curou Naamã da lepra?','Eliseu',['Elias','Isaías','Jeremias'],'2 Reis 5',2],
 ['Milagres e Parábolas','Quantas vezes Naamã mergulhou no rio Jordão?','Sete vezes',['Três vezes','Doze vezes','Quarenta vezes'],'2 Reis 5:14',2],
 ['Milagres e Parábolas','O que Eliseu fez com o ferro do machado que caiu na água?','Fê-lo flutuar',['Fê-lo derreter','Fê-lo brilhar','Fê-lo voar'],'2 Reis 6:6',3],
 ['Milagres e Parábolas','Como Deus sustentou a viúva de Sarepta durante a seca?','Farinha e azeite duraram',['Com corvos','Com maná','Com codornizes'],'1 Reis 17:14-16',2],
 ['Milagres e Parábolas','Na parábola do bom samaritano, quem ajudou o homem ferido na estrada?','O samaritano',['Um sacerdote','Um levita','Um fariseu'],'Lucas 10:33',1],
 ['Milagres e Parábolas','Na parábola do bom samaritano, quem passou de largo antes dele?','Um sacerdote e um levita',['Um rei e um soldado','Dois fariseus','Dois cobradores'],'Lucas 10:31-32',2],
 ['Milagres e Parábolas','Na parábola do filho pródigo, que animais ele cuidava na miséria?','Porcos',['Ovelhas','Camelos','Cavalos'],'Lucas 15:15',1],
 ['Milagres e Parábolas','O que o pai deu ao filho pródigo quando ele voltou?','Manto, anel e sandálias',['Uma casa e terras','Ouro e prata','Um cavalo e uma espada'],'Lucas 15:22',2],
 ['Milagres e Parábolas','Quantas virgens da parábola eram prudentes?','Cinco',['Três','Sete','Dez'],'Mateus 25:2',1],
 ['Milagres e Parábolas','Por que as virgens insensatas ficaram de fora?','Não tinham azeite',['Esqueceram o convite','Chegaram à casa errada','Quebraram as lâmpadas'],'Mateus 25:3-10',1],
 ['Milagres e Parábolas','Na parábola dos talentos, quantos talentos recebeu o primeiro servo?','Cinco',['Dez','Três','Sete'],'Mateus 25:15',2],
 ['Milagres e Parábolas','O que fez o servo que recebeu um talento?','Escondeu-o na terra',['Gastou-o','Investiu-o','Deu aos pobres'],'Mateus 25:25',2],
 ['Milagres e Parábolas','Na parábola do semeador, qual semente deu fruto?','A que caiu em boa terra',['A do caminho','A entre espinhos','A em pedregais'],'Mateus 13:8',1],
 ['Milagres e Parábolas','Quanto produziu a semente que caiu em boa terra?','Cem, sessenta ou trinta',['Dez por um','Mil por um','Dois por um'],'Mateus 13:8',3],
 ['Milagres e Parábolas','Na parábola da semente de mostarda, ela é...','A menor de todas as sementes',['A maior das sementes','Uma semente dourada','Uma semente de trigo'],'Mateus 13:31-32',2],
 ['Milagres e Parábolas','Na parábola do trigo e do joio, quem semeou o joio?','O inimigo',['O servo','O ceifeiro','O dono do campo'],'Mateus 13:25',2],
 ['Milagres e Parábolas','Na parábola do tesouro escondido, o homem vendeu tudo para comprar o quê?','O campo',['A pérola','O celeiro','A vinha'],'Mateus 13:44',3],
 ['Milagres e Parábolas','Na parábola da ovelha perdida, quantas ovelhas o pastor deixou no aprisco?','Noventa e nove',['Noventa','Cinquenta','Cem'],'Lucas 15:4',2],
 ['Milagres e Parábolas','Na parábola da moeda perdida, quantas moedas a mulher tinha?','Dez',['Cinco','Doze','Sete'],'Lucas 15:8',3],
 ['Milagres e Parábolas','Na parábola das duas casas, o que aconteceu com a casa sobre a rocha?','Permaneceu firme',['Foi levada pelo rio','Caiu com a chuva','Pegou fogo'],'Mateus 7:24-25',1],
 ['Milagres e Parábolas','Na parábola do rico insensato, o que ele planejou fazer?','Construir celeiros maiores',['Dar aos pobres','Comprar terras','Viajar'],'Lucas 12:16-18',2],
 ['Milagres e Parábolas','Na parábola do rico e Lázaro, para onde foi Lázaro ao morrer?','Para o seio de Abraão',['Para o monte Sião','Para o jardim do Éden','Para a casa de Davi'],'Lucas 16:22',3],
 ['Milagres e Parábolas','Na parábola dos dois construtores, o que se diz do insensato?','Construiu sobre a areia',['Não construiu casa','Usou cedro','Construiu num monte'],'Mateus 7:26',1],
 ['Milagres e Parábolas','Na parábola do fermento, em quantas medidas de farinha a mulher o misturou?','Três medidas',['Uma medida','Sete medidas','Doze medidas'],'Mateus 13:33',3],
 ['Milagres e Parábolas','Na parábola da grande ceia, quem foi chamado quando os convidados recusaram?','Pobres, cegos e coxos',['Os sacerdotes','Os soldados','Os reis'],'Lucas 14:21',3],
 ['Milagres e Parábolas','Na parábola dos trabalhadores da vinha, quanto recebeu cada um?','Um denário',['Dez denários','Um talento','Uma moeda de ouro'],'Mateus 20:9-10',3],
 ['Livros e Números','Quantos livros tem a Bíblia protestante?','Sessenta e seis',['Setenta e dois','Trinta e nove','Setenta e três'],'Gênesis a Apocalipse',1],
 ['Livros e Números','Quantos livros tem o Antigo Testamento?','Trinta e nove',['Vinte e sete','Quarenta e seis','Sessenta e seis'],'Gênesis a Malaquias',1],
 ['Livros e Números','Quantos livros tem o Novo Testamento?','Vinte e sete',['Trinta e nove','Vinte e um','Sessenta e seis'],'Mateus a Apocalipse',1],
 ['Livros e Números','Qual é o primeiro livro da Bíblia?','Gênesis',['Êxodo','Salmos','Mateus'],'Gênesis 1:1',1],
 ['Livros e Números','Qual é o último livro do Antigo Testamento?','Malaquias',['Zacarias','Ageu','Daniel'],'Malaquias 1:1',2],
 ['Livros e Números','Qual livro da Bíblia tem mais capítulos?','Salmos',['Isaías','Gênesis','Jeremias'],'Salmos',2],
 ['Livros e Números','Quantos Salmos há no livro de Salmos?','Cento e cinquenta',['Cem','Cento e vinte','Sessenta e seis'],'Salmos',2],
 ['Livros e Números','Quantos livros formam o Pentateuco?','Cinco',['Quatro','Sete','Doze'],'Gênesis a Deuteronômio',1],
 ['Livros e Números','Qual livro vem depois de Gênesis?','Êxodo',['Levítico','Números','Josué'],'Êxodo 1:1',1],
 ['Livros e Números','Qual livro registra o censo do povo de Israel no deserto?','Números',['Levítico','Êxodo','Josué'],'Números 1:1',2],
 ['Livros e Números','Qual livro trata das leis sobre sacrifícios e sacerdotes?','Levítico',['Números','Deuteronômio','Êxodo'],'Levítico 1:1',2],
 ['Livros e Números','Qual livro vem depois de Deuteronômio?','Josué',['Juízes','Rute','Números'],'Josué 1:1',2],
 ['Livros e Números','Qual livro vem depois de Juízes?','Rute',['Josué','1 Samuel','Ester'],'Rute 1:1',2],
 ['Livros e Números','Qual livro começa com Vaidade de vaidades?','Eclesiastes',['Provérbios','Salmos','Jó'],'Eclesiastes 1:2',2],
 ['Livros e Números','Que livro leva o nome de uma rainha da Pérsia?','Ester',['Rute','Daniel','Neemias'],'Ester 1',1],
 ['Livros e Números','Quantos capítulos tem o livro de Gênesis?','Cinquenta',['Quarenta','Sessenta e seis','Trinta e oito'],'Gênesis 50',3],
 ['Livros e Números','Quantas tribos tem Israel?','Doze',['Dez','Sete','Catorze'],'Gênesis 49:28',1],
 ['Livros e Números','Quantos apóstolos Jesus escolheu?','Doze',['Sete','Setenta','Dez'],'Lucas 6:13',1],
 ['Livros e Números','Quantos evangelhos há no Novo Testamento?','Quatro',['Três','Cinco','Doze'],'Mateus a João',1],
 ['Livros e Números','Quantos dias Deus trabalhou na criação antes de descansar?','Seis',['Sete','Três','Dez'],'Êxodo 20:11',1],
 ['Livros e Números','Quantos anos viveu Matusalém?','Novecentos e sessenta e nove',['Novecentos e trinta','Setecentos e setenta e sete','Novecentos e cinquenta'],'Gênesis 5:27',3],
 ['Livros e Números','Quantos anos tinha Noé quando veio o dilúvio?','Seiscentos',['Quinhentos','Cento e vinte','Novecentos e cinquenta'],'Gênesis 7:6',3],
 ['Livros e Números','Quantos anos tinha Abraão quando nasceu Isaque?','Cem anos',['Setenta e cinco','Noventa','Cento e vinte'],'Gênesis 21:5',3],
 ['Livros e Números','Com que idade Moisés morreu?','Cento e vinte anos',['Oitenta anos','Cento e dez anos','Cem anos'],'Deuteronômio 34:7',3],
 ['Livros e Números','Quantos anos tinha José quando foi vendido pelos irmãos?','Dezessete',['Doze','Vinte','Quinze'],'Gênesis 37:2',3],
 ['Livros e Números','Quantos dias Jonas ficou dentro do grande peixe?','Três dias e três noites',['Um dia','Sete dias','Quarenta dias'],'Jonas 1:17',1],
 ['Livros e Números','Quantos dias Moisés ficou no monte com Deus?','Quarenta dias e noites',['Sete','Doze','Três'],'Êxodo 24:18',2],
 ['Livros e Números','Com quantos homens Gideão derrotou os midianitas?','Trezentos',['Cem','Mil','Quinhentos'],'Juízes 7:7',2],
 ['Livros e Números','Quantos anos reinou Salomão em Jerusalém?','Quarenta anos',['Vinte','Trinta','Cinquenta'],'1 Reis 11:42',3],
 ['Livros e Números','Qual livro contém a história do rei Belsazar e da mão que escreveu na parede?','Daniel',['Ezequiel','Ester','Jeremias'],'Daniel 5',2],
 ['Livros e Números','Qual livro do Antigo Testamento narra a reconstrução dos muros de Jerusalém?','Neemias',['Esdras','Ester','Ageu'],'Neemias 6:15',2],
 ['Livros e Números','Que livro do Novo Testamento vem logo depois de Atos?','Romanos',['Hebreus','Gálatas','Tiago'],'Romanos 1:1',2],
 ['Livros e Números','Quantos livros de Samuel há na Bíblia?','Dois',['Um','Três','Quatro'],'1 Samuel 1:1',2],
 ['Livros e Números','Qual livro do Antigo Testamento tem o nome de uma mulher moabita?','Rute',['Ester','Débora','Noemi'],'Rute 1:4',1],
 ['Lugares','Em que monte Moisés recebeu os Dez Mandamentos?','Monte Sinai',['Monte Carmelo','Monte Nebo','Monte das Oliveiras'],'Êxodo 19:20',1],
 ['Lugares','Em que monte Elias enfrentou os profetas de Baal?','Monte Carmelo',['Monte Sinai','Monte Hermom','Monte Sião'],'1 Reis 18:19-20',2],
 ['Lugares','Em que monte Abraão levou Isaque para o sacrifício?','Moriá',['Sinai','Carmelo','Hermom'],'Gênesis 22:2',3],
 ['Lugares','Qual era a terra prometida a Abraão e seus descendentes?','Canaã',['Egito','Moabe','Edom'],'Gênesis 12:5-7',1],
 ['Lugares','Que cidade Davi fez capital de seu reino?','Jerusalém',['Siquém','Samaria','Betel'],'2 Samuel 5:6-7',2],
 ['Lugares','Em que cidade nasceu o rei Davi?','Belém',['Hebrom','Nazaré','Jericó'],'1 Samuel 16:1',2],
 ['Lugares','Que mar Jesus caminhou sobre as águas?','Mar da Galileia',['Mar Morto','Mar Vermelho','Mar Mediterrâneo'],'Mateus 14:25',1],
 ['Lugares','Para que cidade Deus enviou Jonas a pregar?','Nínive',['Babilônia','Tarsis','Damasco'],'Jonas 1:1-2',1],
 ['Lugares','Para onde Jonas tentou fugir de navio?','Tarsis',['Sidom','Babilônia','Damasco'],'Jonas 1:3',2],
 ['Lugares','Que cidade teve os muros derrubados no tempo de Josué?','Jericó',['Ai','Hebrom','Siquém'],'Josué 6',1],
 ['Lugares','Para que cidade Saulo ia quando viu uma luz do céu?','Damasco',['Antioquia','Tarso','Jerusalém'],'Atos 9:3',1],
 ['Lugares','Em que cidade os discípulos foram chamados cristãos pela primeira vez?','Antioquia',['Jerusalém','Roma','Éfeso'],'Atos 11:26',2],
 ['Lugares','Qual era a cidade natal do apóstolo Paulo?','Tarso',['Damasco','Antioquia','Corinto'],'Atos 22:3',2],
 ['Lugares','Em que ilha o apóstolo João estava exilado quando recebeu o Apocalipse?','Patmos',['Chipre','Creta','Malta'],'Apocalipse 1:9',2],
 ['Lugares','Em que ilha Paulo naufragou a caminho de Roma?','Malta',['Creta','Chipre','Patmos'],'Atos 28:1',2],
 ['Lugares','De que monte Jesus subiu ao céu?','Monte das Oliveiras',['Monte Sinai','Monte Carmelo','Monte Sião'],'Atos 1:9-12',2],
 ['Lugares','Em que cidade moravam Marta, Maria e Lázaro?','Betânia',['Betel','Belém','Betsaida'],'João 11:1',2],
 ['Lugares','De que cidade eram Pedro, André e Filipe?','Betsaida',['Caná','Nazaré','Cafarnaum'],'João 1:44',3],
 ['Lugares','Em que cidade Jesus encontrou Zaqueu?','Jericó',['Betânia','Jerusalém','Cafarnaum'],'Lucas 19:1-2',2],
 ['Lugares','Em que cidade Paulo e Silas foram presos e houve um terremoto?','Filipos',['Éfeso','Corinto','Atenas'],'Atos 16:12-26',2],
 ['Lugares','Em que cidade Paulo falou sobre o Deus desconhecido no Areópago?','Atenas',['Corinto','Roma','Éfeso'],'Atos 17:22-23',2],
 ['Lugares','Para que cidade Paulo foi levado preso para ser julgado por César?','Roma',['Atenas','Corinto','Antioquia'],'Atos 28:16',2],
 ['Lugares','Para que cidade Israel foi levado cativo por Nabucodonosor?','Babilônia',['Egito','Assíria','Pérsia'],'2 Reis 24:14-16',1],
 ['Lugares','Em que lugar Jacó sonhou com a escada até o céu?','Betel',['Siló','Hebrom','Gilgal'],'Gênesis 28:19',2],
 ['Lugares','Que nome Jacó deu ao lugar onde lutou com Deus?','Peniel',['Betel','Mizpá','Mamre'],'Gênesis 32:30',3],
 ['Lugares','Em que cidade ficava o tabernáculo no tempo de Eli e Samuel?','Siló',['Betel','Gilgal','Hebrom'],'1 Samuel 1:3',3],
 ['Lugares','Qual era a terra de Jó?','Uz',['Midiã','Moabe','Edom'],'Jó 1:1',3],
 ['Lugares','Em que terra Caim habitou depois de matar Abel?','Node',['Sinar','Havilá','Ofir'],'Gênesis 4:16',3],
 ['Lugares','Qual destes rios é citado como saindo do Éden?','Eufrates',['Jordão','Nilo','Arnom'],'Gênesis 2:14',3],
 ['Lugares','Qual cidade Ló escolheu para morar?','Sodoma',['Zoar','Hebrom','Siquém'],'Gênesis 13:12',2],
 ['Lugares','Em que cidade Paulo ensinou por dois anos na escola de Tirano?','Éfeso',['Corinto','Atenas','Tessalônica'],'Atos 19:9-10',3],
 ['Lugares','Em que ilha Paulo e Barnabé pregaram no início da primeira viagem?','Chipre',['Creta','Malta','Patmos'],'Atos 13:4',3],
 ['Lugares','Em que rio Naamã mergulhou sete vezes?','Jordão',['Nilo','Eufrates','Jaboque'],'2 Reis 5:14',2],
 ['Lugares','Em que monte Deus falou com Moisés por meio de uma sarça ardente?','Horebe',['Carmelo','Nebo','Hermom'],'Êxodo 3:1-2',3],
 ['Lugares','Em que vale Davi enfrentou Golias?','Vale de Elá',['Vale de Hinom','Vale de Josafá','Vale de Acor'],'1 Samuel 17:2',3],
 ['Profetas e Reis','Quem foi o primeiro rei de Israel?','Saul',['Davi','Samuel','Salomão'],'1 Samuel 10:1',1],
 ['Profetas e Reis','Que profeta ungiu Saul e depois Davi como reis?','Samuel',['Natã','Elias','Eli'],'1 Samuel 10:1',2],
 ['Profetas e Reis','Quem foi o segundo rei de Israel?','Davi',['Salomão','Roboão','Jeroboão'],'1 Samuel 16:13',1],
 ['Profetas e Reis','Que rei construiu o primeiro templo em Jerusalém?','Salomão',['Davi','Zorobabel','Esdras'],'1 Reis 6:1',1],
 ['Profetas e Reis','O que Salomão pediu a Deus?','Sabedoria',['Riquezas','Vida longa','Vitória sobre os inimigos'],'1 Reis 3:9-12',1],
 ['Profetas e Reis','Que rainha visitou Salomão para testar sua sabedoria?','A rainha de Sabá',['A rainha Ester','A rainha Jezabel','A rainha Atalia'],'1 Reis 10:1',2],
 ['Profetas e Reis','Que filho de Davi e Bate-Seba se tornou rei?','Salomão',['Absalão','Adonias','Amnom'],'2 Samuel 12:24',1],
 ['Profetas e Reis','Que profeta repreendeu Davi pelo pecado com Bate-Seba?','Natã',['Samuel','Elias','Eliseu'],'2 Samuel 12:1-7',2],
 ['Profetas e Reis','Quem era o marido de Bate-Seba, morto por ordem de Davi?','Urias',['Uzias','Natã','Joabe'],'2 Samuel 11:15',2],
 ['Profetas e Reis','Quem era o comandante do exército de Davi?','Joabe',['Abner','Abisai','Urias'],'2 Samuel 8:16',3],
 ['Profetas e Reis','Que rei dividiu o reino ao ouvir conselhos dos jovens?','Roboão',['Jeroboão','Abias','Asa'],'1 Reis 12:13-16',3],
 ['Profetas e Reis','Quem foi o primeiro rei do reino do norte depois da divisão?','Jeroboão',['Roboão','Acabe','Jeú'],'1 Reis 12:20',3],
 ['Profetas e Reis','Que esposa de Acabe perseguiu o profeta Elias?','Jezabel',['Atalia','Dalila','Herodias'],'1 Reis 19:2',2],
 ['Profetas e Reis','Que rei tomou a vinha de Nabote?','Acabe',['Jeú','Jeroboão','Omri'],'1 Reis 21',3],
 ['Profetas e Reis','Quantos profetas de Baal Elias enfrentou no monte Carmelo?','Quatrocentos e cinquenta',['Quatrocentos','Oitocentos e cinquenta','Trezentos'],'1 Reis 18:19',3],
 ['Profetas e Reis','O que aconteceu no monte Carmelo quando Elias orou?','Fogo do céu consumiu o altar',['O povo acendeu o altar','Baal acendeu o fogo','Nada aconteceu'],'1 Reis 18:38',2],
 ['Profetas e Reis','Quem foi chamado por Deus quando arava com doze juntas de bois?','Eliseu',['Elias','Amós','Geazi'],'1 Reis 19:19',3],
 ['Profetas e Reis','Que profeta disse: Eis-me aqui, envia-me a mim?','Isaías',['Jeremias','Ezequiel','Oseias'],'Isaías 6:8',2],
 ['Profetas e Reis','Que profeta anunciou que uma virgem conceberia e daria à luz um filho?','Isaías',['Jeremias','Daniel','Malaquias'],'Isaías 7:14',2],
 ['Profetas e Reis','Que profeta viu um vale de ossos secos voltar à vida?','Ezequiel',['Isaías','Daniel','Jeremias'],'Ezequiel 37',2],
 ['Profetas e Reis','Que profeta disse: Ah, Senhor, eis que não sei falar, porque sou uma criança?','Jeremias',['Samuel','Isaías','Amós'],'Jeremias 1:6',3],
 ['Profetas e Reis','Que profeta era pastor e colhedor de sicômoros?','Amós',['Oseias','Miqueias','Joel'],'Amós 7:14-15',3],
 ['Profetas e Reis','Que profeta anunciou que o Messias nasceria em Belém?','Miqueias',['Naum','Habacuque','Ageu'],'Miqueias 5:2',3],
 ['Profetas e Reis','Que profeta se casou com Gômer por ordem de Deus?','Oseias',['Joel','Amós','Naum'],'Oseias 1:2-3',3],
 ['Profetas e Reis','Que rei da Babilônia destruiu Jerusalém e levou o povo cativo?','Nabucodonosor',['Belsazar','Ciro','Dario'],'2 Reis 25',2],
 ['Profetas e Reis','Que rei persa permitiu aos judeus voltarem para reconstruir o templo?','Ciro',['Belsazar','Nabucodonosor','Herodes'],'Esdras 1:1-3',2],
 ['Profetas e Reis','Que homem reconstruiu os muros de Jerusalém?','Neemias',['Esdras','Zorobabel','Ageu'],'Neemias 2:17-18',2],
 ['Profetas e Reis','Em quantos dias foi concluído o muro de Jerusalém?','Cinquenta e dois dias',['Quarenta dias','Setenta dias','Trinta dias'],'Neemias 6:15',3],
 ['Profetas e Reis','Com que idade Josias começou a reinar?','Oito anos',['Doze anos','Dezesseis anos','Cinco anos'],'2 Reis 22:1',3],
 ['Profetas e Reis','Que rei de Judá teve quinze anos acrescentados à sua vida?','Ezequias',['Josias','Uzias','Acaz'],'Isaías 38:5',3],
 ['Profetas e Reis','Que rei de Judá ficou leproso por tentar queimar incenso no templo?','Uzias',['Ezequias','Acaz','Manassés'],'2 Crônicas 26:19',3],
 ['Profetas e Reis','Que rei lançou Daniel na cova dos leões?','Dario',['Nabucodonosor','Belsazar','Ciro'],'Daniel 6:16',2],
 ['Profetas e Reis','Quem escreveu a maior parte dos Salmos?','Davi',['Salomão','Moisés','Jeremias'],'Salmos 23:1',1],
 ['Profetas e Reis','Quem escreveu a maior parte do livro de Provérbios?','Salomão',['Davi','Moisés','Isaías'],'Provérbios 1:1',2],
 ['Profetas e Reis','Quem era o sumo sacerdote que recebeu o menino Samuel no tabernáculo?','Eli',['Zadoque','Abiatar','Arão'],'1 Samuel 1:25-28',2],
 ['Profetas e Reis','Que rei ordenou reformas e fez o povo ler o livro da lei achado no templo?','Josias',['Acaz','Manassés','Ezequias'],'2 Reis 22:8-13',3],
 ['Profetas e Reis','Quem era o rei quando Daniel interpretou a mão que escreveu na parede?','Belsazar',['Nabucodonosor','Dario','Ciro'],'Daniel 5',2],
 ['Profetas e Reis','Que profeta foi enviado para pregar em Nínive e se irou por Deus perdoar?','Jonas',['Naum','Obadias','Habacuque'],'Jonas 4:1',2],
 ['Mulheres da Bíblia','Quem foi a primeira mulher?','Eva',['Sara','Ana','Lia'],'Gênesis 3:20',1],
 ['Mulheres da Bíblia','Quem era a esposa de Abraão?','Sara',['Rebeca','Raquel','Lia'],'Gênesis 17:15',1],
 ['Mulheres da Bíblia','Qual era o nome da serva egípcia de Sara, mãe de Ismael?','Hagar',['Zilpa','Bila','Ester'],'Gênesis 16:1-4',2],
 ['Mulheres da Bíblia','Quem era a esposa de Isaque?','Rebeca',['Sara','Lia','Raquel'],'Gênesis 24:67',1],
 ['Mulheres da Bíblia','Onde o servo de Abraão encontrou Rebeca?','Junto a um poço',['No templo','No mercado','Numa tenda'],'Gênesis 24:15-16',2],
 ['Mulheres da Bíblia','Qual esposa de Jacó ele amava mais?','Raquel',['Lia','Sara','Débora'],'Gênesis 29:18',1],
 ['Mulheres da Bíblia','Quantos anos Jacó trabalhou primeiro por Raquel?','Sete anos',['Três anos','Catorze anos','Dez anos'],'Gênesis 29:20',2],
 ['Mulheres da Bíblia','Como se chamava a filha de Jacó e Lia?','Diná',['Tamar','Miriã','Dalila'],'Gênesis 30:21',3],
 ['Mulheres da Bíblia','Quem era a mãe de Moisés?','Joquebede',['Miriã','Zípora','Raabe'],'Êxodo 6:20',3],
 ['Mulheres da Bíblia','Quem era a irmã de Moisés que vigiou o cestinho no Nilo?','Miriã',['Zípora','Débora','Joquebede'],'Êxodo 2:4',2],
 ['Mulheres da Bíblia','Quem era a esposa de Moisés?','Zípora',['Miriã','Raabe','Joquebede'],'Êxodo 2:21',3],
 ['Mulheres da Bíblia','Que mulher escondeu os espias em Jericó?','Raabe',['Débora','Rute','Jael'],'Josué 2:1-4',2],
 ['Mulheres da Bíblia','Que sinal Raabe colocou na janela de sua casa?','Um cordão escarlate',['Uma bandeira branca','Uma lâmpada','Um pano azul'],'Josué 2:18',3],
 ['Mulheres da Bíblia','Que mulher foi juíza e profetisa em Israel?','Débora',['Jael','Miriã','Hulda'],'Juízes 4:4',2],
 ['Mulheres da Bíblia','Que mulher matou Sísera com uma estaca de tenda?','Jael',['Débora','Dalila','Jezabel'],'Juízes 4:21',3],
 ['Mulheres da Bíblia','Que mulher traiu Sansão cortando seus cabelos?','Dalila',['Jezabel','Jael','Raabe'],'Juízes 16:19',1],
 ['Mulheres da Bíblia','Que mulher moabita seguiu a sogra até Belém?','Rute',['Orfa','Ester','Débora'],'Rute 1:16',1],
 ['Mulheres da Bíblia','Qual era o nome da sogra de Rute?','Noemi',['Orfa','Ana','Rebeca'],'Rute 1:2',2],
 ['Mulheres da Bíblia','Com quem Rute se casou em Belém?','Boaz',['Elimeleque','Obede','Jessé'],'Rute 4:13',2],
 ['Mulheres da Bíblia','Que mulher orou no templo pedindo um filho e deu à luz Samuel?','Ana',['Penina','Sara','Rebeca'],'1 Samuel 1:10-20',2],
 ['Mulheres da Bíblia','Que esposa de Davi o ajudou a fugir de Saul por uma janela?','Mical',['Abigail','Bate-Seba','Ainoã'],'1 Samuel 19:11-12',3],
 ['Mulheres da Bíblia','Que mulher prudente acalmou Davi e depois se casou com ele?','Abigail',['Mical','Bate-Seba','Ainoã'],'1 Samuel 25:32-42',3],
 ['Mulheres da Bíblia','Quem era a esposa de Urias, com quem Davi pecou?','Bate-Seba',['Abigail','Mical','Tamar'],'2 Samuel 11:3',2],
 ['Mulheres da Bíblia','Quem hospedou e alimentou o profeta Elias durante a seca?','A viúva de Sarepta',['A sunamita','Jezabel','A rainha de Sabá'],'1 Reis 17:9-10',2],
 ['Mulheres da Bíblia','Que mulher construiu um quartinho para hospedar o profeta Eliseu?','A sunamita',['A viúva de Sarepta','Débora','Hulda'],'2 Reis 4:8-10',3],
 ['Mulheres da Bíblia','Que profetisa foi consultada no tempo do rei Josias?','Hulda',['Débora','Miriã','Ana'],'2 Reis 22:14',3],
 ['Mulheres da Bíblia','Que jovem judia se tornou rainha da Pérsia e salvou seu povo?','Ester',['Rute','Vasti','Débora'],'Ester 4:16',1],
 ['Mulheres da Bíblia','Quem criou Ester como filha?','Seu primo Mardoqueu',['Seu tio Hamã','Seu pai Esdras','Seu irmão Neemias'],'Ester 2:7',2],
 ['Mulheres da Bíblia','Com que rei Ester se casou?','Assuero',['Dario','Ciro','Nabucodonosor'],'Ester 2:17',3],
 ['Mulheres da Bíblia','Que rainha se recusou a comparecer ao banquete do rei Assuero?','Vasti',['Ester','Jezabel','Atalia'],'Ester 1:12',3],
 ['Mulheres da Bíblia','Quem foi a mãe de Jesus?','Maria',['Isabel','Marta','Ana'],'Lucas 1:30-31',1],
 ['Mulheres da Bíblia','Quem era a prima de Maria e mãe de João Batista?','Isabel',['Ana','Marta','Salomé'],'Lucas 1:36',2],
 ['Mulheres da Bíblia','Que profetisa idosa reconheceu Jesus no templo?','Ana',['Isabel','Débora','Hulda'],'Lucas 2:36-38',3],
 ['Mulheres da Bíblia','Quais eram as irmãs de Lázaro que moravam em Betânia?','Marta e Maria',['Ana e Isabel','Raquel e Lia','Débora e Jael'],'Lucas 10:38-39',1],
 ['Mulheres da Bíblia','Qual das irmãs sentou-se aos pés de Jesus para ouvi-lo?','Maria',['Marta','Salomé','Joana'],'Lucas 10:39',2],
 ['Mulheres da Bíblia','Que mulher Jesus encontrou junto ao poço de Jacó?','Uma mulher samaritana',['Uma cananeia','A viúva de Naim','Uma sunamita'],'João 4:7',1],
 ['Mulheres da Bíblia','Quem foi a primeira a ver Jesus ressuscitado, segundo João?','Maria Madalena',['Marta','Joana','Salomé'],'João 20:14-16',2],
 ['Mulheres da Bíblia','Quem ungiu os pés de Jesus com perfume e os enxugou com os cabelos, em Betânia?','Maria, irmã de Lázaro',['Marta','Maria Madalena','Joana'],'João 12:3',3],
 ['Mulheres da Bíblia','Que discípula de Jope fazia roupas para os pobres e foi ressuscitada por Pedro?','Dorcas (Tabita)',['Lídia','Priscila','Febe'],'Atos 9:36-40',2],
 ['Mulheres da Bíblia','Que vendedora de púrpura de Filipos abriu o coração ao evangelho?','Lídia',['Dorcas','Priscila','Febe'],'Atos 16:14',2],
 ['Mulheres da Bíblia','Que casal, fabricante de tendas, recebeu Paulo em Corinto?','Áquila e Priscila',['Ananias e Safira','Ana e Simeão','Marta e Lázaro'],'Atos 18:2-3',2],
 ['Mulheres da Bíblia','Que mulher mentiu ao Espírito Santo junto com o marido Ananias?','Safira',['Lídia','Dorcas','Priscila'],'Atos 5:1-10',2],
 ['Mulheres da Bíblia','Quais eram a mãe e a avó de Timóteo?','Eunice e Loide',['Marta e Maria','Lídia e Dorcas','Priscila e Febe'],'2 Timóteo 1:5',3],
 ['Mulheres da Bíblia','Que mulher da Bíblia foi transformada em estátua de sal?','A mulher de Ló',['A mulher de Potifar','A mulher de Noé','A mulher de Jó'],'Gênesis 19:26',1],
 ['Apocalipse e Profecia','Quem escreveu o livro de Apocalipse?','O apóstolo João',['Paulo','Pedro','Judas'],'Apocalipse 1:1-4',1],
 ['Apocalipse e Profecia','Em que dia João estava em espírito quando teve a visão?','No dia do Senhor',['Na Páscoa','No Pentecostes','Na lua nova'],'Apocalipse 1:10',3],
 ['Apocalipse e Profecia','Quantas igrejas recebem cartas em Apocalipse 2 e 3?','Sete',['Doze','Cinco','Dez'],'Apocalipse 1:11',1],
 ['Apocalipse e Profecia','Qual das sete igrejas foi descrita como morna?','Laodiceia',['Esmirna','Sardes','Filadélfia'],'Apocalipse 3:14-16',2],
 ['Apocalipse e Profecia','Qual igreja recebeu uma porta aberta que ninguém pode fechar?','Filadélfia',['Éfeso','Tiatira','Pérgamo'],'Apocalipse 3:7-8',3],
 ['Apocalipse e Profecia','Qual igreja abandonou o primeiro amor?','Éfeso',['Esmirna','Sardes','Tiatira'],'Apocalipse 2:4',2],
 ['Apocalipse e Profecia','Qual igreja foi chamada a ser fiel até a morte para receber a coroa da vida?','Esmirna',['Pérgamo','Tiatira','Sardes'],'Apocalipse 2:10',3],
 ['Apocalipse e Profecia','Qual igreja tinha nome de que vivia, mas estava morta?','Sardes',['Laodiceia','Éfeso','Tiatira'],'Apocalipse 3:1',3],
 ['Apocalipse e Profecia','Quantos selos tinha o livro que o Cordeiro abriu?','Sete',['Doze','Três','Dez'],'Apocalipse 5:1',2],
 ['Apocalipse e Profecia','Quem foi achado digno de abrir o livro selado?','O Cordeiro',['Um anjo forte','Moisés','O profeta João'],'Apocalipse 5:5-9',2],
 ['Apocalipse e Profecia','Qual é a cor do cavalo do primeiro selo?','Branco',['Vermelho','Preto','Azul'],'Apocalipse 6:2',3],
 ['Apocalipse e Profecia','Quantos anjos receberam trombetas em Apocalipse 8?','Sete',['Doze','Três','Dez'],'Apocalipse 8:2',2],
 ['Apocalipse e Profecia','Quantos foram selados entre as tribos de Israel?','144.000',['12.000','1.440','14.400'],'Apocalipse 7:4',2],
 ['Apocalipse e Profecia','Quantos foram selados de cada tribo?','12.000',['1.000','10.000','14.000'],'Apocalipse 7:5-8',3],
 ['Apocalipse e Profecia','Em que lugar os reis se reúnem para a batalha do grande dia?','Armagedom',['Sinai','Sião','Babel'],'Apocalipse 16:16',3],
 ['Apocalipse e Profecia','Por quanto tempo os salvos reinarão com Cristo?','Mil anos',['Cem anos','Sete anos','Quarenta anos'],'Apocalipse 20:4',2],
 ['Apocalipse e Profecia','Qual é o número da besta?','666',['777','444','999'],'Apocalipse 13:18',2],
 ['Apocalipse e Profecia','Que cidade João viu descer do céu, vinda de Deus?','A Nova Jerusalém',['A Nova Sodoma','A Nova Belém','A Nova Roma'],'Apocalipse 21:2',1],
 ['Apocalipse e Profecia','Segundo Apocalipse 21:4, Deus enxugará toda...','lágrima',['ferida','sede','mágoa'],'Apocalipse 21:4',1],
 ['Apocalipse e Profecia','Quantas portas tem a Nova Jerusalém?','Doze',['Sete','Quatro','Dez'],'Apocalipse 21:12',2],
 ['Apocalipse e Profecia','De que é feita cada uma das portas da cidade?','De uma só pérola',['De ouro puro','De jaspe','De cedro'],'Apocalipse 21:21',3],
 ['Apocalipse e Profecia','Quantos frutos dá a árvore da vida, segundo Apocalipse 22:2?','Doze',['Sete','Dez','Quatro'],'Apocalipse 22:2',3],
 ['Apocalipse e Profecia','Quem disse: Eu sou o Alfa e o Ômega?','Jesus',['Miguel','Gabriel','João'],'Apocalipse 22:13',1],
 ['Apocalipse e Profecia','Em Apocalipse 12:9, o diabo é chamado o grande...','dragão',['leão','lobo','touro'],'Apocalipse 12:9',2],
 ['Apocalipse e Profecia','Que anjo lutou contra o dragão no céu?','Miguel',['Gabriel','Rafael','Uriel'],'Apocalipse 12:7',2],
 ['Apocalipse e Profecia','Na mensagem do primeiro anjo de Apocalipse 14, o que se deve dar a Deus?','Glória',['Ofertas','Sacrifícios','Terras'],'Apocalipse 14:7',2],
 ['Apocalipse e Profecia','Qual é o anúncio do segundo anjo de Apocalipse 14?','Caiu Babilônia',['Caiu Jerusalém','Caiu Nínive','Caiu Sodoma'],'Apocalipse 14:8',2],
 ['Apocalipse e Profecia','O terceiro anjo de Apocalipse 14 adverte contra receber o quê?','A marca da besta',['O selo de Deus','O dízimo','O batismo'],'Apocalipse 14:9-10',2],
 ['Apocalipse e Profecia','Quem, segundo Apocalipse 14:12, guarda os mandamentos de Deus e a fé de Jesus?','Os santos',['Os profetas','Os anciãos','Os anjos'],'Apocalipse 14:12',3],
 ['Apocalipse e Profecia','Na estátua do sonho de Nabucodonosor, de que material era a cabeça?','Ouro',['Prata','Bronze','Ferro'],'Daniel 2:32,38',1],
 ['Apocalipse e Profecia','Que reino era representado pela cabeça de ouro?','Babilônia',['Medo-Pérsia','Grécia','Roma'],'Daniel 2:38',2],
 ['Apocalipse e Profecia','Que reino era representado pelo peito e braços de prata?','Medo-Pérsia',['Babilônia','Grécia','Roma'],'Daniel 2:39',2],
 ['Apocalipse e Profecia','Que reino era representado pelo ventre e coxas de bronze?','Grécia',['Babilônia','Medo-Pérsia','Roma'],'Daniel 2:39',2],
 ['Apocalipse e Profecia','O que destruiu a estátua no sonho de Nabucodonosor?','Uma pedra cortada sem mãos',['Um terremoto','Um raio','Uma inundação'],'Daniel 2:34-35',1],
 ['Apocalipse e Profecia','Quantas bestas Daniel viu subir do mar em Daniel 7?','Quatro',['Três','Sete','Dez'],'Daniel 7:3',2],
 ['Apocalipse e Profecia','Com que animal se parecia a primeira besta de Daniel 7?','Com um leão',['Com um urso','Com um leopardo','Com um lobo'],'Daniel 7:4',2],
 ['Apocalipse e Profecia','Quantas tardes e manhãs aparecem em Daniel 8:14 até o santuário ser purificado?','2.300',['1.260','1.290','1.335'],'Daniel 8:14',3],
 ['Apocalipse e Profecia','Que anjo explicou a visão a Daniel no capítulo 8?','Gabriel',['Miguel','Rafael','Uriel'],'Daniel 8:16',2],
 ['Apocalipse e Profecia','Segundo Mateus 24:14, o evangelho será pregado em todo o quê?','Mundo',['Templo','Egito','Israel'],'Mateus 24:14',2],
 ['Apocalipse e Profecia','Quem sabe o dia e a hora da volta de Jesus, segundo Mateus 24:36?','Somente o Pai',['Os anjos','Os profetas','O Filho'],'Mateus 24:36',2],
 ['Apocalipse e Profecia','Como Jesus voltará, segundo Atos 1:11?','Da mesma forma como subiu',['Em segredo','Como um bebê','No deserto'],'Atos 1:11',2],
 ['Apocalipse e Profecia','Quem ressuscitará primeiro na volta de Jesus, segundo 1 Tessalonicenses 4:16?','Os mortos em Cristo',['Os anjos','Os vivos','Os profetas'],'1 Tessalonicenses 4:16',2],
 ['Apocalipse e Profecia','O que soará na volta de Jesus, segundo 1 Tessalonicenses 4:16?','A trombeta de Deus',['Os sinos do templo','Um trovão','Um cântico'],'1 Tessalonicenses 4:16',2],
 ['Mandamentos e Sábado','Quantos mandamentos Deus deu a Moisés no Sinai?','Dez',['Sete','Doze','Cinco'],'Êxodo 20:1-17',1],
 ['Mandamentos e Sábado','Em que dia Deus descansou da criação?','No sétimo dia',['No sexto dia','No primeiro dia','No quarto dia'],'Gênesis 2:2',1],
 ['Mandamentos e Sábado','Qual é o quarto mandamento?','Lembra-te do dia de sábado',['Honra teu pai e tua mãe','Não matarás','Não furtarás'],'Êxodo 20:8',1],
 ['Mandamentos e Sábado','Qual é o primeiro mandamento?','Não ter outros deuses',['Não matarás','Honra teu pai e tua mãe','Lembra-te do sábado'],'Êxodo 20:3',1],
 ['Mandamentos e Sábado','Qual é o quinto mandamento?','Honra teu pai e tua mãe',['Não matarás','Não furtarás','Não adulterarás'],'Êxodo 20:12',2],
 ['Mandamentos e Sábado','Qual é o sexto mandamento?','Não matarás',['Não adulterarás','Não furtarás','Honra teu pai e tua mãe'],'Êxodo 20:13',2],
 ['Mandamentos e Sábado','Qual é o oitavo mandamento?','Não furtarás',['Não matarás','Não cobiçarás','Não adulterarás'],'Êxodo 20:15',2],
 ['Mandamentos e Sábado','Qual é o décimo mandamento?','Não cobiçarás',['Não furtarás','Não matarás','Não adulterarás'],'Êxodo 20:17',3],
 ['Mandamentos e Sábado','Em que foram escritos os Dez Mandamentos?','Em tábuas de pedra',['Em rolos de couro','Em placas de bronze','Em folhas de papiro'],'Êxodo 31:18',1],
 ['Mandamentos e Sábado','Quem escreveu as primeiras tábuas da lei?','Deus, com o seu dedo',['Moisés','Arão','Josué'],'Êxodo 31:18',2],
 ['Mandamentos e Sábado','Quantas tábuas de pedra Moisés recebeu?','Duas',['Quatro','Dez','Uma'],'Êxodo 31:18',1],
 ['Mandamentos e Sábado','Onde as tábuas da lei foram guardadas?','Na arca da aliança',['No altar','No candelabro','Na mesa dos pães'],'Deuteronômio 10:5',1],
 ['Mandamentos e Sábado','Como Deus descreveu o sétimo dia em Gênesis 2:3?','Abençoou-o e santificou-o',['Criou o homem nele','Plantou o jardim nele','Fez os animais nele'],'Gênesis 2:3',2],
 ['Mandamentos e Sábado','Quantos dias temos para trabalhar, segundo o quarto mandamento?','Seis dias',['Cinco dias','Sete dias','Três dias'],'Êxodo 20:9',1],
 ['Mandamentos e Sábado','Complete: Lembra-te do dia de sábado para o...','santificar',['iluminar','enfeitar','comemorar'],'Êxodo 20:8',2],
 ['Mandamentos e Sábado','O que Israel colhia em dobro na sexta-feira, no deserto?','Maná',['Codornizes','Figos','Água'],'Êxodo 16:22-26',2],
 ['Mandamentos e Sábado','Em que dia o maná não caía do céu?','No sábado',['No domingo','Na segunda-feira','Na sexta-feira'],'Êxodo 16:26',1],
 ['Mandamentos e Sábado','Segundo Jesus, para quem foi feito o sábado?','Para o homem',['Para os anjos','Para os sacerdotes','Para Moisés'],'Marcos 2:27',2],
 ['Mandamentos e Sábado','Jesus disse ser Senhor de quê?','Do sábado',['Do templo','Do deserto','Da colheita'],'Mateus 12:8',2],
 ['Mandamentos e Sábado','Qual era o costume de Jesus no dia de sábado?','Ir à sinagoga',['Viajar','Pescar','Jejuar no deserto'],'Lucas 4:16',1],
 ['Mandamentos e Sábado','Em que dia as mulheres descansaram antes de ir ao túmulo de Jesus?','No sábado',['Na sexta-feira','No domingo','Na quinta-feira'],'Lucas 23:56',2],
 ['Mandamentos e Sábado','Segundo Isaías 58:13, como devemos chamar o sábado?','Deleitoso',['Penoso','Temível','Comum'],'Isaías 58:13',3],
 ['Mandamentos e Sábado','Em Êxodo 31:13, o que Deus chamou de sinal entre ele e Israel?','Os seus sábados',['A Páscoa','O arco-íris','O dízimo'],'Êxodo 31:13',3],
 ['Mandamentos e Sábado','Quem mais devia descansar no sábado, além de você?','Servos e estrangeiros',['Só os filhos','Apenas os sacerdotes','Somente os idosos'],'Êxodo 20:10',3],
 ['Mandamentos e Sábado','Como Deus se manifestou no monte Sinai ao dar a lei?','Trovões e fumaça',['Vento suave','Silêncio total','Chuva calma'],'Êxodo 19:16-18',3],
 ['Mandamentos e Sábado','Qual é o primeiro mandamento com promessa?','Honrar pai e mãe',['Guardar o sábado','Não matar','Não furtar'],'Efésios 6:2',3],
 ['Mandamentos e Sábado','Segundo 1 João 5:3, o amor a Deus consiste em quê?','Guardar os seus mandamentos',['Oferecer sacrifícios','Jejuar sempre','Construir templos'],'1 João 5:3',2],
 ['Mandamentos e Sábado','Complete: Se me amais, guardai os meus...','mandamentos',['sacrifícios','altares','cânticos'],'João 14:15',1],
 ['Mandamentos e Sábado','Segundo 1 João 3:4, o que é o pecado?','A transgressão da lei',['O esquecimento','A fraqueza','A doença'],'1 João 3:4',2],
 ['Mandamentos e Sábado','Que porção da renda pertence ao Senhor, segundo Levítico 27:30?','A décima parte',['A quinta parte','A terça parte','A metade'],'Levítico 27:30',1],
 ['Mandamentos e Sábado','Segundo Malaquias 3:10, o que devemos trazer à casa do tesouro?','Todos os dízimos',['Metade da renda','Só as primícias','Apenas animais'],'Malaquias 3:10',2],
 ['Mandamentos e Sábado','Quem deu o dízimo a Melquisedeque?','Abraão',['Isaque','Jacó','Ló'],'Gênesis 14:20',3],
 ['Mandamentos e Sábado','Em que livro os Dez Mandamentos são repetidos por Moisés antes da entrada em Canaã?','Deuteronômio',['Números','Levítico','Gênesis'],'Deuteronômio 5',3],
 ['Mandamentos e Sábado','Hebreus 4:9 diz que resta um repouso para o povo de quem?','De Deus',['De Israel','De Judá','De Moisés'],'Hebreus 4:9',3],
 ['Mandamentos e Sábado','Segundo Tiago 2:10, quem guarda toda a lei, mas tropeça em um ponto, é...','Culpado de todos',['Justo','Perdoado','Digno de louvor'],'Tiago 2:10',3],
 ['Mandamentos e Sábado','O que Deus disse sobre o que fez nos seis dias e no sétimo, em Êxodo 20:11?','Fez céus e terra; descansou',['Fez apenas a terra','Plantou o Éden e descansou','Fez o homem e descansou'],'Êxodo 20:11',2],
 ['Apóstolos e Igreja Primitiva','Quem foi escolhido para substituir Judas entre os doze?','Matias',['Barnabé','Silas','Estêvão'],'Atos 1:26',2],
 ['Apóstolos e Igreja Primitiva','Em que festa o Espírito Santo desceu sobre os discípulos?','Pentecostes',['Páscoa','Tabernáculos','Purim'],'Atos 2:1',1],
 ['Apóstolos e Igreja Primitiva','Como o Espírito Santo apareceu sobre os discípulos?','Como línguas de fogo',['Como uma pomba','Como uma nuvem','Como um arco-íris'],'Atos 2:3',1],
 ['Apóstolos e Igreja Primitiva','Quem pregou o sermão no dia de Pentecostes?','Pedro',['João','Tiago','Paulo'],'Atos 2:14',1],
 ['Apóstolos e Igreja Primitiva','Quantas pessoas foram acrescentadas à igreja no Pentecostes?','Cerca de três mil',['Cem','Quinhentas','Doze mil'],'Atos 2:41',2],
 ['Apóstolos e Igreja Primitiva','Quem foi curado por Pedro e João na porta Formosa?','Um coxo de nascença',['Um cego','Um leproso','Um endemoninhado'],'Atos 3:2-8',2],
 ['Apóstolos e Igreja Primitiva','Quem foi o primeiro mártir cristão?','Estêvão',['Tiago','Paulo','Filipe'],'Atos 7:59-60',1],
 ['Apóstolos e Igreja Primitiva','Que jovem guardou as vestes dos que apedrejaram Estêvão?','Saulo',['Barnabé','Filipe','Timóteo'],'Atos 7:58',2],
 ['Apóstolos e Igreja Primitiva','Que nome tinha Paulo antes da conversão?','Saulo',['Silas','Simão','Sadoque'],'Atos 9:1',1],
 ['Apóstolos e Igreja Primitiva','Quem orou por Saulo e o curou da cegueira em Damasco?','Ananias',['Barnabé','Filipe','Silas'],'Atos 9:17-18',2],
 ['Apóstolos e Igreja Primitiva','Quem levou Saulo aos apóstolos em Jerusalém?','Barnabé',['Silas','Timóteo','Marcos'],'Atos 9:27',3],
 ['Apóstolos e Igreja Primitiva','Que centurião de Cesareia foi o primeiro gentio a receber o evangelho?','Cornélio',['Félix','Festo','Agripa'],'Atos 10:1-2',2],
 ['Apóstolos e Igreja Primitiva','O que Pedro viu em visão antes de ir à casa de Cornélio?','Um lençol com animais',['Uma escada','Uma sarça','Um rio de fogo'],'Atos 10:11-12',2],
 ['Apóstolos e Igreja Primitiva','Qual apóstolo foi libertado da prisão por um anjo em Atos 12?','Pedro',['Paulo','João','Tiago'],'Atos 12:7',2],
 ['Apóstolos e Igreja Primitiva','Qual apóstolo foi morto à espada por Herodes?','Tiago',['Pedro','André','Filipe'],'Atos 12:2',3],
 ['Apóstolos e Igreja Primitiva','Quem acompanhou Paulo na primeira viagem missionária?','Barnabé',['Silas','Timóteo','Tito'],'Atos 13:2-3',2],
 ['Apóstolos e Igreja Primitiva','Em Listra, como o povo chamou Paulo e Barnabé depois de um milagre?','De deuses',['De reis','De profetas','De anjos'],'Atos 14:11-12',3],
 ['Apóstolos e Igreja Primitiva','Quem Paulo escolheu como companheiro na segunda viagem missionária?','Silas',['Barnabé','Timóteo','Lucas'],'Atos 15:40',3],
 ['Apóstolos e Igreja Primitiva','O que Paulo e Silas faziam à meia-noite na prisão de Filipos?','Oravam e cantavam hinos',['Dormiam','Escreviam cartas','Discutiam'],'Atos 16:25',1],
 ['Apóstolos e Igreja Primitiva','O que aconteceu à meia-noite na prisão de Filipos?','Um terremoto abriu as portas',['Um anjo apareceu','Um guarda abriu as celas','Uma luz cegou os presos'],'Atos 16:26',2],
 ['Apóstolos e Igreja Primitiva','Que pergunta importante o carcereiro de Filipos fez a Paulo e Silas?','Como ser salvo?',['Quem são vocês?','Onde está Deus?','Por que oram?'],'Atos 16:30',2],
 ['Apóstolos e Igreja Primitiva','Que inscrição Paulo viu num altar de Atenas?','Ao Deus desconhecido',['A Zeus','A Diana','A Apolo'],'Atos 17:23',3],
 ['Apóstolos e Igreja Primitiva','Que jovem caiu de uma janela durante o sermão longo de Paulo e foi ressuscitado?','Êutico',['Tíquico','Timóteo','Tito'],'Atos 20:9-12',3],
 ['Apóstolos e Igreja Primitiva','Que rei disse a Paulo: Por pouco me persuades a me fazer cristão?','Agripa',['Herodes','Félix','Festo'],'Atos 26:28',3],
 ['Apóstolos e Igreja Primitiva','Que animal mordeu Paulo em Malta?','Uma víbora',['Um escorpião','Uma aranha','Um lobo'],'Atos 28:3',2],
 ['Apóstolos e Igreja Primitiva','Qual era a profissão de Paulo?','Fazedor de tendas',['Pescador','Carpinteiro','Oleiro'],'Atos 18:3',2],
 ['Apóstolos e Igreja Primitiva','Com quem Paulo aprendeu a lei em Jerusalém?','Gamaliel',['Nicodemos','Caifás','Anás'],'Atos 22:3',3],
 ['Apóstolos e Igreja Primitiva','Quem escreveu o livro de Atos?','Lucas',['Marcos','Paulo','João'],'Atos 1:1',2],
 ['Apóstolos e Igreja Primitiva','A quem Lucas dirigiu o seu evangelho e o livro de Atos?','Teófilo',['Timóteo','Tito','Filemom'],'Lucas 1:3',3],
 ['Apóstolos e Igreja Primitiva','Que apóstolo também era chamado Dídimo?','Tomé',['Filipe','Bartolomeu','Mateus'],'João 11:16',3],
 ['Apóstolos e Igreja Primitiva','Que apóstolo era cobrador de impostos antes de seguir Jesus?','Mateus',['Pedro','Tiago','André'],'Mateus 10:3',1],
 ['Apóstolos e Igreja Primitiva','Quais irmãos pescadores Jesus chamou primeiro, junto ao mar da Galileia?','Pedro e André',['Tiago e João','Filipe e Natanael','Tomé e Mateus'],'Mateus 4:18-19',2],
 ['Apóstolos e Igreja Primitiva','Quem eram os filhos de Zebedeu?','Tiago e João',['Pedro e André','Filipe e Bartolomeu','Mateus e Tomé'],'Mateus 4:21',2],
 ['Apóstolos e Igreja Primitiva','A quem Jesus disse: Sobre esta pedra edificarei a minha igreja?','Pedro',['Tomé','Judas','Filipe'],'Mateus 16:18',2],
 ['Apóstolos e Igreja Primitiva','Quem pregou o evangelho ao eunuco etíope?','Filipe',['Pedro','Estêvão','Barnabé'],'Atos 8:35',2],
 ['Apóstolos e Igreja Primitiva','Que livro do Antigo Testamento o eunuco etíope lia na carruagem?','Isaías',['Jeremias','Daniel','Salmos'],'Atos 8:28',2],
 ['Apóstolos e Igreja Primitiva','Que dois irmãos Jesus chamou de Boanerges, filhos do trovão?','Tiago e João',['Pedro e André','Filipe e Natanael','Mateus e Tomé'],'Marcos 3:17',3],
 ['Apóstolos e Igreja Primitiva','Quantos diáconos foram escolhidos em Atos 6 para servir às mesas?','Sete',['Doze','Três','Dez'],'Atos 6:3-5',2],
 ['Apóstolos e Igreja Primitiva','Quem, entre os diáconos de Atos 6, era cheio de fé e do Espírito Santo e foi apedrejado?','Estêvão',['Filipe','Prócoro','Nicanor'],'Atos 6:5; 7:59',3],
];
