(()=>{
const URL='https://gtsaaixuampeaivugxdm.supabase.co',KEY='sb_publishable_0nIK7568ulLb9JN0ctyiug_wHWDV7Qf';
const H={'apikey':KEY,'Authorization':'Bearer '+KEY,'Content-Type':'application/json','Prefer':'return=representation'};
const Q=[
['Quem construiu a arca?',['Noé','Abraão','Moisés','Davi'],0],['Quem derrotou Golias?',['Samuel','Davi','Saul','Jônatas'],1],['Quem foi lançado na cova dos leões?',['Daniel','José','Paulo','Pedro'],0],['Quantos discípulos Jesus escolheu?',['7','10','12','14'],2],['Quem recebeu os Dez Mandamentos?',['Josué','Moisés','Arão','Elias'],1],['Qual foi o primeiro livro da Bíblia?',['Êxodo','Salmos','Gênesis','Mateus'],2],['Quem era a mãe de Jesus?',['Marta','Maria','Isabel','Rute'],1],['Em qual cidade Jesus nasceu?',['Jerusalém','Nazaré','Belém','Jericó'],2],['Quem batizou Jesus?',['Pedro','João Batista','Tiago','André'],1],['Quem traiu Jesus?',['Judas Iscariotes','Tomé','Mateus','Filipe'],0],
['Quem interpretou sonhos no Egito?',['José','Isaque','Jacó','Esaú'],0],['Quem abriu o mar pela direção de Deus?',['Moisés','Josué','Davi','Sansão'],0],['Quem foi engolido por um grande peixe?',['Jonas','Joel','Amós','Naum'],0],['Quem tinha força extraordinária?',['Sansão','Salomão','Samuel','Saul'],0],['Quem pediu sabedoria a Deus?',['Davi','Salomão','Elias','Daniel'],1],['Quem foi o primeiro homem?',['Adão','Caim','Abel','Noé'],0],['Quem foi a primeira mulher?',['Sara','Eva','Rebeca','Raquel'],1],['Quem construiu o templo em Jerusalém?',['Davi','Salomão','Saul','Josias'],1],['Quem sucedeu Moisés?',['Calebe','Josué','Arão','Gideão'],1],['Qual livro contém muitos cânticos e orações?',['Provérbios','Salmos','Atos','Romanos'],1],
['Quem subiu ao céu num redemoinho?',['Eliseu','Elias','Isaías','Jeremias'],1],['Quem negou Jesus três vezes?',['Pedro','João','Tomé','Judas'],0],['Quem era cobrador de impostos antes de seguir Jesus?',['Mateus','Tiago','André','Bartolomeu'],0],['Qual apóstolo ficou conhecido por duvidar da ressurreição?',['Tomé','Pedro','João','Paulo'],0],['Quem escreveu muitas cartas do Novo Testamento?',['Paulo','Moisés','Davi','Lucas'],0],['Qual é o último livro da Bíblia?',['Judas','Hebreus','Apocalipse','Atos'],2],['Quem recebeu a promessa de ser pai de muitas nações?',['Abraão','Ló','Isaque','Jacó'],0],['Quem sonhou com uma escada que chegava ao céu?',['José','Jacó','Daniel','Samuel'],1],['Quem foi vendido pelos próprios irmãos?',['José','Benjamim','Davi','Moisés'],0],['Quem encontrou Moisés bebê no rio?',['Filha de Faraó','Miriã','Sara','Débora'],0],
['Qual alimento caiu do céu no deserto?',['Maná','Uvas','Peixes','Figos'],0],['Quem liderou a conquista de Jericó?',['Josué','Moisés','Gideão','Samuel'],0],['Quem foi uma juíza de Israel?',['Rute','Débora','Ester','Miriã'],1],['Quem se tornou rainha e ajudou a salvar seu povo?',['Ester','Rute','Raquel','Ana'],0],['Quem era sogra de Rute?',['Noemi','Sara','Rebeca','Marta'],0],['Quem ungiu Davi como rei?',['Samuel','Natã','Elias','Eliseu'],0],['Quem enfrentou os profetas de Baal no Carmelo?',['Elias','Eliseu','Isaías','Jeremias'],0],['Quem foi discípulo e sucessor de Elias?',['Eliseu','Samuel','Josué','Amós'],0],['Quem foi lançado numa fornalha com dois amigos?',['Daniel','Sadraque','Neemias','Esdras'],1],['Qual profeta viu um vale de ossos secos?',['Ezequiel','Isaías','Jeremias','Oséias'],0],
['Quem reconstruiu os muros de Jerusalém?',['Neemias','Esdras','Zorobabel','Josias'],0],['Quem anunciou a Maria o nascimento de Jesus?',['Gabriel','Miguel','Pedro','João'],0],['Onde Jesus transformou água em vinho?',['Caná','Belém','Jericó','Betânia'],0],['Quem subiu numa árvore para ver Jesus?',['Zaqueu','Nicodemos','Bartimeu','Lázaro'],0],['Quem Jesus ressuscitou após quatro dias?',['Lázaro','Estêvão','Jairo','Barnabé'],0],['Quem ajudou Jesus a carregar a cruz?',['Simão de Cirene','Pedro','João','José'],0],['Quem pediu o corpo de Jesus a Pilatos?',['José de Arimateia','Nicodemos','Pedro','Tomé'],0],['Quem foi o primeiro mártir cristão citado em Atos?',['Estêvão','Paulo','Tiago','Barnabé'],0],['Quem teve uma visão no caminho de Damasco?',['Saulo','Pedro','Filipe','Silas'],0],['Quem acompanhou Paulo e Silas na prisão em Filipos?',['Eles estavam juntos','Barnabé','Pedro','Timóteo'],0],
['Qual discípulo era irmão de Pedro?',['André','João','Tiago','Filipe'],0],['Quem escreveu o livro de Atos?',['Lucas','Paulo','Pedro','Marcos'],0],['Em qual rio Jesus foi batizado?',['Jordão','Nilo','Eufrates','Tigre'],0],['Quantos dias Jesus jejuou no deserto?',['7','21','30','40'],3],['Qual discípulo caminhou sobre as águas em direção a Jesus?',['Pedro','João','Tiago','André'],0],['Quem preparou o caminho para Jesus pregando no deserto?',['João Batista','Zacarias','Simeão','José'],0],['Qual cidade teve seus muros derrubados após Israel marchar ao redor?',['Jericó','Samaria','Belém','Hebrom'],0],['Quem era irmão de Moisés?',['Arão','Josué','Calebe','Jetro'],0],['Quem era irmã de Moisés?',['Miriã','Débora','Ana','Noemi'],0],['Qual rei escreveu muitos provérbios?',['Salomão','Saul','Acabe','Ezequias'],0]
];
let state={room:null,player:null,host:false,timer:null,clock:null,questionSeconds:20};
const GameSound=(()=>{let ctx=null,master=.55,enabled=localStorage.getItem('iasd_game_sound')!=='off';
function C(){if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
function tone(freq=440,d=.08,type='sine',vol=.12,delay=0){if(!enabled)return;const x=C(),o=x.createOscillator(),g=x.createGain(),t=x.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,vol*master),t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(x.destination);o.start(t);o.stop(t+d+.03)}
function noise(d=.18,vol=.06){if(!enabled)return;const x=C(),n=x.createBufferSource(),b=x.createBuffer(1,x.sampleRate*d,x.sampleRate);for(let i=0;i<b.length;i++)b.getChannelData(0)[i]=(Math.random()*2-1)*(1-i/b.length);const g=x.createGain();g.gain.value=vol*master;n.buffer=b;n.connect(g);g.connect(x.destination);n.start()}
const fx={click(){tone(520,.045,'sine',.07)},join(){tone(523,.08,'sine',.08);tone(659,.11,'sine',.08,.07)},start(){[392,523,659,784].forEach((n,i)=>tone(n,.16,'triangle',.1,i*.08))},tick(){tone(880,.045,'square',.055)},urgent(){tone(1050,.07,'square',.09)},sent(){tone(620,.05,'sine',.06);tone(820,.08,'sine',.07,.04)},correct(){tone(523,.09,'triangle',.1);tone(659,.1,'triangle',.11,.07);tone(784,.18,'triangle',.13,.14)},wrong(){tone(220,.11,'sawtooth',.07);tone(165,.18,'sawtooth',.06,.08)},streak(){[660,784,990,1175].forEach((n,i)=>tone(n,.1,'triangle',.1,i*.055))},reveal(){tone(330,.1,'triangle',.07);tone(494,.16,'triangle',.09,.09)},victory(){noise(.35,.045);[523,659,784,1047].forEach((n,i)=>tone(n,.34,'triangle',.13,i*.11));setTimeout(()=>noise(.5,.055),380)},toggle(){enabled=!enabled;localStorage.setItem('iasd_game_sound',enabled?'on':'off');fx.click();return enabled},isOn(){return enabled},volume(v){master=Math.max(0,Math.min(1,Number(v)));localStorage.setItem('iasd_game_volume',master)}};
const saved=Number(localStorage.getItem('iasd_game_volume'));if(Number.isFinite(saved)&&saved>=0&&saved<=1)master=saved;return fx})();
const api=async(path,opt={})=>{const r=await fetch(URL+'/rest/v1/'+path,{...opt,headers:{...H,...(opt.headers||{})}});if(!r.ok)throw Error(await r.text());const t=await r.text();return t?JSON.parse(t):null};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function css(){if(document.getElementById('live-game-css'))return;const s=document.createElement('style');s.id='live-game-css';s.textContent=`
#live-game-launch{position:fixed;right:16px;bottom:92px;z-index:80;border:0;border-radius:999px;padding:12px 16px;background:#17375e;color:white;font-weight:800;box-shadow:0 8px 28px #0003}
.lg-backdrop{position:fixed;inset:0;z-index:9999;background:#07111dd9;backdrop-filter:blur(10px);display:grid;place-items:center;padding:14px}.lg{width:min(720px,100%);max-height:92dvh;overflow:auto;background:#fff;color:#172b45;border-radius:24px;padding:22px;box-shadow:0 25px 80px #0006}.lg h2{margin:0 0 8px;font-size:26px}.lg p{color:#65758a}.lg-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.lg button{border:0;border-radius:14px;padding:14px;font-weight:800;background:#e9eef5;color:#183451}.lg .primary{background:#d6a74e;color:#241a09}.lg input{width:100%;padding:14px;border:1px solid #d7dfeb;border-radius:13px;margin:8px 0}.lg-code{font-size:42px;letter-spacing:.14em;font-weight:900;text-align:center;color:#153d72}.lg-answers{display:grid;grid-template-columns:1fr 1fr;gap:10px}.lg-answers button{min-height:84px;font-size:16px}.lg-player{display:flex;justify-content:space-between;padding:10px 4px;border-bottom:1px solid #edf0f4}.lg-close{float:right;background:#eef2f6!important;padding:8px 11px!important}.lg-rank{font-size:18px;font-weight:800}.lg-badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#edf3fb;font-size:12px}.lg-top{display:flex;justify-content:space-between;align-items:center;gap:10px}.lg-timer{font-size:26px;font-weight:900;color:#b47c1d}.lg-progress{height:7px;background:#edf1f6;border-radius:99px;overflow:hidden;margin:14px 0}.lg-progress>i{display:block;height:100%;background:linear-gradient(90deg,#d5a348,#173e72);transition:width .25s}.lg-hero{text-align:center;padding:16px;border-radius:18px;background:linear-gradient(145deg,#102c50,#1f558b);color:#fff;margin:12px 0}.lg-hero p{color:#dbe8f7}.lg-qr{width:150px;height:150px;border-radius:14px;background:#fff;padding:8px;margin:10px auto;display:block}.lg-pop{animation:lgpop .28s ease}.lg-answers button{transition:transform .15s,box-shadow .15s}.lg-answers button:active{transform:scale(.97)}@keyframes lgpop{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}@media(max-width:520px){.lg-grid,.lg-answers{grid-template-columns:1fr}.lg{padding:17px}.lg-code{font-size:34px}}
`;document.head.appendChild(s)}
function modal(html){css();GameSound.click();let b=document.getElementById('lg-modal');if(!b){b=document.createElement('div');b.id='lg-modal';b.className='lg-backdrop';document.body.appendChild(b);reconnect()}b.innerHTML='<div class="lg lg-pop"><button class="lg-close" onclick="IASDLive.close()">✕</button>'+html+'</div>'}
function home(){modal('<span class="lg-badge">🎮 JOGO COLETIVO</span><h2>Desafio Bíblico Ao Vivo</h2><p>Crie uma sala para o telão ou entre pelo celular usando o código de 6 dígitos.</p><div class="lg-grid"><button class="primary" onclick="IASDLive.create()">Criar sala</button><button onclick="IASDLive.joinForm()">Entrar com código</button></div><p>Banco atual: '+Q.length+' perguntas • sem repetição dentro da partida.</p>')}
async function create(){try{const code=String(Math.floor(100000+Math.random()*900000));const r=await api('live_game_rooms',{method:'POST',body:JSON.stringify({code})});state.room=r[0];state.host=true;localStorage.setItem('iasd_live_host',JSON.stringify({id:state.room.id,token:state.room.host_token,code}));lobby();poll()}catch(e){alert('Não foi possível criar a sala. Tente novamente.')}}
function joinForm(){modal('<h2>Entrar na partida</h2><input id="lg-code" inputmode="numeric" maxlength="6" placeholder="Código da sala"><input id="lg-name" maxlength="30" placeholder="Seu nome"><button class="primary" onclick="IASDLive.join()">Entrar</button>')}
async function join(){const code=(document.getElementById('lg-code').value||'').replace(/\D/g,''),name=(document.getElementById('lg-name').value||'').trim();if(code.length!==6||!name)return alert('Informe o código de 6 dígitos e seu nome.');try{const rooms=await api('live_game_rooms?code=eq.'+code+'&status=neq.finished&select=*');if(!rooms.length)return alert('Sala não encontrada.');state.room=rooms[0];const p=await api('live_game_players',{method:'POST',body:JSON.stringify({room_id:state.room.id,name})});state.player=p[0];state.host=false;GameSound.join();localStorage.setItem('iasd_live_player',JSON.stringify({room:state.room.id,player:state.player.id}));playerView();poll()}catch(e){alert('Não foi possível entrar na sala.')}}
async function players(){return await api('live_game_players?room_id=eq.'+state.room.id+'&order=joined_at.asc&select=*')}
async function lobby(){const ps=await players();const join=location.origin+location.pathname+'?game='+state.room.code;const qr='https://api.qrserver.com/v1/create-qr-code/?size=220x220&data='+encodeURIComponent(join);modal('<span class="lg-badge">SALA ABERTA</span><h2>Entre pelo IASD APP</h2><div class="lg-hero"><div class="lg-code">'+state.room.code+'</div><img class="lg-qr" alt="QR Code para entrar" src="'+qr+'"><p>Escaneie o QR Code ou digite o código no IASD APP</p></div><p style="text-align:center"><b>'+ps.length+'</b> jogador(es) conectado(s)</p><div>'+ps.map(p=>'<div class="lg-player"><b>'+esc(p.name)+'</b><span>pronto</span></div>').join('')+'</div><button class="primary" style="width:100%;margin-top:14px" onclick="IASDLive.start()">COMEÇAR PARTIDA</button>')}
async function start(){GameSound.start();await patchRoom({status:'question',current_question:0,question_started_at:new Date().toISOString()});hostQuestion()}
async function patchRoom(obj){await api('live_game_rooms?id=eq.'+state.room.id,{method:'PATCH',body:JSON.stringify(obj),headers:{'Prefer':'return=minimal'}});Object.assign(state.room,obj)}
function qIndex(){return ((Number(state.room.current_question)||0)*17)%Q.length}
function hostQuestion(){const q=Q[qIndex()];modal('<div class="lg-top"><span class="lg-badge">PERGUNTA '+(state.room.current_question+1)+' / 15</span><span class="lg-timer" id="lg-timer">20</span></div><div class="lg-progress"><i id="lg-progress" style="width:100%"></i></div><h2>'+esc(q[0])+'</h2><div class="lg-answers">'+q[1].map((x,i)=>'<button>'+['🔴','🔵','🟡','🟢'][i]+' '+esc(x)+'</button>').join('')+'</div><p id="lg-count">Respostas chegando…</p><button onclick="IASDLive.reveal()">Mostrar resposta</button>');startClock()}
async function reveal(){GameSound.reveal();clearInterval(state.clock);await patchRoom({status:'reveal'});await applyScores();await scoreboard()}
async function applyScores(){const qi=state.room.current_question,q=Q[qIndex()],start=new Date(state.room.question_started_at).getTime();const [ps,ans]=await Promise.all([players(),api('live_game_answers?room_id=eq.'+state.room.id+'&question_index=eq.'+qi+'&select=*')]);for(const p of ps){const a=ans.find(x=>x.player_id===p.id),ok=a&&a.answer_index===q[2],ms=a?Math.max(0,new Date(a.answered_at).getTime()-start):99999,streak=ok?(Number(p.streak)||0)+1:0,base=ok?Math.max(300,1000-Math.floor(ms/25)):0,bonus=ok?Math.min(300,Math.max(0,streak-1)*50):0,score=(Number(p.score)||0)+base+bonus;await api('live_game_players?id=eq.'+p.id,{method:'PATCH',body:JSON.stringify({score,streak}),headers:{'Prefer':'return=minimal'}})}}
async function scoreboard(){const qi=state.room.current_question,q=Q[qIndex()];const [ps,ans]=await Promise.all([players(),api('live_game_answers?room_id=eq.'+state.room.id+'&question_index=eq.'+qi+'&select=*')]);const start=new Date(state.room.question_started_at).getTime();const ranks=ps.sort((a,b)=>Number(b.score)-Number(a.score));modal('<span class="lg-badge">PLACAR AO VIVO</span><h2>✓ '+esc(q[1][q[2]])+'</h2>'+ranks.slice(0,10).map((p,i)=>'<div class="lg-player lg-rank"><b>'+(i===0?'🥇 ':i===1?'🥈 ':i===2?'🥉 ':'')+(i+1)+'º '+esc(p.name)+'</b><span>'+Number(p.score).toLocaleString('pt-BR')+' pts</span></div>').join('')+'<button class="primary" style="width:100%;margin-top:14px" onclick="IASDLive.next()">Próxima</button>')}
function startClock(){clearInterval(state.clock);let n=20;state.clock=setInterval(()=>{n--;const t=document.getElementById('lg-timer'),p=document.getElementById('lg-progress');if(t)t.textContent=n;if(p)p.style.width=(n/20*100)+'%';if(n<=5&&n>0)GameSound.urgent();else if(n>5&&n<=10)GameSound.tick();if(n<=0){clearInterval(state.clock);if(state.host)reveal()}},1000)}
async function next(){const n=state.room.current_question+1;if(n>=15){await patchRoom({status:'finished'});await finalPodium();return}await patchRoom({status:'question',current_question:n,question_started_at:new Date().toISOString()});hostQuestion()}
async function finalPodium(){GameSound.victory();const ps=(await players()).sort((a,b)=>Number(b.score)-Number(a.score));modal('<div class="lg-hero"><div style="font-size:52px">🏆</div><h2>Partida encerrada!</h2><p>15 rodadas concluídas</p></div>'+ps.slice(0,3).map((p,i)=>'<div class="lg-player lg-rank"><b>'+['🥇','🥈','🥉'][i]+' '+esc(p.name)+'</b><span>'+Number(p.score).toLocaleString('pt-BR')+' pts</span></div>').join('')+'<button class="primary" style="width:100%;margin-top:14px" onclick="IASDLive.home()">Nova partida</button>')}
async function playerView(){if(state.room.status==='lobby')return modal('<h2>Você entrou! 🎉</h2><div class="lg-code">'+state.room.code+'</div><p>Aguardando o apresentador começar…</p>');if(state.room.status==='question'){const q=Q[qIndex()];return modal('<span class="lg-badge">PERGUNTA '+(state.room.current_question+1)+'</span><h2>'+esc(q[0])+'</h2><div class="lg-answers">'+q[1].map((x,i)=>'<button onclick="IASDLive.answer('+i+')">'+['🔴','🔵','🟡','🟢'][i]+' '+esc(x)+'</button>').join('')+'</div>')}if(state.room.status==='reveal'){const q=Q[qIndex()];return modal('<h2>Resposta: '+esc(q[1][q[2]])+'</h2><p>Aguardando a próxima rodada…</p>')}finalPodium()}
async function answer(i){try{GameSound.sent();await api('live_game_answers',{method:'POST',body:JSON.stringify({room_id:state.room.id,player_id:state.player.id,question_index:state.room.current_question,answer_index:i})});modal('<h2>Resposta enviada! ✓</h2><p>Aguardando os demais jogadores…</p>')}catch(e){modal('<h2>Resposta registrada</h2><p>Aguarde a próxima rodada.</p>')}}
async function tick(){if(!state.room)return;try{const r=await api('live_game_rooms?id=eq.'+state.room.id+'&select=*');if(!r.length)return;const old=state.room.status+'|'+state.room.current_question;state.room=r[0];const now=state.room.status+'|'+state.room.current_question;if(state.host){if(state.room.status==='lobby')lobby();else if(old!==now&&state.room.status==='question')hostQuestion();else if(old!==now&&state.room.status==='finished')finalPodium();else if(state.room.status==='question'){const n=(await api('live_game_answers?room_id=eq.'+state.room.id+'&question_index=eq.'+state.room.current_question+'&select=id')).length,el=document.getElementById('lg-count');if(el)el.textContent=n+' resposta(s) recebida(s)'}}else if(old!==now)playerView()}catch(e){}}
function poll(){clearInterval(state.timer);state.timer=setInterval(tick,1500)}
function close(){clearInterval(state.timer);clearInterval(state.clock);state.timer=null;document.getElementById('lg-modal')?.remove()}
function leave(){clearInterval(state.timer);clearInterval(state.clock);if(state.host)localStorage.removeItem('iasd_live_host');else localStorage.removeItem('iasd_live_player');state={room:null,player:null,host:false,timer:null,clock:null,questionSeconds:20};document.getElementById('lg-modal')?.remove()}
function fullscreen(){const el=document.getElementById('lg-modal');if(!document.fullscreenElement)el?.requestFullscreen?.();else document.exitFullscreen?.()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function reconnect(){try{const h=JSON.parse(localStorage.getItem('iasd_live_host')||'null');if(h?.id){const rr=await api('live_game_rooms?id=eq.'+h.id+'&select=*');if(rr.length&&rr[0].status!=='finished'){state.room=rr[0];state.host=true;poll();state.room.status==='lobby'?lobby():hostQuestion();return}}const p=JSON.parse(localStorage.getItem('iasd_live_player')||'null');if(p?.room&&p?.player){const rr=await api('live_game_rooms?id=eq.'+p.room+'&select=*'),pp=await api('live_game_players?id=eq.'+p.player+'&select=*');if(rr.length&&pp.length&&rr[0].status!=='finished'){state.room=rr[0];state.player=pp[0];state.host=false;poll();playerView()}}}catch(e){}}
function install(){css();reconnect()}
window.IASDLive={home,create,joinForm,join,start,reveal,next,answer,close,leave,fullscreen,sound:GameSound};
const gameCode=new URLSearchParams(location.search).get('game');if(gameCode){setTimeout(()=>{home();setTimeout(()=>{joinForm();const i=document.getElementById('lg-code');if(i)i.value=gameCode},50)},250)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();