(function(){'use strict';
const B=()=>window.IASDMagicPathBridge;const IMG={hero:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=88',bible:'https://images.unsplash.com/photo-1504052434569-70ad5836ab65?auto=format&fit=crop&w=900&q=85',mountain:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85',sound:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=85',worship:'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=900&q=85'};
const nav=[['Início','home','⌂'],['Cronogramas','schedule','▣'],['Escalas','scales','♙'],['Sonoplastia','sound','♫'],['Bíblia','bible','▤'],['Lição Sabática','lesson','▤'],['Jogos','games','◇'],['Datas Especiais','dates','☆'],['Palavra em Cena','stage','▣'],['Hinário','hymnal','♫']];
const mods=[['Cronograma','Veja a programação de hoje','schedule',IMG.hero],['Sonoplastia','Acesse o Studio de Projeção','sound',IMG.sound],['Bíblia','Leia e pesquise as Escrituras','bible',IMG.bible],['Lição Sabática','Jovem e Adulto','lesson',IMG.worship],['Jogos','Atividades e interação','games',IMG.mountain],['Escalas','Consulte as escalas mensais','scales',IMG.sound],['Datas Especiais','Eventos e comemorações','dates',IMG.hero],['Hinário','Novo e Antigo','hymnal',IMG.sound]];
const quick=[['Músicas ambientes','sound',IMG.sound],['Provai e Vede','sound',IMG.worship],['Sorteador','sound',IMG.mountain],['Dízimos e Informativos','sound',IMG.sound],['Músicas especiais','sound',IMG.worship],['Bíblia de Projeção','sound',IMG.bible]];
const books=['Gênesis','Êxodo','Levítico','Números','Deuteronômio','Josué','Juízes','Rute','1 Samuel','2 Samuel','1 Reis','2 Reis','1 Crônicas','2 Crônicas','Esdras'];
let root,user=null,schedules=[],projector={connected:false,paired:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function current(){return sessionStorage.getItem('iasd-current-page')||window.IASDRouter?.pageFromLocation?.()||'Painel'}
function keyForPage(p){return {Painel:'home',Cronograma:'schedule',Escalas:'scales',Sonoplastia:'sound','Bíblia':'bible','Lição da Escola Sabatina':'lesson',Jogo:'games','Datas especiais':'dates','Palavra em Cena':'stage','Hinário':'hymnal'}[p]||null}
function go(k){B()?.go(k);setTimeout(render,20)}
function logo(){return '<div class="mp-logo"><span class="mp-mark">◢</span><div><b>IASD <em>APP</em></b><small>SONOPLASTIA E PROJEÇÃO</small></div></div>'}
function bottom(active){return '<nav class="mp-bottom">'+[['Início','home'],['Bíblia','bible'],['Cronograma','schedule'],['Agenda','dates'],['Jograis','stage']].map(x=>'<button class="'+(active===x[1]?'active':'')+'" data-go="'+x[1]+'">'+x[0]+'</button>').join('')+'</nav>'}
function side(active){return '<aside class="mp-side">'+logo()+'<div class="mp-nav">'+nav.map(x=>'<button class="'+(active===x[1]?'active':'')+'" data-go="'+x[1]+'"><b>'+x[2]+'</b><span>'+x[0]+'</span><i>›</i></button>').join('')+'</div><div class="mp-admin"><label>ADMINISTRAÇÃO</label><button data-go="admin">♛ Painel do Fundador</button><button data-go="assets">▣ Acervo do Site</button><button data-go="profile">⚙ Configurações</button></div><div class="mp-promo"><b>IASD <em>APP</em></b><br>Mais que tecnologia,<br>uma ferramenta para<br>o Reino de Deus.</div></aside>'}
function userHtml(){const n=user?.name||'Minha conta',r=user?.role||'',a=user?.avatar;return '<div class="mp-user">'+(a?'<img class="mp-avatar" src="'+esc(a)+'">':'<span class="mp-avatar"></span>')+'<div><b>'+esc(n)+'</b><small>'+esc(r)+'</small></div></div>'}
function top(){return '<header class="mp-top"><button class="mp-round">☰</button><label class="mp-search">⌕<input placeholder="Pesquisar no IASD APP..."></label><div class="mp-topright"><button class="mp-round" data-theme>◐</button><button class="mp-round" data-go="alerts">♢</button>'+userHtml()+'</div></header>'}
function hero(){return '<section class="mp-hero" style="background-image:url('+IMG.hero+')"><div class="mp-herotxt"><span>EVANGELISMO</span><h1>O FIM DO <em>PECADO</em></h1><p>“E vi novo céu e nova terra...”</p><small>Apocalipse 21:1</small><button class="mp-primary" data-go="schedule">▣ &nbsp; Ver programação da semana &nbsp; ›</button></div></section>'}
function modules(){return '<section class="mp-mods">'+mods.map(x=>'<button class="mp-card" data-go="'+x[2]+'"><div class="pic" style="background-image:url('+x[3]+')"></div><div class="ct"><b>'+x[0]+'</b><small>'+x[1]+'</small></div></button>').join('')+'</section>'}
function schedulePanel(){const rows=(schedules||[]).slice(0,5);let ev=rows.length?rows.map((x,i)=>{const t=x.time||x.start_time||x.horario||'';const title=x.title||x.name||x.activity||x.atividade||'Atividade';return '<div class="mp-event"><time>'+esc(t)+'</time><span>'+esc(title)+'</span>'+(i===0?'<b class="mp-now">Agora</b>':'')+'</div>'}).join(''):'<div class="mp-event"><span>Sem programação cadastrada para exibir.</span></div>';return '<article class="mp-panel"><header><h2>▣ &nbsp; Cronograma de hoje</h2></header><div class="mp-timeline">'+ev+'</div><button class="mp-outline" data-go="schedule">Ver cronograma completo ›</button></article>'}
function projectorPanel(){const state=projector.connected?'Conectado':projector.paired?'Pareado':'Desconectado';return '<article class="mp-panel mp-projector"><header><h2>▣ &nbsp; IASD Projetor</h2><span class="mp-status">'+state+'</span></header><div class="mp-projector-body"><div>Estado real do IASD Projetor: <b>'+state+'</b></div><div>'+(projector.monitor||projector.display||'')+'</div></div><button class="mp-primary" data-go="sound">▷ &nbsp; Abrir Studio de Projeção &nbsp; ›</button><div class="mp-actions"><button class="mp-outline" data-projector-refresh>Testar conexão</button><button class="mp-outline" data-go="sound">⚙ Configurações</button></div></article>'}
function passage(){return '<article class="mp-panel mp-passage" style="background-image:linear-gradient(180deg,rgba(4,17,31,.08),rgba(4,17,31,.92)),url('+IMG.mountain+')"><header><h2>▤ &nbsp; Bíblia</h2></header><blockquote>Leia e pesquise as Escrituras.</blockquote><span>Conteúdo bíblico real disponível na Bíblia do IASD APP.</span><div class="mp-actions"><button class="mp-outline" data-go="bible">Abrir Bíblia</button><button class="mp-outline" data-go="bible">Pesquisar</button></div></article>'}
function quickHtml(){return '<section class="mp-quick"><h2>⚡ Acessos rápidos</h2><div class="mp-quickgrid">'+quick.map(x=>'<button class="mp-q" data-go="'+x[1]+'" style="background-image:linear-gradient(0deg,rgba(3,13,24,.9),transparent),url('+x[2]+')">'+x[0]+' ›</button>').join('')+'</div></section>'}
function mobileHead(title){return '<div class="mp-mobilehead" style="display:none">'+(title?'<button class="mp-round" data-go="home">‹</button><h2 style="flex:1">'+title+'</h2>':logo())+'<button class="mp-round" data-theme>◐</button></div>'}
function home(){return side('home')+'<main class="mp-main">'+top()+'<div class="mp-content">'+mobileHead('')+hero()+modules()+'<section class="mp-info">'+schedulePanel()+projectorPanel()+passage()+'</section>'+quickHtml()+'</div>'+bottom('home')+'</main>'}
function sound(){return side('sound')+'<main class="mp-main">'+top()+'<div class="mp-page">'+mobileHead('Sonoplastia')+'<div class="mp-pagehead"><h1>Sonoplastia</h1></div><div class="mp-tabs"><button class="active">Studio</button><button>Projeção</button><button>Ferramentas</button></div><section class="mp-soundbox"><header><h2>▣ IASD Projetor</h2><span class="mp-status">'+(projector.connected?'Conectado':projector.paired?'Pareado':'Desconectado')+'</span></header><div class="mp-projector-body">Status obtido do IASD Projetor local. Nenhum monitor ou conexão é inventado.</div><button class="mp-primary" onclick="window.open('/projection-studio.html','_self')">▷ Abrir Studio de Projeção ›</button><div class="mp-actions"><button class="mp-outline" data-projector-refresh>Testar conexão</button><button class="mp-outline" onclick="window.open('/projection-studio.html#setup','_self')">⚙ Configurações</button></div></section>'+quickHtml()+'</div>'+bottom('')+'</main>'}
function bible(){return side('bible')+'<main class="mp-main">'+top()+'<div class="mp-page">'+mobileHead('Bíblia')+'<div class="mp-pagehead"><h1>Bíblia</h1></div><label class="mp-search" style="width:100%;max-width:none">⌕<input placeholder="Pesquisar na Bíblia..."></label><div class="mp-biblebar"><button class="active">NVI</button><button>NAA</button><button>ARC</button><button>ARA</button><button>KJA</button></div><article class="mp-panel mp-passage mp-passage-mobile" style="height:130px;background-image:linear-gradient(90deg,rgba(8,17,29,.88),rgba(8,17,29,.15)),url('+IMG.bible+')"><b>Leitura e pesquisa bíblica</b><small>Use a Bíblia real do IASD APP para abrir livros, capítulos e versículos.</small></article><h2>Livros</h2><div class="mp-books">'+books.map(x=>'<button data-open-bible>'+x+'</button>').join('')+'</div></div>'+bottom('bible')+'</main>'}
function render(){if(!root)return;const p=current(),k=keyForPage(p);if(!['home','sound','bible'].includes(k)){root.style.display='none';return}root.style.display='block';root.className=B()?.theme()==='light'?'light':'';root.innerHTML='<div class="mp-shell">'+(k==='home'?home():k==='sound'?sound():bible())+'</div>';bind()}
function bind(){root.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>go(el.dataset.go));root.querySelectorAll('[data-theme]').forEach(el=>el.onclick=()=>{const n=root.classList.contains('light')?'dark':'light';B()?.setTheme(n);root.classList.toggle('light',n==='light')});root.querySelectorAll('[data-projector-refresh]').forEach(el=>el.onclick=async()=>{projector=await B().projector();render()});root.querySelectorAll('[data-open-bible]').forEach(el=>el.onclick=()=>go('bible'))}
async function hydrate(){try{[user,schedules,projector]=await Promise.all([B().user(),B().schedules(),B().projector()])}catch(e){console.warn('IASD MagicPath bridge',e)}render()}
function boot(){root=document.createElement('div');root.id='mp-app';document.body.appendChild(root);const original=window.go;if(typeof original==='function')window.go=function(){const r=original.apply(this,arguments);setTimeout(render,0);return r};window.addEventListener('popstate',()=>setTimeout(render,0));window.addEventListener('iasd:theme',render);render();hydrate()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();