const E=require('../games/constellations/engine.js');const a=require('assert');
const board=Array.from({length:64},(_,i)=>[i%32,-1]);const pub={board,lines:[]};
a.deepStrictEqual(E.validCells(pub,5,0),[5,37],'cada carta aparece em 2 posições');
board[5][1]=0;a.deepStrictEqual(E.validCells(pub,5,0),[37],'casa ocupada não é válida');
a.strictEqual(E.validCells(pub,E.WILD,0).length,63,'coringa: qualquer casa livre');
a.deepStrictEqual(E.validCells(pub,E.REMOVE,0),[],'remover: só ficha adversária');
a.deepStrictEqual(E.validCells(pub,E.REMOVE,1),[5],'remover: ficha do outro time');
pub.lines=[{t:0,c:[5,6,7,8,9]}];a.deepStrictEqual(E.validCells(pub,E.REMOVE,1),[],'ficha de sequência pronta é protegida');
a.strictEqual(E.canPlay(pub,[5],0),true);a.strictEqual(E.info(E.WILD).kind,'wild');a.strictEqual(E.initials('Ana Paula'),'AP');
console.log('constellations engine OK');
