const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function fixture(file='estudo.js'){
 const timers=new Map(),local=new Map(),writes=[];let uid='a',remote=null,error=null,serial=0;
 const document={getElementById:()=>null,querySelectorAll:()=>[],addEventListener(){},body:{classList:{remove(){},toggle(){}}}};
 const query={select(){return this},eq(){return this},async maybeSingle(){return{data:remote,error}},async upsert(x){writes.push(x);return{error}},update(){return this},then(resolve){resolve({error:null})}};
 const ctx={console,document,localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)},sessionStorage:{getItem:()=>null},cloudRole:'founder',Date,Math,JSON,crypto:require('node:crypto').webcrypto,setTimeout:f=>{timers.set(++serial,f);return serial},clearTimeout:id=>timers.delete(id),setInterval(){},clearInterval(){},URLSearchParams,location:{search:''},Event:class{},window:{iasdCloud:{from:()=>query},iasdCurrentUser:()=>uid?{id:uid}:null,IASDAccess:{canStudy:()=>true},addEventListener(){},dispatchEvent(){}}};ctx.IASDAccess=ctx.window.IASDAccess;
 let code=fs.readFileSync(path.join(__dirname,'../ui',file),'utf8');if(file==='estudo.js')code=code.replace('window.IASDEstudoCore={','window.testStudy={prepareCourse,migrateProgress,loadProg,saveProg,progressKey,lessonKey,lp,resetAfterRoom,replaceMediaTrack,fmtAns,optsHTML};window.IASDEstudoCore={');
 vm.runInNewContext(code,ctx);return{ctx,local,writes,timers,setUser:v=>uid=v,setRemote:v=>remote=v,setError:v=>error=v,flush:async()=>{const tasks=[...timers.values()];timers.clear();for(const f of tasks)await f();}};
}
test('stable lesson IDs retain migrated answers and completion after reorder or deletion',async()=>{const f=fixture(),T=f.ctx.window.testStudy,S=f.ctx.window.IASDEstudoCore.S;const c=T.prepareCourse({id:'course',lessons:[{title:'A',blocks:[{id:'q1'}]},{title:'B',blocks:[{id:'q2'}]}]});S.courses=[c];S.cid=c.id;f.setRemote({data:{'0':{a:{q1:'Resposta A'},d:true},'1':{a:{q2:'Resposta B'},d:false}}});await T.loadProg();assert.equal(T.lp(0).a.q1,'Resposta A');f.ctx.window.IASDEstudo.moveLesson(0,1);assert.equal(T.lp(1).a.q1,'Resposta A');assert.equal(T.lp(1).d,true);c.lessons.splice(0,1);assert.equal(T.lp(0).a.q1,'Resposta A');T.resetAfterRoom();assert.equal(T.lp(0).a.q1,'Resposta A');});
test('account caches are separate and pending save never writes a second account data',async()=>{const f=fixture(),T=f.ctx.window.testStudy,S=f.ctx.window.IASDEstudoCore.S;S.cid='c';S.prog={x:{a:{q:'A'},d:true}};T.saveProg();f.setUser('b');S.prog={};await T.loadProg();assert.equal(Object.keys(S.prog).length,0);await f.flush();assert.equal(f.writes.length,0);assert(f.local.has('iasd-study-prog-a-c'));});
test('profile converts legacy lesson positions and preserves explicit undo of completion',async()=>{const f=fixture('estudo-me.js'),M=f.ctx.window.IASDStudyMe;M.rec('c','Curso',1,0,'Lição','q','Pergunta','Resposta');M.done('c','Curso',1,0,'Lição',true);M.migrateCourse('c',[{id:'stable',legacyIndex:0}]);assert.equal(M.get().courses.c.lessons.stable.a.q.a,'Resposta');assert.equal(M.get().courses.c.lessons[0],undefined);M.done('c','Curso',1,'stable','Lição',false);assert.equal(M.get().courses.c.lessons.stable.d,0);assert(M.get().courses.c.lessons.stable.dt>0);f.setUser('b');assert.equal(M.counts().ans,0);});

test('failed microphone replacement restores previous outgoing tracks and releases new device',async()=>{const f=fixture(),T=f.ctx.window.testStudy,S=f.ctx.window.IASDEstudoCore.S,old={stop(){throw Error('old microphone must stay live')}},calls=[];let fail=true,stopped=0;const sender1={replaceTrack:async t=>calls.push(t)},sender2={replaceTrack:async t=>{if(fail){fail=false;throw Error('sender failure')}calls.push(t)}};S.room={voice:{aTrack:old,mic:true,pcs:{a:{aT:{sender:sender1}},b:{aT:{sender:sender2}}}}};const replacement={stop(){stopped++}};await assert.rejects(T.replaceMediaTrack('audio',replacement,'local'));assert.equal(S.room.voice.aTrack,old);assert.equal(stopped,1);assert.equal(calls.filter(t=>t===old).length,2)});
test('multiple choice answers retain selected alternatives and render checkboxes',()=>{const f=fixture(),T=f.ctx.window.testStudy,b={id:'q',kind:'x',opts:['A','B','C'],keys:['X','X','']};assert.equal(T.fmtAns(b,'0,1'),'A\nB');assert.match(T.optsHTML(b,{a:{q:'0,1'}},false),/type="checkbox"/)});
