const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const uid='11111111-1111-4111-8111-111111111111',pair='22222222-2222-4222-8222-222222222222';
function fixture(){const sent=[],local=new Map(),session=new Map(),intervals=[],elements=new Map(),timers=[];let role=true,room={code:'ABCDE',voice:null},media;
const storage=m=>({getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}),core={S:{room},esc:x=>String(x),canCameraPhone:()=>role,toast(){},mediaConstraints:()=>({video:{},audio:{echoCancellation:true}}),ice:async()=>({iceServers:[]}),stopCam(){room.voice=null},stopMic(){room.voice=null},replaceMediaTrack:async()=>{}};
class PC{constructor(){this.connectionState='new';this.senders=[]}addTransceiver(track){const sender={track:typeof track==='string'?null:track,replaceTrack:async t=>sender.track=t};this.senders.push(sender);return {sender}}getSenders(){return this.senders}async setLocalDescription(d){this.localDescription={...d,toJSON:()=>d}}async setRemoteDescription(d){this.remoteDescription=d;if(d.type==='offer')this.transceivers=['video','audio'].map(kind=>({receiver:{track:{kind}},sender:{replaceTrack:async t=>{this.attached=this.attached||{};this.attached[kind]=t}}}))}getTransceivers(){return this.transceivers||[]}async createOffer(){return{type:'offer',sdp:'test'}}async createAnswer(){return{type:'answer',sdp:'test'}}async addIceCandidate(){}close(){this.connectionState='closed'}}
const channel={on(){return this},subscribe(fn){fn('SUBSCRIBED');return this},send:async p=>{sent.push(p);return 'ok'}};
const ctx={window:{IASDEstudoCore:core,iasdCloud:{channel:()=>channel,removeChannel:async()=>{}},iasdCurrentUser:()=>({id:uid}),addEventListener(){}},document:{getElementById:id=>elements.get(id)||null,addEventListener(){}},navigator:{mediaDevices:{getUserMedia:()=>media}},location:{href:'https://example.com/estudo',origin:'https://example.com'},localStorage:storage(local),sessionStorage:storage(session),crypto:require('node:crypto').webcrypto,URL,Date,Promise,console,RTCPeerConnection:PC,MediaStream:class{constructor(tracks){this.tracks=tracks}},setTimeout:f=>{timers.push(f);return timers.length},clearTimeout(){},setInterval:f=>{intervals.push(f);return intervals.length},clearInterval(){}};
let src=fs.readFileSync(path.join(__dirname,'../ui/study-devices.js'),'utf8');src=src.replace('window.IASDStudyDevices={','window.testDevices={drawMirrored,acquire,receive,message,connect,captureVideo,allowedResume,persistPhone,chooseMic,autoResume,setP:p=>P=p,getP:()=>P};window.IASDStudyDevices={');vm.runInNewContext(src,ctx);return{T:ctx.window.testDevices,D:ctx.window.IASDStudyDevices,ctx,core,sent,local,session,intervals,timers,setRole:x=>role=x,setMedia:x=>media=x};}
test('paired phone may reconnect with a new client after refresh; hello is not addressed to obsolete PC',async()=>{const f=fixture(),p={role:'pc',owner:uid,id:pair,client:pair,ready:true,channel:f.ctx.window.iasdCloud.channel(),peer:uid};f.T.setP(p);await f.T.receive(p,{role:'phone',client:uid,event:'hello',time:Date.now(),data:{}});assert.equal(f.sent[0].payload.event,'description');const old=p.pc;await f.T.receive(p,{role:'phone',client:pair,event:'hello',time:Date.now(),data:{}});assert.equal(old.connectionState,'closed');assert.equal(p.peer,pair);p.role='phone';await f.T.message(p,'hello',{});assert.equal(f.sent.at(-1).payload.to,null);});
test('stopping a pending camera acquisition releases late media and cancels persistent permission',async()=>{const f=fixture(),p={role:'phone',owner:uid,id:pair};let resolve,stopped=0;f.setMedia(new Promise(r=>resolve=r));f.T.setP(p);f.T.persistPhone(p,true);const pending=f.T.captureVideo(p);await f.D.stopPhone();resolve({getTracks:()=>[{stop:()=>stopped++}]});await pending;assert.equal(stopped,1);assert.equal(f.T.getP(),null);assert.equal(f.T.allowedResume(p),null);});
test('microphone acquired after leaving the room is immediately stopped',async()=>{const f=fixture();let resolve,stopped=0,applied=0;f.setMedia(new Promise(r=>resolve=r));f.core.replaceMediaTrack=async()=>applied++;const pending=f.T.chooseMic('device');f.core.S.room=null;resolve({getTracks:()=>[{stop:()=>stopped++}]});await pending;assert.equal(stopped,1);assert.equal(applied,0);});
test('resume permission is scoped to owner/pair and expires; unauthorized role cannot resume',async()=>{const f=fixture(),p={owner:uid,id:pair,mic:true};f.T.persistPhone(p,true);assert(f.T.allowedResume(p));assert.equal(f.T.allowedResume({...p,id:uid}),null);f.ctx.location.href='https://example.com/estudo?cameraOwner='+uid+'&camera='+pair;f.setRole(false);await f.T.autoResume();assert.equal(f.T.getP(),null);});
test('wrong recipient, same role and stale signaling do not open a camera peer',async()=>{const f=fixture(),p={role:'pc',client:pair};f.T.setP(p);for(const m of [{role:'pc',client:uid},{role:'phone',client:uid,to:uid},{role:'phone',client:uid,time:0}])await f.T.receive(p,{event:'hello',data:{},time:Date.now(),...m});assert.equal(p.pc,undefined);assert.equal(f.sent.length,0);});

test('permission timeout reports failure and releases media if approval arrives late',async()=>{const f=fixture();let resolve,stopped=0;f.setMedia(new Promise(r=>resolve=r));const request=f.T.acquire({video:true});f.timers.at(-1)();await assert.rejects(request,/permissão/);resolve({getTracks:()=>[{stop:()=>stopped++}]});await Promise.resolve();assert.equal(stopped,1);});

test('phone uses the video transceiver offered by PC instead of creating an unnegotiated sender',async()=>{const f=fixture(),video={kind:'video'},p={role:'phone',client:pair,video,ready:true,channel:f.ctx.window.iasdCloud.channel()};f.T.setP(p);await f.T.receive(p,{role:'pc',client:uid,event:'description',data:{type:'offer',sdp:'test'},time:Date.now()});assert.equal(p.pc.attached.video,video);assert.equal(p.pc.senders.length,0);assert.equal(p.pc.getTransceivers()[0].direction,'sendonly');assert.equal(f.sent.at(-1).payload.data.type,'answer')});

test('mirror correction flips horizontally at source dimensions without stretching',()=>{const f=fixture(),calls=[],video={};const ctx=Object.fromEntries(['save','translate','scale','drawImage','restore'].map(k=>[k,(...args)=>calls.push([k,...args])]));f.T.drawMirrored(ctx,video,720,1280);assert.deepEqual(calls,[['save'],['translate',720,0],['scale',-1,1],['drawImage',video,0,0,720,1280],['restore']]);const p={owner:uid,id:pair,mirror:true};f.T.persistPhone(p,true);assert.equal(f.T.allowedResume(p).mirror,true)});
