(function(){
'use strict';
const E=window.ConstellationEngine,KEY='iasd-constellations-v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const symbols=['✦','◆','●','▲'],families=['Estrela','Cristal','Órbita','Farol'];
const label=c=>typeof c==='number'?families[Math.floor(c/8)]+' '+(c%8+1):c==='remove'?'Pulso':'Escudo';
const art=c=>typeof c==='number'?'<span class="cs-symbol f'+Math.floor(c/8)+'">'+symbols[Math.floor(c/8)]+'</span><small>'+(c%8+1)+'</small>':'<span class="cs-symbol">'+(c==='remove'?'⊖':'⬡')+'</span><small>'+label(c)+'</small>';
let root,state,selected=null,pending=null,privateHand=true,spectator=false,muted=false,busy=false,timer,observer,abort,audio,nodes=[],zoom=56,drag=null,suppressUntil=0,perspectiveTeam=null;
function read(){try{return E.restore(localStorage.getItem(KEY))}catch{return null}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{message('Não foi possível salvar neste navegador. Evite recarregar a página.');return false}}
function sound(kind){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});nodes.forEach(n=>{try{n.stop()}catch{}});nodes=[];
 const melody={click:[460],select:[620],place:[420,660],turn:[520,780],invalid:[160,130],block:[280,190],line:[520,660,880],win:[520,660,780,1040],lose:[440,330,220],draw:[420,360],timeout:[220,180]}[kind]||[460];
 melody.forEach((freq,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.085;o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.065,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+.12);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.14);nodes.push(o);o.onended=()=>{o.disconnect();g.disconnect();nodes=nodes.filter(n=>n!==o)}})
 }catch{/* O áudio nunca controla a partida. */}}
function dispose(){clearInterval(timer);timer=null;observer?.disconnect();abort?.abort();root?.getAnimations?.({subtree:true}).forEach(a=>a.cancel());nodes.forEach(n=>{try{n.stop()}catch{}});nodes=[];if(audio){audio.close().catch(()=>{});audio=null}root=null;drag=null;selected=pending=null;busy=false}
function text(el,value){if(el.textContent===value)return;el.textContent=value;try{el.getAnimations?.().forEach(a=>a.cancel());if(!matchMedia('(prefers-reduced-motion: reduce)').matches)el.animate?.([{opacity:.4,transform:'translateY(3px)'},{opacity:1,transform:'translateY(0)'}],{duration:220})}catch{/* Efeitos visuais não controlam o estado. */}}
function message(text){const el=root?.querySelector('.cs-message');if(el)el.textContent=text}
function pan(ev){if(ev.type==='pointerdown'){const viewport=ev.target.closest('.cs-viewport');if(viewport&&ev.pointerType!=='touch'&&ev.button===0)drag={viewport,x:ev.clientX,y:ev.clientY,left:viewport.scrollLeft,top:viewport.scrollTop,moved:false}}else if(ev.type==='pointermove'&&drag&&ev.buttons===1){const dx=ev.clientX-drag.x,dy=ev.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>8){drag.moved=true;drag.viewport.setPointerCapture(ev.pointerId);drag.viewport.scrollLeft=drag.left-dx;drag.viewport.scrollTop=drag.top-dy;ev.preventDefault()}}else if(ev.type==='pointerup'||ev.type==='pointercancel'){if(drag?.moved)suppressUntil=performance.now()+250;drag=null}}
function open(){dispose();drag=null;suppressUntil=0;const host=document.getElementById('game-stage');if(!host)return;root=document.createElement('section');root.className='cs';host.replaceChildren(root);abort=new AbortController();root.addEventListener('click',click,{signal:abort.signal});root.addEventListener('change',change,{signal:abort.signal});for(const event of ['pointerdown','pointermove','pointerup','pointercancel'])root.addEventListener(event,pan,{signal:abort.signal});
 window.addEventListener('storage',ev=>{if(ev.key!==KEY||!state)return;const latest=read();if(latest&&latest.id===state.id&&latest.revision>state.revision){state=latest;privateHand=true;selected=pending=null;if(state.status!=='playing')sound(state.status==='draw'?'draw':perspectiveTeam!==null&&perspectiveTeam!==state.winner?'lose':'win');paint()}else if(latest&&latest.id!==state.id){state=null;setup();message('Uma nova partida foi iniciada em outra aba.')}} ,{signal:abort.signal});
 window.addEventListener('pagehide',dispose,{signal:abort.signal});observer=new MutationObserver(()=>{if(root&&!root.isConnected)dispose()});observer.observe(document.getElementById('content')||document.body,{childList:true,subtree:true});state=null;setup();root.scrollIntoView({block:'start',behavior:'smooth'});
}
function header(){return '<header class="cs-header"><button data-action="back">‹ Jogos</button><h2>Constelações<span>✦</span></h2><button data-action="mute" aria-label="Alternar efeitos sonoros">'+(muted?'Som off':'Som on')+'</button></header>'}
function setup(){root.classList.remove('cs-playing','cs-spectator');clearInterval(timer);timer=null;root.innerHTML=header()+'<div class="cs-intro"><div class="cs-emblem">✦</div><h3>Uma carta. Uma escolha.<br>Uma nova conexão.</h3><p>Conecte cinco fichas e conquiste duas constelações antes da outra equipe.</p></div><div class="cs-setup"><label>Participantes <select id="cs-count">'+[2,4,6,8,10,12].map(n=>'<option value="'+n+'">'+n/2+' × '+n/2+' · '+n+' jogadores</option>').join('')+'</select></label><label>Tempo por turno <select id="cs-time"><option value="45">45 segundos</option><option value="30">30 segundos</option><option value="60">60 segundos</option><option value="0">Sem cronômetro</option></select></label><div class="cs-names"></div><button class="cs-primary" data-action="start">Iniciar partida local</button>'+(read()?'<button data-action="resume">Continuar partida salva</button>':'')+'<p>Jogue passando o dispositivo. Os nomes alternam Azul e Ouro. Funciona sem sala online.</p></div>'+rules()+'<p class="cs-message" role="status" aria-live="polite"></p>';names(2)}
function names(count){root.querySelector('.cs-names').innerHTML=Array.from({length:count},(_,i)=>'<label class="cs-team'+i%2+'">'+(i%2?'Ouro':'Azul')+' · '+(Math.floor(i/2)+1)+'<input maxlength="32" placeholder="Jogador '+(i+1)+'" aria-label="Nome do jogador '+(i+1)+'"></label>').join('')}
function rules(){return '<details class="cs-rules"><summary>Como jogar</summary><p>Cada carta de símbolo e número aparece em duas casas do tabuleiro. Selecione uma carta, toque numa casa iluminada e confirme. Cada jogador tem cinco cartas e compra outra ao jogar.</p><p>Duas linhas de cinco fichas da sua equipe vencem: horizontal, vertical ou diagonal. Linhas podem compartilhar apenas uma casa. Uma linha completa fica protegida.</p><p><b>Pulso:</b> remove uma ficha adversária sem proteção. <b>Escudo:</b> protege uma ficha sua. Apenas oito cartas especiais no baralho de 136 cartas. Ocupar uma casa também bloqueia o adversário.</p><p>Uma carta sem destino pode ser trocada, consumindo o turno. Passar ou deixar o tempo acabar também passa o turno. Tabuleiro cheio, duas voltas sem ação no tabuleiro ou 500 turnos encerram em empate. Cartas descartadas são reembaralhadas.</p><p>No telão, as mãos ficam ocultas. O cronômetro continua durante a passagem do dispositivo. O primeiro participante é sorteado. A partida fica salva neste navegador.</p></details>'}
function change(ev){if(ev.target.id==='cs-count')names(Number(ev.target.value))}
function mount(){perspectiveTeam=null;root.classList.add('cs-playing');selected=pending=null;privateHand=true;zoom=innerWidth>=760?64:56;
 root.innerHTML=header()+'<div class="cs-score"><div class="cs-team0"><i>✦</i><span>Azul <b id="cs-blue"></b></span></div><div class="cs-turn"><b id="cs-player"></b><span id="cs-clock"></span></div><div class="cs-team1"><i>✦</i><span>Ouro <b id="cs-gold"></b></span></div></div><div class="cs-tools"><button data-action="zoom-out" aria-label="Diminuir zoom">−</button><span>Arraste para navegar</span><button data-action="zoom-in" aria-label="Aumentar zoom">+</button><button data-action="screen">Telão</button><button data-action="fullscreen">Expandir</button></div><div class="cs-arena"><div class="cs-viewport"><div class="cs-board" role="group" aria-label="Tabuleiro 8 por 8">'+state.board.map((c,i)=>'<button class="cs-cell" data-cell="'+i+'" aria-label="Linha '+(Math.floor(i/8)+1)+', coluna '+(i%8+1)+', '+label(c.value)+'">'+art(c.value)+'<i class="cs-piece"></i><span class="cs-shield">⬡</span></button>').join('')+'<svg class="cs-lines" viewBox="0 0 800 800" aria-hidden="true"></svg></div></div><div class="cs-cover"></div></div><div class="cs-bottom"><div class="cs-hand"></div><div class="cs-actions"><button class="cs-primary" data-action="confirm" disabled>Confirmar jogada</button><button data-action="exchange" disabled>Trocar carta</button><button data-action="pass">Passar turno</button></div></div><p class="cs-message" role="status" aria-live="polite"></p><div class="cs-order"></div>'+rules();
 root.style.setProperty('--cs-cell',zoom+'px');paint();clearInterval(timer);timer=state.status==='playing'&&state.deadline!==null?setInterval(tick,500):null;tick();
}
function paint(){if(!state||!root)return;root.classList.toggle('cs-spectator',spectator);const p=state.players[state.turn],canSee=!privateHand&&!spectator&&state.status==='playing';const valid=canSee&&selected!==null?E.valid(state,p.hand[selected]):[];
 text(root.querySelector('#cs-blue'),state.sequences[0].length+' / 2');text(root.querySelector('#cs-gold'),state.sequences[1].length+' / 2');text(root.querySelector('#cs-player'),state.status==='playing'?p.name+' · '+(p.team?'Ouro':'Azul'):state.status==='won'?(state.winner?'Ouro':'Azul')+' venceu!':'Empate');
 root.querySelector('.cs-turn').className='cs-turn cs-team'+p.team;
 root.querySelectorAll('.cs-cell').forEach((el,i)=>{const c=state.board[i];el.className='cs-cell'+(c.owner!==null?' owned cs-team'+c.owner:'')+(valid.includes(i)?' valid':'')+(pending===i?' pending':'')+(c.shield?' shield':'')+(E.locked(state,i)?' locked':'')+(state.last?.cell===i?' recent':'');el.setAttribute('aria-pressed',pending===i?'true':'false');el.setAttribute('aria-label','Linha '+(Math.floor(i/8)+1)+', coluna '+(i%8+1)+', '+label(c.value)+(c.owner!==null?', ficha '+(c.owner?'Ouro':'Azul'):'')+(c.shield?', protegida':'')+(valid.includes(i)?', posição válida':''))});
 const lineLayer=root.querySelector('.cs-lines'),lineKey=JSON.stringify(state.sequences);if(lineLayer.dataset.key!==lineKey){lineLayer.dataset.key=lineKey;lineLayer.innerHTML=state.sequences.flatMap((lines,t)=>lines.map(line=>{const a=line[0],b=line[4];return '<line class="cs-line cs-team'+t+'" x1="'+((a%8)*100+50)+'" y1="'+(Math.floor(a/8)*100+50)+'" x2="'+((b%8)*100+50)+'" y2="'+(Math.floor(b/8)*100+50)+'" />'})).join('');}
 const cover=root.querySelector('.cs-cover');cover.hidden=canSee||spectator;cover.innerHTML=state.status==='playing'?'<div><span class="cs-cover-star">✦</span><h3>'+esc(p.name)+'</h3><p>Entregue o dispositivo ao participante da equipe '+(p.team?'Ouro':'Azul')+'.</p><button class="cs-primary" data-action="reveal">Ver minha mão e jogar</button></div>':'<div class="cs-result"><span class="cs-cover-star">'+(state.status==='won'?'✦':'◇')+'</span><h3>'+ (state.status==='won'?'Equipe '+(state.winner?'Ouro':'Azul')+' venceu!':'Partida empatada')+'</h3><p>'+state.revision+' turnos · Azul '+state.sequences[0].length+' × '+state.sequences[1].length+' Ouro</p><button data-action="inspect">Ver tabuleiro</button><button class="cs-primary" data-action="new">Nova partida</button></div>';
 const hand=root.querySelector('.cs-hand');hand.innerHTML=canSee?'<div class="cs-hand-title">Sua mão <span>'+esc(p.name)+' · selecione uma carta</span></div><div class="cs-cards">'+p.hand.map((c,i)=>'<button data-card="'+i+'" aria-label="'+label(c)+'" aria-pressed="'+(selected===i)+'" class="cs-card '+(selected===i?'selected':'')+'">'+art(c)+'</button>').join('')+'</div>':'<p>'+ (spectator?'Telão · mãos privadas ocultas':'Mão oculta · passe o dispositivo')+'</p>';
 root.querySelector('[data-action="confirm"]').disabled=!canSee||pending===null||busy;
 root.querySelector('[data-action="exchange"]').disabled=!canSee||selected===null||valid.length>0||busy;
 root.querySelector('[data-action="pass"]').disabled=!canSee||busy;
 root.querySelector('[data-action="screen"]').textContent=spectator?'Voltar ao jogador':'Telão';
 root.querySelector('.cs-order').innerHTML='<b>Ordem dos turnos</b> '+state.players.map((x,i)=>'<span class="cs-team'+x.team+(i===state.turn?' active':'')+'">'+(i+1)+'. '+esc(x.name)+'</span>').join('')+(state.status!=='playing'?'<button data-action="new">Nova partida</button>':'');
}
function tick(){if(!state||!root)return;const clock=root.querySelector('#cs-clock');if(!clock)return;const remaining=state.deadline===null?null:Math.max(0,Math.ceil((state.deadline-Date.now())/1000));clock.textContent=state.status!=='playing'?'Partida encerrada':remaining===null?'Sem limite de tempo':remaining+' s';clock.classList.toggle('urgent',remaining!==null&&remaining<=10);if(state.status!=='playing'){clearInterval(timer);timer=null}else if(remaining===0&&!busy)commit('timeout')}
async function commit(type){if(busy||!state)return;busy=true;const action={type,match:state.id,revision:state.revision,player:state.players[state.turn].id,card:selected,cell:pending};
 const run=()=>{const saved=read();if(saved&&saved.id!==state.id)throw Error('Outra partida foi iniciada nesta aba ou em outra janela.');if(saved&&saved.revision>state.revision){state=saved;throw Error('O turno mudou em outra aba.')}state=E.apply(state,action);save()};
 try{if(navigator.locks)await navigator.locks.request(KEY,run);else run();selected=pending=null;privateHand=true;sound(state.status==='won'?'win':state.status==='draw'?'draw':state.last.formed.length?'line':type==='timeout'?'timeout':state.last.card==='remove'?'block':'place');paint();message(state.last.formed.length?'Constelação completa! Linha protegida.':type==='timeout'?'Tempo esgotado. Próximo participante.':'Turno concluído. Passe o dispositivo.');}
 catch(e){selected=pending=null;privateHand=true;sound('invalid');paint();message(e.message)}finally{busy=false;tick()}
}
function click(ev){const btn=ev.target.closest('button');if(!btn||!root.contains(btn)||btn.disabled)return;
 if(btn.dataset.card!==undefined){selected=Number(btn.dataset.card);pending=null;sound('select');paint();const positions=E.valid(state,state.players[state.turn].hand[selected]);message(positions.length?positions.length+' posições válidas. Toque em uma casa e confirme.':'Sem posição válida. Você pode trocar esta carta e passar o turno.');if(positions.length)root.querySelector('[data-cell="'+positions[0]+'"]').scrollIntoView({block:'nearest',inline:'center',behavior:'smooth'});return}
 if(btn.dataset.cell!==undefined){if(performance.now()<suppressUntil||privateHand||spectator||state.status!=='playing')return;const cell=Number(btn.dataset.cell);if(selected===null||!E.valid(state,state.players[state.turn].hand[selected]).includes(cell)){sound('invalid');message('Selecione uma carta e uma casa iluminada.');return}pending=cell;sound('click');paint();message('Casa selecionada. Confirme para concluir.');return}
 const a=btn.dataset.action;
 if(a==='back'){dispose();const stage=document.getElementById('game-stage');if(stage)stage.innerHTML=window.IASDPages.gameCards();return}
 if(a==='mute'){muted=!muted;btn.textContent=muted?'Som off':'Som on';if(muted){nodes.forEach(n=>{try{n.stop()}catch{}});nodes=[]}return}
 if(a==='start'){state=E.create([...root.querySelectorAll('.cs-names input')].map(i=>i.value),Number(root.querySelector('#cs-time').value));spectator=false;save();mount();sound('turn');message('Primeiro participante sorteado: '+state.players[state.turn].name);return}
 if(a==='resume'){state=read();if(state){spectator=false;mount();message('Partida recuperada neste dispositivo.')}return}
 if(a==='new'){state=null;spectator=false;setup();return}
 if(a==='reveal'){perspectiveTeam=state.players[state.turn].team;privateHand=false;sound('turn');paint();tick();return}
 if(a==='screen'){spectator=!spectator;privateHand=true;selected=pending=null;paint();return}
 if(a==='inspect'){spectator=true;paint();return}
 if(a==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else root.requestFullscreen?.().catch(()=>message('Expansão indisponível neste navegador.'));return}
 if(a==='zoom-in'||a==='zoom-out'){zoom=Math.max(56,Math.min(104,zoom+(a==='zoom-in'?8:-8)));root.style.setProperty('--cs-cell',zoom+'px');return}
 if(a==='confirm')commit('play');if(a==='exchange')commit('exchange');if(a==='pass')commit('pass');
}
window.IASDConstellations={open,dispose};
})();
