/* Private draft controller, loaded on demand. No direct writes to public content tables. */
(function(){
'use strict';
const M=window.IASDEditorModel,E=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),clone=M.clone;
let pendingPreset,confirmedDocument,root,frame,history,base,draftRevision=0,uid,localKey,selected='banner',list=[],timer,saving,queued=false,busy=false,preview=false,width=1440,abort,resizeObserver,framePending,frameConfirmed,frameSlot,conflict=false,localAvailable=true,lastSaved='';
const $=id=>root?.querySelector('#'+id),doc=()=>history.value;
const perms=()=>({texts:IASDAccess.canEditTexts(cloudRole)||IASDAccess.canEditSite(cloudRole),assets:IASDAccess.canEditSite(cloudRole),tabs:IASDAccess.canManageTabs(cloudRole)});
function status(s){if($('ed-status'))$('ed-status').textContent=s;}
async function rpc(name,args){const r=await window.iasdCloud.rpc(name,args);if(r.error)throw Error(r.error.message);return r.data;}
function error(e){conflict=/CONFLICT/.test(e.message);status(conflict?'Conflito: outra edição mudou. Seu rascunho foi preservado.':'Erro: '+e.message);}
function local(){try{localStorage.setItem(localKey,JSON.stringify({document:doc(),base,draftRevision,at:Date.now()}));localAvailable=true;return true}catch(e){localAvailable=false;status('Armazenamento local indisponível. Mantenha esta janela aberta até salvar no servidor.');return false}}
function counts(){if(!root)return;$('ed-inspector').inert=busy;$('ed-canvas').inert=busy;const n=M.diff(base.document,doc()).length;$('ed-count').textContent=n+' '+(n===1?'alteração não publicada':'alterações não publicadas');$('ed-undo').disabled=busy||!history.undoStack.length;$('ed-redo').disabled=busy||!history.redoStack.length;$('ed-publish').disabled=busy||!n||conflict||!IASDEdit.allowed();}
function send(){if(frame?.contentWindow)frame.contentWindow.postMessage({type:'iasd-editor-document',document:doc(),preview},location.origin);}
function changed(group,mutate){if(busy||conflict||!IASDEdit.allowed())return;const d=clone(doc());mutate(d);if(!history.set(d,group))return;local();send();counts();status('Alterações salvas neste dispositivo; aguardando sincronização…');clearTimeout(timer);timer=setTimeout(save,900);}
async function save(){clearTimeout(timer);if(busy||conflict)return false;if(saving){queued=true;await saving;return save()}if(!IASDEdit.allowed()||window.iasdCurrentUser?.()?.id!==uid){status('Sua sessão ou permissão mudou. Rascunho local preservado.');return false}if(!navigator.onLine){status('Sem conexão: rascunho salvo neste dispositivo.');return false}
 const value=clone(doc()),errors=M.validate(value);if(errors.length){status(errors[0]);return false}if(M.canonical(value)===lastSaved)return true;
 status('Salvando rascunho…');saving=rpc('iasd_editor_save',{p_document:value,p_base_revision:base.revision,p_base_fingerprint:base.fingerprint,p_expected:draftRevision}).then(r=>{draftRevision=r.draft_revision;lastSaved=M.canonical(value);local();status('Rascunho salvo • '+new Date(r.updated_at).toLocaleTimeString('pt-BR'));return true}).catch(e=>{error(e);return false});
 const ok=await saving;saving=null;if(queued){queued=false;if(ok)timer=setTimeout(save,0)}return ok;
}
function props(){try{return JSON.parse(doc().texts.home_editor_props||'{}')}catch(e){return {}}}
function prop(key,value){changed(selected+':'+key,d=>{const p=JSON.parse(d.texts.home_editor_props||'{}');p[selected]={...(p[selected]||{}),[key]:value};d.texts.home_editor_props=JSON.stringify(p)});}
function input(label,value,attr=''){return '<label>'+E(label)+'<input value="'+E(value)+'" '+attr+'></label>'}
function inspector(){
 const c=list.find(x=>x.id===selected)||{id:selected,label:selected==='tabs'?'Abas personalizadas':'Banner principal',type:selected==='tabs'?'tabs':'banner',slot:'home_banner'},p=props()[selected]||{};
 const options=list.map(x=>'<option value="'+E(x.id)+'" '+(x.id===selected?'selected':'')+'>'+E(x.label)+'</option>').join('')+'<option value="tabs" '+(selected==='tabs'?'selected':'')+'>Abas personalizadas</option>';
 let html='<h3>'+E(c.label)+'</h3><label>Componente<select id="ed-component">'+options+'</select></label><p class="ed-note">Somente os componentes cadastrados podem ser editados. As áreas operacionais e de segurança ficam protegidas.</p>';
 if(c.type==='tabs')html+=tabsHTML();
 else{
  if(c.type==='banner'){for(const [key,label,def]of [['eyebrow','Categoria','EVANGELISMO'],['title','Título','O FIM DO'],['accent','Destaque','PECADO'],['verse','Mensagem','“E vi novo céu e nova terra...”'],['reference','Referência','Apocalipse 21:1'],['button','Texto do botão','Ver programação da semana']])html+=input(label,doc().texts['home_editor_banner_'+key]??c.fields?.[key]??def,'data-text="home_editor_banner_'+key+'" maxlength="1000" '+(!perms().texts?'disabled':''));html+=input('Tempo de troca (segundos)',doc().texts.home_carousel_seconds||4.5,'data-text="home_carousel_seconds" type="number" min="2" max="30" step="0.5" '+(!perms().texts?'disabled':''));}
  if(c.type==='card')html+=input('Título',p.title??c.label,'data-prop="title" maxlength="1000"')+input('Descrição',p.description??c.description??'','data-prop="description" maxlength="1000"')+'<label>Destino<select data-prop="destination"><option value="">Manter destino atual</option>'+['Cronograma','Bíblia','Escalas','Datas especiais','Mídia','Mais',...doc().tabs.map(t=>'custom:'+t.id)].map(x=>'<option '+(p.destination===x?'selected':'')+' value="'+E(x)+'">'+E(x)+'</option>').join('')+'</select></label>';
  if(c.type!=='section')html+='<label>Alinhamento<select data-prop="align">'+['left','center','right'].map((x,i)=>'<option value="'+x+'" '+((p.align||'left')===x?'selected':'')+'>'+['Esquerda','Centro','Direita'][i]+'</option>').join('')+'</select></label><label><span><input type="checkbox" data-prop="hidden" '+(p.hidden?'checked':'')+'> Ocultar componente</span></label>';
  if(c.type==='banner')html+=carouselHTML();if(c.slot)html+=imageHTML(c.slot);
  if(c.type==='section'||c.type==='card')html+='<h4>Ordem dos cartões</h4><p class="ed-note">Reordene apenas os cartões permitidos.</p>'+list.filter(x=>x.type==='card').sort((a,b)=>(props()[a.id]?.order??list.indexOf(a))-(props()[b.id]?.order??list.indexOf(b))).map(x=>'<div class="ed-row ed-order" draggable="true" data-order-id="'+E(x.id)+'"><span>☰ '+E(x.label)+'</span><button data-move="'+E(x.id)+'" data-dir="-1" aria-label="Mover para cima">↑</button><button data-move="'+E(x.id)+'" data-dir="1" aria-label="Mover para baixo">↓</button></div>').join('');
 }
 if(list.length&&selected!=='tabs'&&!list.some(c=>c.id===selected)){html='<h3>Componente protegido</h3><label>Componente<select id="ed-component"><option value="">Escolha um componente permitido</option>'+options+'</select></label><p class="ed-note">Este alvo não faz parte do registro de edição. Escolha um componente permitido.</p>'; }$('ed-inspector').innerHTML=html;
 $('ed-inspector').querySelectorAll('[data-prop],[data-carousel],[data-slide],[data-slide-toggle]').forEach(el=>el.disabled=!perms().texts);
 if(c.slot){frameSlot=c.slot;frameConfirmed=clone(doc().frames[c.slot]||{position_x:50,position_y:50,zoom:1});framePending=clone(frameConfirmed);updateFrame();}
}
function carouselHTML(){let c={};try{c=JSON.parse(doc().texts.home_carousel_cfg||'{}')}catch(e){}const order=[...(c.order||[]).filter(s=>doc().assets[s]),...Object.keys(doc().assets).filter(s=>/^home_banner(?:_[1-9][0-9]*)?$/.test(s)&&!(c.order||[]).includes(s))];return '<h4>Carrossel</h4><label>Transição<select data-carousel="fx">'+['fade','slide','zoom'].map(x=>'<option '+((c.fx||'fade')===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label>'+[['shuffle','Ordem aleatória'],['dots','Bolinhas'],['arrows','Setas'],['pause','Pausar ao passar o mouse']].map(([k,l])=>'<label><span><input type="checkbox" data-carousel="'+k+'" '+((c[k]??(['dots','arrows','pause'].includes(k)))?'checked':'')+'> '+l+'</span></label>').join('')+order.map(slot=>'<div class="ed-row ed-order"><span>'+E(slot)+((c.off||[]).includes(slot)?' · desativada':'')+'</span><button data-slide="'+E(slot)+'" data-dir="-1">↑</button><button data-slide="'+E(slot)+'" data-dir="1">↓</button><button data-slide-toggle="'+E(slot)+'">'+((c.off||[]).includes(slot)?'Ativar':'Ocultar')+'</button></div>').join('');}
function carouselChange(mutate){if(!perms().texts)return;changed('',d=>{const c=JSON.parse(d.texts.home_carousel_cfg||'{}');mutate(c,d);d.texts.home_carousel_cfg=JSON.stringify(c)});}
function imageHTML(slot){const slots=Object.keys(doc().assets).filter(s=>/^home_banner(?:_\d+)?$/.test(s)).sort((a,b)=>(a==='home_banner'?0:Number(a.slice(12)))-(b==='home_banner'?0:Number(b.slice(12))));return '<h4>Imagem e enquadramento</h4>'+(slot==='home_banner'?'<label>Imagem do carrossel<select id="ed-banner-slot">'+(slots.length?slots:['home_banner']).map(s=>'<option>'+E(s)+'</option>').join('')+'</select></label><button data-action="add-slide">＋ Nova imagem no carrossel</button>':'')+'<div class="ed-image" id="ed-image"><img id="ed-image-preview" alt="Prévia do enquadramento"></div>'+input('Texto alternativo',props()[selected]?.alt||'','data-prop="alt" maxlength="1000"')+'<div class="ed-row"><button data-action="library" '+(!perms().assets?'disabled':'')+'>Biblioteca</button><label>Importar<input id="ed-upload" type="file" accept="image/jpeg,image/png,image/webp,image/gif" '+(!perms().assets?'disabled':'')+'></label></div><div id="ed-gallery" class="ed-gallery"></div>'+['position_x','position_y','zoom'].map((k,i)=>'<label>'+['Horizontal','Vertical','Zoom'][i]+' <output id="ed-out-'+k+'"></output><input data-frame="'+k+'" type="range" min="'+(i===2?1:0)+'" max="'+(i===2?3:100)+'" step="'+(i===2?.05:1)+'" '+(!perms().assets?'disabled':'')+'></label>').join('')+'<div class="ed-row"><button data-action="frame-reset">Centralizar</button><button data-action="frame-cancel">Cancelar ajuste</button><button data-action="frame-confirm" class="primary">Confirmar ajuste</button><button data-action="image-remove" class="danger">Remover do rascunho</button></div>';}
function updateFrame(){const img=$('ed-image-preview');if(!img||!framePending)return;img.src=doc().assets[frameSlot]?imageUrl(doc().assets[frameSlot]):'';img.hidden=!doc().assets[frameSlot];img.style.cssText='object-position:'+framePending.position_x+'% '+framePending.position_y+'%;transform-origin:'+framePending.position_x+'% '+framePending.position_y+'%;transform:scale('+framePending.zoom+')';for(const k of ['position_x','position_y','zoom']){const el=root.querySelector('[data-frame="'+k+'"]');if(el)el.value=framePending[k];if($('ed-out-'+k))$('ed-out-'+k).textContent=framePending[k]+(k==='zoom'?'×':'%')}}
async function library(){try{const r=await window.iasdCloud.rpc('iasd_list_site_images');if(r.error)throw Error(r.error.message);if(!$('ed-gallery'))return;$('ed-gallery').innerHTML=(r.data||[]).filter(x=>/\.(jpe?g|png|webp|gif)$/i.test(x.name)).map(x=>'<button data-image="'+E(x.name)+'" title="'+E(x.name)+'"><img loading="lazy" alt="'+E(x.name)+'" src="'+E(imageUrl(x.name))+'"></button>').join('')}catch(e){error(e)}}
async function upload(file){if(!perms().assets||!file)return;if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>50*1024*1024){status('Use JPG, PNG, WebP ou GIF de até 50 MB.');return}const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif"}[file.type],path=crypto.randomUUID()+'.'+ext;status('Enviando imagem…');const r=await window.iasdCloud.storage.from('iasd-images').upload(path,file,{contentType:file.type,upsert:false});if(r.error){error(Error(r.error.message));return}choose(path);}
function choose(path){if(!perms().assets)return;changed('',d=>{d.assets[frameSlot]=path;d.frames[frameSlot]={position_x:50,position_y:50,zoom:1}});const chosenSlot=frameSlot;inspector();frameSlot=chosenSlot;if($('ed-banner-slot'))$('ed-banner-slot').value=frameSlot;frameConfirmed={position_x:50,position_y:50,zoom:1};framePending=clone(frameConfirmed);updateFrame();}
function tabsHTML(){if(!perms().tabs)return '<p>Você não tem permissão para gerenciar abas.</p>';return doc().tabs.map(t=>'<section class="ed-version" data-tab="'+E(t.id)+'">'+input('Nome',t.title,'data-tab-field="title" maxlength="70"')+input('Descrição',t.description,'data-tab-field="description" maxlength="2000"')+input('Ícone',t.icon,'data-tab-field="icon" maxlength="12"')+'<div class="ed-row"><button data-tab-order="'+E(t.id)+'" data-dir="-1">↑</button><button data-tab-order="'+E(t.id)+'" data-dir="1">↓</button><button data-delete-tab="'+E(t.id)+'" class="danger">Remover aba</button></div></section>').join('')+'<button data-action="new-tab">＋ Criar aba no rascunho</button>';}
function reorder(id,dir,tabs=false){if(!(tabs?perms().tabs:perms().texts))return;changed('',d=>{if(tabs){const a=d.tabs.sort((a,b)=>a.sort_order-b.sort_order),i=a.findIndex(t=>t.id===id),j=i+dir;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];a.forEach((t,n)=>t.sort_order=100+n)}else{const p=JSON.parse(d.texts.home_editor_props||'{}'),a=list.filter(c=>c.type==='card').sort((a,b)=>(p[a.id]?.order??list.indexOf(a))-(p[b.id]?.order??list.indexOf(b))),i=a.findIndex(c=>c.id===id),j=i+dir;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];a.forEach((c,n)=>p[c.id]={...(p[c.id]||{}),order:n});d.texts.home_editor_props=JSON.stringify(p)}});inspector();}
function dialog(title,body,buttons){root.querySelector('.ed-dialog')?.remove();const div=document.createElement('div');div.className='ed-dialog';div.innerHTML='<section role="dialog" aria-modal="true" aria-label="'+E(title)+'"><h3>'+E(title)+'</h3>'+body+'<div class="ed-row">'+buttons+'<button data-action="dialog-close">Cancelar</button></div></section>';root.appendChild(div);div.querySelector('button')?.focus();}
function summary(changes){return '<ul>'+changes.map(c=>'<li>'+E(({texts:'Texto',assets:'Imagem',frames:'Enquadramento',tabs:'Aba'})[c.scope])+': '+E(c.key)+(c.after===undefined?' — removido':' — alterado')+'</li>').join('')+'</ul>';}
async function confirmPublish(){if(conflict||busy)return;if(framePending&&M.canonical(framePending)!==M.canonical(frameConfirmed)){status('Confirme ou cancele o enquadramento antes de publicar.');return}status('Validando…');const errors=M.validate(doc());if(errors.length){status(errors.join(' '));return}if(!await save())return;confirmedDocument=M.canonical(doc());dialog('Publicar alterações?', '<p>O site público será atualizado de uma vez. O estado atual ficará no histórico para restauração.</p>'+summary(M.diff(base.document,doc())),'<button data-action="publish-confirm" class="primary">Confirmar publicação</button>');}
async function publish(restore=null){if(busy||conflict)return;if(restore===null&&confirmedDocument!==M.canonical(doc())){status('O rascunho mudou. Revise e confirme a publicação novamente.');root.querySelector('.ed-dialog')?.remove();return}if(restore===null&&!await save())return;busy=true;counts();status(restore?'Restaurando como nova versão…':'Publicando…');try{const r=await rpc('iasd_editor_publish',{p_expected:draftRevision,p_revision:base.revision,p_fingerprint:base.fingerprint,p_restore:restore});base=r;history=new M.History(r.document);draftRevision=0;lastSaved=M.canonical(r.document);conflict=false;localStorage.removeItem(localKey);root.querySelector('.ed-dialog')?.remove();send();inspector();await IASDEdit.loadPublished();status('Publicado com sucesso • versão '+r.revision)}catch(e){error(e)}finally{busy=false;counts()}}
async function versions(page=0){try{const r=await window.iasdCloud.from('iasd_editor_versions').select('revision,created_at,actor,reason,restored_from,summary').order('revision',{ascending:false}).range(page*100,page*100+99);if(r.error)throw Error(r.error.message);dialog('Histórico de publicações','<p class="ed-note">Restaurar cria uma nova publicação e preserva todo o histórico.</p>'+(r.data||[]).map(v=>'<div class="ed-version"><strong>Versão '+v.revision+' · '+E(v.reason)+'</strong><p>'+E(new Date(v.created_at).toLocaleString('pt-BR'))+'<br>Responsável: '+E(v.actor||'Estado inicial')+'</p><button data-compare="'+v.revision+'">Comparar e restaurar</button></div>').join(''),(page>0?'<button data-more-history="'+(page-1)+'">Mais recentes</button>':'')+((r.data||[]).length===100?'<button data-more-history="'+(page+1)+'">Versões anteriores</button>':''))}catch(e){error(e)}}
async function compare(id){try{const r=await window.iasdCloud.from('iasd_editor_versions').select('document').eq('revision',id).single();if(r.error)throw Error(r.error.message);dialog('Restaurar versão '+id+'?','<p>Seu rascunho atual será substituído após a restauração. O conteúdo publicado atual será preservado no histórico.</p>'+summary(M.diff(base.document,r.data.document)),'<button data-restore="'+id+'" class="primary">Restaurar como nova publicação</button>')}catch(e){error(e)}}
async function discard(){if(busy)return;clearTimeout(timer);if(saving)await saving;busy=true;try{await rpc('iasd_editor_discard',{p_expected:draftRevision});const r=await rpc('iasd_editor_published',{});base=r;history=new M.History(r.document);draftRevision=0;lastSaved=M.canonical(r.document);conflict=false;localStorage.removeItem(localKey);send();inspector();root.querySelector('.ed-dialog')?.remove();status('Rascunho descartado. Conteúdo publicado preservado.')}catch(e){error(e)}finally{busy=false;counts()}}
function fit(){if(!frame)return;root.style.setProperty('--ed-footer-height',root.querySelector('footer').offsetHeight+'px');const stage=$('ed-stage'),scale=Math.min(1,(stage.clientWidth-8)/width),height=Math.max(300,Math.round(stage.clientHeight/scale));frame.style.width=width+'px';frame.style.height=height+'px';frame.style.transform='scale('+scale+')';$('ed-framewrap').style.width=width*scale+'px';$('ed-framewrap').style.height=height*scale+'px';}
async function close(){clearTimeout(timer);const persisted=local();let synced=M.canonical(doc())===lastSaved;if(queued||!synced)synced=await save();if(!persisted&&!synced&&IASDEdit.allowed()){dialog('Preserve seu rascunho','<p>O armazenamento local e a sincronização falharam. Exporte o rascunho antes de fechar esta janela.</p>','<button data-action="export">Exportar rascunho</button>');return}abort?.abort();resizeObserver?.disconnect();root?.remove();root=null;frame=null;document.body.style.overflow='';document.querySelector('[data-act="account"]')?.focus();}
async function open(select,preset){pendingPreset=preset||null;if(saving)await saving;if(root){selected=select||selected;inspector();if(pendingPreset){const c=list.find(c=>c.slot===pendingPreset.slot)||(/^home_banner(?:_[1-9][0-9]*)?$/.test(pendingPreset.slot)?list.find(c=>c.id==='banner'):null);if(c&&M.path(pendingPreset.path)){selected=c.id;inspector();frameSlot=pendingPreset.slot;choose(pendingPreset.path)}pendingPreset=null}return}if(!IASDEdit.allowed())return;uid=window.iasdCurrentUser?.()?.id;if(!uid)return;localKey='iasd-editor-draft:'+uid;status('');let cached=null;try{cached=JSON.parse(localStorage.getItem(localKey)||'null')}catch(e){}let published,r,recoveredOffline=false;try{published=await rpc('iasd_editor_published',{});r=await window.iasdCloud.from('iasd_editor_drafts').select('*').eq('user_id',uid).maybeSingle();if(r.error)throw Error(r.error.message)}catch(e){if(!cached||M.validate(cached.document).length)throw e;published=cached.base;r={data:null};recoveredOffline=true;}
 base=published;draftRevision=r.data?.draft_revision??(recoveredOffline?cached?.draftRevision||0:0);let value=published.document;lastSaved=M.canonical(value);conflict=false;
 if(r.data){base={document:published.document,revision:r.data.base_revision,fingerprint:r.data.base_fingerprint};value=r.data.document;lastSaved=M.canonical(value);conflict=published.revision!==base.revision||published.fingerprint!==base.fingerprint;}
 try{const cached=JSON.parse(localStorage.getItem(localKey)||'null');if(cached&&!M.validate(cached.document).length&&(!r.data||M.canonical(cached.document)!==M.canonical(r.data.document))){value=cached.document;base=cached.base;conflict=base.revision!==published.revision||base.fingerprint!==published.fingerprint||!!(r.data&&cached.draftRevision!==r.data.draft_revision&&cached.at<Date.parse(r.data.updated_at));}}catch(e){}
 history=new M.History(value);selected=select||'banner';preview=false;busy=false;queued=false;framePending=null;list=[];width=1440;
 if(!document.getElementById('iasd-editor-css')){const link=document.createElement('link');link.id='iasd-editor-css';link.rel='stylesheet';link.href='/ui/editor.css?v=1';document.head.appendChild(link)}
 root=document.createElement('section');root.id='iasd-editor';root.setAttribute('aria-label','Modo de Edição');root.innerHTML='<header><button data-action="exit">← Sair</button><strong>IASD APP · Modo de Edição</strong><span id="ed-status" role="status" aria-live="polite"></span><button id="ed-undo" data-action="undo">↶ Desfazer</button><button id="ed-redo" data-action="redo">↷ Refazer</button><select id="ed-device" aria-label="Dispositivo da prévia"><option value="1440">PC · 1440</option><option value="768">Tablet · 768</option><option value="390">Celular · 390</option></select><button id="ed-preview" data-action="preview">◉ Visualizar</button><button id="ed-publish" data-action="publish" class="primary">Publicar</button></header><div class="ed-body"><div class="ed-stage" id="ed-stage"><div id="ed-framewrap" class="ed-framewrap"><iframe id="ed-canvas" title="Prévia privada do rascunho"></iframe></div></div><aside id="ed-inspector"></aside></div><footer><span id="ed-count"></span><button data-action="properties">Propriedades</button><button data-action="versions">Histórico</button><button data-action="conflict">Revisar conflito</button><button data-action="discard" class="danger">Descartar rascunho</button></footer>';
 document.body.appendChild(root);document.body.style.overflow='hidden';frame=$('ed-canvas');abort=new AbortController();const signal=abort.signal;
 window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow)return;if(e.data?.type==='iasd-editor-ready'){const different=M.canonical(list.map(c=>c.id))!==M.canonical(e.data.components.map(c=>c.id));list=e.data.components;if(different)inspector();if(pendingPreset){const c=list.find(c=>c.slot===pendingPreset.slot)||(/^home_banner(?:_[1-9][0-9]*)?$/.test(pendingPreset.slot)?list.find(c=>c.id==='banner'):null);if(c&&perms().assets&&M.path(pendingPreset.path)){selected=c.id;inspector();frameSlot=pendingPreset.slot;choose(pendingPreset.path);}else status('Este componente está protegido ou não foi cadastrado para edição.');pendingPreset=null;}if(!frame.dataset.started){frame.dataset.started='1';send()}}if(e.data?.type==='iasd-editor-select'){selected=e.data.id;inspector();$('ed-inspector').classList.remove('collapsed')}},{signal});
 let drag=null;root.addEventListener('pointerdown',e=>{const box=e.target.closest('#ed-image');if(!box||!perms().assets||!doc().assets[frameSlot])return;drag={x:e.clientX,y:e.clientY,frame:clone(framePending),box};box.setPointerCapture(e.pointerId)},{signal});root.addEventListener('pointermove',e=>{if(!drag)return;framePending.position_x=Math.round(Math.max(0,Math.min(100,drag.frame.position_x+(drag.x-e.clientX)/drag.box.clientWidth*100)));framePending.position_y=Math.round(Math.max(0,Math.min(100,drag.frame.position_y+(drag.y-e.clientY)/drag.box.clientHeight*100)));updateFrame()},{signal});root.addEventListener('pointerup',()=>drag=null,{signal});root.addEventListener('pointercancel',()=>drag=null,{signal});let dragged=null;root.addEventListener('dragstart',e=>{dragged=e.target.closest('[data-order-id]')?.dataset.orderId;if(dragged)e.dataTransfer.setData('text/plain',dragged)},{signal});root.addEventListener('dragover',e=>{if(dragged&&e.target.closest('[data-order-id]'))e.preventDefault()},{signal});root.addEventListener('drop',e=>{const target=e.target.closest('[data-order-id]')?.dataset.orderId;if(!dragged||!target||!perms().texts)return;e.preventDefault();const from=dragged;dragged=null;changed('',d=>{const p=JSON.parse(d.texts.home_editor_props||'{}'),a=list.filter(c=>c.type==='card').sort((a,b)=>(p[a.id]?.order??list.indexOf(a))-(p[b.id]?.order??list.indexOf(b))).map(c=>c.id),i=a.indexOf(from),j=a.indexOf(target);if(i<0||j<0)return;a.splice(i,1);a.splice(j,0,from);a.forEach((id,n)=>p[id]={...(p[id]||{}),order:n});d.texts.home_editor_props=JSON.stringify(p)});inspector()},{signal});root.addEventListener('dragend',()=>dragged=null,{signal});root.addEventListener('input',onInput,{signal});root.addEventListener('change',onChange,{signal});root.addEventListener('click',onClick,{signal});
 window.addEventListener('online',()=>{if(root)save()},{signal});window.addEventListener('beforeunload',e=>{if(root){local();if(!localAvailable||saving||M.canonical(doc())!==lastSaved){e.preventDefault();e.returnValue=''}}},{signal});
 window.addEventListener('keydown',e=>{if(e.key==='Escape'){root.querySelector('.ed-dialog')?.remove();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();travel(e.shiftKey?'redo':'undo')}},{signal});
 resizeObserver=new ResizeObserver(fit);resizeObserver.observe($('ed-stage'));frame.src='/?editor-preview=1&ui=new';inspector();fit();counts();local();status(conflict?'Conflito detectado. Revise antes de publicar.':M.diff(base.document,doc()).length?'Rascunho recuperado.':'Rascunho privado • nenhuma alteração publicada.');$('ed-preview').focus();
}
function travel(action){if(busy||conflict)return;if(history[action]()){local();send();inspector();counts();clearTimeout(timer);timer=setTimeout(save,900)}}
function onInput(e){const el=e.target;if(el.dataset.text&&perms().texts)changed(el.dataset.text,d=>{d.texts[el.dataset.text]=el.value;if(el.dataset.text==='home_carousel_seconds'){const cfg=JSON.parse(d.texts.home_carousel_cfg||'{}');cfg.sec=Number(el.value);d.texts.home_carousel_cfg=JSON.stringify(cfg)}});if(el.dataset.prop&&perms().texts&&el.type!=='checkbox'&&el.tagName!=='SELECT')prop(el.dataset.prop,el.value);if(el.dataset.frame&&perms().assets){framePending[el.dataset.frame]=Number(el.value);updateFrame()}if(el.dataset.tabField&&perms().tabs){const id=el.closest('[data-tab]').dataset.tab;changed(id+el.dataset.tabField,d=>d.tabs.find(t=>t.id===id)[el.dataset.tabField]=el.value)}}
function onChange(e){const el=e.target;if(el.dataset.carousel){carouselChange(c=>c[el.dataset.carousel]=el.type==='checkbox'?el.checked:el.value);}if(el.id==='ed-component'){selected=el.value;inspector()}if(el.id==='ed-device'){width=Number(el.value);fit()}if(el.id==='ed-upload')upload(el.files[0]);if(el.id==='ed-banner-slot'){frameSlot=el.value;frameConfirmed=clone(doc().frames[frameSlot]||{position_x:50,position_y:50,zoom:1});framePending=clone(frameConfirmed);updateFrame()}if(el.dataset.prop&&perms().texts){if(el.type==='checkbox')prop(el.dataset.prop,el.checked);else if(el.tagName==='SELECT'&&el.value)prop(el.dataset.prop,el.value)}}
async function onClick(e){const b=e.target.closest('button');if(!b||b.disabled||busy)return;if(b.dataset.slide){carouselChange((c,d)=>{const order=[...(c.order||[]).filter(s=>d.assets[s]),...Object.keys(d.assets).filter(s=>/^home_banner(?:_[1-9][0-9]*)?$/.test(s)&&!(c.order||[]).includes(s))],i=order.indexOf(b.dataset.slide),j=i+Number(b.dataset.dir);if(i>=0&&j>=0&&j<order.length)[order[i],order[j]]=[order[j],order[i]];c.order=order});inspector();return}if(b.dataset.slideToggle){carouselChange(c=>{const off=c.off||[],slot=b.dataset.slideToggle;c.off=off.includes(slot)?off.filter(s=>s!==slot):[...off,slot]});inspector();return}if(b.dataset.image){choose(b.dataset.image);return}if(b.dataset.move){reorder(b.dataset.move,Number(b.dataset.dir));return}if(b.dataset.tabOrder){reorder(b.dataset.tabOrder,Number(b.dataset.dir),true);return}if(b.dataset.deleteTab&&perms().tabs){dialog('Remover aba do rascunho?','<p>A aba publicada continua disponível até você publicar.</p>','<button data-delete-confirm="'+E(b.dataset.deleteTab)+'" class="danger">Remover</button>');return}if(b.dataset.deleteConfirm){changed('',d=>{d.tabs=d.tabs.filter(t=>t.id!==b.dataset.deleteConfirm);delete d.assets['custom_cover_'+b.dataset.deleteConfirm];delete d.frames['custom_cover_'+b.dataset.deleteConfirm];const p=JSON.parse(d.texts.home_editor_props||'{}');delete p['card:custom_cover_'+b.dataset.deleteConfirm];for(const v of Object.values(p))if(v.destination==='custom:'+b.dataset.deleteConfirm)delete v.destination;d.texts.home_editor_props=JSON.stringify(p)});root.querySelector('.ed-dialog')?.remove();inspector();return}if(b.dataset.moreHistory){versions(Number(b.dataset.moreHistory));return}if(b.dataset.compare){compare(Number(b.dataset.compare));return}if(b.dataset.restore){publish(Number(b.dataset.restore));return}
 switch(b.dataset.action){case 'exit':close();break;case 'undo':travel('undo');break;case 'redo':travel('redo');break;case 'preview':preview=!preview;root.querySelector('header strong').textContent=preview?'IASD APP · Prévia do rascunho':'IASD APP · Modo de Edição';root.classList.toggle('ed-preview',preview);$('ed-preview').textContent=preview?'← Voltar à edição':'◉ Visualizar';send();fit();break;case 'properties':$('ed-inspector').classList.toggle('collapsed');break;case 'library':library();break;case 'frame-reset':framePending={position_x:50,position_y:50,zoom:1};updateFrame();break;case 'frame-cancel':framePending=clone(frameConfirmed);updateFrame();break;case 'frame-confirm':if(perms().assets){changed('',d=>d.frames[frameSlot]=clone(framePending));frameConfirmed=clone(framePending)}break;case 'image-remove':if(perms().assets){changed('',d=>{delete d.assets[frameSlot];delete d.frames[frameSlot];if(/^home_banner/.test(frameSlot)&&d.texts.home_carousel_cfg){const c=JSON.parse(d.texts.home_carousel_cfg);for(const k of ['order','off'])c[k]=(c[k]||[]).filter(s=>s!==frameSlot);d.texts.home_carousel_cfg=JSON.stringify(c)}});updateFrame()}break;case 'add-slide':if(perms().assets){const nums=Object.keys(doc().assets).filter(s=>/^home_banner_[1-9][0-9]*$/.test(s)).map(s=>Number(s.slice(12)));frameSlot='home_banner_'+(Math.max(0,...nums)+1);status('Escolha uma imagem na biblioteca ou importe um arquivo para a nova posição.');library()}break;case 'new-tab':if(perms().tabs){changed('',d=>d.tabs.push({id:crypto.randomUUID(),title:'Nova aba',description:'',icon:'✦',sort_order:100+d.tabs.length}));inspector()}break;case 'publish':await confirmPublish();break;case 'publish-confirm':await publish();break;case 'versions':await versions();break;case 'dialog-close':root.querySelector('.ed-dialog')?.remove();break;case 'discard':dialog('Descartar rascunho?','<p>As alterações privadas serão removidas. O site publicado e o histórico permanecem disponíveis.</p>','<button data-action="discard-confirm" class="danger">Confirmar descarte</button>');break;case 'discard-confirm':await discard();break;case 'conflict':dialog('Conflito de edição','<p>Para evitar sobrescrever outro administrador, a publicação está bloqueada quando a base muda. Exporte seu rascunho antes de descartá-lo e carregar a versão publicada atual.</p>','<button data-action="export">Exportar rascunho</button><button data-action="discard" class="danger">Descartar e carregar atual</button>');break;case 'export':{const url=URL.createObjectURL(new Blob([JSON.stringify({base,document:doc()},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='iasd-rascunho.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break}}
}
window.IASDEditor={open,checkAccess(){if(root&&!IASDEdit.allowed()){local();close()}},get active(){return !!root}};
})();
