(function(){
'use strict';
const tabs=['Visão geral','Igrejas','Dispositivos','Tokens','QR Codes','Alertas'];
const state={tab:'Igrejas',query:'',filter:'Todas',selected:'c1',dialog:null,notice:'',churches:[{id:'c1',name:'Igreja exemplo — Centro',city:'Salvador / BA',status:'Ativa',owner:'Responsável exemplo',email:'contato@example.com'},{id:'c2',name:'Igreja exemplo — Norte',city:'Feira de Santana / BA',status:'Ativa',owner:'Responsável exemplo',email:'norte@example.com'},{id:'c3',name:'Igreja exemplo — Sul',city:'Vitória da Conquista / BA',status:'Pendente',owner:'A definir',email:''}],devices:[{id:'d1',name:'Studio Principal',church:'c1',status:'Online',detail:'Windows · Studio PC'},{id:'d2',name:'Sala Jovem',church:'c1',status:'Offline',detail:'Windows · Studio PC'},{id:'d3',name:'Sonoplastia',church:'c2',status:'Online',detail:'Windows · Studio PC'}],tokens:[{id:'t1',name:'Vinculação do Studio Principal',church:'c1',status:'Disponível',detail:'Uso único · validade de 10 minutos',code:'DEMO-123456'},{id:'t2',name:'Vinculação da Sala Jovem',church:'c1',status:'Utilizado',detail:'Uso único · dispositivo vinculado',code:'DEMO-654321'}],qrs:[{id:'q1',name:'Cadastro do computador',church:'c2',status:'Pendente',detail:'Ativação por celular · uso único'}],alerts:[{id:'a1',name:'Ajustar o volume da trilha',church:'c1',status:'Respondido',detail:'Exemplo de mensagem · resposta: volume ajustado'},{id:'a2',name:'Preparar o próximo vídeo',church:'c2',status:'Pendente',detail:'Exemplo de mensagem · aguardando resposta'}]};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>'<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="'+({church:'M4 21h16V10l-8-6-8 6v11M12 1v6M9 3h6M9 21v-7h6v7',device:'M3 4h18v12H3zM12 16v5M8 21h8',key:'M14 10a5 5 0 1 0-4 4l-7 7H1v-3l7-7',qr:'M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h3v3h3v3h-6z',bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5l-2 3M10 21h4',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',search:'M21 21l-5-5M17 10a7 7 0 1 0-14 0 7 7 0 0 0 14 0',plus:'M12 5v14M5 12h14',close:'M6 6l12 12M6 18L18 6',arrow:'M9 5l7 7-7 7'}[n]||'M5 12h14')+'"/></svg>';
const keys={'Igrejas':'churches','Dispositivos':'devices','Tokens':'tokens','QR Codes':'qrs','Alertas':'alerts'};
const descriptions={'Igrejas':'Gerencie as igrejas que utilizam o IASD Studio.','Dispositivos':'Computadores vinculados, conexão e acesso ao programa.','Tokens':'Códigos temporários para vincular um computador à igreja.','QR Codes':'Vinculações por celular e solicitações de cadastro.','Alertas':'Acompanhe mensagens enviadas à sonoplastia de cada igreja.'};
const actions={'Igrejas':'Cadastrar igreja','Dispositivos':'Vincular dispositivo','Tokens':'Gerar token','QR Codes':'Criar QR Code','Alertas':'Novo alerta'};
const church=id=>state.churches.find(c=>c.id===id);
const count=id=>state.devices.filter(d=>d.church===id).length;
const badge=s=>'<span class="sa-status '+(['Ativa','Online','Disponível','Respondido'].includes(s)?'good':['Revogado','Suspensa'].includes(s)?'bad':'wait')+'"><i></i>'+esc(s)+'</span>';
const button=(label,action,extra='',primary=false)=>'<button type="button" class="sa-button'+(primary?' primary':'')+'" data-sa="'+action+'" '+extra+'>'+label+'</button>';
function redraw(){const root=document.getElementById('studio-admin');if(root)root.outerHTML=render();}
function table(){const rows=state[keys[state.tab]].filter(r=>(r.name+' '+(r.city||church(r.church)?.name||'')).toLocaleLowerCase().includes(state.query.toLocaleLowerCase())&&(state.filter==='Todas'||r.status===state.filter));const churches=state.tab==='Igrejas';return '<div class="sa-table-scroll"><table><thead><tr><th>'+esc(churches?'Igreja':state.tab==='Dispositivos'?'Dispositivo':state.tab==='Alertas'?'Mensagem':'Identificação')+'</th><th>'+esc(churches?'Localização':'Igreja')+'</th><th>'+esc(churches?'Dispositivos':'Detalhes')+'</th><th>Situação</th><th>Ações</th></tr></thead><tbody>'+rows.map(r=>'<tr class="'+(state.selected===r.id?'selected':'')+'"><td><div class="sa-name">'+icon(churches?'church':state.tab==='Dispositivos'?'device':state.tab==='Tokens'?'key':state.tab==='QR Codes'?'qr':'bell')+'<b>'+esc(r.name)+'</b></div></td><td>'+esc(churches?r.city:church(r.church)?.name||'—')+'</td><td>'+esc(churches?count(r.id)+(count(r.id)===1?' dispositivo':' dispositivos'):r.detail)+'</td><td>'+badge(r.status)+'</td><td>'+button('Ver detalhes '+icon('arrow'),'detail','data-id="'+esc(r.id)+'"')+'</td></tr>').join('')+'</tbody></table>'+(rows.length?'':'<div class="sa-empty">Nenhum resultado. Tente outro nome ou filtro.</div>')+'</div><footer class="sa-footer">'+rows.length+' '+esc(state.tab.toLocaleLowerCase())+' de demonstração</footer>';}
function details(){const r=state[keys[state.tab]]?.find(x=>x.id===state.selected);if(!r)return '<aside class="sa-detail"><h3>Detalhes</h3><p>Selecione um item para consultar e administrar.</p></aside>';const isChurch=state.tab==='Igrejas',c=isChurch?r:church(r.church);return '<aside class="sa-detail"><div class="sa-detail-top"><h3>'+esc(r.name)+'</h3>'+button(icon('close'),'close-detail','aria-label="Fechar detalhes"')+'</div>'+badge(r.status)+'<h4>'+esc(isChurch?'Informações da igreja':'Informações')+'</h4><dl><dt>Nome</dt><dd>'+esc(r.name)+'</dd><dt>Igreja</dt><dd>'+esc(c?.name||'—')+'</dd><dt>Localização</dt><dd>'+esc(c?.city||'—')+'</dd>'+(isChurch?'<dt>Contato</dt><dd>'+esc(r.email||'Não informado')+'</dd><dt>Responsável</dt><dd>'+esc(r.owner)+'</dd>':'<dt>Detalhes</dt><dd>'+esc(r.detail)+'</dd>')+'</dl>'+(state.tab==='Tokens'?'<div class="sa-code"><small>Código de demonstração — não vincula PCs</small><strong>'+esc(r.code)+'</strong></div>':'')+(state.tab==='QR Codes'?'<div class="sa-empty">'+icon('qr')+'<b>Prévia da ativação por QR Code</b><p>O código real será gerado após integrar a vinculação.</p></div>':'')+(isChurch?'<h4>Dispositivos ('+count(r.id)+')</h4>'+state.devices.filter(d=>d.church===r.id).map(d=>'<div class="sa-device">'+icon('device')+'<span>'+esc(d.name)+'</span>'+badge(d.status)+'</div>').join('')+button('Gerenciar acessos '+icon('arrow'),'tab','data-tab="Tokens"',true):button(esc(state.tab==='Alertas'?'Ver resposta':'Revogar acesso'),'revoke','data-id="'+esc(r.id)+'"'))+'<p class="sa-muted">Prévia: alterações válidas apenas nesta sessão.</p></aside>';}
function overview(){return '<div class="sa-overview"><h2>Visão geral</h2><p>Acompanhe igrejas, computadores e solicitações de acesso.</p><div class="sa-metrics">'+[['Igrejas',state.churches.length],['Dispositivos',state.devices.length],['Tokens',state.tokens.filter(t=>t.status==='Disponível').length],['Alertas',state.alerts.filter(a=>a.status==='Pendente').length]].map(([t,n])=>button('<strong>'+n+'</strong><span>'+esc(t)+'</span>','tab','data-tab="'+t+'"')).join('')+'</div><div class="sa-overview-columns"><section><h3>Últimas atividades de demonstração</h3><div class="sa-activity">'+icon('device')+'<div><b>Studio Principal vinculado</b><p>Igreja exemplo — Centro · ativação por token</p></div></div><div class="sa-activity">'+icon('bell')+'<div><b>Alerta respondido</b><p>Ajustar o volume da trilha</p></div></div><div class="sa-activity">'+icon('church')+'<div><b>Igreja aguardando cadastro</b><p>Igreja exemplo — Sul</p></div></div></section><section><h3>Conexão deste computador</h3>'+button('Abrir painel do projetor','local', '',true)+'<p>Consulte o painel já existente com a conexão e a equipe em serviço.</p></section></div></div>';}
function modal(){if(!state.dialog)return '';const t=state.dialog;return '<div class="sa-modal-backdrop"><section class="sa-modal" role="dialog" aria-modal="true" aria-labelledby="sa-modal-title"><div class="sa-detail-top"><h3 id="sa-modal-title">'+esc(actions[t])+'</h3>'+button(icon('close'),'close-modal','aria-label="Fechar formulário"')+'</div><p>Cadastro de demonstração. Nenhum acesso real será criado.</p><form id="sa-form"><label>'+esc(t==='Alertas'?'Mensagem':t==='Igrejas'?'Nome da igreja':'Nome / identificação')+'<input name="name" required maxlength="100" autocomplete="off"></label>'+(t==='Igrejas'?'<label>Cidade / estado<input name="city" required maxlength="80"></label><label>Responsável<input name="owner" required maxlength="80"></label><label>E-mail<input name="email" type="email" maxlength="120"></label>':'<label>Igreja<select name="church">'+state.churches.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('')+'</select></label>')+(t==='Tokens'?'<label>Validade<select name="duration"><option>10 minutos</option><option>30 minutos</option><option>1 hora</option></select></label><p>Código temporário e de uso único. O acesso do dispositivo será gerenciado separadamente.</p>':'')+'<div class="sa-modal-actions">'+button('Cancelar','close-modal')+'<button class="sa-button primary" type="submit">'+esc(t==='Alertas'?'Simular envio':'Salvar na prévia')+'</button></div></form></section></div>';}
function render(){return '<section id="studio-admin" class="studio-admin iu-home"><div class="sa-heading"><div><img src="/shots/studio-entry/logo.svg" alt="" width="50" height="50"><div><h1>Administração do IASD Studio</h1><p>Igrejas, dispositivos e acessos em um só lugar.</p></div></div><span class="sa-preview">Prévia da interface · Dados de demonstração</span></div><nav class="sa-tabs" aria-label="Seções da administração">'+tabs.map((t,i)=>button(icon(['grid','church','device','key','qr','bell'][i])+esc(t),'tab','data-tab="'+t+'" aria-current="'+(t===state.tab?'page':'false')+'"')).join('')+'</nav>'+(state.notice?'<div class="sa-notice" role="status">'+esc(state.notice)+'</div>':'')+(state.tab==='Visão geral'?overview():state.tab==='Projetor local'?'<section class="sa-local"><h2>Conexão deste computador</h2>'+button('Voltar à visão geral','tab','data-tab="Visão geral"')+'<div id="sa-local-slot"></div></section>':'<div class="sa-layout"><section class="sa-list"><div class="sa-toolbar"><div><h2>'+esc(state.tab)+'</h2><p>'+esc(descriptions[state.tab])+'</p></div><div class="sa-tools"><label class="sa-search">'+icon('search')+'<input data-sa-search aria-label="Pesquisar '+esc(state.tab.toLocaleLowerCase())+'" placeholder="Pesquisar '+esc(state.tab.toLocaleLowerCase())+'..." value="'+esc(state.query)+'"></label>'+button(icon('plus')+esc(actions[state.tab]),'new','',true)+'</div></div><div class="sa-filter"><label>Situação <select data-sa-filter><option>Todas</option>'+[...new Set(state[keys[state.tab]].map(r=>r.status))].map(v=>'<option'+(state.filter===v?' selected':'')+'>'+esc(v)+'</option>').join('')+'</select></label></div>'+table()+'</section>'+details()+'</div>')+modal()+'</section>';}
document.addEventListener('click',e=>{const b=e.target.closest('[data-sa]');if(!b||!b.closest('#studio-admin'))return;const a=b.dataset.sa;if(a==='tab'){state.tab=b.dataset.tab;state.selected=state[keys[state.tab]]?.[0]?.id||null;state.query='';state.filter='Todas';state.notice='';}if(a==='detail')state.selected=b.dataset.id;if(a==='close-detail')state.selected=null;if(a==='new')state.dialog=state.tab;if(a==='close-modal')state.dialog=null;if(a==='revoke'){const r=state[keys[state.tab]].find(x=>x.id===b.dataset.id);if(state.tab==='Alertas')state.notice=r.detail;else{r.status='Revogado';state.notice='Acesso revogado na demonstração. Nenhum dispositivo real foi afetado.';}}if(a==='local'){state.tab='Projetor local';redraw();const slot=document.getElementById('sa-local-slot');if(slot&&window.IASDUI?.localProjectorPanel)slot.innerHTML=window.IASDUI.localProjectorPanel();return;}redraw();if(a==='new')document.querySelector('#sa-form input')?.focus();});
document.addEventListener('input',e=>{if(!e.target.matches('[data-sa-search]'))return;state.query=e.target.value;state.selected=null;const pos=e.target.selectionStart;redraw();const input=document.querySelector('[data-sa-search]');input?.focus();input?.setSelectionRange(pos,pos);});
document.addEventListener('change',e=>{if(e.target.matches('[data-sa-filter]')){state.filter=e.target.value;redraw();}});
document.addEventListener('submit',e=>{if(e.target.id!=='sa-form')return;e.preventDefault();const f=new FormData(e.target),t=state.dialog,r={id:'demo-'+Date.now(),name:f.get('name'),church:f.get('church'),status:t==='Igrejas'?'Pendente':t==='Dispositivos'?'Offline':t==='Tokens'?'Disponível':'Pendente',detail:t==='Tokens'?'Uso único · validade de '+f.get('duration'):t==='Dispositivos'?'Aguardando vinculação de demonstração':'Criado nesta prévia'};if(t==='Igrejas')Object.assign(r,{city:f.get('city'),owner:f.get('owner'),email:f.get('email')});if(t==='Tokens')r.code='DEMO-'+String(state.tokens.length+1).padStart(6,'0');state[keys[t]].unshift(r);state.selected=r.id;state.dialog=null;state.notice=t==='Alertas'?'Envio simulado. Nenhuma mensagem foi enviada.':'Registro adicionado à prévia. Nenhum dado foi enviado ao servidor.';redraw();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.dialog){state.dialog=null;redraw();}});
window.IASDStudioAdmin={render};
})();
