/* Microfone local e câmera remota. O celular envia somente mídia; não entra como aluno. */
(function(){
'use strict';
const K=()=>window.IASDEstudoCore,cloud=()=>window.iasdCloud,user=()=>window.iasdCurrentUser?.();
const $=id=>document.getElementById(id),esc=x=>K().esc(x),UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
let P=null,opening=false,micSerial=0,autoTimer=null,phoneViewKey='';
const prefKey=()=> 'iasd-study-mic-'+(user()?.id||'guest');
function micConstraints(){let id='';try{id=localStorage.getItem(prefKey())||''}catch(e){}return id?{deviceId:{exact:id}}:{}}
/* A permissão pode ficar pendente no navegador. A mídia tardia é liberada após o prazo. */
function acquire(constraints){let expired=false,timer;const request=navigator.mediaDevices.getUserMedia(constraints);request.then(st=>{if(expired)st.getTracks().forEach(t=>t.stop())}).catch(()=>{});return Promise.race([request,new Promise((resolve,reject)=>{timer=setTimeout(()=>{expired=true;reject(Error('Aguardando permissão do navegador. Permita o dispositivo e tente novamente.'))},20000)})]).finally(()=>clearTimeout(timer))}
function errorText(e){return e?.name==='NotAllowedError'?'Permita o acesso à câmera ou ao microfone no navegador.':e?.name==='NotFoundError'?'Dispositivo não encontrado. Escolha outro.':e?.name==='NotReadableError'?'O dispositivo está ocupado por outro aplicativo.':e?.name==='OverconstrainedError'?'O dispositivo escolhido não está mais conectado. Escolha outro.':e?.message||'Não foi possível acessar o dispositivo.'}
function panel(title){$('es-devices')?.remove();const o=document.createElement('div');o.id='es-devices';o.className='es-expw';o.innerHTML='<section class="es-expb" role="dialog" aria-modal="true" aria-label="'+esc(title)+'"><header class="es-exph"><b>'+esc(title)+'</b><button type="button" class="es-expx" aria-label="Fechar">×</button></header><div class="es-expc" id="study-device-body"></div><footer class="es-expf"><button type="button" class="study-device-close">Fechar</button></footer></section>';document.body.appendChild(o);o.querySelectorAll('.es-expx,.study-device-close').forEach(b=>b.onclick=()=>{if(P?.role==='phone')stopPhone();o.remove()});o.addEventListener('keydown',e=>{if(e.key==='Escape')o.remove()});o.querySelector('.es-expx').focus();return $('study-device-body')}
function status(text){if(P)P.status=text;const el=$('study-camera-status');if(el)el.textContent=text}
async function deviceOptions(select,selected){if(!navigator.mediaDevices?.enumerateDevices){select.disabled=true;return}const list=await navigator.mediaDevices.enumerateDevices();select.innerHTML='<option value="">Microfone padrão do aparelho</option>'+list.filter(d=>d.kind==='audioinput'&&d.deviceId!=='default').map((d,i)=>'<option value="'+esc(d.deviceId)+'">'+esc(d.label||'Microfone '+(i+1))+'</option>').join('');select.value=selected||''}
async function chooseMic(id){const token=++micSerial,R=K().S.room;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Microfone indisponível neste navegador.');const st=await acquire({audio:{...K().mediaConstraints().audio,...(id?{deviceId:{exact:id}}:{})},video:false});if(token!==micSerial||K().S.room!==R||!R){st.getTracks().forEach(t=>t.stop());return}disablePhoneMic();await K().replaceMediaTrack('audio',st.getAudioTracks()[0],'local');try{localStorage.setItem(prefKey(),id)}catch(e){}K().toast('Microfone escolhido e ligado.');await deviceOptions($('study-mic'),id)}catch(e){K().toast(errorText(e))}}
async function open(){if(!K().S.room){K().toast('Entre em uma sala para escolher os dispositivos.');return}const body=panel('Microfone e câmera');body.innerHTML='<label for="study-mic">Microfone deste aparelho</label><select id="study-mic"></select><button type="button" id="study-mic-use">Usar e ligar microfone</button><p>Os nomes aparecem depois de permitir o microfone.</p>'+(K().canCameraPhone()?'<hr><h3>Câmera do celular</h3><p>Use o celular como câmera desta chamada. Entre na mesma conta administrativa nos dois aparelhos.</p><button type="button" id="study-phone-open">'+(P?.role==='pc'?'Ver conexão do celular':'Conectar celular')+'</button>':'');await deviceOptions($('study-mic'),micConstraints().deviceId?.exact);$('study-mic-use').onclick=()=>chooseMic($('study-mic').value);if($('study-phone-open'))$('study-phone-open').onclick=startPC}
function pairFromURL(){const u=new URL(location.href),owner=u.searchParams.get('cameraOwner'),id=u.searchParams.get('camera');return UUID.test(owner||'')&&UUID.test(id||'')?{owner,id}:null}
function storageKey(p){return 'iasd-study-camera-'+p.owner+'-'+p.id}
function persistPhone(p,enabled){try{if(enabled)localStorage.setItem(storageKey(p),JSON.stringify({until:Date.now()+12*3600000,mic:p.useMic,facing:p.facing||'environment'}));else localStorage.removeItem(storageKey(p))}catch(e){}}
function allowedResume(pair){try{const v=JSON.parse(localStorage.getItem(storageKey(pair))||'null');return v&&v.until>Date.now()?v:null}catch(e){return null}}
function pcPersist(p){try{if(p)sessionStorage.setItem('iasd-study-camera-pc',JSON.stringify({id:p.id,owner:p.owner,room:p.room,useMic:p.useMic,until:Date.now()+12*3600000}));else sessionStorage.removeItem('iasd-study-camera-pc')}catch(e){}}
async function startPC(){if(opening)return;if(!K().canCameraPhone()||!K().S.room){K().toast('Recurso exclusivo para administradores dentro da sala.');return}if(P?.role==='pc'){renderPC();return}opening=true;try{const p=P={role:'pc',owner:user().id,id:crypto.randomUUID(),room:K().S.room.code,client:crypto.randomUUID(),last:0,status:'Preparando conexão…',useMic:false};renderPC();await connect(p);if(P!==p)return;pcPersist(p);status('Aguardando o celular. O vínculo será mantido se a conexão cair.')}catch(e){status(errorText(e));await stopPhone(false)}finally{opening=false}}
function renderPC(){const p=P;if(!p)return;const body=panel('Câmera do celular');const url=new URL('/estudo',location.origin);url.searchParams.set('cameraOwner',p.owner);url.searchParams.set('camera',p.id);body.innerHTML='<p>Leia o QR code no celular e entre na mesma conta. Toque em “Iniciar câmera” no celular.</p><div class="study-camera-qr" id="study-camera-qr"></div><label for="study-camera-link">Link do celular</label><input id="study-camera-link" readonly value="'+esc(url.href)+'"><button type="button" id="study-camera-copy">Copiar link</button><p id="study-camera-status" role="status">'+esc(p.status||'Aguardando celular…')+'</p><video class="study-camera-preview" id="study-camera-preview" autoplay muted playsinline hidden></video><p>O vídeo será usado como sua câmera na chamada.</p><button type="button" id="study-phone-mic">'+(p.useMic?'Desligar microfone do celular':'Usar microfone do celular')+'</button><p id="study-phone-mic-status">O microfone atual do PC continua ativo até você escolher o do celular.</p><button type="button" id="study-camera-stop">Desvincular e desligar</button>';if(window.qrcode){const qr=qrcode(0,'M');qr.addData(url.href);qr.make();$('study-camera-qr').innerHTML=qr.createSvgTag({scalable:true,margin:16})}$('study-camera-copy').onclick=async()=>{try{await navigator.clipboard.writeText(url.href);K().toast('Link copiado.')}catch(e){$('study-camera-link').select();K().toast('Selecione e copie o link.')}};$('study-camera-stop').onclick=()=>stopPhone();$('study-phone-mic').onclick=async()=>{p.useMic=!p.useMic;pcPersist(p);await message(p,'mic',{on:p.useMic});$('study-phone-mic').textContent=p.useMic?'Desligar microfone do celular':'Usar microfone do celular';$('study-phone-mic-status').textContent=p.useMic?'Aguardando permissão do microfone no celular…':'Microfone do celular desligado. Escolha o microfone local se quiser falar.';if(!p.useMic&&phoneMicActive())K().stopMic()};showPreview(p)}
function renderPhone(pair,resume){const body=panel('Celular como câmera');body.innerHTML='<p>Mantenha esta página aberta durante a chamada. O som da sala fica no PC para evitar eco.</p><p id="study-camera-status" role="status">'+(user()?.id!==pair.owner?'Entre na mesma conta administrativa usada no PC.':K().canCameraPhone()?'Pronto para conectar.':'Disponível apenas para fundador, cofundador e administrador.')+'</p>'+(!user()?'<button type="button" id="study-phone-login">Entrar na conta do PC</button>':'')+'<label for="study-phone-facing">Câmera</label><select id="study-phone-facing"><option value="environment">Traseira</option><option value="user">Frontal</option></select><label for="study-phone-local-mic">Microfone do celular</label><select id="study-phone-local-mic"></select><button type="button" id="study-phone-start">Iniciar câmera</button><button type="button" id="study-phone-allow-mic" hidden>Permitir microfone do celular</button><video class="study-camera-preview" id="study-camera-preview" autoplay muted playsinline hidden></video><button type="button" id="study-camera-stop">Parar transmissão</button>';if($('study-phone-login'))$('study-phone-login').onclick=()=>{$('es-devices')?.remove();window.IASDAuth?.open(false)};deviceOptions($('study-phone-local-mic'));$('study-phone-facing').value=resume?.facing||'environment';$('study-phone-start').disabled=user()?.id!==pair.owner||!K().canCameraPhone();$('study-phone-start').onclick=()=>startPhone(pair);$('study-camera-stop').onclick=()=>stopPhone();$('study-phone-facing').onchange=()=>{if(P?.role==='phone')switchPhoneCamera($('study-phone-facing').value)};$('study-phone-local-mic').onchange=()=>{if(P?.role==='phone'&&P.useMic)phoneMic(P,true)};$('study-phone-allow-mic').onclick=()=>{if(P?.role==='phone')phoneMic(P,true)};if(resume&&!$('study-phone-start').disabled)startPhone(pair,resume)}
async function startPhone(pair,resume){if(opening||P?.role==='phone')return;if(user()?.id!==pair.owner||!K().canCameraPhone()){K().toast('Entre na mesma conta administrativa do PC.');return}opening=true;const p=P={...pair,role:'phone',client:crypto.randomUUID(),last:0,status:'Preparando câmera…',facing:resume?.facing||$('study-phone-facing')?.value||'environment',useMic:!!resume?.mic};try{status('Permita a câmera no navegador do celular para iniciar.');await captureVideo(p);if(P!==p)return;await connect(p);if(P!==p)return;persistPhone(p,true);$('study-phone-start').disabled=true;status('Aguardando o PC…');if(p.useMic)await phoneMic(p,true);await message(p,'hello',{});}catch(e){status(errorText(e)+' Toque em Iniciar câmera para tentar novamente.');await stopPhone(false);if($('study-phone-start'))$('study-phone-start').disabled=false}finally{opening=false}}
async function captureVideo(p){if(!navigator.mediaDevices?.getUserMedia)throw Error('Câmera indisponível. Use um navegador com HTTPS.');const stream=await acquire({audio:false,video:{...K().mediaConstraints().video,facingMode:{ideal:p.facing}}});if(P!==p){stream.getTracks().forEach(t=>t.stop());return}p.video=stream.getVideoTracks()[0];p.video.onended=()=>{if(P===p){phoneViewKey='';stopPhone(false).then(()=>status('Câmera suspensa. Toque em Iniciar câmera para retomar.'))}};showPreview(p)}
async function switchPhoneCamera(facing){const p=P;if(!p||p.role!=='phone')return;const old=p.video;p.facing=facing;try{await captureVideo(p);if(P!==p)return;if(p.pc)await p.pc.getSenders().find(s=>s.track?.kind==='video')?.replaceTrack(p.video);old?.stop();persistPhone(p,true)}catch(e){p.video=old;status(errorText(e))}}
async function phoneMic(p,on){try{if(!on){p.useMic=false;const old=p.audio;p.audio=null;if(p.pc?.audioSender)await p.pc.audioSender.replaceTrack(null);old?.stop();persistPhone(p,true);await message(p,'mic-state',{on:false});return}const select=$('study-phone-local-mic'),id=select?.value;const stream=await acquire({audio:{...K().mediaConstraints().audio,...(id?{deviceId:{exact:id}}:{})},video:false});if(P!==p){stream.getTracks().forEach(t=>t.stop());return}const old=p.audio;p.audio=stream.getAudioTracks()[0];p.useMic=true;if(p.pc?.audioSender)await p.pc.audioSender.replaceTrack(p.audio);old?.stop();persistPhone(p,true);if($('study-phone-allow-mic'))$('study-phone-allow-mic').hidden=true;await deviceOptions(select,id);await message(p,'mic-state',{on:true})}catch(e){p.useMic=false;status(errorText(e));if($('study-phone-allow-mic'))$('study-phone-allow-mic').hidden=false;await message(p,'mic-state',{on:false})}}
function showPreview(p){const el=$('study-camera-preview');const t=p.role==='phone'?p.video:p.remoteVideo;if(el&&t){el.hidden=false;el.srcObject=new MediaStream([t]);el.play()?.catch(()=>{})}}
async function message(p,event,data){if(P!==p||!p.channel||!p.ready)return;const result=await p.channel.send({type:'broadcast',event:'camera',payload:{role:p.role,client:p.client,to:event==='hello'?null:p.peer||null,event,data,time:Date.now()}});if(result!=='ok')throw Error('Conexão interrompida. Tentando reconectar…')}
async function connect(p){const c=cloud();if(!c)throw Error('Conexão com o site indisponível.');const ch=p.channel=c.channel('study-camera:'+p.owner+':'+p.id,{config:{private:true,broadcast:{self:false,ack:true}}});p.queue=Promise.resolve();ch.on('broadcast',{event:'camera'},({payload})=>{p.queue=p.queue.then(()=>receive(p,payload)).catch(e=>{if(P===p)status(errorText(e))})});await new Promise((resolve,reject)=>{let settled=false;const timer=setTimeout(()=>{if(!settled){settled=true;reject(Error('Não foi possível conectar o celular. Tente novamente.'))}},15000);ch.subscribe((state)=>{if(P!==p)return;if(state==='SUBSCRIBED'){p.ready=true;if(!settled){settled=true;clearTimeout(timer);resolve()}else{p.last=0;if(p.role==='phone')message(p,'hello',{}).catch(()=>{})}}else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(state)){p.ready=false;status('Conexão interrompida. Tentando reconectar…');if(!settled){settled=true;clearTimeout(timer);reject(Error('Não foi possível abrir a conexão privada.'))}}})});p.heartbeat=setInterval(()=>{if(P!==p)return;if(p.owner!==user()?.id||!K().canCameraPhone()){stopPhone();return}if(p.role==='pc'&&K().S.room?.code!==p.room){stopPhone();return}if(p.last&&Date.now()-p.last>20000){p.last=0;closePeer(p);status('Celular desconectado. Aguardando ele voltar…')}if(p.ready)message(p,p.role==='phone'&&(!p.pc||p.pc.connectionState!=='connected')?'hello':'beat',{}).catch(()=>{})},4000)}
async function receive(p,m){if(P!==p||!m||m.role===p.role||!['pc','phone'].includes(m.role)||!UUID.test(m.client||'')||!Number.isFinite(m.time)||Math.abs(Date.now()-m.time)>60000||m.to&&m.to!==p.client)return;if(m.event==='hello'&&p.role==='pc'){if(p.peer!==m.client||!p.pc||['failed','closed'].includes(p.pc.connectionState)){closePeer(p);p.peer=m.client;await makePeer(p);await p.pc.setLocalDescription(await p.pc.createOffer());await message(p,'description',p.pc.localDescription.toJSON())}p.last=Date.now();return}if(p.role==='phone'&&m.event==='description'&&m.data?.type==='offer'){p.peer=m.client;closePeer(p);await makePeer(p);await p.pc.setRemoteDescription(m.data);await p.pc.setLocalDescription(await p.pc.createAnswer());await message(p,'description',p.pc.localDescription.toJSON());p.last=Date.now();return}if(p.peer!==m.client)return;p.last=Date.now();if(m.event==='description'&&p.role==='pc'){await p.pc?.setRemoteDescription(m.data);for(const candidate of p.pendingIce||[])await p.pc.addIceCandidate(candidate);p.pendingIce=[];if(p.useMic)await message(p,'mic',{on:true})}else if(m.event==='ice'){if(p.pc?.remoteDescription)await p.pc.addIceCandidate(m.data);else(p.pendingIce=p.pendingIce||[]).push(m.data)}else if(m.event==='mic'&&p.role==='phone'){await phoneMic(p,!!m.data?.on)}else if(m.event==='mic-state'&&p.role==='pc'){const el=$('study-phone-mic-status');if(el)el.textContent=m.data?.on?'Microfone do celular conectado.':'O celular não está transmitindo microfone.';if(!m.data?.on&&phoneMicActive())K().stopMic();if(m.data?.on&&p.useMic&&p.remoteAudio)await K().replaceMediaTrack('audio',p.remoteAudio,'phone')}else if(m.event==='stop'){await stopPhone(true,false);status('A transmissão foi encerrada no outro aparelho.')}}
async function makePeer(p){const pc=p.pc=new RTCPeerConnection(await K().ice());if(P!==p){pc.close();return}if(p.role==='phone'){pc.addTransceiver(p.video,{direction:'sendonly'});p.pc.audioSender=pc.addTransceiver(p.audio||'audio',{direction:'sendonly'}).sender}else{pc.addTransceiver('video',{direction:'recvonly'});pc.addTransceiver('audio',{direction:'recvonly'})}pc.onicecandidate=e=>{if(e.candidate)message(p,'ice',e.candidate.toJSON()).catch(()=>{})};pc.ontrack=e=>{if(P!==p||p.role!=='pc'){e.track.stop();return}if(e.track.kind==='video'){p.remoteVideo=e.track;K().replaceMediaTrack('video',e.track,'phone').then(()=>showPreview(p)).catch(e=>status(errorText(e)))}else{p.remoteAudio=e.track;if(p.useMic)K().replaceMediaTrack('audio',e.track,'phone').catch(e=>status(errorText(e)))}};pc.onconnectionstatechange=()=>{if(P!==p)return;if(pc.connectionState==='connected'){status('Celular conectado. Transmissão ativa.');p.last=Date.now()}else if(['failed','disconnected'].includes(pc.connectionState)){status('Conexão interrompida. Tentando reconectar…');if(pc.connectionState==='failed')closePeer(p)}}}
function closePeer(p){const pc=p.pc;p.pc=null;pc?.close();p.pendingIce=[];if(p.role==='pc'){if(K().S.room?.voice?.videoSource==='phone')K().stopCam();if(phoneMicActive())K().stopMic();p.remoteVideo=p.remoteAudio=null}}
async function stopPhone(clear=true,notify=true){const p=P;if(!p)return;const notification=clear&&notify?message(p,'stop',{}).catch(()=>{}):Promise.resolve();if(clear){if(p.role==='pc')pcPersist(null);persistPhone(p,false)}P=null;clearInterval(p.heartbeat);closePeer(p);p.video?.stop();p.audio?.stop();await notification;if(p.channel)await cloud()?.removeChannel(p.channel);const preview=$('study-camera-preview');if(preview)preview.srcObject=null;if($('study-phone-start'))$('study-phone-start').disabled=false;const el=$('study-camera-status');if(el)el.textContent=clear?'Transmissão desligada.':'Conexão encerrada. Reabra a conexão para tentar novamente.'}
function disablePhoneMic(){if(P?.role==='pc'){P.useMic=false;pcPersist(P);message(P,'mic',{on:false}).catch(()=>{})}}
const phoneActive=()=>P?.role==='pc'&&!!P.remoteVideo;
const phoneMicActive=()=>K().S.room?.voice?.audioSource==='phone'&&!!K().S.room?.voice?.mic;
async function autoResume(){if(document.hidden||!K()||!cloud()||!user()||!K().canCameraPhone()||P||opening)return;const pair=pairFromURL();if(pair){const viewKey=pair.id+user().id+K().canCameraPhone();if(phoneViewKey!==viewKey){phoneViewKey=viewKey;renderPhone(pair,allowedResume(pair))}return}let saved;try{saved=JSON.parse(sessionStorage.getItem('iasd-study-camera-pc')||'null')}catch(e){}if(saved&&saved.owner===user().id&&saved.until>Date.now()&&K().S.room?.code===saved.room){const p=P={...saved,role:'pc',client:crypto.randomUUID(),last:0,status:'Retomando conexão com o celular…',useMic:!!saved.useMic};try{await connect(p)}catch(e){K().toast(errorText(e));await stopPhone(false)}}}
function boot(){clearTimeout(autoTimer);autoTimer=setTimeout(autoResume,600)}
window.addEventListener('iasd-auth',()=>{if(P&&P.owner!==user()?.id)stopPhone();boot()});window.addEventListener('iasd-access-changed',boot);window.addEventListener('pagehide',()=>{phoneViewKey='';stopPhone(false)});window.addEventListener('pageshow',boot);document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(P?.role==='phone')message(P,'hello',{}).catch(()=>{});else boot()}});setInterval(()=>{if(!P)autoResume()},4000);
window.IASDStudyDevices={showPhone:()=>{const pair=pairFromURL();if(pair&&!P){phoneViewKey=pair.id+(user()?.id||'guest')+K().canCameraPhone();renderPhone(pair,user()?.id===pair.owner&&K().canCameraPhone()?allowedResume(pair):null)}else boot()},open,startPC,stopPhone,micConstraints,phoneActive,phoneMicActive,disablePhoneMic};boot();
})();
